import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/02-06.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 105, 60, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.8, ...extra });
const cast = (): Prop[] => [
  p("ringmaster", 135, 310, undefined, {
    scale: 0.8,
    reveal: { x: 235, y: 405 },
  }),
  p("giraffe", 835, 275, undefined, {
    scale: 0.78,
    reveal: { x: 755, y: 415 },
  }),
  p("beetle", 850, 465, undefined, { scale: 0.8, reveal: { x: 625, y: 470 } }),
];
const recipes: {
  targets: Target[];
  props: Prop[];
  stamp: string;
  extra?: Partial<Level>;
}[] = [
  {
    targets: [
      t("hat", "Thaw Tick's very punctual hat", "melt", 270, 205, 145, 85),
      warm(
        "microphone",
        "Prepare a welcoming introduction",
        600,
        390,
        [25, 35],
        [15, 30],
        ["hat"],
      ),
    ],
    props: [
      p("clockhat", 342, 285, "hat", { scale: 0.85 }),
      p("microphone", 652, 443, "microphone", { scale: 0.75 }),
      p("ticket", 480, 415, undefined, {
        scale: 0.9,
        reveal: { x: 485, y: 330 },
      }),
    ],
    stamp: "SHOWTIME: TALL PAST SIX",
    extra: { start: [345, 145], par: 85 },
  },
  {
    targets: [
      t(
        "leftBlock",
        "Build the first presentation block",
        "freeze",
        310,
        425,
        145,
        45,
      ),
      t(
        "rightBlock",
        "Build the second presentation block",
        "freeze",
        490,
        425,
        145,
        45,
      ),
      t(
        "name",
        "Unveil Bea's exceedingly polite name",
        "melt",
        395,
        235,
        155,
        80,
        {
          requires: ["leftBlock", "rightBlock"],
        },
      ),
    ],
    props: [
      p("ticket", 472, 300, "name", {
        scale: 1.35,
        reveal: { x: 465, y: 380, scale: 1.6 },
      }),
      p("biscuit", 560, 400, undefined, { scale: 0.55, revealOnly: true }),
    ],
    stamp: "BEA. EXCELLENT REFERENCES. VERY TALL.",
    extra: { start: [380, 365], temp: -25, pressure: 35 },
  },
  {
    targets: [
      t(
        "act",
        "Read the splash-spectacular program",
        "melt",
        440,
        315,
        105,
        55,
      ),
      t(
        "trough",
        "Fill the enormous splash trough",
        "fill",
        235,
        430,
        220,
        60,
        {
          requires: ["act"],
        },
      ),
      t("cup", "Fill Tock's tiny starring cup", "fill", 655, 225, 60, 65, {
        requires: ["act"],
      }),
    ],
    props: [
      p("ticket", 492, 360, "act", { scale: 0.7 }),
      p("cup", 345, 490, "trough", { scale: 1.35 }),
      p("cup", 685, 288, "cup", { scale: 0.55 }),
      p("scarf", 485, 440, undefined, { scale: 1.1, revealOnly: true }),
    ],
    stamp: "SMALL SPLASH. SPECTACULAR TOWEL.",
  },
  {
    targets: [
      t("drive", "Wind up a round of applause", "spin", 315, 330, 70, 65),
      warm(
        "scarf",
        "Give the scarf a square of care",
        495,
        330,
        [20, 35],
        [10, 25],
        ["drive"],
        { w: 90, h: 90 },
      ),
    ],
    props: [
      p("circuswheel", 350, 305, undefined, { scale: 1.3 }),
      p("scarf", 540, 400, "scarf", { reveal: { x: 620, y: 350 } }),
      ...[280, 390, 500, 610].map((x) =>
        p("ticket", x, 475, undefined, {
          scale: 0.5,
          revealOnly: true,
        }),
      ),
      p("biscuit", 665, 435, undefined, { scale: 0.55, revealOnly: true }),
    ],
    stamp: "APPLAUSE IN EIGHT LANGUAGES, INCLUDING SANDWICH",
  },
  {
    targets: [
      t(
        "upper",
        "Open a peephole in the upper program",
        "melt",
        290,
        210,
        135,
        110,
      ),
      t(
        "lower",
        "Read the program beneath the peephole",
        "melt",
        330,
        345,
        105,
        90,
      ),
      warm(
        "rehearsal",
        "Warm the rehearsal invitation",
        605,
        390,
        [25, 40],
        [20, 35],
        ["upper", "lower"],
      ),
    ],
    props: [
      p("ticket", 358, 295, "upper", { scale: 1.05 }),
      p("ticket", 382, 410, "lower", {
        scale: 0.9,
        reveal: { x: 485, y: 320 },
      }),
      p("spotlight", 658, 447, "rehearsal", { scale: 0.7 }),
      p("biscuit", 625, 330, undefined, { scale: 0.75, revealOnly: true }),
    ],
    stamp: "INTERMISSION: NOW AVAILABLE AS A BISCUIT",
  },
  {
    targets: [
      warm("scarf", "Scarf care: softly does it", 245, 380, [15, 25], [10, 25]),
      warm("collar", "Polish the brass collar", 610, 240, [40, 55], [30, 45]),
      t(
        "portrait",
        "Build a comfortable portrait base",
        "freeze",
        415,
        460,
        180,
        45,
        {
          requires: ["scarf", "collar"],
        },
      ),
    ],
    props: [
      p("scarf", 297, 425, "scarf", {
        tint: "#d9acd0",
        reveal: { x: 695, y: 350 },
      }),
      p("circuswheel", 662, 285, "collar", { scale: 0.55 }),
      p("ticket", 505, 430, "portrait", { scale: 1.1, revealOnly: true }),
    ],
    stamp: "OFFICIAL PORTRAIT: CROOKED SCARF INCLUDED",
    extra: { start: [297, 325], temp: 20, pressure: 17 },
  },
  {
    targets: [
      t("drumCard", "Read Tock's drum cue", "melt", 250, 205, 110, 60),
      t("teaCard", "Read Bea's refreshment cue", "melt", 625, 270, 110, 60),
      t("drum", "Prepare Tock's drumroll", "spin", 265, 370, 75, 65, {
        requires: ["drumCard"],
      }),
      t("tea", "Prepare Bea's magnificent sip", "fill", 605, 415, 145, 60, {
        requires: ["teaCard"],
      }),
    ],
    props: [
      p("ticket", 305, 250, "drumCard", { scale: 0.8 }),
      p("ticket", 680, 315, "teaCard", { scale: 0.8 }),
      p("drum", 302, 442, "drum", { scale: 1.2 }),
      p("cup", 678, 480, "tea", { scale: 1.05 }),
      p("biscuit", 465, 465, undefined, { scale: 0.6, revealOnly: true }),
    ],
    stamp: "REFRESHMENTS: REMARKABLY COORDINATED",
  },
  {
    targets: [
      t(
        "leftBase",
        "Build the table's left display block",
        "freeze",
        275,
        440,
        110,
        40,
      ),
      t(
        "middleBase",
        "Build the higher middle block",
        "freeze",
        425,
        390,
        110,
        40,
      ),
      t(
        "rightBase",
        "Build the table's right display block",
        "freeze",
        575,
        450,
        110,
        40,
      ),
      t(
        "ribbon",
        "Unfreeze the ribbon for an ordinary table",
        "melt",
        425,
        230,
        110,
        65,
        {
          requires: ["leftBase", "middleBase", "rightBase"],
        },
      ),
    ],
    props: [
      p("ticket", 480, 280, "ribbon", {
        scale: 0.8,
        reveal: { x: 485, y: 225 },
      }),
      p("circustable", 480, 440, undefined, { scale: 1.25, revealOnly: true }),
      p("cup", 500, 366, undefined, { scale: 0.5, revealOnly: true }),
    ],
    stamp: "A BREATHTAKING ABSENCE OF WOBBLE",
    extra: { start: [330, 380], temp: -30, pressure: 35 },
  },
  {
    targets: [
      t(
        "recipe",
        "Read the teacup juggler's recipe",
        "melt",
        265,
        200,
        100,
        60,
      ),
      t("lowCup", "Fill the juggler's low cup", "fill", 235, 340, 60, 55, {
        requires: ["recipe"],
      }),
      t(
        "middleCup",
        "Fill the juggler's middle cup",
        "fill",
        410,
        285,
        70,
        55,
        {
          requires: ["recipe"],
        },
      ),
      t("highCup", "Fill the juggler's high cup", "fill", 615, 215, 65, 55, {
        requires: ["recipe"],
      }),
      warm(
        "service",
        "A calm finish before the cups fly",
        420,
        450,
        [30, 40],
        [15, 25],
        ["lowCup", "middleCup", "highCup"],
        { w: 180, h: 65 },
      ),
    ],
    props: [
      p("ticket", 315, 247, "recipe", { scale: 0.7 }),
      p("cup", 265, 392, "lowCup", { scale: 0.55, reveal: { x: 350, y: 235 } }),
      p("cup", 445, 338, "middleCup", {
        scale: 0.65,
        reveal: { x: 480, y: 180 },
      }),
      p("cup", 647, 267, "highCup", { scale: 0.6, reveal: { x: 610, y: 235 } }),
      p("biscuit", 685, 400, undefined, { scale: 0.7, revealOnly: true }),
    ],
    stamp: "BISCUITS REMAIN FIRMLY ON THE GROUND",
  },
  {
    targets: [
      t(
        "water",
        "Fill the garden clown's watering basin",
        "fill",
        385,
        430,
        170,
        65,
      ),
      t("leftVase", "Build the left bouquet stand", "freeze", 240, 440, 80, 40),
      t(
        "rightVase",
        "Build the right bouquet stand",
        "freeze",
        680,
        440,
        80,
        40,
      ),
      warm(
        "collar",
        "Encourage the flower collar",
        425,
        280,
        [20, 30],
        [10, 25],
        ["water", "leftVase", "rightVase"],
      ),
    ],
    props: [
      p("flower", 477, 325, "collar", { scale: 1.2 }),
      p("cup", 470, 490, "water", { scale: 1.1 }),
      p("flower", 280, 430, "leftVase", { scale: 0.7, revealOnly: true }),
      p("flower", 720, 430, "rightVase", { scale: 0.7, revealOnly: true }),
      p("ticket", 630, 340, undefined, { scale: 0.6, revealOnly: true }),
    ],
    stamp: "THE FIRST ACT WITH ITS OWN AUDIENCE",
  },
  {
    targets: [
      t(
        "leftSound",
        "Clear the first sound-check tile",
        "melt",
        430,
        205,
        50,
        95,
      ),
      t(
        "rightSound",
        "Clear the second sound-check tile",
        "melt",
        565,
        235,
        50,
        95,
      ),
      warm(
        "drum",
        "Warm the echo performer's drum",
        475,
        395,
        [25, 40],
        [15, 30],
        ["leftSound", "rightSound"],
      ),
      t(
        "accompaniment",
        "Start the echo's accompaniment",
        "spin",
        255,
        330,
        70,
        60,
        {
          requires: ["drum"],
        },
      ),
    ],
    props: [
      p("ticket", 455, 278, "leftSound", { scale: 0.5 }),
      p("ticket", 590, 308, "rightSound", { scale: 0.5 }),
      p("drum", 527, 445, "drum", { scale: 1.1 }),
      p("circuswheel", 290, 397, "accompaniment", { scale: 0.75 }),
      p("bubble", 605, 370, undefined, { scale: 0.45, revealOnly: true }),
      p("bubble", 670, 325, undefined, { scale: 0.35, revealOnly: true }),
    ],
    stamp: "DRESSING ROOM RESERVED FOR PLUS ONE",
  },
  {
    targets: [
      t(
        "leftStar",
        "Build the left star-display block",
        "freeze",
        270,
        285,
        70,
        40,
      ),
      t(
        "highStar",
        "Build the high star-display block",
        "freeze",
        440,
        220,
        70,
        40,
      ),
      t(
        "rightStar",
        "Build the right star-display block",
        "freeze",
        610,
        285,
        70,
        40,
      ),
      t(
        "placard",
        "Read the cosmic scarf's act placard",
        "melt",
        400,
        360,
        145,
        60,
        {
          requires: ["leftStar", "highStar", "rightStar"],
        },
      ),
      warm(
        "scarf",
        "Prepare the scarf's snack-break orbit",
        590,
        435,
        [30, 45],
        [20, 35],
        ["placard"],
      ),
    ],
    props: [
      p("moon", 305, 273, "leftStar", {
        scale: 0.4,
        revealOnly: true,
        reveal: { x: 375, y: 300 },
      }),
      p("moon", 475, 208, "highStar", { scale: 0.45, revealOnly: true }),
      p("moon", 645, 273, "rightStar", {
        scale: 0.4,
        revealOnly: true,
        reveal: { x: 565, y: 300 },
      }),
      p("ticket", 472, 407, "placard", { scale: 0.9 }),
      p("scarf", 642, 480, "scarf", {
        tint: "#a89dd3",
        reveal: { x: 470, y: 370, scale: 1.2 },
      }),
      p("biscuit", 475, 292, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "ASTRONOMY, WITH BISCUITS",
    extra: { start: [475, 155], temp: -25, pressure: 35 },
  },
  {
    targets: [
      t(
        "firstAppointment",
        "Thaw the first eight o'clock solo",
        "melt",
        240,
        200,
        110,
        50,
      ),
      t(
        "secondAppointment",
        "Thaw the other eight o'clock solo",
        "melt",
        385,
        305,
        110,
        50,
      ),
      t(
        "thirdAppointment",
        "Thaw the third eight o'clock solo",
        "melt",
        530,
        410,
        110,
        50,
      ),
      warm(
        "firstSolo",
        "First solo: gently",
        385,
        195,
        [20, 30],
        [10, 25],
        ["firstAppointment"],
        { w: 95 },
      ),
      warm(
        "secondSolo",
        "Second solo: comfortably",
        530,
        300,
        [30, 40],
        [20, 35],
        ["secondAppointment"],
        { w: 95 },
      ),
      warm(
        "thirdSolo",
        "Third solo: brassily",
        675,
        405,
        [40, 50],
        [30, 45],
        ["thirdAppointment"],
        { w: 95 },
      ),
    ],
    props: [
      p("ticket", 295, 242, "firstAppointment", {
        tint: "#deb1c8",
        scale: 0.65,
      }),
      p("ticket", 440, 347, "secondAppointment", {
        tint: "#a7cdd0",
        scale: 0.65,
      }),
      p("ticket", 585, 452, "thirdAppointment", {
        tint: "#e0c38c",
        scale: 0.65,
      }),
      p("circuswheel", 432, 248, "firstSolo", { tint: "#deb1c8", scale: 0.45 }),
      p("circuswheel", 577, 353, "secondSolo", {
        tint: "#a7cdd0",
        scale: 0.45,
      }),
      p("circuswheel", 722, 458, "thirdSolo", { tint: "#e0c38c", scale: 0.45 }),
    ],
    stamp: "THREE SOLOS. ONE FRIENDLY TRIO.",
    extra: { start: [295, 145], par: 190 },
  },
  {
    targets: [
      warm("brass", "Follow the wheel", 435, 300, [45, 60], [35, 50], [], {
        motion: { rx: 65, ry: 100, period: 28 },
      }),
      warm(
        "leftRibbon",
        "A soft ribbon on the left",
        235,
        335,
        [15, 25],
        [10, 20],
      ),
      warm(
        "rightRibbon",
        "A soft ribbon on the right",
        650,
        335,
        [15, 25],
        [10, 20],
      ),
    ],
    props: [
      p("circuswheel", 0, 0, "brass", {
        follow: "brass",
        scale: 0.75,
        reveal: { x: 488, y: 375 },
      }),
      p("scarf", 287, 385, "leftRibbon", {
        tint: "#e0adbf",
        reveal: { x: 380, y: 375 },
      }),
      p("scarf", 702, 385, "rightRibbon", {
        tint: "#9bc4c8",
        reveal: { x: 595, y: 375 },
      }),
      p("ticket", 485, 475, undefined, { scale: 0.75, revealOnly: true }),
    ],
    stamp: "PLEASE WELCOME OUR WELL-DRESSED WHEEL",
    extra: { start: [552, 248], temp: 52, pressure: 42, par: 155 },
  },
  {
    targets: [
      t(
        "leftStage",
        "Build the first very modest landing",
        "freeze",
        245,
        445,
        115,
        45,
      ),
      t(
        "middleStage",
        "Build the middle landing block",
        "freeze",
        415,
        445,
        115,
        45,
      ),
      t(
        "rightStage",
        "Build the final landing block",
        "freeze",
        585,
        445,
        115,
        45,
      ),
      t("hopCard", "Unveil the first compliment", "melt", 290, 235, 120, 65, {
        requires: ["leftStage", "middleStage", "rightStage"],
      }),
      t(
        "arrivalCard",
        "Unveil the second compliment",
        "melt",
        555,
        235,
        120,
        65,
        {
          requires: ["leftStage", "middleStage", "rightStage"],
        },
      ),
      t(
        "refreshment",
        "Fill a cup for the excellent arrival",
        "fill",
        455,
        345,
        65,
        60,
        {
          requires: ["hopCard", "arrivalCard"],
        },
      ),
    ],
    props: [
      p("ticket", 350, 285, "hopCard", {
        scale: 0.9,
        reveal: { x: 380, y: 265, scale: 1.25 },
      }),
      p("ticket", 615, 285, "arrivalCard", {
        scale: 0.9,
        reveal: { x: 565, y: 265, scale: 1.25 },
      }),
      p("cup", 487, 402, "refreshment", { scale: 0.55 }),
      p("flower", 300, 430, undefined, { scale: 0.65, revealOnly: true }),
      p("flower", 640, 430, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "LOVELY HOP! EXCELLENT ARRIVAL!",
    extra: { start: [302, 385], temp: -25, pressure: 35, par: 190 },
  },
  {
    targets: [
      t("firstBeat", "Tock's first beat", "spin", 270, 315, 80, 70, {
        pulse: { period: 3.6, open: 1.6, phase: 0 },
      }),
      t("secondBeat", "Tock's answering beat", "spin", 635, 315, 80, 70, {
        pulse: { period: 3.6, open: 1.6, phase: 1.8 },
      }),
      warm(
        "pause",
        "Make room for a satisfying pause",
        440,
        350,
        [25, 35],
        [15, 30],
        ["firstBeat", "secondBeat"],
      ),
    ],
    props: [
      p("drum", 310, 425, "firstBeat", { scale: 1.1 }),
      p("drum", 675, 425, "secondBeat", { tint: "#99bec7", scale: 1.1 }),
      p("ticket", 492, 402, "pause", {
        scale: 0.9,
        reveal: { x: 485, y: 270, scale: 1.15 },
      }),
      p("biscuit", 492, 475, undefined, { scale: 0.6, revealOnly: true }),
    ],
    stamp: "THE PAUSE RECEIVES ITS OWN APPLAUSE",
    extra: { start: [310, 250], temp: 55, pressure: 85, par: 150 },
  },
  {
    targets: [
      t(
        "percussion",
        "Prepare a very considerate drumroll",
        "spin",
        445,
        265,
        75,
        65,
      ),
      warm(
        "scarf",
        "Give Bea's scarf a gentle introduction",
        245,
        400,
        [20, 30],
        [10, 25],
        ["percussion"],
      ),
      warm(
        "flowers",
        "Ask the flowers to hold their bows",
        625,
        400,
        [30, 40],
        [15, 30],
        ["percussion"],
      ),
    ],
    props: [
      p("drum", 482, 360, "percussion", { scale: 1.35 }),
      p("scarf", 297, 450, "scarf", { reveal: { x: 710, y: 350 } }),
      p("flower", 677, 450, "flowers", { scale: 1.1 }),
      p("ticket", 480, 440, undefined, { scale: 0.8, revealOnly: true }),
    ],
    stamp: "THUNDEROUS CONSIDERATION. TINY TAPS.",
    extra: { start: [482, 205], temp: 50, pressure: 85 },
  },
  {
    targets: [
      t(
        "frontSeat",
        "Build a seat with the best view",
        "freeze",
        270,
        310,
        145,
        45,
      ),
      t(
        "backSeat",
        "Build another seat with the best view",
        "freeze",
        270,
        440,
        145,
        45,
      ),
      t("hospitality", "Thaw the hospitality sign", "melt", 600, 205, 120, 65),
      t(
        "drinks",
        "Fill the audience refreshment basin",
        "fill",
        585,
        380,
        155,
        65,
        {
          requires: ["hospitality"],
        },
      ),
      t(
        "houseLights",
        "Switch on everyone's best view",
        "spin",
        460,
        240,
        75,
        65,
        {
          requires: ["frontSeat", "backSeat", "drinks"],
        },
      ),
    ],
    props: [
      p("ticket", 342, 300, "frontSeat", { scale: 0.75, revealOnly: true }),
      p("ticket", 342, 430, "backSeat", { scale: 0.75, revealOnly: true }),
      p("ticket", 660, 255, "hospitality", { scale: 0.85 }),
      p("cup", 662, 445, "drinks", { scale: 1.05 }),
      p("spotlight", 497, 335, "houseLights", { scale: 1.05 }),
      p("wizard", 345, 320, undefined, { scale: 0.55, revealOnly: true }),
      p("penguin", 345, 450, undefined, { scale: 0.6, revealOnly: true }),
      p("flower", 465, 460, undefined, { scale: 0.85, revealOnly: true }),
    ],
    stamp: "EVERY CHAIR: BEST VIEW. REALLY.",
    extra: { start: [342, 250], temp: -25, pressure: 35, par: 175 },
  },
  {
    targets: [
      t(
        "coatPanel",
        "Open a channel through Bea's coat ice",
        "melt",
        240,
        205,
        140,
        150,
      ),
      t(
        "pocketPanel",
        "Reach the smaller pocket panel below",
        "melt",
        280,
        380,
        110,
        65,
      ),
      warm(
        "note",
        "Care for the encore in the pocket",
        580,
        310,
        [20, 35],
        [10, 25],
        ["coatPanel", "pocketPanel"],
      ),
      t(
        "display",
        "Build a stand for an unrushed encore",
        "freeze",
        565,
        450,
        145,
        45,
        {
          requires: ["note"],
        },
      ),
    ],
    props: [
      p("coat", 310, 315, "coatPanel", { scale: 1.2 }),
      p("letter", 335, 425, "pocketPanel", {
        scale: 0.65,
        reveal: { x: 475, y: 295, scale: 1.05 },
      }),
      p("ticket", 632, 355, "note", { scale: 0.8 }),
      p("biscuit", 635, 435, "display", { scale: 0.55, revealOnly: true }),
    ],
    stamp: "ENCORE LENGTH: AS LONG AS YOU LIKE",
    extra: { start: [335, 145], par: 160 },
  },
  {
    targets: [
      t(
        "curtain",
        "Thaw the curtain for one more bow",
        "melt",
        315,
        205,
        155,
        80,
      ),
      t("stage", "Build the stage for everyone", "freeze", 540, 460, 220, 45),
      warm(
        "bea",
        "Let Bea take her time",
        245,
        355,
        [20, 30],
        [10, 25],
        ["curtain", "stage"],
      ),
      warm(
        "tock",
        "Give Tock a comfortable cue",
        620,
        335,
        [35, 45],
        [25, 40],
        ["curtain", "stage"],
      ),
      t(
        "applause",
        "Start the applause when everyone is ready",
        "spin",
        465,
        330,
        90,
        70,
        {
          requires: ["bea", "tock"],
        },
      ),
    ],
    props: [
      p("ticket", 392, 268, "curtain", { scale: 1.1 }),
      p("scarf", 297, 402, "bea", {
        tint: "#c5b0d8",
        reveal: { x: 705, y: 345 },
      }),
      p("drum", 672, 405, "tock", { scale: 1.05 }),
      p("circuswheel", 510, 422, "applause", {
        scale: 1.0,
        reveal: { x: 475, y: 405 },
      }),
      p("flower", 365, 455, undefined, { scale: 0.9, revealOnly: true }),
      p("bubble", 365, 340, undefined, { scale: 0.5, revealOnly: true }),
      p("bubble", 390, 310, undefined, { scale: 0.35, revealOnly: true }),
      p("moon", 580, 235, undefined, { scale: 0.45, revealOnly: true }),
      p("biscuit", 575, 470, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "SHOWTIME: WHEN EVERYONE IS READY",
    extra: { start: [392, 145], par: 185 },
  },
];

// Dispatches introduce the joke; detailed hose instructions remain in the source cards.
const dispatches = [
  "Tick's clock hat says tall past six. The show can start as soon as his microphone believes him.",
  "Introducing Bea! Her name fits on the sign. Her list of polite qualifications is still unfolding.",
  "Tock has booked an enormous splash pool. He intends to use the teacup beside it.",
  "Bea's scarf needs a little care before its big round of applause. It has rehearsed an excellent fold.",
  "Bea is meant to juggle the intermission. Thaw the program before she tries to pick it up.",
  "Bea's scarf and brass collar disagree about comfortable. The portrait can include both opinions.",
  "Tock performs the drumroll. Bea performs the tea break. Both acts deserve a proper rehearsal.",
  "Tick promises a breathtaking display of stability. Bea would be delighted with a table that stays put.",
  "The teacup juggler is visiting. Bea has volunteered to keep the biscuits considerably less airborne.",
  "This flower collar keeps bowing before the act begins. Prepare a stage for its enormous enthusiasm.",
  "The cave echo has requested its own curtain call. Tock is deciding whether it also needs a dressing room.",
  "A cosmic scarf has brought three planets and one biscuit. Bea hopes the biscuit is the one staying for tea.",
  "Tick has scheduled three solos for eight o'clock. With a little care, that could be a rather friendly trio.",
  "The rehearsal wheel has rehearsed going round. Now it would like help choosing two very soft ribbons.",
  "Bea plans one modest hop. Tick has prepared two enormous compliments and a well-earned refreshment.",
  "Tock has discovered the pause. Help him put a beat on either side so nobody mistakes it for the end.",
  "Tock's next drumroll is mostly consideration. Bea and the flowers would like a moment to be introduced.",
  "The visitors are here! Tick has personally promised every chair the best view, including the one behind the tall hat.",
  "Bea left the encore in her coat pocket. Nobody has checked its length. Nobody intends to.",
  "The scarf, flowers, echo, and rehearsal wheel have all come back for a bow. Tick has finally stopped checking the time.",
];
const source = designs.packs.find((pack) => pack.id === "04")!;
export const circusLevels: Level[] = recipes.map((recipe, i) => {
  const card = source.scenes[i];
  return {
    id: card.id,
    pack: "04",
    name: card.title,
    chapter: source.title,
    theme: "circus",
    pitch: dispatches[i],
    hint: card.puzzle.replace(/With (MOTION|PULSE)( enabled)?, /g, ""),
    ending: card.payoff,
    start: [475, 145],
    temp: 65,
    pressure: 45,
    par: 50 + recipe.targets.length * 22,
    targets: recipe.targets,
    props: [...cast(), ...recipe.props],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
