import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/02-06.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 105, 60, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.8, ...extra });
const cast = (): Prop[] => [
  p("mousemayor", 135, 300, undefined, {
    scale: 0.8,
    reveal: { x: 245, y: 415 },
  }),
  p("hedgehog", 835, 275, undefined, {
    scale: 0.8,
    reveal: { x: 755, y: 425 },
  }),
  p("inspector", 850, 465, undefined, {
    scale: 0.8,
    reveal: { x: 635, y: 470 },
  }),
];
const recipes: {
  targets: Target[];
  props: Prop[];
  stamp: string;
  extra?: Partial<Level>;
}[] = [
  {
    targets: [
      t("window", "Thaw Quill's service window", "melt", 350, 215, 170, 100),
      warm(
        "stamp",
        "Condition the stamp for warm regards",
        390,
        405,
        [20, 35],
        [15, 30],
        ["window"],
      ),
    ],
    props: [
      p("archive", 435, 305, "window", { scale: 0.95 }),
      p("stamp", 442, 455, "stamp", { scale: 0.8 }),
      p("pencil", 670, 280, undefined, { scale: 1.2 }),
      p("townsign", 580, 405, undefined, { scale: 0.85, revealOnly: true }),
    ],
    stamp: "WINDOW ONE: OPEN TO REASON",
    extra: { start: [435, 150], par: 85 },
  },
  {
    targets: [
      t(
        "lowPlatform",
        "Build the first accessible platform",
        "freeze",
        265,
        445,
        170,
        45,
      ),
      t(
        "highPlatform",
        "Build the platform beside the counter",
        "freeze",
        500,
        385,
        170,
        55,
      ),
      t(
        "notice",
        "Unfreeze the accessibility notice",
        "melt",
        535,
        215,
        125,
        70,
        {
          requires: ["lowPlatform", "highPlatform"],
        },
      ),
    ],
    props: [
      p("townsign", 597, 280, "notice", { scale: 0.75 }),
      p("paperclip", 350, 410, undefined, { scale: 0.8 }),
      p("leafbug", 710, 420, undefined, {
        scale: 0.6,
        reveal: { x: 585, y: 370 },
      }),
      p("receipt", 445, 270, undefined, { scale: 0.7, revealOnly: true }),
    ],
    stamp: "APPLICATION-WINDOW ACCESS: NO APPLICATION REQUIRED",
    extra: { start: [350, 380], temp: -25, pressure: 35, par: 115 },
  },
  {
    targets: [
      t(
        "fountainCover",
        "Carve the public fountain's ice cover",
        "melt",
        275,
        225,
        145,
        85,
      ),
      t(
        "cupCover",
        "Carve the testing cup's smaller cover",
        "melt",
        635,
        190,
        75,
        65,
      ),
      t(
        "fountain",
        "Fill the public fountain basin",
        "fill",
        235,
        410,
        220,
        65,
      ),
      t("testingCup", "Fill the raised testing cup", "fill", 605, 315, 110, 65),
    ],
    props: [
      p("townsign", 347, 300, "fountainCover", { scale: 0.7 }),
      p("receipt", 672, 243, "cupCover", { scale: 0.5 }),
      p("cup", 345, 475, "fountain", { scale: 1.25 }),
      p("cup", 660, 375, "testingCup", { scale: 0.7 }),
      p("biscuit", 510, 425, undefined, { scale: 0.9, revealOnly: true }),
    ],
    stamp: "PUBLICLY REFRESHING. BISCUITS PENDING INSPECTION.",
    extra: { start: [345, 165], par: 130 },
  },
  {
    targets: [
      t(
        "ventilation",
        "Start the office's very official fan",
        "spin",
        350,
        290,
        80,
        70,
      ),
      warm(
        "ribbon",
        "Care for the mayor's enormous ribbon",
        525,
        370,
        [25, 40],
        [15, 25],
        ["ventilation"],
        { w: 125 },
      ),
    ],
    props: [
      p("paperclip", 390, 398, "ventilation", { scale: 0.9 }),
      p("scarf", 587, 420, "ribbon", {
        scale: 1.25,
        tint: "#cab584",
        reveal: { x: 500, y: 315 },
      }),
      p("eraser", 290, 460, undefined, { scale: 0.85 }),
      p("ticket", 700, 335, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "RIBBON OPENED BY POLITE UNTYING",
    extra: { start: [390, 230], temp: 50, pressure: 85, par: 95 },
  },
  {
    targets: [
      t("firstCopy", "Read the first archive copy", "melt", 255, 190, 105, 70),
      t(
        "middleCopy",
        "Open a channel through the middle copy",
        "melt",
        305,
        285,
        120,
        100,
      ),
      t(
        "lastCopy",
        "Reach the last copy below the channel",
        "melt",
        335,
        410,
        105,
        70,
      ),
      warm(
        "document",
        "Give the legible copy a little care",
        620,
        380,
        [20, 30],
        [10, 25],
        ["firstCopy", "middleCopy", "lastCopy"],
      ),
    ],
    props: [
      p("archive", 307, 250, "firstCopy", { scale: 0.65 }),
      p("archive", 365, 370, "middleCopy", { scale: 0.85 }),
      p("archive", 387, 468, "lastCopy", { scale: 0.65 }),
      p("receipt", 672, 430, "document", {
        scale: 0.75,
        reveal: { x: 525, y: 300 },
      }),
      p("paperclip", 580, 245, undefined, { scale: 0.75, revealOnly: true }),
    ],
    stamp: "PLEASE USE ONE COPY. IN TRIPLICATE.",
    extra: { start: [307, 135], par: 150 },
  },
  {
    targets: [
      t(
        "address",
        "Thaw the puddle's location plaque",
        "melt",
        445,
        225,
        120,
        65,
      ),
      t(
        "basin",
        "Fill the puddle's approved address",
        "fill",
        245,
        405,
        190,
        65,
        { requires: ["address"] },
      ),
      t(
        "nameBase",
        "Build a stand for the resident sign",
        "freeze",
        610,
        435,
        145,
        45,
        { requires: ["address"] },
      ),
    ],
    props: [
      p("townsign", 505, 285, "address", { scale: 0.75 }),
      p("puddle", 340, 450, "basin", {
        scale: 1.0,
        reveal: { x: 460, y: 435, scale: 1.1 },
      }),
      p("townsign", 682, 420, "nameBase", {
        scale: 0.65,
        revealOnly: true,
        reveal: { x: 575, y: 440 },
      }),
      p("pencil", 310, 260, undefined, { scale: 0.7 }),
    ],
    stamp: "RESIDENT. EXCELLENT AT REFLECTION.",
    extra: { start: [505, 165], par: 120 },
  },
  {
    targets: [
      warm("blueStamp", "Soft blue regards", 235, 285, [15, 25], [10, 20]),
      warm("brassStamp", "Bright brass regards", 625, 285, [40, 50], [30, 45]),
      t(
        "ink",
        "Fill the shared good-wishes ink basin",
        "fill",
        415,
        435,
        155,
        65,
        { requires: ["blueStamp", "brassStamp"] },
      ),
    ],
    props: [
      p("stamp", 287, 338, "blueStamp", { tint: "#98bfd0", scale: 0.85 }),
      p("stamp", 677, 338, "brassStamp", { tint: "#d3b474", scale: 0.85 }),
      p("cup", 492, 495, "ink", { scale: 0.85 }),
      p("receipt", 355, 215, undefined, {
        tint: "#98bfd0",
        scale: 0.65,
        revealOnly: true,
      }),
      p("receipt", 610, 215, undefined, {
        tint: "#d3b474",
        scale: 0.65,
        revealOnly: true,
      }),
    ],
    stamp: "WE'RE HERE FOR YOU. CONFETTI LEVEL: SENSIBLE.",
    extra: { start: [287, 225], temp: 20, pressure: 15, par: 130 },
  },
  {
    targets: [
      t(
        "seatCard",
        "Thaw the sitting-down appointment",
        "melt",
        245,
        300,
        105,
        60,
      ),
      t(
        "drinkCard",
        "Thaw the refreshment appointment",
        "melt",
        625,
        260,
        110,
        65,
      ),
      t(
        "seat",
        "Build a place to wait comfortably",
        "freeze",
        395,
        435,
        140,
        45,
        { requires: ["seatCard"] },
      ),
      t(
        "drinks",
        "Fill the queue-free refreshment basin",
        "fill",
        605,
        410,
        155,
        65,
        { requires: ["drinkCard"] },
      ),
      warm(
        "information",
        "Prepare the very helpful information",
        440,
        195,
        [25, 35],
        [15, 30],
        ["seat", "drinks"],
      ),
    ],
    props: [
      p("receipt", 297, 349, "seatCard", { scale: 0.7 }),
      p("receipt", 680, 315, "drinkCard", { scale: 0.7 }),
      p("cup", 682, 470, "drinks", { scale: 1.0 }),
      p("townsign", 492, 252, "information", { scale: 0.8 }),
      p("sock", 350, 240, undefined, { scale: 0.6, revealOnly: true }),
      p("sock", 650, 200, undefined, { scale: 0.6, revealOnly: true }),
    ],
    stamp: "PLEASE SIT ANYWHERE. WE'LL BRING THE FORMS.",
    extra: { start: [297, 240], par: 175 },
  },
  {
    targets: [
      t(
        "sitePlan",
        "Read the one-crumb cafe's site plan",
        "melt",
        255,
        215,
        120,
        70,
      ),
      t(
        "preparation",
        "Fill the cafe preparation basin",
        "fill",
        235,
        370,
        185,
        65,
        { requires: ["sitePlan"] },
      ),
      t(
        "nearTable",
        "Build the first tiny cafe table",
        "freeze",
        600,
        345,
        100,
        40,
      ),
      t(
        "farTable",
        "Build the second tiny cafe table",
        "freeze",
        690,
        435,
        90,
        40,
      ),
      warm(
        "menu",
        "Prepare the very small tasting menu",
        435,
        275,
        [30, 40],
        [15, 25],
        ["preparation", "nearTable", "farTable"],
      ),
    ],
    props: [
      p("receipt", 315, 275, "sitePlan", { scale: 0.8 }),
      p("cup", 327, 430, "preparation", { scale: 1.05 }),
      p("biscuit", 480, 190, undefined, { scale: 1.65 }),
      p("townsign", 487, 330, "menu", { scale: 0.8 }),
      p("biscuit", 650, 332, "nearTable", { scale: 0.25, revealOnly: true }),
      p("biscuit", 735, 422, "farTable", { scale: 0.25, revealOnly: true }),
    ],
    stamp: "THREE MAGNIFYING GLASSES. ONE DELICIOUS CRUMB.",
    extra: { start: [315, 155], par: 175 },
  },
  {
    targets: [
      t(
        "leftAddress",
        "Thaw the leaf's street address",
        "melt",
        255,
        235,
        95,
        70,
      ),
      t(
        "rightAddress",
        "Thaw the leaf's optional branch address",
        "melt",
        625,
        235,
        95,
        70,
      ),
      t(
        "watering",
        "Fill the welcome watering basin",
        "fill",
        395,
        445,
        180,
        65,
        { requires: ["leftAddress", "rightAddress"] },
      ),
      warm(
        "leafCare",
        "Offer the new resident gentle care",
        435,
        315,
        [20, 30],
        [10, 25],
        ["watering"],
      ),
    ],
    props: [
      p("townsign", 302, 298, "leftAddress", { scale: 0.65 }),
      p("townsign", 672, 298, "rightAddress", { scale: 0.65 }),
      p("leafbug", 665, 425, "leafCare", {
        scale: 1.0,
        reveal: { x: 530, y: 375 },
      }),
      p("cup", 485, 505, "watering", { scale: 1.05 }),
      p("flower", 310, 440, undefined, { scale: 0.7, revealOnly: true }),
    ],
    stamp: "RESIDENT AND SHADE PROVIDER. NOT FOR PRUNING.",
    extra: { start: [302, 175], par: 150 },
  },
  {
    targets: [
      t(
        "upperPermit",
        "Carve through the upper sound permit",
        "melt",
        285,
        195,
        140,
        125,
      ),
      t(
        "lowerPermit",
        "Read the permit under the opening",
        "melt",
        325,
        355,
        110,
        80,
      ),
      warm(
        "microphone",
        "Make the welcome sound welcoming",
        605,
        300,
        [20, 35],
        [15, 25],
        ["upperPermit", "lowerPermit"],
      ),
      t(
        "announcement",
        "Start the new resident announcement",
        "spin",
        550,
        440,
        80,
        65,
        { requires: ["microphone"] },
      ),
    ],
    props: [
      p("archive", 355, 300, "upperPermit", { scale: 1.0 }),
      p("receipt", 380, 420, "lowerPermit", { scale: 0.8 }),
      p("microphone", 657, 357, "microphone", { scale: 0.75 }),
      p("townsign", 590, 435, "announcement", {
        scale: 0.65,
        revealOnly: true,
      }),
      p("bubble", 485, 290, undefined, { scale: 0.5, revealOnly: true }),
      p("bubble", 515, 250, undefined, { scale: 0.35, revealOnly: true }),
    ],
    stamp: "WELCOME, DEPUTY MAYOR OF WELCOMES, WELCOMES...",
    extra: { start: [380, 135], par: 155 },
  },
  {
    targets: [
      t(
        "firstMarker",
        "Build the marker beside the pencil",
        "freeze",
        235,
        285,
        85,
        40,
      ),
      t(
        "secondMarker",
        "Build the low sparkle marker",
        "freeze",
        385,
        405,
        85,
        40,
      ),
      t(
        "thirdMarker",
        "Build the third sparkle marker",
        "freeze",
        595,
        215,
        85,
        40,
      ),
      t(
        "registration",
        "Thaw the moonbeam registration",
        "melt",
        550,
        345,
        140,
        65,
        {
          requires: ["firstMarker", "secondMarker", "thirdMarker"],
        },
      ),
      warm(
        "signature",
        "Care for the exceptionally tidy signature",
        345,
        210,
        [30, 45],
        [20, 35],
        ["registration"],
      ),
    ],
    props: [
      p("pencil", 260, 440, undefined, { scale: 0.9 }),
      p("moon", 277, 272, "firstMarker", { scale: 0.25, revealOnly: true }),
      p("moon", 427, 392, "secondMarker", { scale: 0.3, revealOnly: true }),
      p("moon", 637, 202, "thirdMarker", { scale: 0.35, revealOnly: true }),
      p("archive", 620, 400, "registration", { scale: 0.85 }),
      p("stamp", 397, 263, "signature", { scale: 0.7 }),
    ],
    stamp: "ADDRESS: THIRD SPARKLE AFTER THE PENCIL",
    extra: { start: [277, 225], temp: -25, pressure: 35, par: 175 },
  },
  {
    targets: [
      t(
        "puddleForm",
        "Read the puddle's exceptional application",
        "melt",
        285,
        225,
        100,
        65,
      ),
      t(
        "leafForm",
        "Read the leaf's exceptional application",
        "melt",
        645,
        235,
        100,
        65,
      ),
      t(
        "moonbeamForm",
        "Read the moonbeam's exceptional application",
        "melt",
        435,
        395,
        100,
        60,
      ),
      warm(
        "newForm",
        "Make a little room for everyone",
        480,
        310,
        [25, 35],
        [15, 30],
        ["puddleForm", "leafForm", "moonbeamForm"],
      ),
      t(
        "charterBase",
        "Build the welcoming charter display",
        "freeze",
        270,
        475,
        200,
        40,
        { requires: ["newForm"] },
      ),
    ],
    props: [
      p("receipt", 335, 280, "puddleForm", { tint: "#a6cad3", scale: 0.75 }),
      p("receipt", 695, 290, "leafForm", { tint: "#b7ca99", scale: 0.75 }),
      p("receipt", 485, 447, "moonbeamForm", { tint: "#d3c4dc", scale: 0.75 }),
      p("stamp", 532, 363, "newForm", { scale: 0.75 }),
      p("townsign", 370, 458, "charterBase", { scale: 0.9, revealOnly: true }),
      p("eraser", 660, 415, undefined, { scale: 0.95, revealOnly: true }),
    ],
    stamp: "TELL US ABOUT YOURSELF. THERE'S ROOM.",
    extra: { start: [335, 165], par: 180 },
  },
  {
    targets: [
      t(
        "ice",
        "Build the calibrated ice counterweight",
        "freeze",
        600,
        380,
        140,
        65,
      ),
      t(
        "water",
        "Fill the matching collection pan",
        "fill",
        260,
        380,
        140,
        65,
        { requires: ["ice"] },
      ),
      warm(
        "certificate",
        "Certify one fairly shared biscuit",
        440,
        440,
        [20, 35],
        [15, 25],
        ["ice", "water"],
        {
          h: 55,
          needsSignals: ["scale"],
        },
      ),
    ],
    props: [
      p("ruler", 740, 320, undefined, { scale: 0.65 }),
      p("biscuit", 480, 185, undefined, { scale: 0.95, revealOnly: true }),
      p("stamp", 492, 490, "certificate", { scale: 0.7 }),
    ],
    stamp: "MUNICIPAL BISCUIT: CERTIFIED FAIRLY SHARED",
    extra: {
      start: [670, 320],
      temp: -25,
      pressure: 35,
      par: 150,
      balance: {
        id: "scale",
        x: 480,
        y: 260,
        arm: 110,
        left: { target: "water", mass: 5 },
        right: { target: "ice", mass: 5 },
      },
    },
  },
  {
    targets: [
      t(
        "leftSeat",
        "Build a seat for the shade provider",
        "freeze",
        245,
        445,
        120,
        40,
      ),
      t(
        "middleSeat",
        "Build a seat for a reflected neighbor",
        "freeze",
        425,
        445,
        120,
        40,
      ),
      t(
        "rightSeat",
        "Build a seat for the evening sparkle",
        "freeze",
        605,
        445,
        120,
        40,
      ),
      t(
        "leafWelcome",
        "Thaw the leaf-shaped welcome",
        "melt",
        300,
        230,
        85,
        75,
        {
          requires: ["leftSeat", "middleSeat", "rightSeat"],
        },
      ),
      t(
        "starWelcome",
        "Thaw the star-shaped welcome",
        "melt",
        595,
        230,
        85,
        75,
        {
          requires: ["leftSeat", "middleSeat", "rightSeat"],
        },
      ),
      t(
        "refreshments",
        "Fill the neighborhood meeting basin",
        "fill",
        425,
        340,
        170,
        65,
        {
          requires: ["leafWelcome", "starWelcome"],
        },
      ),
    ],
    props: [
      p("townsign", 342, 298, "leafWelcome", { tint: "#b7ca99", scale: 0.65 }),
      p("townsign", 637, 298, "starWelcome", { tint: "#d3c4dc", scale: 0.65 }),
      p("cup", 510, 400, "refreshments", { scale: 1.0 }),
      p("leafbug", 305, 430, undefined, { scale: 0.65, revealOnly: true }),
      p("puddle", 485, 480, undefined, { scale: 0.65, revealOnly: true }),
      p("moon", 665, 415, undefined, { scale: 0.4, revealOnly: true }),
    ],
    stamp: "REFLECTIONS ARE NEIGHBORS TOO",
    extra: { start: [305, 385], temp: -25, pressure: 35, par: 195 },
  },
  {
    targets: [
      t(
        "upperMirror",
        "Build the upper-right mirror",
        "freeze",
        680,
        190,
        60,
        60,
      ),
      t(
        "lowerMirror",
        "Build the lower-right mirror",
        "freeze",
        680,
        360,
        60,
        60,
      ),
      t(
        "aperture",
        "Carve the frozen lamp aperture",
        "melt",
        450,
        195,
        95,
        50,
        {
          requires: ["upperMirror", "lowerMirror"],
        },
      ),
      warm(
        "signature",
        "Sign for an excellent patch of sunshine",
        440,
        410,
        [25, 35],
        [15, 30],
        ["upperMirror", "lowerMirror", "aperture"],
        {
          needsSignals: ["sunlight"],
        },
      ),
    ],
    props: [
      p("stamp", 492, 462, "signature", { scale: 0.7 }),
      p("scarf", 335, 460, undefined, {
        scale: 0.85,
        tint: "#efdbac",
        revealOnly: true,
      }),
      p("biscuit", 335, 425, undefined, { scale: 0.65, revealOnly: true }),
      p("pencil", 585, 315, undefined, { scale: 0.65 }),
    ],
    stamp: "SUNSHINE OCCUPANCY: LUNCH APPROVED",
    extra: {
      start: [710, 135],
      temp: -25,
      pressure: 35,
      par: 175,
      optics: {
        source: { x: 250, y: 220, dx: 1, dy: 0 },
        mirrors: [
          {
            target: "upperMirror",
            x: 710,
            y: 220,
            angle: Math.PI / 4,
            length: 80,
          },
          {
            target: "lowerMirror",
            x: 710,
            y: 390,
            angle: -Math.PI / 4,
            length: 80,
          },
        ],
        detectors: [{ id: "sunlight", x: 250, y: 390, radius: 18 }],
      },
    },
  },
  {
    targets: [
      t(
        "gardenNotice",
        "Thaw the garden-hours notice",
        "melt",
        235,
        205,
        110,
        55,
      ),
      t(
        "cafeNotice",
        "Thaw the shared-crumbs notice",
        "melt",
        435,
        285,
        110,
        55,
      ),
      t(
        "caveNotice",
        "Thaw the quiet-visits notice",
        "melt",
        635,
        195,
        110,
        55,
      ),
      warm(
        "garden",
        "A gentle welcome to the garden",
        245,
        355,
        [20, 30],
        [10, 25],
        ["gardenNotice"],
      ),
      warm(
        "cafe",
        "A comfortably warm cafe welcome",
        445,
        425,
        [35, 45],
        [20, 35],
        ["cafeNotice"],
      ),
      warm(
        "cave",
        "A considerate welcome to the cave",
        645,
        330,
        [25, 35],
        [15, 30],
        ["caveNotice"],
      ),
    ],
    props: [
      p("townsign", 290, 255, "gardenNotice", { tint: "#b7ca99", scale: 0.65 }),
      p("townsign", 490, 335, "cafeNotice", { tint: "#d3b474", scale: 0.65 }),
      p("townsign", 690, 245, "caveNotice", { tint: "#b5bbd3", scale: 0.65 }),
      p("flower", 297, 402, "garden", { scale: 0.75 }),
      p("biscuit", 497, 468, "cafe", { scale: 0.65 }),
      p("microphone", 697, 386, "cave", { scale: 0.7 }),
      p("receipt", 520, 205, undefined, { scale: 0.8, revealOnly: true }),
    ],
    stamp: "IT IS FINE TO ASK US THINGS",
    extra: { start: [290, 145], par: 195 },
  },
  {
    targets: [
      t(
        "watering",
        "Fill the shared square's watering basin",
        "fill",
        235,
        400,
        180,
        65,
      ),
      t(
        "dayTable",
        "Build a table for the daytime neighbors",
        "freeze",
        550,
        365,
        100,
        45,
      ),
      t(
        "eveningTable",
        "Build a table for the evening neighbors",
        "freeze",
        685,
        440,
        100,
        45,
      ),
      t("route", "Thaw the route to the commons", "melt", 280, 215, 120, 65),
      t(
        "houseLight",
        "Light the square for every neighbor",
        "spin",
        465,
        275,
        80,
        70,
        {
          requires: ["watering", "dayTable", "eveningTable", "route"],
        },
      ),
    ],
    props: [
      p("cup", 325, 460, "watering", { scale: 1.05 }),
      p("townsign", 340, 275, "route", { scale: 0.75 }),
      p("spotlight", 505, 372, "houseLight", { scale: 0.8 }),
      p("leafbug", 600, 350, "dayTable", { scale: 0.75, revealOnly: true }),
      p("moon", 735, 410, "eveningTable", { scale: 0.45, revealOnly: true }),
      p("puddle", 485, 475, undefined, { scale: 0.75, revealOnly: true }),
    ],
    stamp: "SHADE BY DAY. SPARKLE BY EVENING.",
    extra: { start: [325, 340], temp: 35, pressure: 45, par: 180 },
  },
  {
    targets: [
      t(
        "archive",
        "Build the archive for kindly retired ideas",
        "freeze",
        235,
        405,
        120,
        70,
      ),
      t(
        "upperForm",
        "Carve through the unnecessary form",
        "melt",
        455,
        195,
        145,
        100,
      ),
      t(
        "lowerForm",
        "Reach the form's equally unnecessary copy",
        "melt",
        490,
        320,
        115,
        70,
      ),
      t(
        "basin",
        "Collect the water beneath the forms",
        "fill",
        455,
        435,
        190,
        65,
      ),
      warm(
        "document",
        "Give the last form a kind retirement",
        685,
        315,
        [20, 30],
        [10, 25],
        ["archive", "upperForm", "lowerForm", "basin"],
      ),
    ],
    props: [
      p("archive", 295, 460, "archive", { scale: 0.95, revealOnly: true }),
      p("receipt", 527, 275, "upperForm", {
        scale: 1.05,
        reveal: { x: 295, y: 355, scale: 0.55 },
      }),
      p("receipt", 547, 375, "lowerForm", {
        scale: 0.8,
        reveal: { x: 310, y: 375, scale: 0.55 },
      }),
      p("cup", 550, 495, "basin", { scale: 1.05 }),
      p("stamp", 737, 368, "document", { scale: 0.75 }),
      p("eraser", 370, 270, undefined, { scale: 0.8 }),
    ],
    stamp: "FILED UNDER: IDEAS WE HAVE KINDLY OUTGROWN",
    extra: { start: [295, 345], temp: -25, pressure: 35, par: 185 },
  },
  {
    targets: [
      t(
        "charter",
        "Thaw the charter of the welcome mat",
        "melt",
        395,
        205,
        155,
        80,
      ),
      t(
        "welcome",
        "Fill the neighborhood welcome basin",
        "fill",
        245,
        425,
        165,
        65,
        { requires: ["charter"] },
      ),
      t(
        "display",
        "Build the shared charter display",
        "freeze",
        610,
        445,
        150,
        45,
        { requires: ["charter"] },
      ),
      warm(
        "quill",
        "Make room for Quill's signature",
        270,
        310,
        [20, 30],
        [10, 25],
        ["welcome", "display"],
      ),
      warm(
        "midge",
        "Make room for Midge's signature",
        625,
        310,
        [35, 45],
        [25, 40],
        ["welcome", "display"],
      ),
    ],
    props: [
      p("receipt", 472, 270, "charter", {
        scale: 1.2,
        reveal: { x: 485, y: 310, scale: 1.6 },
      }),
      p("cup", 327, 485, "welcome", { scale: 1.0 }),
      p("townsign", 685, 430, "display", { scale: 0.8, revealOnly: true }),
      p("stamp", 322, 362, "quill", { tint: "#b3c7ce", scale: 0.75 }),
      p("stamp", 677, 362, "midge", { tint: "#d7bd86", scale: 0.75 }),
      p("leafbug", 380, 420, undefined, { scale: 0.6, revealOnly: true }),
      p("puddle", 480, 480, undefined, { scale: 0.8, revealOnly: true }),
      p("moon", 600, 220, undefined, { scale: 0.4, revealOnly: true }),
      p("biscuit", 555, 430, undefined, { scale: 0.25, revealOnly: true }),
    ],
    stamp: "IF YOU ARE HERE, PULL UP A CHAIR",
    extra: { start: [472, 145], par: 185 },
  },
];

// Keep the arrival joke short; the exact source puzzle stays in the help panel.
const dispatches = [
  "Quill's window is frozen shut. He has already prepared the sign OPEN TO REASON, which seems promising.",
  "The counter is taller than several citizens. Quill suspects reaching it should not require a permit.",
  "The public fountain is a teacup. Inspector Pin has brought a smaller teacup to test its publicness.",
  "Mayor Midge is opening the fan office. Her ribbon is larger than the office and has become rather attached to its bow.",
  "Three archive copies have frozen together. Quill hopes at least one explains why there are three archive copies.",
  "The puddle would like a permanent address. Inspector Pin is delighted to meet someone who shares his best reflection.",
  "One stamp offers quiet support. The other offers confetti. Quill insists both are entirely sincere.",
  "There is a queue for the queue-free window. Quill has a chair, a teacup, and a much better idea.",
  "A cafe beneath one biscuit has applied for zoning. Inspector Pin is bringing his largest appetite and smallest magnifying glass.",
  "The walking leaf would like to put down roots. Figuratively. It has several appointments this afternoon.",
  "A cave echo has applied to live here, live here. Midge thinks its welcome should be worth repeating.",
  "The moonbeam's address is almost legible. Quill has narrowed it down to somewhere after the pencil.",
  "The puddle, leaf, and moonbeam have all ticked OTHER. Quill wonders whether the form could ask a better question.",
  "Inspector Pin wants one municipal biscuit shared fairly. His measuring equipment is taking this very seriously.",
  "Midge has invited every neighbor to the meeting. The puddle has asked whether its reflection may have a chair.",
  "A patch of sunshine has applied to occupy Midge's picnic napkin. The proposed use is lunch.",
  "Today's public notices contain free shade, shared crumbs, and welcome echoes. Quill is considering a larger noticeboard.",
  "The leaf has offered the daytime shade shift. The moonbeam has offered evenings. The square is beginning to feel like a neighborhood.",
  "Quill has found a form requesting permission to enjoy the square. He knows exactly where it belongs.",
  "Midge's new charter has room for paws, leaves, reflections, and one carefully measured crumb. Quill has put away the species boxes.",
];
const source = designs.packs.find((pack) => pack.id === "05")!;
export const boroughLevels: Level[] = recipes.map((recipe, i) => {
  const card = source.scenes[i];
  return {
    id: card.id,
    pack: "05",
    name: card.title,
    chapter: source.title,
    theme: "borough",
    pitch: dispatches[i],
    hint: card.puzzle.replace(/With (BALANCE|OPTICS)( enabled)?, /g, ""),
    ending: card.payoff,
    start: [475, 145],
    temp: 65,
    pressure: 45,
    par: 50 + recipe.targets.length * 22,
    targets: recipe.targets,
    props: [...cast(), ...recipe.props],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
