import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/02-06.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 105, 60, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.8, ...extra });
const cast = (): Prop[] => [
  p("pudding", 135, 305, undefined, { scale: 0.8, reveal: { x: 245, y: 430 } }),
  p("biscuitcaptain", 835, 275, undefined, {
    scale: 0.8,
    reveal: { x: 745, y: 425 },
  }),
  p("jellybean", 850, 465, undefined, {
    scale: 0.8,
    reveal: { x: 635, y: 470 },
  }),
];
const recipes: {
  targets: Target[];
  props: Prop[];
  stamp: string;
  extra?: Partial<Level>;
}[] = [
  {
    targets: [
      t(
        "petition",
        "Thaw President Wobble's petition",
        "melt",
        290,
        220,
        165,
        95,
      ),
      warm(
        "signature",
        "Prepare the caramel signature",
        610,
        410,
        [25, 40],
        [15, 30],
        ["petition"],
      ),
    ],
    props: [
      p("recipe", 372, 300, "petition", { scale: 1.05 }),
      p("spoon", 662, 462, "signature", { scale: 0.75 }),
      p("wafer", 535, 330, undefined, { scale: 0.85 }),
      p("biscuit", 520, 415, undefined, { scale: 0.25, revealOnly: true }),
    ],
    stamp: "BREAKFAST IS ALSO A TIME. CRUMB, FULL STOP.",
    extra: { start: [372, 160], par: 85 },
  },
  {
    targets: [
      t(
        "leftPlinth",
        "Build the first serving plinth",
        "freeze",
        245,
        435,
        175,
        50,
      ),
      t(
        "rightPlinth",
        "Build the second serving plinth",
        "freeze",
        570,
        435,
        175,
        50,
      ),
      t(
        "speakingCard",
        "Unveil the president's opening remarks",
        "melt",
        430,
        235,
        125,
        75,
        { requires: ["leftPlinth", "rightPlinth"] },
      ),
    ],
    props: [
      p("recipe", 492, 295, "speakingCard", { scale: 0.85 }),
      p("spoon", 492, 425, undefined, {
        scale: 1.15,
        reveal: { x: 410, y: 340 },
      }),
      p("wafer", 330, 405, "leftPlinth", { scale: 0.6, revealOnly: true }),
      p("wafer", 657, 405, "rightPlinth", { scale: 0.6, revealOnly: true }),
    ],
    stamp: "MINUTES: UNANIMOUS ENTHUSIASM, WITH WOBBLING",
    extra: { start: [332, 375], temp: -25, pressure: 35, par: 115 },
  },
  {
    targets: [
      t("recipe", "Read the public jelly recipe", "melt", 450, 305, 100, 65),
      t(
        "publicTray",
        "Fill the enormous public jelly tray",
        "fill",
        235,
        420,
        215,
        65,
        { requires: ["recipe"] },
      ),
      t(
        "tastingCup",
        "Fill the tall quality-control cup",
        "fill",
        655,
        215,
        65,
        90,
        { requires: ["recipe"] },
      ),
    ],
    props: [
      p("recipe", 500, 358, "recipe", { scale: 0.75 }),
      p("cup", 342, 478, "publicTray", { scale: 1.25 }),
      p("cup", 687, 298, "tastingCup", { scale: 0.55 }),
      p("jellybean", 390, 407, "publicTray", {
        tint: "#c595b9",
        scale: 0.55,
        revealOnly: true,
      }),
      p("jellybean", 682, 275, "tastingCup", {
        tint: "#c595b9",
        scale: 0.25,
        revealOnly: true,
      }),
    ],
    stamp: "TWO THUMBS-UP. SAME VERY SMALL THUMB.",
    extra: { start: [500, 245], par: 120 },
  },
  {
    targets: [
      t("whisk", "Whisk up a smooth majority", "spin", 255, 305, 85, 75),
      warm(
        "custard",
        "Give the custard time to agree",
        635,
        380,
        [30, 45],
        [15, 30],
      ),
    ],
    props: [
      p("whisk", 297, 420, "whisk", { scale: 1.15 }),
      p("cup", 687, 438, "custard", { scale: 0.8 }),
      p("spoon", 485, 305, undefined, {
        scale: 1.2,
        reveal: { x: 480, y: 405 },
      }),
      p("recipe", 475, 460, undefined, { scale: 0.75, revealOnly: true }),
    ],
    stamp: "CONSENSUS: PLEASANTLY SMOOTH",
    extra: { start: [297, 245], temp: 50, pressure: 85, par: 105 },
  },
  {
    targets: [
      t(
        "upperMinutes",
        "Carve a channel into the cake archive",
        "melt",
        505,
        200,
        155,
        100,
      ),
      t(
        "lowerMinutes",
        "Reach the minutes between the lower layers",
        "melt",
        545,
        340,
        120,
        100,
      ),
      warm(
        "archive",
        "Preserve the full range of spoon debate",
        280,
        410,
        [20, 30],
        [10, 25],
        ["upperMinutes", "lowerMinutes"],
      ),
    ],
    props: [
      p("layercake", 582, 285, "upperMinutes", { scale: 0.85 }),
      p("layercake", 605, 422, "lowerMinutes", { scale: 0.8 }),
      p("recipe", 332, 463, "archive", {
        scale: 0.85,
        reveal: { x: 400, y: 320 },
      }),
      p("wafer", 475, 450, undefined, { scale: 0.8 }),
      p("spoon", 430, 245, undefined, { scale: 0.7, revealOnly: true }),
    ],
    stamp: "FOUNDING DEBATE: SPOON, WITH POSSIBLE FORK",
    extra: { start: [595, 140], par: 135 },
  },
  {
    targets: [
      warm(
        "custard",
        "Custard prefers gentle company",
        235,
        385,
        [20, 30],
        [10, 25],
      ),
      warm(
        "cocoa",
        "Cocoa prefers a toastier welcome",
        635,
        220,
        [45, 60],
        [30, 45],
      ),
      t(
        "platter",
        "Build one platter for two opinions",
        "freeze",
        420,
        460,
        175,
        45,
        { requires: ["custard", "cocoa"] },
      ),
    ],
    props: [
      p("cup", 287, 441, "custard", {
        tint: "#e9cc83",
        scale: 0.8,
        reveal: { x: 455, y: 408 },
      }),
      p("cup", 687, 276, "cocoa", {
        tint: "#a97865",
        scale: 0.8,
        reveal: { x: 555, y: 408 },
      }),
      p("recipe", 370, 270, undefined, { scale: 0.8 }),
      p("wafer", 507, 455, "platter", { scale: 0.95, revealOnly: true }),
    ],
    stamp: "AGREEMENT NEED NOT HAVE IDENTICAL TOPPINGS",
    extra: { start: [287, 325], temp: 25, pressure: 17, par: 130 },
  },
  {
    targets: [
      t(
        "preparationLabel",
        "Thaw the biscuit-preparation label",
        "melt",
        245,
        215,
        110,
        65,
      ),
      t(
        "seatingLabel",
        "Thaw the easy-access seating label",
        "melt",
        650,
        205,
        110,
        65,
      ),
      t(
        "preparation",
        "Fill the invitation preparation basin",
        "fill",
        230,
        385,
        190,
        65,
        { requires: ["preparationLabel"] },
      ),
      t(
        "seat",
        "Build a seat without a fork climb",
        "freeze",
        495,
        435,
        140,
        45,
        { requires: ["seatingLabel"] },
      ),
      warm(
        "invitation",
        "Care for the large clear crumb symbol",
        440,
        285,
        [20, 35],
        [10, 25],
        ["preparation", "seat"],
      ),
    ],
    props: [
      p("recipe", 300, 270, "preparationLabel", { scale: 0.75 }),
      p("recipe", 705, 260, "seatingLabel", { scale: 0.75 }),
      p("cup", 325, 443, "preparation", { scale: 1.05 }),
      p("biscuit", 492, 335, "invitation", { scale: 1.0 }),
      p("spoon", 720, 430, undefined, {
        scale: 0.9,
        reveal: { x: 585, y: 365 },
      }),
    ],
    stamp: "LARGE PRINT. LOW SEAT. NO FORK CLIMB.",
    extra: { start: [300, 155], par: 175 },
  },
  {
    targets: [
      t(
        "firstSeat",
        "Build the eclair's low seat",
        "freeze",
        245,
        445,
        125,
        40,
      ),
      t(
        "middleSeat",
        "Build the eclair's middle seat",
        "freeze",
        405,
        395,
        125,
        40,
      ),
      t(
        "lastSeat",
        "Build the eclair's high seat",
        "freeze",
        565,
        345,
        125,
        40,
      ),
      t(
        "nameplate",
        "Unfreeze a generously margined name tag",
        "melt",
        710,
        225,
        75,
        70,
        { requires: ["firstSeat", "middleSeat", "lastSeat"] },
      ),
    ],
    props: [
      p("eclair", 455, 290, undefined, {
        scale: 1.45,
        reveal: { x: 475, y: 310, scale: 1.6 },
      }),
      p("recipe", 747, 280, "nameplate", {
        scale: 0.55,
        reveal: { x: 195, y: 255, scale: 1.0 },
      }),
      p("scarf", 330, 390, undefined, { scale: 0.5, revealOnly: true }),
      p("scarf", 495, 430, undefined, { scale: 0.5, revealOnly: true }),
      p("scarf", 665, 405, undefined, { scale: 0.5, revealOnly: true }),
    ],
    stamp: "ONE NAME TAG. THREE POLITE NAPKIN OPINIONS.",
    extra: { start: [307, 385], temp: -25, pressure: 35, par: 150 },
  },
  {
    targets: [
      t(
        "guestCard",
        "Read the savory ambassador's guest card",
        "melt",
        245,
        210,
        120,
        65,
      ),
      t("rinse", "Fill the welcome rinse basin", "fill", 230, 385, 190, 65, {
        requires: ["guestCard"],
      }),
      warm(
        "wrapper",
        "A gentle welcome for the wrapper",
        470,
        280,
        [25, 35],
        [15, 25],
        ["rinse"],
      ),
      warm(
        "tea",
        "A toastier cup of welcome tea",
        645,
        410,
        [40, 50],
        [25, 40],
        ["rinse"],
      ),
    ],
    props: [
      p("recipe", 305, 265, "guestCard", { scale: 0.8 }),
      p("cup", 325, 443, "rinse", { scale: 1.05 }),
      p("dumpling", 522, 332, "wrapper", {
        scale: 0.9,
        reveal: { x: 490, y: 360 },
      }),
      p("cup", 697, 466, "tea", { scale: 0.8 }),
      p("jellybean", 490, 295, undefined, { scale: 0.2, revealOnly: true }),
    ],
    stamp: "SAVORY AMBASSADOR. HONORARY SPRINKLE HAT.",
    extra: { start: [305, 150], par: 160 },
  },
  {
    targets: [
      t(
        "firstDelegate",
        "Thaw the first strawberry's name",
        "melt",
        245,
        205,
        85,
        60,
      ),
      t(
        "secondDelegate",
        "Thaw the second strawberry's name",
        "melt",
        390,
        280,
        85,
        60,
      ),
      t(
        "thirdDelegate",
        "Thaw the third strawberry's name",
        "melt",
        535,
        355,
        85,
        60,
      ),
      t(
        "watering",
        "Fill the garden delegation's basin",
        "fill",
        285,
        450,
        240,
        60,
        { requires: ["firstDelegate", "secondDelegate", "thirdDelegate"] },
      ),
      warm(
        "berries",
        "Care for the picnic steering committee",
        675,
        300,
        [20, 30],
        [10, 25],
        ["watering"],
      ),
    ],
    props: [
      p("recipe", 287, 255, "firstDelegate", { scale: 0.65 }),
      p("recipe", 432, 330, "secondDelegate", { scale: 0.65 }),
      p("recipe", 577, 405, "thirdDelegate", { scale: 0.65 }),
      p("cup", 405, 505, "watering", { scale: 1.15 }),
      ...[365, 475, 585].map((x) =>
        p("strawberry", x, 355, undefined, { scale: 0.7, revealOnly: true }),
      ),
      p("sun", 475, 255, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "THREE DELEGATES. ONE EXCELLENT PICNIC SPOT.",
    extra: { start: [287, 145], par: 180 },
  },
  {
    targets: [
      t(
        "leftScore",
        "Thaw the choir's opening crunch",
        "melt",
        235,
        225,
        130,
        70,
      ),
      t(
        "rightScore",
        "Thaw the choir's answering crunch",
        "melt",
        650,
        225,
        130,
        70,
      ),
      t(
        "firstStand",
        "Build the first crystalline music stand",
        "freeze",
        380,
        415,
        75,
        40,
        { requires: ["leftScore", "rightScore"] },
      ),
      t(
        "middleStand",
        "Build the middle music stand",
        "freeze",
        475,
        445,
        75,
        40,
        { requires: ["leftScore", "rightScore"] },
      ),
      t("lastStand", "Build the low music stand", "freeze", 565, 470, 75, 40, {
        requires: ["leftScore", "rightScore"],
      }),
      t(
        "chorus",
        "Start the wonderfully crunchy chorus",
        "spin",
        485,
        290,
        60,
        70,
        { requires: ["firstStand", "middleStand", "lastStand"] },
      ),
    ],
    props: [
      p("recipe", 300, 285, "leftScore", { scale: 0.85 }),
      p("recipe", 715, 285, "rightScore", { scale: 0.85 }),
      p("whisk", 515, 390, "chorus", { scale: 0.75 }),
      p("wafer", 417, 400, "firstStand", {
        tint: "#bee0d7",
        scale: 0.5,
        revealOnly: true,
      }),
      p("wafer", 512, 430, "middleStand", {
        tint: "#d9cde1",
        scale: 0.5,
        revealOnly: true,
      }),
      p("wafer", 602, 455, "lastStand", {
        tint: "#d9dfb5",
        scale: 0.5,
        revealOnly: true,
      }),
      p("scarf", 310, 410, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "PERCUSSION SECTION: PLEASE TAKE A NAPKIN",
    extra: { start: [300, 165], par: 195 },
  },
  {
    targets: [
      t(
        "leftStrip",
        "Open the parcel's first frosted strip",
        "melt",
        320,
        205,
        55,
        110,
      ),
      t(
        "rightStrip",
        "Open the parcel's second frosted strip",
        "melt",
        440,
        230,
        55,
        110,
      ),
      t(
        "collection",
        "Collect water beneath the cosmic parcel",
        "fill",
        280,
        410,
        240,
        65,
      ),
      warm(
        "starlightLabel",
        "Read the outer-pantry breakfast request",
        640,
        385,
        [30, 40],
        [15, 30],
        ["leftStrip", "rightStrip", "collection"],
      ),
    ],
    props: [
      p("parcel", 407, 340, undefined, {
        scale: 1.05,
        reveal: { x: 440, y: 330 },
      }),
      p("recipe", 692, 435, "starlightLabel", { scale: 0.8 }),
      p("cup", 400, 470, "collection", { scale: 1.2 }),
      ...[350, 450, 550].map((x, i) =>
        p("moon", x, 225 + (i % 2) * 30, undefined, {
          scale: 0.3,
          revealOnly: true,
        }),
      ),
    ],
    stamp: "OUTER PANTRY: NEXT STOP, BREAKFAST",
    extra: { start: [347, 145], par: 150 },
  },
  {
    targets: [
      warm(
        "jelly",
        "Jelly votes for a gentle tasting",
        235,
        205,
        [15, 25],
        [10, 20],
      ),
      warm(
        "cocoa",
        "Cocoa votes for a toastier tasting",
        630,
        305,
        [45, 60],
        [35, 50],
      ),
      warm(
        "custard",
        "Custard has a comfortable third opinion",
        270,
        405,
        [25, 35],
        [15, 30],
      ),
      t(
        "menu",
        "Build a menu with room for every opinion",
        "freeze",
        440,
        470,
        325,
        40,
        { requires: ["jelly", "cocoa", "custard"] },
      ),
    ],
    props: [
      p("cup", 287, 260, "jelly", { scale: 0.7, reveal: { x: 420, y: 395 } }),
      p("cup", 682, 360, "cocoa", { scale: 0.7, reveal: { x: 540, y: 395 } }),
      p("cup", 322, 460, "custard", { scale: 0.7, reveal: { x: 660, y: 395 } }),
      p("recipe", 600, 455, "menu", { scale: 1.3, revealOnly: true }),
      p("spoon", 470, 250, undefined, { scale: 0.85 }),
    ],
    stamp: "TASTING NOTES: THREE DISAGREEMENTS, THREE DISHES",
    extra: { start: [287, 145], temp: 20, pressure: 15, par: 175 },
  },
  {
    targets: [
      t("mold", "Build the ice mold", "freeze", 325, 245, 220, 210, {
        phase: {
          steps: [
            {
              verb: "freeze",
              name: "Build the ice mold",
              signal: "mold:formed",
            },
            {
              verb: "melt",
              name: "Open the finished mold",
              requires: ["basin"],
              signal: "mold:open",
            },
          ],
        },
      }),
      t(
        "basin",
        "Fill the formed mold's preparation basin",
        "fill",
        375,
        330,
        120,
        65,
        {
          needsSignals: ["mold:formed"],
        },
      ),
      warm(
        "release",
        "Give the pudding a gentle release",
        625,
        370,
        [25, 35],
        [15, 25],
        ["mold", "basin"],
        {
          needsSignals: ["mold:open"],
        },
      ),
    ],
    props: [
      p("wafer", 290, 410, undefined, {
        scale: 1.0,
        reveal: { x: 315, y: 410 },
      }),
      p("wafer", 580, 410, undefined, { scale: 1.0 }),
      p("pudding", 435, 480, "mold", {
        scale: 0.95,
        revealOnly: true,
        reveal: { x: 465, y: 480, scale: 1.1 },
      }),
      p("spoon", 677, 425, "release", { scale: 0.75 }),
      p("recipe", 685, 235, undefined, { scale: 0.85 }),
    ],
    stamp: "THANK YOU, MOLD. EXCELLENT PERSONAL GROWTH.",
    extra: { start: [435, 185], temp: -25, pressure: 35, par: 195 },
  },
  {
    targets: [
      t("pinkRecipe", "Thaw the pink icing recipe", "melt", 205, 200, 85, 50),
      t("goldRecipe", "Thaw the golden icing recipe", "melt", 345, 310, 85, 50),
      t("blueRecipe", "Thaw the blue icing recipe", "melt", 465, 420, 85, 50),
      t(
        "pinkIcing",
        "Fill the upper pink-icing basin",
        "fill",
        320,
        195,
        125,
        65,
        { requires: ["pinkRecipe"] },
      ),
      t(
        "goldIcing",
        "Fill the middle golden-icing basin",
        "fill",
        460,
        305,
        125,
        65,
        { requires: ["goldRecipe"] },
      ),
      t(
        "blueIcing",
        "Fill the lower blue-icing basin",
        "fill",
        580,
        415,
        125,
        65,
        { requires: ["blueRecipe"] },
      ),
      t(
        "whisk",
        "Whisk an inclusive icing moustache",
        "spin",
        750,
        455,
        60,
        60,
        { requires: ["pinkIcing", "goldIcing", "blueIcing"] },
      ),
    ],
    props: [
      p("recipe", 247, 242, "pinkRecipe", { tint: "#da9fae", scale: 0.6 }),
      p("recipe", 387, 352, "goldRecipe", { tint: "#ddc083", scale: 0.6 }),
      p("recipe", 507, 462, "blueRecipe", { tint: "#a5c4d2", scale: 0.6 }),
      p("cup", 382, 253, "pinkIcing", { scale: 0.75 }),
      p("cup", 522, 363, "goldIcing", { scale: 0.75 }),
      p("cup", 642, 473, "blueIcing", { scale: 0.75 }),
      p("whisk", 780, 510, "whisk", { scale: 0.65 }),
      ...[380, 485, 590].map((x) =>
        p("spoon", x, 395, undefined, { scale: 0.5, revealOnly: true }),
      ),
    ],
    stamp: "THREE ICINGS. ONE VERY INCLUSIVE MOUSTACHE.",
    extra: { start: [247, 140], par: 205 },
  },
  {
    targets: [
      t(
        "far",
        "Fill the far pancake basin from the inlet",
        "fill",
        635,
        270,
        140,
        60,
        { flowOnly: true },
      ),
      t(
        "spillway",
        "Open the full basin's overflow spillway",
        "melt",
        575,
        355,
        65,
        50,
        { requires: ["far"] },
      ),
      t(
        "near",
        "Send surplus along the return spillway",
        "fill",
        360,
        435,
        160,
        60,
        { flowOnly: true, requires: ["spillway"] },
      ),
    ],
    props: [
      p("pancake", 705, 325, "far", { scale: 0.9, reveal: { x: 605, y: 350 } }),
      p("wafer", 607, 397, "spillway", { scale: 0.45 }),
      p("pancake", 440, 489, "near", {
        scale: 0.95,
        reveal: { x: 420, y: 405 },
      }),
      p("recipe", 260, 375, undefined, { scale: 0.9, revealOnly: true }),
      p("letter", 560, 465, undefined, { scale: 0.7, revealOnly: true }),
    ],
    stamp: "SYRUP SCENIC ROUTE. BREAKFAST PLUMBING INVITED.",
    extra: {
      start: [295, 115],
      temp: 45,
      pressure: 65,
      par: 190,
      channels: {
        inlet: { x: 245, y: 170, w: 100, h: 40 },
        junction: [375, 245],
        branches: [
          {
            target: "far",
            via: [
              [435, 245],
              [500, 200],
              [705, 200],
            ],
          },
          {
            target: "near",
            gate: "spillway",
            overflowFrom: "far",
            via: [
              [435, 245],
              [500, 200],
              [705, 200],
              [705, 300],
              [705, 340],
              [607, 380],
              [520, 390],
              [440, 410],
            ],
          },
        ],
      },
    },
  },
  {
    targets: [
      t(
        "sweetHeading",
        "Thaw the sweet menu heading",
        "melt",
        235,
        225,
        110,
        65,
      ),
      t(
        "savoryHeading",
        "Thaw the savory menu heading",
        "melt",
        435,
        225,
        110,
        65,
      ),
      t(
        "undecidedHeading",
        "Thaw the take-your-time heading",
        "melt",
        635,
        225,
        110,
        65,
      ),
      warm(
        "sweet",
        "Make room for something sweet",
        240,
        390,
        [20, 30],
        [10, 25],
        ["sweetHeading"],
      ),
      warm(
        "savory",
        "Make room for something savory",
        440,
        390,
        [40, 50],
        [25, 40],
        ["savoryHeading"],
      ),
      warm(
        "undecided",
        "Make room for taking your time",
        640,
        390,
        [30, 40],
        [15, 30],
        ["undecidedHeading"],
      ),
    ],
    props: [
      p("recipe", 290, 280, "sweetHeading", { tint: "#dca3b6", scale: 0.8 }),
      p("recipe", 490, 280, "savoryHeading", { tint: "#d7c18c", scale: 0.8 }),
      p("recipe", 690, 280, "undecidedHeading", {
        tint: "#b4cbd2",
        scale: 0.8,
      }),
      p("strawberry", 292, 445, "sweet", { scale: 0.8 }),
      p("dumpling", 492, 445, "savory", { scale: 0.8 }),
      p("cup", 692, 445, "undecided", { scale: 0.8 }),
      p("scarf", 695, 480, undefined, { scale: 0.6, revealOnly: true }),
    ],
    stamp: "TRY THIS. OR THIS. TAKE YOUR TIME.",
    extra: { start: [290, 165], par: 200 },
  },
  {
    targets: [
      t(
        "leftExtension",
        "Build the left breakfast-table extension",
        "freeze",
        235,
        420,
        155,
        45,
      ),
      t(
        "rightExtension",
        "Build the right breakfast-table extension",
        "freeze",
        620,
        420,
        155,
        45,
      ),
      t(
        "guestList",
        "Open the long breakfast guest list",
        "melt",
        440,
        215,
        95,
        75,
        { requires: ["leftExtension", "rightExtension"] },
      ),
      t(
        "waterService",
        "Catch the welcome water beneath the list",
        "fill",
        445,
        335,
        85,
        65,
      ),
      warm(
        "tableService",
        "Prepare the expanded breakfast service",
        425,
        445,
        [25, 40],
        [15, 30],
        ["leftExtension", "rightExtension", "guestList", "waterService"],
        { w: 155, h: 55 },
      ),
    ],
    props: [
      p("recipe", 487, 278, "guestList", { scale: 0.75 }),
      p("cup", 487, 395, "waterService", { scale: 0.65 }),
      p("spoon", 502, 495, "tableService", { scale: 0.8 }),
      p("circustable", 480, 375, undefined, { scale: 2.15, revealOnly: true }),
      p("dumpling", 380, 265, undefined, { scale: 0.6, revealOnly: true }),
      p("strawberry", 465, 260, undefined, { scale: 0.6, revealOnly: true }),
      p("wafer", 545, 255, undefined, {
        tint: "#c2d8db",
        scale: 0.5,
        revealOnly: true,
      }),
      p("moon", 620, 240, undefined, { scale: 0.35, revealOnly: true }),
    ],
    stamp: "THE REPUBLIC HAS OUTGROWN ITS ORIGINAL SHELF",
    extra: { start: [312, 360], temp: -25, pressure: 35, par: 185 },
  },
  {
    targets: [
      t(
        "firstRule",
        "Thaw the old menu's first slim panel",
        "melt",
        310,
        205,
        50,
        120,
      ),
      t(
        "middleRule",
        "Thaw the old menu's middle panel",
        "melt",
        455,
        235,
        50,
        120,
      ),
      t(
        "lastRule",
        "Thaw the old menu's final panel",
        "melt",
        600,
        205,
        50,
        120,
      ),
      warm(
        "invitation",
        "Prepare the useful blank side",
        395,
        400,
        [20, 35],
        [10, 25],
        ["firstRule", "middleRule", "lastRule"],
        { w: 220 },
      ),
      t(
        "display",
        "Build a stand for a kinder invitation",
        "freeze",
        240,
        455,
        110,
        45,
        { requires: ["invitation"] },
      ),
    ],
    props: [
      p("recipe", 335, 302, "firstRule", { scale: 0.5 }),
      p("recipe", 480, 332, "middleRule", { scale: 0.5 }),
      p("recipe", 625, 302, "lastRule", { scale: 0.5 }),
      p("recipe", 505, 450, "invitation", {
        scale: 1.35,
        reveal: { x: 445, y: 335 },
      }),
      p("spoon", 295, 443, "display", { scale: 0.6, revealOnly: true }),
      p("biscuit", 695, 435, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "KEEP THE PAPER. RETIRE THE BOSSY SENTENCE.",
    extra: { start: [335, 145], par: 185 },
  },
  {
    targets: [
      t(
        "leftService",
        "Fill the sweet-and-savory welcome basin",
        "fill",
        235,
        385,
        145,
        65,
      ),
      t(
        "rightService",
        "Fill the take-your-time welcome basin",
        "fill",
        635,
        385,
        145,
        65,
      ),
      t(
        "welcome",
        "Thaw the welcome for every course",
        "melt",
        445,
        375,
        110,
        75,
      ),
      t(
        "centerpiece",
        "Build the shared breakfast centerpiece",
        "freeze",
        370,
        215,
        150,
        50,
        { requires: ["leftService", "rightService", "welcome"] },
      ),
      t(
        "whisk",
        "Serve breakfast to the whole table",
        "spin",
        610,
        225,
        85,
        65,
        { requires: ["centerpiece"] },
      ),
    ],
    props: [
      p("cup", 307, 444, "leftService", { scale: 0.85 }),
      p("cup", 707, 444, "rightService", { scale: 0.85 }),
      p("recipe", 500, 435, "welcome", {
        scale: 0.85,
        reveal: { x: 480, y: 235 },
      }),
      p("strawberry", 445, 200, "centerpiece", {
        scale: 0.65,
        revealOnly: true,
      }),
      p("whisk", 652, 325, "whisk", { scale: 1.0 }),
      p("circustable", 480, 460, undefined, { scale: 2.65, revealOnly: true }),
      p("scarf", 485, 337, undefined, {
        scale: 1.5,
        tint: "#dfae83",
        revealOnly: true,
      }),
      p("dumpling", 380, 325, undefined, { scale: 0.6, revealOnly: true }),
      p("pancake", 565, 325, undefined, { scale: 0.6, revealOnly: true }),
      p("biscuit", 655, 325, undefined, { scale: 0.25, revealOnly: true }),
    ],
    stamp: "BREAKFAST BELONGS TO THE TABLE",
    extra: { start: [307, 325], temp: 35, pressure: 45, par: 185 },
  },
];

const dispatches = [
  "President Wobble has filed a petition about breakfast. Captain Crumb has brought a particularly well-punctuated crumb to sign it.",
  "Wobble's opening speech requires a platform. Sprinkle has left plenty of room in the minutes for a powerful wobble.",
  "One enormous jelly is for the public. One tiny jelly is for quality control. Captain Crumb takes both responsibilities seriously.",
  "The whisk is ready for vigorous debate. The custard would prefer gentle persuasion. Sprinkle has reserved time for both.",
  "The founding minutes are between the cake layers. Wobble remembers an important spoon discussion and would like the record to show it.",
  "Custard and cocoa agree on breakfast. They disagree about comfortable. Sprinkle has ordered two cups and one very diplomatic platter.",
  "Captain Crumb would like a clearer invitation and a lower chair. His last meeting involved an unnecessary fork expedition.",
  "The eclair has arrived with three opinions about napkins. Sprinkle is arranging three seats and one unusually long name tag.",
  "A soup dumpling has arrived at the dessert assembly. Captain Crumb is preparing a warm welcome and a remarkably small honorary hat.",
  "Three strawberry delegates have brought one enormous sunhat. Sprinkle thinks this committee is unusually qualified to choose a picnic spot.",
  "The sugar-crystal choir has arrived from the caves. Captain Crumb is warming up for the crunchy percussion section.",
  "A parcel from the outer pantry contains a breakfast inquiry. Sprinkle is practicing a wave that says yes, even from several shelves away.",
  "The tasting notes disagree completely. Wobble has a radical proposal: perhaps breakfast could contain all three dishes.",
  "The ice mold has been very supportive. Now it must learn the difficult but important art of letting the pudding go.",
  "The republic offers three equal icing services. Captain Crumb has already designed a moustache that uses the whole public provision.",
  "The syrup is taking the scenic route. Fill the far pancake's basin, then open its spillway so breakfast reaches the pancake nearer home.",
  "Sweet, savory, or still deciding? Sprinkle has put all three on the menu and found the undecided column a very comfortable chair.",
  "The guest list includes dumplings, strawberries, sugar crystals, and star visitors. Wobble suspects the table needs another shelf's worth of room.",
  "The old menu says DESSERT LAST. Wobble has noticed the back is blank, useful, and considerably less bossy.",
  "Every course is here for breakfast. Wobble is lending the table his sash; Captain Crumb is finishing a beautifully punctuated signature.",
];
const source = designs.packs.find((pack) => pack.id === "06")!;
export const puddingLevels: Level[] = recipes.map((recipe, i) => {
  const card = source.scenes[i];
  return {
    id: card.id,
    pack: "06",
    name: card.title,
    chapter: source.title,
    theme: "pudding",
    pitch: dispatches[i],
    hint:
      card.id === "06.14"
        ? "Build → fill → open. " +
          card.puzzle.replace(/^With PHASE enabled, /, "")
        : card.puzzle.replace(/With FLOW, /g, ""),
    ending: card.payoff,
    start: [475, 145],
    temp: 65,
    pressure: 45,
    par: 50 + recipe.targets.length * 22,
    targets: recipe.targets,
    props: [...cast(), ...recipe.props],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
