import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/07-11.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 105, 60, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.75, ...extra });
const cast = (variant?: "socks" | "portrait"): Prop[] => [
  p("principal", 135, 310, undefined, {
    scale: 0.7,
    reveal: {
      x: 265,
      y: 420,
      ...(variant === "socks" ? { kind: "principalsocks" as PropKind } : {}),
    },
  }),
  p("diplodocus", 835, 285, undefined, {
    scale: 0.65,
    reveal:
      variant === "portrait"
        ? { kind: "diplodocusframe", x: 480, y: 490, scale: 0.95 }
        : { x: 735, y: 420, scale: 0.7 },
  }),
  p("ankylosaur", 850, 470, undefined, {
    scale: 0.7,
    reveal: variant === "portrait" ? { x: 590, y: 420 } : { x: 600, y: 460 },
  }),
];
const recipes: {
  targets: Target[];
  props: Prop[];
  stamp: string;
  cast?: "socks" | "portrait";
  extra?: Partial<Level>;
}[] = [
  {
    targets: [
      t(
        "badge",
        "Thaw the name tag in Dapple's cubby",
        "melt",
        605,
        395,
        115,
        70,
      ),
      warm(
        "stamper",
        "Warm Fern's name-badge stamper",
        250,
        225,
        [30, 40],
        [20, 40],
        ["badge"],
      ),
    ],
    props: [
      p("cubby", 662, 475, undefined, { scale: 1.1 }),
      p("badge", 662, 450, "badge", {
        scale: 0.85,
        reveal: { x: 745, y: 330, scale: 0.5 },
      }),
      p("scarf", 665, 335, undefined, { scale: 0.85 }),
      p("stamp", 302, 280, "stamper", { scale: 0.7 }),
      p("crayon", 460, 440, undefined, { scale: 0.8 }),
    ],
    stamp: "DAPPLE: PRESENT, INCLUDING MOST OF HER NECK",
    extra: { start: [662, 335], par: 90 },
  },
  {
    targets: [
      t(
        "leftBowl",
        "Fill the first leaf lunch bowl",
        "fill",
        235,
        355,
        135,
        65,
      ),
      t(
        "rightBowl",
        "Fill the other leaf lunch bowl",
        "fill",
        630,
        355,
        135,
        65,
      ),
      warm(
        "lunch",
        "Warm the sleepy leaf lunch",
        450,
        245,
        [35, 45],
        [20, 35],
        ["leftBowl", "rightBowl"],
      ),
    ],
    props: [
      p("leafbowl", 302, 411, "leftBowl", { scale: 0.9 }),
      p("leafbowl", 697, 411, "rightBowl", { scale: 0.9 }),
      p("leafbowl", 502, 295, "lunch", { scale: 0.85 }),
      p("leafbowl", 475, 465, undefined, { scale: 1.5, revealOnly: true }),
    ],
    stamp: "ONE LEAF. A VERY GENEROUS PLATE.",
    extra: { start: [302, 295], temp: 20, par: 120 },
  },
  {
    targets: [
      t("longNest", "Build Dapple's long nap pad", "freeze", 235, 415, 250, 50),
      t(
        "littleNest",
        "Build Pebble's compact nap pad",
        "freeze",
        645,
        400,
        80,
        80,
      ),
      warm(
        "blanket",
        "Warm the nap committee's blanket",
        490,
        285,
        [25, 35],
        [20, 40],
        ["longNest", "littleNest"],
      ),
    ],
    props: [
      p("nest", 360, 430, "longNest", { scale: 1.25, revealOnly: true }),
      p("nest", 685, 437, "littleNest", { scale: 0.65, revealOnly: true }),
      p("scarf", 542, 335, "blanket", { scale: 0.95 }),
      p("storybook", 365, 260, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "NAP AGENDA: UNANIMOUSLY POSTPONED",
    extra: { start: [360, 355], temp: -20, pressure: 35, par: 125 },
  },
  {
    targets: [
      t(
        "serviceLabel",
        "Thaw the giant fan's small label",
        "melt",
        265,
        410,
        125,
        65,
      ),
      t("fan", "Make an extremely small breeze", "spin", 635, 235, 90, 80, {
        requires: ["serviceLabel"],
      }),
    ],
    props: [
      p("badge", 327, 465, "serviceLabel", { scale: 0.8 }),
      p("mobile", 680, 360, "fan", { scale: 0.9 }),
      p("crayon", 475, 335, undefined, { scale: 0.95 }),
      p("badge", 570, 435, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "ONE REVOLUTION. A VERY IMPORTANT HELPER.",
    extra: { start: [327, 350], par: 95 },
  },
  {
    targets: [
      t(
        "raincloud",
        "Carve an opening in Dapple's raincloud",
        "melt",
        335,
        215,
        230,
        90,
      ),
      t(
        "fernBasin",
        "Catch useful drips for the class fern",
        "fill",
        375,
        420,
        155,
        65,
      ),
    ],
    props: [
      p("crayon", 645, 325, undefined, { scale: 0.85 }),
      p("classfern", 452, 405, "fernBasin", { scale: 1.05 }),
      p("leafbowl", 452, 480, "fernBasin", { scale: 1.0 }),
      p("badge", 290, 405, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "TODAY'S FORECAST: TEACHER-SHAPED",
    extra: { start: [452, 155], par: 100 },
  },
  {
    targets: [
      t(
        "mitten",
        "Thaw Pebble's carefully chosen mitten",
        "melt",
        245,
        215,
        125,
        70,
      ),
      t("bootRack", "Build Dapple's boot rack", "freeze", 605, 435, 145, 45),
      warm(
        "drying",
        "Dry the very special tail mitten",
        265,
        375,
        [30, 40],
        [20, 35],
        ["mitten"],
      ),
      warm(
        "socks",
        "Warm Dapple's toastier socks",
        625,
        240,
        [40, 50],
        [35, 50],
        ["bootRack"],
      ),
    ],
    props: [
      p("cubby", 307, 300, undefined, { scale: 0.95 }),
      p("sock", 307, 274, "mitten", { scale: 0.8, reveal: { x: 650, y: 455 } }),
      p("scarf", 317, 425, "drying", { scale: 0.7 }),
      p("sock", 677, 290, "socks", { scale: 0.9 }),
      p("fossilblock", 677, 420, "bootRack", { scale: 0.75, revealOnly: true }),
    ],
    stamp: "TAIL MITTEN: EXACTLY AS INTENDED",
    extra: { start: [307, 155], par: 160 },
  },
  {
    targets: [
      t(
        "lowStep",
        "Build the first little-foot step",
        "freeze",
        235,
        455,
        125,
        40,
      ),
      t(
        "middleStep",
        "Build the next little-foot step",
        "freeze",
        390,
        375,
        120,
        40,
        { requires: ["lowStep"] },
      ),
      t(
        "highStep",
        "Build the step nearest the sink",
        "freeze",
        535,
        295,
        105,
        40,
        { requires: ["middleStep"] },
      ),
      t("sink", "Fill the handwashing basin", "fill", 650, 205, 100, 65, {
        requires: ["lowStep", "middleStep", "highStep"],
      }),
    ],
    props: [
      p("fossilblock", 297, 446, "lowStep", { scale: 0.7, revealOnly: true }),
      p("fossilblock", 450, 366, "middleStep", {
        scale: 0.65,
        revealOnly: true,
      }),
      p("fossilblock", 587, 286, "highStep", { scale: 0.6, revealOnly: true }),
      p("leafbowl", 700, 262, "sink", { scale: 0.8 }),
      p("badge", 695, 410, undefined, { scale: 0.7, revealOnly: true }),
    ],
    stamp: "THREE STEPS. ONE VERY WELL-WASHED FOOT.",
    extra: { start: [297, 395], temp: -20, pressure: 35, par: 155 },
  },
  {
    targets: [
      warm(
        "sunny",
        "Pebble's sunny blanket corner",
        235,
        220,
        [40, 50],
        [40, 55],
      ),
      warm(
        "shady",
        "Dapple's shady blanket corner",
        635,
        220,
        [25, 35],
        [20, 35],
      ),
      t(
        "eggPillow",
        "Build the egg-pillow corner",
        "freeze",
        235,
        420,
        100,
        65,
        { requires: ["sunny", "shady"] },
      ),
      t(
        "tea",
        "Fill Fern's remarkably large tea corner",
        "fill",
        615,
        420,
        160,
        65,
        { requires: ["eggPillow"] },
      ),
    ],
    props: [
      p("scarf", 287, 272, "sunny", { tint: "#e5c485", scale: 0.8 }),
      p("scarf", 687, 272, "shady", { tint: "#b7d0c1", scale: 0.8 }),
      p("nest", 285, 450, "eggPillow", { scale: 0.75, revealOnly: true }),
      p("cup", 695, 475, "tea", { scale: 1.2 }),
      p("crayon", 460, 350, undefined, { scale: 1.0 }),
    ],
    stamp: "BIGGEST MAP SQUARE: FERN'S TEACUP",
    extra: { start: [287, 160], temp: 45, pressure: 47, par: 165 },
  },
  {
    targets: [
      t(
        "pancake",
        "Thaw the pancake with a passport",
        "melt",
        255,
        215,
        145,
        80,
      ),
      t(
        "plinth",
        "Build the pancake's serving plinth",
        "freeze",
        610,
        435,
        155,
        45,
      ),
      warm(
        "griddle",
        "Warm the visiting pancake's griddle",
        445,
        330,
        [50, 60],
        [25, 40],
        ["pancake", "plinth"],
      ),
    ],
    props: [
      p("pancake", 327, 283, "pancake", {
        scale: 0.85,
        reveal: { x: 687, y: 410, scale: 0.9 },
      }),
      p("badge", 497, 385, "griddle", { scale: 0.8 }),
      p("fossilblock", 687, 427, "plinth", { scale: 0.85, revealOnly: true }),
      p("storybook", 355, 425, undefined, { scale: 0.75, revealOnly: true }),
    ],
    stamp: "PASSPORT STAMP: ADMITTED TO TUMMY",
    extra: { start: [327, 155], par: 140 },
  },
  {
    targets: [
      t("book", "Thaw the cave's bedtime book", "melt", 415, 205, 145, 80),
      t(
        "leftSeat",
        "Build the left reading cushion",
        "freeze",
        235,
        445,
        130,
        45,
      ),
      t(
        "rightSeat",
        "Build the right reading cushion",
        "freeze",
        655,
        445,
        130,
        45,
      ),
      warm(
        "lantern",
        "Give the story a gentle lantern glow",
        445,
        375,
        [35, 45],
        [20, 35],
        ["book"],
      ),
    ],
    props: [
      p("storybook", 487, 275, "book", {
        scale: 1.0,
        reveal: { x: 480, y: 330 },
      }),
      p("spotlight", 497, 432, "lantern", { scale: 0.75 }),
      p("nest", 300, 445, "leftSeat", { scale: 0.85, revealOnly: true }),
      p("nest", 720, 445, "rightSeat", { scale: 0.85, revealOnly: true }),
      p("bat", 315, 290, undefined, { scale: 0.45, revealOnly: true }),
      p("bat", 675, 270, undefined, { scale: 0.4, revealOnly: true }),
    ],
    stamp: "BEDTIME STORY: WINGED LISTENERS WELCOME",
    extra: { start: [487, 145], par: 160 },
  },
  {
    targets: [
      t(
        "booster",
        "Build a booster seat for the moon",
        "freeze",
        250,
        445,
        150,
        45,
      ),
      t(
        "starBasin",
        "Fill the planetarium's star basin",
        "fill",
        610,
        410,
        155,
        65,
      ),
      t(
        "projector",
        "Start Pebble's potato constellation",
        "spin",
        645,
        230,
        80,
        70,
        { requires: ["booster", "starBasin"] },
      ),
    ],
    props: [
      p("moon", 325, 410, "booster", {
        scale: 0.65,
        reveal: { x: 325, y: 410 },
      }),
      p("leafbowl", 687, 468, "starBasin", { scale: 0.95 }),
      p("crayon", 500, 310, undefined, { scale: 1.0 }),
      p("papercrown", 325, 350, undefined, { scale: 0.6, revealOnly: true }),
      p("storybook", 515, 455, "projector", { scale: 0.9, revealOnly: true }),
    ],
    stamp: "NEW CONSTELLATION: POTATO, WITH SIX STARS",
    extra: { start: [325, 385], temp: -20, pressure: 35, par: 140 },
  },
  {
    targets: [
      t(
        "leftPot",
        "Fill the first imaginary-tooth pot",
        "fill",
        235,
        415,
        125,
        65,
      ),
      t(
        "rightPot",
        "Fill the other imaginary-tooth pot",
        "fill",
        650,
        415,
        125,
        65,
      ),
      t(
        "centralIce",
        "Open the ice over the middle pot",
        "melt",
        435,
        215,
        145,
        90,
      ),
      t(
        "middlePot",
        "Catch early drips in the middle pot",
        "fill",
        450,
        415,
        115,
        65,
      ),
    ],
    props: [
      p("leafbowl", 297, 473, "leftPot", { scale: 0.85 }),
      p("leafbowl", 712, 473, "rightPot", { scale: 0.85 }),
      p("leafbowl", 507, 473, "middlePot", { scale: 0.85 }),
      ...[297, 507, 712].map((x) =>
        p("toothflower", x, 395, undefined, { scale: 0.85, revealOnly: true }),
      ),
      p("badge", 350, 280, undefined, { scale: 0.7 }),
    ],
    stamp: "DEFINITELY NOT FOR BITING",
    extra: { start: [297, 355], temp: 20, par: 150 },
  },
  {
    targets: [
      t(
        "invitations",
        "Thaw the different-sized family invitations",
        "melt",
        440,
        205,
        125,
        75,
      ),
      t(
        "broadStand",
        "Build Pebble's broad portrait stand",
        "freeze",
        235,
        435,
        215,
        45,
        { requires: ["invitations"] },
      ),
      t(
        "tallStand",
        "Build Dapple's tall portrait stand",
        "freeze",
        655,
        315,
        65,
        120,
        { requires: ["invitations"] },
      ),
      warm(
        "welcome",
        "Warm the welcome for every family",
        460,
        355,
        [30, 40],
        [20, 40],
        ["broadStand", "tallStand"],
      ),
    ],
    props: [
      p("storybook", 502, 272, "invitations", { scale: 0.9 }),
      p("badge", 342, 412, "broadStand", { scale: 1.05, revealOnly: true }),
      p("badge", 687, 300, "tallStand", { scale: 0.65, revealOnly: true }),
      p("crayon", 512, 411, "welcome", { scale: 0.75 }),
      p("pterosaur", 565, 460, undefined, { scale: 0.55, revealOnly: true }),
    ],
    stamp: "EVERY FAMILY: THE SAME ENORMOUS SMILE",
    extra: { start: [502, 145], par: 170 },
  },
  {
    targets: [
      t(
        "fan",
        "Prepare the outside fan for inside voices",
        "spin",
        235,
        255,
        95,
        80,
      ),
      t(
        "musicStand",
        "Build the very proud music stand",
        "freeze",
        430,
        455,
        175,
        45,
      ),
      warm(
        "microphone",
        "Give the microphone a quiet welcome",
        635,
        275,
        [30, 40],
        [15, 30],
        ["fan", "musicStand"],
      ),
    ],
    props: [
      p("badge", 282, 405, "fan", { scale: 0.75 }),
      p("fossilblock", 517, 445, "musicStand", {
        scale: 0.85,
        revealOnly: true,
      }),
      p("microphone", 687, 332, "microphone", { scale: 0.75 }),
      p("storybook", 517, 385, "musicStand", { scale: 0.7, revealOnly: true }),
      p("crayon", 450, 270, undefined, { scale: 0.8 }),
    ],
    stamp: "A WHISPER WORTH APPLAUDING EARLY",
    extra: { start: [282, 195], temp: 20, pressure: 80, par: 140 },
  },
  {
    targets: [
      t(
        "iceSeat",
        "Build the smallest dinosaur's grand seat",
        "freeze",
        600,
        445,
        140,
        55,
      ),
    ],
    props: [
      p("fossilblock", 670, 432, "iceSeat", { scale: 0.75, revealOnly: true }),
      p("storybook", 265, 410, undefined, { scale: 0.85, revealOnly: true }),
      p("biscuit", 535, 445, undefined, { scale: 0.55, revealOnly: true }),
    ],
    stamp: "SMALL DINOSAUR. GRAND SEAT. FAIR SHARE.",
    extra: {
      start: [670, 385],
      temp: -20,
      pressure: 35,
      par: 110,
      needsSignals: ["seesaw"],
      completionHint: "A little wobble… then level!",
      balance: {
        id: "seesaw",
        x: 430,
        y: 300,
        arm: 75,
        left: { mass: 3, arm: 1 },
        right: { target: "iceSeat", mass: 1, arm: 3 },
      },
    },
  },
  {
    targets: [
      t(
        "pebbleSock",
        "Thaw Pebble's rehearsal sock",
        "melt",
        235,
        215,
        110,
        65,
      ),
      t(
        "dappleSock",
        "Thaw Dapple's rehearsal sock",
        "melt",
        435,
        265,
        110,
        65,
      ),
      t("fernSock", "Thaw Fern's very formal socks", "melt", 635, 215, 110, 65),
      warm(
        "pebbleCare",
        "A sunny finish for Pebble's sock",
        240,
        380,
        [40, 50],
        [30, 45],
        ["pebbleSock"],
      ),
      warm(
        "dappleCare",
        "A shady finish for Dapple's sock",
        440,
        435,
        [25, 35],
        [20, 35],
        ["dappleSock"],
      ),
      warm(
        "fernCare",
        "A tea-cozy finish for Fern's socks",
        640,
        380,
        [35, 45],
        [20, 35],
        ["fernSock"],
      ),
    ],
    props: [
      p("cubby", 290, 295, undefined, { scale: 0.8 }),
      p("cubby", 490, 345, undefined, { scale: 0.8 }),
      p("cubby", 690, 295, undefined, { scale: 0.8 }),
      p("sock", 290, 270, "pebbleSock", { scale: 0.7 }),
      p("sock", 490, 320, "dappleSock", { scale: 0.7 }),
      p("sock", 690, 270, "fernSock", { scale: 0.7 }),
      p("badge", 292, 433, "pebbleCare", { scale: 0.7 }),
      p("badge", 492, 488, "dappleCare", { scale: 0.7 }),
      p("badge", 692, 433, "fernCare", { scale: 0.7 }),
    ],
    stamp: "FORMAL DRESS: SOCKS ON HORNS, NATURALLY",
    cast: "socks",
    extra: { start: [290, 155], par: 205 },
  },
  {
    targets: [
      t(
        "song",
        "Thaw Dapple's leaf-orchestra song card",
        "melt",
        435,
        215,
        125,
        70,
      ),
      t(
        "instrumentBowl",
        "Fill the leaf instrument bowl",
        "fill",
        235,
        415,
        170,
        65,
        { requires: ["song"] },
      ),
      t(
        "musicStand",
        "Build the conductor's music stand",
        "freeze",
        610,
        435,
        150,
        45,
        { requires: ["song"] },
      ),
      t(
        "fan",
        "Start a gentle leaf-rustling flourish",
        "spin",
        650,
        235,
        85,
        70,
        { requires: ["instrumentBowl", "musicStand"] },
      ),
    ],
    props: [
      p("storybook", 497, 275, "song", { scale: 0.85 }),
      p("leafbowl", 320, 473, "instrumentBowl", { scale: 1.0 }),
      p("fossilblock", 685, 425, "musicStand", {
        scale: 0.75,
        revealOnly: true,
      }),
      p("scarf", 692, 370, "fan", { tint: "#b4cfa6", scale: 0.75 }),
      p("papercrown", 600, 405, undefined, { scale: 0.6, revealOnly: true }),
      p("crayon", 445, 415, undefined, { scale: 0.75 }),
    ],
    stamp: "CONDUCTOR'S HAT: NOW CONDUCTING PEBBLE",
    extra: { start: [497, 155], par: 165 },
  },
  {
    targets: [
      t("plaque", "Thaw the mobile's start plaque", "melt", 430, 465, 120, 50),
      ...[
        ["pebbleHammock", "Pebble's nest", 0],
        ["dappleHammock", "Dapple's nest", (Math.PI * 2) / 3],
        ["fernHammock", "Fern's nest", (Math.PI * 4) / 3],
      ].map(([id, name, phase]) =>
        warm(
          String(id),
          String(name),
          430,
          272.5,
          [30, 40],
          [20, 40],
          ["plaque"],
          {
            w: 100,
            h: 55,
            motion: {
              rx: 185,
              ry: 90,
              period: 32,
              phase: Number(phase),
              after: ["plaque"],
            },
          },
        ),
      ),
    ],
    props: [
      p("badge", 490, 507, "plaque", { scale: 0.65 }),
      p("nest", 0, 0, "pebbleHammock", { follow: "pebbleHammock", scale: 0.6 }),
      p("nest", 0, 0, "dappleHammock", { follow: "dappleHammock", scale: 0.6 }),
      p("nest", 0, 0, "fernHammock", { follow: "fernHammock", scale: 0.6 }),
      p("ankylosaur", 0, 0, undefined, {
        follow: "pebbleHammock",
        scale: 0.3,
        revealOnly: true,
      }),
      p("diplodocus", 0, 0, undefined, {
        follow: "dappleHammock",
        scale: 0.3,
        revealOnly: true,
      }),
      p("pterosaur", 0, 0, undefined, {
        follow: "fernHammock",
        scale: 0.3,
        revealOnly: true,
      }),
      p("badge", 240, 445, undefined, { scale: 0.75, revealOnly: true }),
    ],
    stamp: "HONORARY DIPLOMA IN ADVANCED NAPPING",
    extra: {
      start: [490, 405],
      par: 200,
      mobile: {
        x: 480,
        y: 300,
        targets: ["pebbleHammock", "dappleHammock", "fernHammock"],
      },
    },
  },
  {
    targets: [
      t(
        "badgeSheet",
        "Carve useful drips through the badge sheet",
        "melt",
        270,
        210,
        150,
        95,
      ),
      t(
        "basin",
        "Collect the helpers' badge-making water",
        "fill",
        250,
        405,
        185,
        65,
      ),
      t(
        "frame",
        "Build the thank-you display frame",
        "freeze",
        605,
        435,
        155,
        45,
      ),
      warm(
        "ribbon",
        "Warm a classroom-length thank-you ribbon",
        635,
        255,
        [30, 40],
        [20, 35],
        ["basin", "frame"],
      ),
    ],
    props: [
      p("badge", 345, 290, "badgeSheet", {
        scale: 1.0,
        reveal: { x: 425, y: 335, scale: 1.6 },
      }),
      p("leafbowl", 342, 463, "basin", { scale: 1.0 }),
      p("cubby", 682, 470, "frame", { scale: 0.9, revealOnly: true }),
      p("scarf", 687, 307, "ribbon", {
        scale: 0.9,
        reveal: { x: 490, y: 435, scale: 1.8 },
      }),
      p("crayon", 485, 255, undefined, { scale: 0.7 }),
    ],
    stamp: "FERN: EXCELLENT GROWN-UP. RIBBON: CLASSROOM-SIZED.",
    extra: { start: [345, 150], par: 165 },
  },
  {
    targets: [
      t(
        "welcome",
        "Thaw the family portrait's welcome plaque",
        "melt",
        435,
        190,
        130,
        70,
      ),
      t(
        "leftRiser",
        "Build the first comfortable portrait riser",
        "freeze",
        245,
        445,
        170,
        45,
        { requires: ["welcome"] },
      ),
      t(
        "rightRiser",
        "Build the other comfortable portrait riser",
        "freeze",
        565,
        445,
        120,
        45,
        { requires: ["welcome"] },
      ),
      t(
        "flowers",
        "Fill the family-photo flower basin",
        "fill",
        430,
        365,
        150,
        65,
        { requires: ["welcome"] },
      ),
      warm(
        "camera",
        "Give the family camera a gentle finish",
        445,
        280,
        [30, 40],
        [15, 30],
        ["leftRiser", "rightRiser", "flowers"],
      ),
    ],
    props: [
      p("storybook", 500, 250, "welcome", { scale: 0.9 }),
      p("leafbowl", 505, 421, "flowers", { scale: 0.9 }),
      p("classfern", 505, 357, "flowers", { scale: 0.75, revealOnly: true }),
      p("badge", 497, 330, "camera", { scale: 0.7 }),
      p("pterosaur", 350, 425, undefined, { scale: 0.6, revealOnly: true }),
      p("ankylosaur", 665, 422, undefined, { scale: 0.55, revealOnly: true }),
      p("badge", 285, 435, undefined, { scale: 0.8, revealOnly: true }),
    ],
    stamp: "EVERYBODY FITS. INCLUDING THE EXCELLENT GROWN-UP.",
    cast: "portrait",
    extra: { start: [500, 130], par: 185 },
  },
];
const dispatches = [
  "Dapple's name tag is in her cubby. Her cubby is not nearly tall enough to explain where the tag will eventually go.",
  "Pebble has arranged lunch in three leaf bowls. Fern is being served one leaf on the biggest plate in the preschool.",
  "The nap committee needs one long nest, one little nest, and a blanket. Fern has promised to stay awake for the minutes.",
  "Pebble's paper windmill needs a breeze. The available fan is considerably more enthusiastic than the windmill requested.",
  "Dapple has drawn a raincloud over the class fern. The forecast is drips, followed by a leaf that looks suspiciously like the principal.",
  "Pebble knows precisely where his mitten belongs. Dapple's socks would like a toastier drying station and considerably more shelf space.",
  "The class is building three handwashing steps. Dapple has promised to begin with one foot and see how the morning goes.",
  "The blanket is now a picnic map. Sunny for Pebble, shady for Dapple, and an unexpectedly large district for Fern's tea.",
  "Dapple has issued breakfast a passport. Fern is checking the pancake's papers before granting permission to enter her tummy.",
  "The cave reading nook needs cushions and a little light. Fern suspects the extra listeners hanging overhead have already heard this one.",
  "The visiting moon needs a booster seat. Pebble has prepared a magnificent constellation that is definitely, probably, a potato.",
  "Pebble is growing imaginary teeth. Fern has approved the gardening project on the firm understanding that the flowers will not bite.",
  "The family invitations need different-sized stands. Every family portrait has arrived with exactly the same enormous smile.",
  "Pebble has prepared a very proud whisper. The fan and microphone would like to rehearse being considerate first.",
  "One very small dinosaur would like a fair turn on the seesaw. Fern has brought a picture card, a model dinosaur, and a biscuit for diplomacy.",
  "The dress rehearsal requires warm socks. The children have unanimously decided that Fern's horns are the most formal place to wear hers.",
  "Dapple is conducting the leaf orchestra. Pebble is standing nearby in case the conductor's hat decides to change careers.",
  "The classroom mobile is making its rounds. Three blanket hammocks need care before Fern can award its honorary nap diploma.",
  "The children have made Fern a helper badge. Dapple measured its ribbon very carefully and included the entire classroom, just in case.",
  "The family photograph is ready for everyone. Dapple has volunteered to be the border, and Fern's excellent-grown-up badge is almost in frame.",
];
const source = designs.packs.find((pack) => pack.id === "07")!;
export const preschoolLevels: Level[] = recipes.map((recipe, i) => {
  const card = source.scenes[i];
  return {
    id: card.id,
    pack: "07",
    name: card.title,
    chapter: source.title,
    theme: "preschool",
    pitch: dispatches[i],
    hint: card.puzzle,
    ending: card.payoff,
    start: [475, 145],
    temp: 40,
    pressure: 40,
    par: 50 + recipe.targets.length * 22,
    targets: recipe.targets,
    props: [...cast(recipe.cast), ...recipe.props],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
