import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/07-11.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 105, 60, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.75, ...extra });
const cast = (): Prop[] => [
  p("coachnika", 135, 310, undefined, { scale: 0.65 }),
  p("gus", 835, 275, undefined, { scale: 0.65 }),
  p("irisharpy", 850, 470, undefined, { scale: 0.55 }),
];

const dispatches = [
  "Coach Nika has one tiny whistle. Gus has two horn sweatbands and a stretch large enough to improve the architecture.",
  "The centaur brought eight cups, just in case hooves count. Nika calls this excellent advance planning.",
  "Iris starts sideways. Gus needs a broader block. The lane arrow can learn to accommodate both.",
  "This fan needs to practice its manners. Iris has brought a ribbon; Nika has unwisely left her whistle unwrapped.",
  "Gus would like this hurdle to become a doorway. Iris is preparing an equally impressive demonstration of going around.",
  "A modest hop and a graceful glide need different landing pads. Nika has brought enthusiastic chalk for both.",
  "Gus packed sandwiches with the discus. Please help Nika distinguish the sports equipment from the excellent lunch.",
  "Warm wings, cozy knees, and tea for the coach. The teacup has requested its own team sweatband.",
  "Today's laurels are pasta. Gus, official noodle inspector, needs enough room in his wreath for both horns.",
  "Pass the baton gently through three warm stations. The cave echo may finish cheering slightly after everyone else.",
  "Iris reserved the front row for pollinators. Please prepare the flowers; a bee has already asked for a ticket.",
  "A comet has joined the relay. Its baton is tiny. The ribbon attached to the baton requires additional planning.",
  "Gus needs fitted horn caps; Iris needs warm wing sleeves. The spare cap is auditioning as the snack-break megaphone.",
  "Two strong breezes, two gentle finishing touches. Nika's quietest whistle deserves everyone's best listening.",
  "Follow the patient lamps, not a deadline. Untimed assist keeps one lamp open until you're ready for the next.",
  "These podiums have different widths and exactly the same height. Every medal celebrates making someone else's day nicer.",
  "Three rehearsal bays need five useful jobs. Gus is hoping remembering everyone's towels counts as an extra event.",
  "Build an ice pontoon, fill the basin, and watch the loaded models float up to the dock. Tiny towels are standing by.",
  "The team bench has supported everybody all day. Gus thinks it has earned a medal and a very good sit-down.",
  "One banner, two wreath stands, and drinks for everyone. Please prepare enough celebration for the bench to join the hug.",
];

const source = designs.packs.find((pack) => pack.id === "10")!;
const recipes: {
  targets: Target[];
  props: Prop[];
  front?: Prop[];
  stamp: string;
  cast?: Prop[];
  extra?: Partial<Level>;
}[] = [
  {
    targets: [
      warm("whistle", "Warm the tiny whistle", 255, 245, [30, 40], [20, 35]),
      warm(
        "mat",
        "Warm Gus's roomy stretch mat",
        540,
        415,
        [40, 50],
        [30, 45],
        ["whistle"],
        { w: 230, h: 55 },
      ),
    ],
    cast: [
      p("coachnika", 135, 310, undefined, { scale: 0.65 }),
      p("gus", 835, 275, "mat", {
        scale: 0.65,
        reveal: { x: 560, y: 405, scale: 0.8 },
      }),
      p("irisharpy", 850, 470, undefined, { scale: 0.55 }),
    ],
    props: [
      p("whistle", 307, 298, "whistle", { scale: 0.7 }),
      p("paddedcolumn", 460, 407, "mat", { scale: 0.9 }),
      p("sportstowel", 657, 465, "mat", { scale: 1.05 }),
    ],
    stamp: "EXCELLENT STRETCH. BONUS ARCHITECTURE.",
    extra: { start: [307, 185], temp: 35, pressure: 27, par: 100 },
  },
  {
    targets: [
      t("leftTrough", "Fill the first long trough", "fill", 235, 410, 165, 65),
      t("rightTrough", "Fill the other long trough", "fill", 630, 410, 165, 65),
      warm(
        "drinks",
        "Warm the shared drink station",
        455,
        235,
        [25, 35],
        [20, 35],
        ["leftTrough", "rightTrough"],
      ),
    ],
    props: [
      p("centaurathlete", 510, 405, "drinks", { scale: 0.65 }),
      p("sportscup", 507, 288, "drinks", { scale: 0.65 }),
      ...Array.from({ length: 8 }, (_, i) =>
        p("cup", 438 + (i % 4) * 43, 455 + Math.floor(i / 4) * 40, undefined, {
          scale: 0.25,
          revealOnly: true,
        }),
      ),
    ],
    stamp: "EIGHT CUPS. FOUR HOOVES. EXCELLENT PLANNING.",
    extra: { start: [317, 350], temp: 20, par: 130 },
  },
  {
    targets: [
      t("irisBlock", "Build Iris's sideways start", "freeze", 255, 245, 75, 80),
      t("gusBlock", "Build Gus's broad start", "freeze", 565, 420, 210, 55),
      t("laneName", "Thaw a more helpful arrow", "melt", 440, 325, 115, 70, {
        requires: ["irisBlock", "gusBlock"],
      }),
    ],
    cast: [
      p("coachnika", 135, 310, undefined, { scale: 0.65 }),
      p("gus", 835, 275, "laneName", {
        scale: 0.65,
        reveal: { x: 670, y: 415, scale: 0.65 },
      }),
      p("irisharpy", 850, 470, "laneName", {
        scale: 0.55,
        reveal: { x: 292, y: 238, scale: 0.55 },
      }),
    ],
    props: [
      p("scoreplacard", 497, 387, "laneName", { scale: 0.8 }),
      p("sportsribbon", 650, 300, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "SIDEWAYS IS A PERFECTLY GOOD DIRECTION.",
    extra: { start: [292, 185], temp: -20, par: 130 },
  },
  {
    targets: [
      t(
        "instructions",
        "Thaw the polite fan notice",
        "melt",
        250,
        405,
        125,
        65,
      ),
      t("fan", "Make a dignified tailwind", "spin", 665, 215, 95, 85, {
        requires: ["instructions"],
      }),
    ],
    props: [
      p("scoreplacard", 312, 462, "instructions", { scale: 0.8 }),
      p("circuswheel", 712, 295, "fan", { scale: 1.1 }),
      p("sportsribbon", 535, 410, "fan", { scale: 1.1 }),
      p("whistle", 200, 338, undefined, { scale: 0.55, revealOnly: true }),
    ],
    stamp: "TAILWIND: POLITE. WHISTLE: GIFT-WRAPPED.",
    extra: { start: [312, 345], par: 105 },
  },
  {
    targets: [
      t("leftPost", "Build the first padded post", "freeze", 270, 350, 75, 125),
      t(
        "rightPost",
        "Build the other padded post",
        "freeze",
        650,
        350,
        75,
        125,
      ),
      t(
        "doorSign",
        "Thaw the welcome-through sign",
        "melt",
        440,
        345,
        120,
        65,
        { requires: ["leftPost"] },
      ),
      warm(
        "ribbon",
        "Warm an equally good way around",
        660,
        205,
        [25, 35],
        [15, 30],
        ["rightPost"],
      ),
    ],
    cast: [
      p("coachnika", 135, 310, undefined, { scale: 0.65 }),
      p("gus", 835, 275, undefined, {
        scale: 0.65,
        reveal: { x: 500, y: 465, scale: 0.6 },
      }),
      p("irisharpy", 850, 470, undefined, {
        scale: 0.55,
        reveal: { x: 790, y: 360, scale: 0.55 },
      }),
    ],
    props: [
      p("hurdle", 500, 480, undefined, { scale: 1.25 }),
      p("scoreplacard", 500, 404, "doorSign", {
        scale: 0.8,
        reveal: { x: 500, y: 220, scale: 0.65 },
      }),
      p("sportsribbon", 712, 258, "ribbon", { scale: 0.7 }),
      p("sportsplate", 500, 285, undefined, { scale: 0.6, revealOnly: true }),
    ],
    stamp: "THROUGH OR AROUND: BOTH EXCELLENT OPTIONS.",
    extra: { start: [307, 290], temp: -20, par: 160 },
  },
  {
    targets: [
      t("shortLanding", "Build the broad hop pad", "freeze", 415, 400, 140, 80),
      t(
        "longLanding",
        "Build the slender glide pad",
        "freeze",
        605,
        440,
        190,
        40,
      ),
      warm(
        "launch",
        "Warm the welcoming launch",
        240,
        250,
        [35, 45],
        [20, 40],
        ["shortLanding", "longLanding"],
      ),
    ],
    cast: [
      p("coachnika", 135, 310, undefined, { scale: 0.65 }),
      p("gus", 835, 275, undefined, {
        scale: 0.65,
        reveal: { x: 485, y: 382, scale: 0.6 },
      }),
      p("irisharpy", 850, 470, undefined, {
        scale: 0.55,
        reveal: { x: 700, y: 423, scale: 0.55 },
      }),
    ],
    props: [
      p("sportstowel", 485, 397, "shortLanding", {
        scale: 0.8,
        revealOnly: true,
      }),
      p("sportstowel", 700, 437, "longLanding", {
        scale: 1.0,
        revealOnly: true,
      }),
      p("sportsplate", 292, 305, "launch", { scale: 0.65 }),
      p("scoreplacard", 505, 310, undefined, { scale: 0.8, revealOnly: true }),
    ],
    stamp: "HOP AND GLIDE BOTH RECEIVE ENTHUSIASTIC STARS.",
    extra: { start: [485, 340], temp: -20, par: 135 },
  },
  {
    targets: [
      t("discusLabel", "Thaw the discus label", "melt", 245, 235, 120, 65),
      t("dinnerLabel", "Thaw the dinner label", "melt", 660, 235, 120, 65),
      t(
        "rack",
        "Build the sporting display rack",
        "freeze",
        435,
        325,
        135,
        100,
        { requires: ["discusLabel", "dinnerLabel"] },
      ),
      warm(
        "towel",
        "Warm the refreshment coach's towel",
        655,
        425,
        [30, 40],
        [20, 35],
        ["rack"],
      ),
    ],
    props: [
      p("sportsdiscus", 305, 292, "discusLabel", { scale: 0.75 }),
      p("sportsplate", 720, 292, "dinnerLabel", { scale: 0.75 }),
      p("sportsdiscus", 502, 320, "rack", { scale: 0.75, revealOnly: true }),
      p("sportstowel", 707, 478, "towel", { scale: 0.75 }),
      p("basket", 295, 455, undefined, { scale: 0.9 }),
      p("sportsplate", 480, 490, undefined, { scale: 0.85, revealOnly: true }),
    ],
    stamp: "ASSISTANT COACH, DEPARTMENT OF SANDWICHES.",
    extra: { start: [305, 175], par: 165 },
  },
  {
    targets: [
      warm("wingTowel", "Warm Iris's wing towel", 445, 225, [25, 35], [15, 30]),
      warm(
        "kneeWrap",
        "Warm Gus's cozy knee wrap",
        255,
        385,
        [40, 50],
        [30, 45],
      ),
      warm("coachTea", "Warm Nika's team tea", 655, 385, [35, 45], [20, 35]),
    ],
    cast: [
      p("coachnika", 135, 310, "coachTea", {
        scale: 0.65,
        reveal: { x: 575, y: 435, scale: 0.55 },
      }),
      p("gus", 835, 275, "kneeWrap", {
        scale: 0.65,
        reveal: { x: 435, y: 435, scale: 0.55 },
      }),
      p("irisharpy", 850, 470, "wingTowel", {
        scale: 0.55,
        reveal: { x: 510, y: 410, scale: 0.5 },
      }),
    ],
    props: [
      p("sportsbench", 510, 450, undefined, { scale: 1.05 }),
      p("sportstowel", 497, 278, "wingTowel", { scale: 0.75 }),
      p("sportstowel", 307, 438, "kneeWrap", { scale: 0.9 }),
      p("sportscup", 707, 438, "coachTea", { scale: 0.8 }),
    ],
    stamp: "NEW TEAM MEMBER: THE TEACUP.",
    extra: { start: [497, 165], temp: 30, pressure: 22, par: 130 },
  },
  {
    targets: [
      t("recipe", "Carve the pasta-laurel recipe", "melt", 390, 225, 190, 90),
      t("water", "Fill beneath the noodle recipe", "fill", 415, 425, 140, 65),
      t("tray", "Build the medal-making tray", "freeze", 645, 395, 135, 85),
      warm(
        "cooking",
        "Warm the wearable pasta",
        235,
        345,
        [50, 60],
        [25, 40],
        ["water", "tray"],
      ),
    ],
    props: [
      p("recipe", 485, 307, "recipe", { scale: 1.0 }),
      p("pastalaurel", 287, 400, "cooking", { scale: 0.8 }),
      p("vegetablemedal", 712, 388, "tray", { scale: 0.7, revealOnly: true }),
      p("pastalaurel", 835, 180, undefined, { scale: 0.45, revealOnly: true }),
      p("sportsplate", 290, 483, undefined, { scale: 0.8, revealOnly: true }),
    ],
    stamp: "WREATH ADJUSTED FOR TWO VERY IMPORTANT HORNS.",
    extra: { start: [485, 165], par: 165 },
  },
  {
    targets: [
      warm(
        "firstBaton",
        "Warm the first echo handoff",
        240,
        225,
        [30, 40],
        [20, 35],
      ),
      warm(
        "secondBaton",
        "Warm the next echo handoff",
        420,
        315,
        [30, 40],
        [20, 35],
        ["firstBaton"],
      ),
      warm(
        "thirdBaton",
        "Warm the last echo handoff",
        600,
        420,
        [30, 40],
        [20, 35],
        ["secondBaton"],
      ),
      t("bell", "Ring the patient relay bell", "spin", 745, 315, 85, 80, {
        requires: ["firstBaton", "secondBaton", "thirdBaton"],
      }),
    ],
    props: [
      p("relaybaton", 292, 278, "firstBaton", { scale: 0.7 }),
      p("relaybaton", 472, 368, "secondBaton", { scale: 0.7 }),
      p("relaybaton", 652, 473, "thirdBaton", { scale: 0.7 }),
      p("helpbell", 787, 390, "bell", { scale: 0.8 }),
      p("cyclopsathlete", 300, 465, "bell", { scale: 0.65 }),
      p("scoreplacard", 500, 490, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "LATE CHEER ACCEPTED WITH ENTHUSIASM.",
    extra: { start: [292, 165], temp: 35, pressure: 27, par: 160 },
  },
  {
    targets: [
      t(
        "leftPlanter",
        "Fill the first spectator flowers",
        "fill",
        235,
        420,
        135,
        65,
      ),
      t(
        "rightPlanter",
        "Fill the other spectator flowers",
        "fill",
        660,
        420,
        135,
        65,
      ),
      t("shade", "Build the pollinator shade", "freeze", 435, 425, 150, 55),
      warm(
        "placard",
        "Welcome the flowerbed fans",
        455,
        225,
        [30, 40],
        [20, 35],
        ["leftPlanter", "rightPlanter", "shade"],
      ),
    ],
    props: [
      p("flower", 302, 414, "leftPlanter", { scale: 0.8 }),
      p("flower", 727, 414, "rightPlanter", { scale: 0.8 }),
      p("scoreplacard", 507, 278, "placard", { scale: 0.8 }),
      p("pastalaurel", 835, 180, undefined, { scale: 0.45, revealOnly: true }),
      p("beedragon", 792, 180, undefined, { scale: 0.15, revealOnly: true }),
      p("ticket", 779, 199, undefined, { scale: 0.16, revealOnly: true }),
    ],
    stamp: "FRONT ROW RESERVED FOR POLLINATORS.",
    extra: { start: [302, 360], temp: 20, par: 160 },
  },
  {
    targets: [
      t(
        "visitorBadge",
        "Thaw the comet's team badge",
        "melt",
        245,
        295,
        125,
        75,
      ),
      t("cradle", "Build the little baton cradle", "freeze", 640, 430, 145, 50),
      t(
        "projector",
        "Project a very long relay lane",
        "spin",
        650,
        215,
        90,
        80,
        { requires: ["visitorBadge", "cradle"] },
      ),
    ],
    props: [
      p("badge", 307, 361, "visitorBadge", { scale: 0.75 }),
      p("cometdragon", 490, 375, undefined, { scale: 0.8 }),
      p("spotlight", 695, 290, "projector", { scale: 0.8 }),
      p("relaybaton", 712, 423, "cradle", { scale: 0.45, revealOnly: true }),
      p("sportsribbon", 535, 488, undefined, { scale: 1.2, revealOnly: true }),
    ],
    stamp: "EXTRA LANE PROVIDED FOR THE REST OF THE COMET.",
    extra: { start: [307, 235], par: 135 },
  },
  {
    targets: [
      t("hornLabel", "Thaw the horn-cap label", "melt", 245, 230, 130, 70),
      t("wingRack", "Build the wing-sleeve rack", "freeze", 630, 380, 145, 100),
      warm(
        "hornCaps",
        "Warm Gus's fitted horn caps",
        255,
        405,
        [40, 50],
        [30, 45],
        ["hornLabel"],
      ),
      warm(
        "wingSleeves",
        "Warm Iris's fitted wing sleeves",
        645,
        225,
        [25, 35],
        [15, 30],
        ["wingRack"],
      ),
    ],
    cast: [
      p("coachnika", 135, 310, undefined, { scale: 0.65 }),
      p("gus", 835, 275, "hornCaps", {
        scale: 0.65,
        reveal: { x: 415, y: 400, scale: 0.65 },
      }),
      p("irisharpy", 850, 470, "wingSleeves", {
        scale: 0.55,
        reveal: { x: 565, y: 395, scale: 0.6 },
      }),
    ],
    props: [
      p("scoreplacard", 310, 292, "hornLabel", { scale: 0.75 }),
      p("sportstowel", 307, 458, "hornCaps", { scale: 0.75 }),
      p("sportstowel", 697, 278, "wingSleeves", { scale: 0.75 }),
      p("brasshorn", 610, 375, undefined, { scale: 0.45, revealOnly: true }),
    ],
    stamp: "SPARE HORN CAP NOW ANNOUNCES SNACK BREAK.",
    extra: { start: [310, 170], par: 160 },
  },
  {
    targets: [
      t("ribbonFan", "Prepare the ribbon flourish", "spin", 255, 215, 95, 85),
      t("whistleFan", "Prepare the quiet response", "spin", 650, 215, 95, 85),
      warm(
        "handles",
        "Warm the gentle ribbon handles",
        250,
        410,
        [30, 40],
        [20, 35],
        ["ribbonFan"],
      ),
      warm(
        "whistle",
        "Warm Nika's quiet whistle",
        650,
        395,
        [25, 35],
        [15, 30],
        ["whistleFan"],
      ),
    ],
    props: [
      p("sportsribbon", 302, 464, "handles", { scale: 0.9 }),
      p("whistle", 702, 448, "whistle", { scale: 0.8 }),
      p("sportsbench", 500, 430, undefined, { scale: 0.8 }),
      p("sportsribbon", 495, 300, undefined, { scale: 1.05, revealOnly: true }),
    ],
    stamp: "QUIET WHISTLE. EXCEPTIONAL LISTENING.",
    extra: { start: [302, 155], temp: 20, pressure: 80, par: 165 },
  },
  {
    targets: [
      warm(
        "leftLane",
        "Warm the first patient baton",
        245,
        355,
        [30, 40],
        [20, 35],
        [],
        {
          pulse: { period: 9, open: 3, phase: 0, untimedOrder: 1 },
        },
      ),
      warm(
        "middleLane",
        "Warm the next patient baton",
        450,
        355,
        [30, 40],
        [20, 35],
        [],
        {
          pulse: { period: 9, open: 3, phase: 6, untimedOrder: 2 },
        },
      ),
      warm(
        "rightLane",
        "Warm the last patient baton",
        655,
        355,
        [30, 40],
        [20, 35],
        [],
        {
          pulse: { period: 9, open: 3, phase: 3, untimedOrder: 3 },
        },
      ),
    ],
    props: [
      p("relaybaton", 297, 409, "leftLane", { scale: 0.8, tint: "#8fb6bf" }),
      p("relaybaton", 502, 409, "middleLane", { scale: 0.8, tint: "#d6bd79" }),
      p("relaybaton", 707, 409, "rightLane", { scale: 0.8, tint: "#bb9abc" }),
      p("scoreplacard", 490, 245, undefined, { scale: 0.85 }),
      p("sportsribbon", 500, 495, undefined, { scale: 1.2, revealOnly: true }),
    ],
    stamp: "TAKE YOUR TIME. THE LAMP UNDERSTANDS.",
    extra: { start: [297, 295], temp: 35, pressure: 27, par: 185 },
  },
  {
    targets: [
      t("gusPodium", "Build Gus's roomy podium", "freeze", 245, 415, 165, 65),
      t("irisPodium", "Build Iris's neat podium", "freeze", 455, 415, 95, 65),
      t("nikaPodium", "Build Nika's equal podium", "freeze", 625, 415, 145, 65),
      warm(
        "gusMedal",
        "Warm Gus's kindness medal",
        255,
        235,
        [40, 50],
        [30, 45],
        ["gusPodium"],
      ),
      warm(
        "irisMedal",
        "Warm Iris's kindness medal",
        450,
        235,
        [25, 35],
        [15, 30],
        ["irisPodium"],
      ),
      warm(
        "nikaMedal",
        "Warm Nika's kindness medal",
        645,
        235,
        [35, 45],
        [20, 35],
        ["nikaPodium"],
      ),
    ],
    cast: [
      p("coachnika", 135, 310, "nikaMedal", {
        scale: 0.65,
        reveal: { x: 697, y: 398, scale: 0.55 },
      }),
      p("gus", 835, 275, "gusMedal", {
        scale: 0.65,
        reveal: { x: 328, y: 397, scale: 0.6 },
      }),
      p("irisharpy", 850, 470, "irisMedal", {
        scale: 0.55,
        reveal: { x: 502, y: 397, scale: 0.6 },
      }),
    ],
    props: [
      p("vegetablemedal", 307, 288, "gusMedal", { scale: 0.65 }),
      p("vegetablemedal", 502, 288, "irisMedal", { scale: 0.65 }),
      p("vegetablemedal", 697, 288, "nikaMedal", { scale: 0.65 }),
    ],
    front: [
      p("vegetablemedal", 328, 390, undefined, {
        scale: 0.32,
        revealOnly: true,
      }),
      p("vegetablemedal", 502, 390, undefined, {
        scale: 0.32,
        revealOnly: true,
      }),
      p("vegetablemedal", 697, 391, undefined, {
        scale: 0.32,
        revealOnly: true,
      }),
    ],
    stamp: "EVERY MEDAL: MADE IT NICER FOR SOMEONE.",
    extra: { start: [328, 355], temp: -20, par: 225 },
  },
  {
    targets: [
      t(
        "eventCard",
        "Thaw the hydration event card",
        "melt",
        240,
        225,
        130,
        70,
      ),
      t("landing", "Build the towel team's mat", "freeze", 430, 420, 150, 60),
      t("flag", "Fly the helpful team flag", "spin", 700, 320, 90, 85),
      t("drink", "Fill the rehearsal drinks", "fill", 235, 425, 140, 65, {
        requires: ["eventCard"],
      }),
      warm(
        "towel",
        "Warm a towel for everybody",
        450,
        255,
        [30, 40],
        [20, 35],
        ["landing"],
      ),
    ],
    props: [
      p("scoreplacard", 305, 287, "eventCard", { scale: 0.8 }),
      p("sportstowel", 502, 308, "towel", { scale: 0.9 }),
      p("sportsribbon", 745, 400, "flag", { scale: 0.95 }),
      p("sportscup", 305, 418, "drink", { scale: 0.65 }),
      p("scoreplacard", 620, 492, undefined, { scale: 0.75, revealOnly: true }),
      p("sportstowel", 685, 475, undefined, { scale: 0.7, revealOnly: true }),
    ],
    stamp: "BONUS EVENT: REMEMBERED EVERYBODY'S TOWEL.",
    extra: { start: [305, 165], par: 185 },
  },
  {
    targets: [
      t(
        "pontoon",
        "Build the floating ice podium",
        "freeze",
        410,
        440,
        150,
        45,
      ),
      t("basin", "Fill to the floating-deck mark", "fill", 350, 325, 280, 160, {
        requires: ["pontoon"],
      }),
    ],
    props: [
      p("sportstowel", 690, 485, undefined, { scale: 0.3, revealOnly: true }),
      p("sportstowel", 750, 485, undefined, { scale: 0.3, revealOnly: true }),
    ],
    stamp: "EVERYONE RISES WITH THE OCCASION.",
    extra: {
      start: [485, 380],
      temp: -20,
      par: 145,
      buoyancy: {
        id: "podium:afloat",
        iceTarget: "pontoon",
        fillTarget: "basin",
        basin: { x: 350, y: 325, w: 280, h: 160 },
        pontoon: { x: 410, w: 150, h: 45, depth: 0.15 },
        pixelsPerMeter: 500,
        loadMass: 0.15,
        dockY: 322.9316666667,
      },
      needsSignals: ["podium:afloat"],
      completionHint: "Let the floating podium settle beside the dock.",
    },
  },
  {
    targets: [
      t(
        "thanks",
        "Thaw the bench's thank-you plaque",
        "melt",
        440,
        205,
        135,
        70,
      ),
      t(
        "wideStand",
        "Build the roomy badge stand",
        "freeze",
        245,
        415,
        160,
        65,
        { requires: ["thanks"] },
      ),
      t(
        "narrowStand",
        "Build the little badge stand",
        "freeze",
        695,
        405,
        75,
        75,
        { requires: ["thanks"] },
      ),
      warm(
        "ribbon",
        "Warm the bench's medal ribbon",
        455,
        445,
        [25, 35],
        [15, 30],
        ["wideStand", "narrowStand"],
      ),
    ],
    cast: [
      p("coachnika", 135, 310, undefined, {
        scale: 0.65,
        reveal: { x: 580, y: 407, scale: 0.5 },
      }),
      p("gus", 835, 275, undefined, {
        scale: 0.65,
        reveal: { x: 450, y: 407, scale: 0.5 },
      }),
      p("irisharpy", 850, 470, undefined, {
        scale: 0.55,
        reveal: { x: 515, y: 382, scale: 0.45 },
      }),
    ],
    props: [
      p("sportsbench", 515, 425, "ribbon", { scale: 1.05 }),
      p("scoreplacard", 507, 267, "thanks", { scale: 0.85 }),
      p("sportsribbon", 507, 498, "ribbon", { scale: 0.8 }),
      p("vegetablemedal", 325, 410, "wideStand", {
        scale: 0.65,
        revealOnly: true,
      }),
      p("vegetablemedal", 732, 400, "narrowStand", {
        scale: 0.55,
        revealOnly: true,
      }),
    ],
    stamp: "BENCH'S BEST EVENT: EVERYBODY SITTING DOWN.",
    extra: { start: [507, 145], par: 165 },
  },
  {
    targets: [
      t(
        "banner",
        "Thaw the everybody-helped banner",
        "melt",
        420,
        180,
        140,
        65,
      ),
      t(
        "leftWreath",
        "Build the first wreath stand",
        "freeze",
        245,
        445,
        85,
        55,
        { requires: ["banner"] },
      ),
      t(
        "rightWreath",
        "Build the other wreath stand",
        "freeze",
        685,
        445,
        85,
        55,
        { requires: ["banner"] },
      ),
      t(
        "drinks",
        "Fill the shared celebration drinks",
        "fill",
        435,
        450,
        140,
        60,
        { requires: ["banner"] },
      ),
      t(
        "celebration",
        "Celebrate all the helpful people",
        "spin",
        735,
        275,
        85,
        80,
        { requires: ["leftWreath", "rightWreath", "drinks"] },
      ),
    ],
    cast: [],
    props: [
      p("sportshug", 480, 405, "celebration", { scale: 1.0 }),
      p("scoreplacard", 490, 238, "banner", { scale: 0.9 }),
      p("pastalaurel", 287, 438, "leftWreath", {
        scale: 0.65,
        revealOnly: true,
      }),
      p("pastalaurel", 727, 438, "rightWreath", {
        scale: 0.65,
        revealOnly: true,
      }),
      p("pastalaurel", 320, 240, undefined, { scale: 0.35, revealOnly: true }),
      p("pastalaurel", 635, 215, undefined, { scale: 0.35, revealOnly: true }),
      p("sportscup", 505, 443, "drinks", { scale: 0.45, revealOnly: true }),
    ],
    stamp: "EVERYBODY HELPED. INCLUDING THE BENCH.",
    extra: { start: [490, 120], par: 190 },
  },
];

export const sportsLevels: Level[] = recipes.map((recipe, index) => {
  const card = source.scenes[index];
  return {
    id: card.id,
    pack: "10",
    name: card.title,
    chapter: source.title,
    theme: "sports",
    pitch: dispatches[index],
    hint: card.puzzle,
    ending: card.payoff,
    start: [475, 145],
    temp: 40,
    pressure: 40,
    par: 60 + recipe.targets.length * 25,
    targets: recipe.targets,
    props: [
      ...recipe.props,
      ...(recipe.cast ?? cast()),
      ...(recipe.front ?? []),
    ],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
