import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/07-11.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 105, 60, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.75, ...extra });
const cast = (): Prop[] => [
  p("adaplanner", 135, 310, undefined, { scale: 0.65 }),
  p("weddingbell", 835, 275, undefined, { scale: 0.7 }),
];
const recipes: {
  targets: Target[];
  props: Prop[];
  front?: Prop[];
  cast?: Prop[];
  stamp: string;
  extra?: Partial<Level>;
}[] = [
  {
    targets: [
      t("rillName", "Thaw Rill's name card", "melt", 245, 375, 125, 70),
      t("mossName", "Thaw Moss's name card", "melt", 645, 375, 125, 70),
      warm(
        "announcement",
        "Warm Bell's gentle announcement",
        450,
        235,
        [30, 40],
        [20, 35],
        ["rillName", "mossName"],
      ),
    ],
    props: [
      p("circustable", 510, 490, undefined, { scale: 2.15 }),
      p("placecard", 307, 435, "rillName", { scale: 0.8 }),
      p("placecard", 707, 435, "mossName", { scale: 0.8 }),
      p("placecard", 502, 290, "announcement", { scale: 0.9 }),
      p("rill", 420, 440, undefined, { scale: 0.65, revealOnly: true }),
      p("moss", 585, 450, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "TWO NAMES. ALWAYS THE SAME TABLE.",
    extra: { start: [307, 315], par: 130 },
  },
  {
    targets: [
      t(
        "firstDew",
        "Fill the first dewy refreshments",
        "fill",
        240,
        400,
        140,
        65,
      ),
      t(
        "otherDew",
        "Fill the other dewy refreshments",
        "fill",
        435,
        425,
        140,
        65,
      ),
      warm(
        "stoneHand",
        "Warm Moss's generous stone hand",
        650,
        235,
        [40, 50],
        [25, 40],
        ["firstDew", "otherDew"],
        { w: 135, h: 75 },
      ),
    ],
    props: [
      p("cloudfamily", 365, 355, undefined, { scale: 0.8 }),
      p("moss", 740, 435, "stoneHand", { scale: 0.8 }),
      p("cup", 310, 394, "firstDew", { scale: 0.55, revealOnly: true }),
      p("cup", 505, 419, "otherDew", { scale: 0.55, revealOnly: true }),
      p("sportstowel", 620, 475, undefined, { scale: 0.35, revealOnly: true }),
    ],
    stamp: "CEREMONIAL HAND POLISH: GRATEFULLY ACCEPTED.",
    extra: { start: [310, 340], temp: 20, par: 130 },
  },
  {
    targets: [
      t(
        "narrowCushion",
        "Build the neat ring cushion",
        "freeze",
        260,
        420,
        95,
        60,
      ),
      t(
        "broadCushion",
        "Build the generous ring cushion",
        "freeze",
        590,
        420,
        185,
        60,
      ),
      t(
        "ribbonLabel",
        "Thaw the very serious ribbon label",
        "melt",
        440,
        225,
        135,
        70,
        { requires: ["narrowCushion", "broadCushion"] },
      ),
    ],
    cast: [
      p("adaplanner", 135, 310, undefined, { scale: 0.65 }),
      p("weddingbell", 835, 275, undefined, {
        scale: 0.7,
        reveal: { x: 835, y: 275, kind: "bellringcrown", scale: 0.7 },
      }),
    ],
    props: [
      p("ringcushion", 307, 415, "narrowCushion", {
        scale: 0.65,
        revealOnly: true,
        reveal: { x: 307, y: 415, kind: "emptyringcushion" },
      }),
      p("ringcushion", 682, 415, "broadCushion", {
        scale: 1.0,
        revealOnly: true,
      }),
      p("placecard", 507, 286, "ribbonLabel", { scale: 0.8 }),
    ],
    stamp: "RING BEARER TEMPORARILY PROMOTED TO MONARCH.",
    extra: { start: [307, 360], temp: -20, par: 135 },
  },
  {
    targets: [
      t(
        "addresses",
        "Thaw the eight-handed address list",
        "melt",
        445,
        345,
        130,
        70,
      ),
      t("printer", "Turn Ada's invitation printer", "spin", 250, 210, 95, 85, {
        requires: ["addresses"],
      }),
      warm(
        "seal",
        "Warm the gentle invitation seal",
        665,
        425,
        [30, 40],
        [15, 30],
        ["printer"],
      ),
    ],
    props: [
      p("placecard", 510, 407, "addresses", { scale: 0.85 }),
      p("stamp", 717, 480, "seal", { scale: 0.75 }),
      p("letter", 297, 340, "printer", { scale: 0.95 }),
      p("bowtieinvite", 485, 490, undefined, { scale: 0.8, revealOnly: true }),
      ...Array.from({ length: 4 }, (_, i) =>
        p("letter", 275 + i * 52, 455, undefined, {
          scale: 0.3,
          revealOnly: true,
        }),
      ),
    ],
    stamp: "PLUS ONE: BELL'S SPARE BOW TIE.",
    extra: { start: [510, 285], par: 135 },
  },
  {
    targets: [
      t(
        "umbrellaStand",
        "Build the cloud umbrella stand",
        "freeze",
        245,
        420,
        145,
        60,
      ),
      t(
        "stoneLuggage",
        "Thaw the stone luggage label",
        "melt",
        635,
        225,
        140,
        70,
      ),
      warm(
        "cloudWelcome",
        "Warm the gentle cloud welcome",
        255,
        235,
        [25, 35],
        [15, 30],
        ["umbrellaStand"],
      ),
      warm(
        "stoneWelcome",
        "Warm the sturdy stone welcome",
        650,
        410,
        [45, 55],
        [30, 45],
        ["stoneLuggage"],
      ),
    ],
    props: [
      p("cloudfamily", 450, 375, "cloudWelcome", { scale: 0.65 }),
      p("stoneuncle", 565, 425, "stoneWelcome", { scale: 0.7 }),
      p("placecard", 705, 286, "stoneLuggage", { scale: 0.85 }),
      p("weddingchair", 307, 290, "cloudWelcome", { scale: 0.65 }),
      p("weddingchair", 702, 465, "stoneWelcome", { scale: 0.65 }),
    ],
    stamp: "LUGGAGE CONTENTS: ONE CAREFULLY FOLDED FERN.",
    extra: { start: [317, 360], temp: -20, par: 165 },
  },
  {
    targets: [
      t("lace", "Carve both useful lace windows", "melt", 330, 225, 360, 95),
      t(
        "leftFlowers",
        "Fill beneath the left lace window",
        "fill",
        355,
        425,
        130,
        65,
      ),
      t(
        "rightFlowers",
        "Fill beneath the right lace window",
        "fill",
        550,
        425,
        130,
        65,
      ),
    ],
    props: [
      p("lacepanel", 510, 325, "lace", { scale: 1.45 }),
      p("flower", 420, 419, "leftFlowers", { scale: 0.8 }),
      p("flower", 615, 419, "rightFlowers", { scale: 0.8 }),
      p("clipboardflower", 510, 405, undefined, {
        scale: 0.7,
        revealOnly: true,
      }),
      p("rill", 250, 455, undefined, { scale: 0.6 }),
      p("moss", 810, 465, undefined, { scale: 0.65 }),
    ],
    stamp: "A FLOWER IN THE SHAPE OF EXCELLENT PLANNING.",
    extra: { start: [420, 165], par: 150 },
  },
  {
    targets: [
      warm(
        "caveBlossoms",
        "Warm the cave blossoms",
        245,
        420,
        [20, 30],
        [15, 30],
      ),
      warm(
        "gardenRoses",
        "Warm the garden roses",
        455,
        315,
        [35, 45],
        [25, 40],
      ),
      warm("starLilies", "Warm the star lilies", 665, 210, [45, 55], [35, 50]),
    ],
    props: [
      p("flowercousins", 297, 409, "caveBlossoms", {
        scale: 0.6,
        tint: "#b5b0d9",
      }),
      p("flowercousins", 507, 304, "gardenRoses", {
        scale: 0.6,
        tint: "#e7a5b4",
      }),
      p("flowercousins", 717, 199, "starLilies", {
        scale: 0.6,
        tint: "#e8d294",
      }),
      p("clipboardflower", 595, 460, undefined, {
        scale: 0.85,
        revealOnly: true,
      }),
      p("ribbonspool", 410, 485, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "FORECAST: THREE COLORS, ONE EXCELLENT CENTERPIECE.",
    extra: { start: [297, 360], temp: 25, pressure: 22, par: 135 },
  },
  {
    targets: [
      t("dais", "Build the broad welcome dais", "freeze", 245, 420, 170, 60),
      t("marker", "Build the tall aisle marker", "freeze", 485, 340, 65, 140),
      t("mat", "Build the shallow side mat", "freeze", 735, 445, 100, 35),
      warm(
        "light",
        "Warm the unhurried welcome light",
        250,
        235,
        [30, 40],
        [20, 35],
        ["dais", "mat"],
      ),
      t("flowers", "Fill the aisle flowers", "fill", 600, 225, 110, 65, {
        requires: ["marker"],
      }),
    ],
    props: [
      p("booklamp", 302, 288, "light", { scale: 0.75 }),
      p("flowercousins", 655, 219, "flowers", { scale: 0.5 }),
      p("rill", 680, 415, undefined, { scale: 0.65 }),
      p("moss", 425, 400, undefined, {
        scale: 0.6,
        reveal: { x: 595, y: 460, scale: 0.6 },
      }),
      p("ribbonspool", 325, 413, "dais", { scale: 0.6, revealOnly: true }),
    ],
    stamp: "THE AISLE IS HAPPY TO MAKE ROOM.",
    extra: { start: [330, 360], temp: -20, par: 190 },
  },
  {
    targets: [
      t("recipe", "Carve the two-sided cake recipe", "melt", 300, 225, 190, 90),
      t("mixing", "Fill beneath the cake recipe", "fill", 325, 425, 140, 65),
      warm(
        "cloudIcing",
        "Warm Rill's cloud icing",
        595,
        225,
        [25, 35],
        [15, 30],
        ["mixing"],
      ),
      warm(
        "leafIcing",
        "Warm Moss's leaf icing",
        740,
        400,
        [40, 50],
        [25, 40],
        ["mixing"],
      ),
    ],
    props: [
      p("recipe", 395, 308, "recipe", { scale: 1.0 }),
      p("rill", 647, 360, "cloudIcing", { scale: 0.55 }),
      p("ribbonspool", 792, 453, "leafIcing", { scale: 0.65 }),
      p("twosidedcake", 570, 450, undefined, { scale: 1.0, revealOnly: true }),
    ],
    stamp: "BELL REQUESTS THE CORNER WHERE BOTH SIDES MEET.",
    extra: { start: [395, 165], par: 165 },
  },
  {
    targets: [
      t(
        "greeting",
        "Thaw the crystal aunt's greeting",
        "melt",
        245,
        240,
        135,
        75,
      ),
      t(
        "chimeStand",
        "Build the echo's chime stand",
        "freeze",
        635,
        425,
        145,
        55,
      ),
      warm(
        "chime",
        "Warm the happy-for-you chime",
        650,
        235,
        [30, 40],
        [15, 30],
        ["greeting", "chimeStand"],
      ),
    ],
    props: [
      p("placecard", 312, 307, "greeting", { scale: 0.85 }),
      p("crystalaunt", 480, 440, "chime", { scale: 0.9 }),
      p("crystalchime", 707, 416, "chimeStand", {
        scale: 0.6,
        revealOnly: true,
      }),
      p("crystalchime", 702, 288, "chime", { scale: 0.65 }),
    ],
    stamp: "HAPPY FOR YOU. HAPPY FOR YOU. HAPPY FOR YOU.",
    extra: { start: [312, 180], par: 135 },
  },
  {
    targets: [
      t(
        "shawlStand",
        "Build Grandmother's shawl stand",
        "freeze",
        430,
        425,
        150,
        55,
      ),
      t(
        "familyPhoto",
        "Thaw the much-loved family photo",
        "melt",
        245,
        390,
        125,
        80,
      ),
      warm(
        "shawl",
        "Warm a small constellation shawl",
        650,
        340,
        [25, 35],
        [15, 30],
        ["shawlStand", "familyPhoto"],
      ),
    ],
    props: [
      p("moongrandmother", 515, 335, "shawl", { scale: 1.0 }),
      p("placecard", 307, 461, "familyPhoto", { scale: 0.8 }),
      p("scarf", 702, 393, "shawl", { scale: 0.8 }),
      p("rill", 337, 350, undefined, { scale: 0.28, revealOnly: true }),
      p("placecard", 790, 485, undefined, { scale: 0.45, revealOnly: true }),
    ],
    stamp: "ANOTHER COPY FOR THE CRATER SHELF, PLEASE.",
    extra: { start: [505, 365], temp: -20, par: 140 },
  },
  {
    targets: [
      t("leftInk", "Fill the first leaf-print ink", "fill", 245, 425, 135, 65, {
        fillColor: "#698a5bcc",
      }),
      t(
        "rightInk",
        "Fill the other leaf-print ink",
        "fill",
        645,
        425,
        135,
        65,
        { fillColor: "#698a5bcc" },
      ),
      t(
        "writingStand",
        "Build the guest-book writing stand",
        "freeze",
        435,
        350,
        140,
        70,
        { requires: ["leftInk", "rightInk"] },
      ),
      warm(
        "drying",
        "Dry the smallest fern signature",
        445,
        215,
        [30, 40],
        [20, 35],
        ["writingStand"],
      ),
    ],
    props: [
      p("weddingguestbook", 505, 343, "writingStand", {
        scale: 0.85,
        revealOnly: true,
      }),
      p("flowercousins", 285, 400, "drying", { scale: 0.65 }),
      p("flowercousins", 715, 400, "drying", { scale: 0.65, tint: "#dcc485" }),
      p("placecard", 497, 269, "drying", { scale: 0.8 }),
      p("stoneuncle", 835, 465, undefined, { scale: 0.55, revealOnly: true }),
    ],
    stamp: "THE SUITCASE FERN SIGNED TOO.",
    extra: { start: [312, 365], temp: 20, par: 165 },
  },
  {
    targets: [
      t(
        "cloudSeat",
        "Build the cloud family's platform",
        "freeze",
        245,
        420,
        140,
        60,
      ),
      t(
        "stoneSeat",
        "Build the stone family's platform",
        "freeze",
        645,
        420,
        140,
        60,
      ),
      t(
        "starSeat",
        "Build the star family's platform",
        "freeze",
        445,
        475,
        120,
        40,
      ),
      warm(
        "cloudComfort",
        "Welcome the cloud weather",
        255,
        235,
        [25, 35],
        [15, 30],
        ["cloudSeat"],
      ),
      warm(
        "stoneComfort",
        "Welcome the stone weather",
        650,
        235,
        [45, 55],
        [30, 45],
        ["stoneSeat"],
      ),
      warm(
        "starComfort",
        "Welcome the star weather",
        450,
        330,
        [35, 45],
        [20, 35],
        ["starSeat"],
      ),
    ],
    props: [
      p("weddingchair", 315, 413, "cloudSeat", { scale: 0.6 }),
      p("weddingchair", 715, 413, "stoneSeat", { scale: 0.6 }),
      p("weddingchair", 505, 468, "starSeat", { scale: 0.6 }),
      p("cloudfamily", 315, 399, "cloudComfort", { scale: 0.55 }),
      p("stoneuncle", 715, 399, "stoneComfort", { scale: 0.6 }),
      p("moongrandmother", 505, 452, "starComfort", { scale: 0.6 }),
    ],
    stamp: "A LITTLE MOONLIGHT FOR THE TRAVELING FERN.",
    extra: { start: [315, 360], temp: -20, par: 225 },
  },
  {
    targets: [
      t("speech", "Thaw the very gentle speech", "melt", 245, 405, 130, 65),
      t("fan", "Prepare a very large breath", "spin", 450, 220, 100, 90, {
        requires: ["speech"],
      }),
      warm(
        "ding",
        "Warm Bell's very small ding",
        675,
        420,
        [25, 35],
        [15, 30],
        ["fan"],
      ),
    ],
    cast: [
      p("adaplanner", 135, 310, undefined, { scale: 0.65 }),
      p("weddingbell", 835, 275, "ding", {
        scale: 0.7,
        reveal: { x: 727, y: 395, scale: 0.65 },
      }),
    ],
    props: [
      p("placecard", 310, 462, "speech", { scale: 0.8 }),
      p("rill", 425, 445, undefined, {
        scale: 0.65,
        reveal: { x: 475, y: 445, scale: 0.65 },
      }),
      p("moss", 590, 465, undefined, {
        scale: 0.65,
        reveal: { x: 560, y: 450, scale: 0.65 },
      }),
      ...Array.from({ length: 8 }, (_, i) =>
        p("pencil", 235 + i * 24, 345, undefined, { scale: 0.25 }),
      ),
    ],
    stamp: "UNEXPECTED REHEARSAL SUCCESS: LEANING CLOSER.",
    extra: { start: [310, 345], par: 140 },
  },
  {
    targets: [
      t(
        "splitter",
        "Build the shared-light splitter",
        "freeze",
        300,
        150,
        100,
        100,
      ),
      t(
        "rillLens",
        "Build Rill's fixed ice lens",
        "freeze",
        500,
        130,
        120,
        160,
      ),
      t(
        "mossLens",
        "Build Moss's fixed ice lens",
        "freeze",
        260,
        320,
        160,
        120,
      ),
      t("shutter", "Open the rainbow appointment", "melt", 220, 175, 55, 60, {
        requires: ["splitter", "rillLens", "mossLens"],
      }),
    ],
    cast: [
      p("adaplanner", 135, 380, undefined, { scale: 0.65 }),
      p("weddingbell", 835, 440, undefined, {
        scale: 0.7,
        reveal: { x: 835, y: 365, scale: 0.55 },
      }),
    ],
    props: [
      p("rill", 735, 435, undefined, { scale: 0.6 }),
      p("moss", 515, 480, undefined, { scale: 0.65 }),
      p("ribbonspool", 665, 490, undefined, { scale: 0.65, revealOnly: true }),
    ],
    stamp: "BOW TIE: FORMALLY RAINBOW-APPROPRIATE.",
    extra: {
      start: [350, 95],
      temp: -20,
      par: 175,
      optics: {
        source: { x: 160, y: 200, dx: 1, dy: 0 },
        mirrors: [],
        splitters: [
          {
            target: "splitter",
            x: 350,
            y: 200,
            angle: Math.PI / 4,
            length: 100,
          },
        ],
        prisms: [
          {
            target: "rillLens",
            vertices: [
              [500, 130],
              [500, 290],
              [620, 290],
            ],
            refractiveIndex: 1.31,
          },
          {
            target: "mossLens",
            vertices: [
              [420, 320],
              [260, 320],
              [260, 440],
            ],
            refractiveIndex: 1.31,
          },
        ],
        detectors: [
          {
            id: "rill",
            name: "Rill",
            x: 820,
            y: 271.3930758363,
            radius: 10,
            label: [820, 315],
          },
          {
            id: "moss",
            name: "Moss",
            x: 315.9715246014,
            y: 500,
            radius: 10,
            label: [240, 530],
          },
        ],
      },
      needsSignals: ["rill", "moss"],
      completionHint:
        "One shared beam, two names. Let both place cards catch the light.",
    },
  },
  {
    targets: [
      t("leftTray", "Build the first favor tray", "freeze", 240, 425, 160, 55),
      t("rightTray", "Build the other favor tray", "freeze", 635, 425, 145, 55),
      t("leftTag", "Thaw the first thank-you tag", "melt", 255, 230, 125, 70, {
        requires: ["leftTray"],
      }),
      t("rightTag", "Thaw the other thank-you tag", "melt", 645, 230, 125, 70, {
        requires: ["rightTray"],
      }),
      warm(
        "ribbons",
        "Warm eight grateful ribbons",
        450,
        335,
        [30, 40],
        [20, 35],
        ["leftTag", "rightTag"],
      ),
    ],
    props: [
      p("placecard", 317, 292, "leftTag", { scale: 0.8 }),
      p("placecard", 707, 292, "rightTag", { scale: 0.8 }),
      p("ribbonspool", 502, 388, "ribbons", { scale: 0.8 }),
      p("weddingfavors", 510, 475, undefined, {
        scale: 0.95,
        revealOnly: true,
      }),
      p("biscuit", 320, 416, "leftTray", { scale: 0.55, revealOnly: true }),
      p("recipe", 707, 416, "rightTray", { scale: 0.45, revealOnly: true }),
    ],
    stamp: "EIGHT PACKAGES. ONE THANK-YOU PER HELPFUL HAND.",
    extra: { start: [320, 365], temp: -20, par: 190 },
  },
  {
    targets: [
      t(
        "instructions",
        "Carve the tiny rehearsal guide",
        "melt",
        410,
        205,
        175,
        90,
      ),
      t("flowers", "Fill the model's flower basin", "fill", 430, 430, 140, 65),
      t("arch", "Build the model ceremony arch", "freeze", 625, 375, 140, 105),
      warm(
        "vows",
        "Warm the miniature vows",
        245,
        335,
        [30, 40],
        [20, 35],
        ["arch", "flowers"],
      ),
      t("ribbon", "Turn the miniature celebration", "spin", 775, 220, 80, 80, {
        requires: ["vows"],
      }),
    ],
    cast: [
      p("adaplanner", 135, 310, undefined, { scale: 0.65 }),
      p("weddingbell", 835, 415, undefined, { scale: 0.7 }),
    ],
    props: [
      p("placecard", 497, 287, "instructions", { scale: 1.0 }),
      p("ceremonymodel", 510, 395, undefined, { scale: 0.8, revealOnly: true }),
      p("flower", 500, 424, "flowers", { scale: 0.65 }),
      p("placecard", 297, 388, "vows", { scale: 0.7 }),
      p("ribbonspool", 815, 297, "ribbon", { scale: 0.8 }),
    ],
    stamp: "THE MODEL AUDIENCE INCLUDES ALL EIGHT ARMS.",
    extra: { start: [497, 145], par: 195 },
  },
  {
    targets: [
      t("band", "Build the leaf proof", "freeze", 350, 300, 190, 90, {
        phase: {
          steps: [
            {
              verb: "freeze",
              name: "Build the leaf proof",
              signal: "band:leaf",
            },
            {
              verb: "melt",
              name: "Open the first proof",
              requires: ["engraver"],
              signal: "band:open",
            },
            {
              verb: "freeze",
              name: "Build the cloud-and-leaf proof",
              signal: "band:both",
            },
          ],
        },
      }),
      warm(
        "engraver",
        "Warm the cloud-proof engraver",
        650,
        235,
        [30, 40],
        [20, 35],
        [],
        { needsSignals: ["band:leaf"] },
      ),
    ],
    props: [
      p("weddingrings", 445, 293, "band", { scale: 0.8, revealOnly: true }),
      p("pencil", 702, 288, "engraver", { scale: 0.7 }),
      p("memorybook", 660, 475, undefined, { scale: 0.65, revealOnly: true }),
      p("rill", 265, 465, undefined, { scale: 0.6 }),
      p("moss", 805, 465, undefined, { scale: 0.65 }),
    ],
    stamp: "SECOND FIRST DRAFT: LEAF AND CLOUD, TOGETHER.",
    extra: { start: [445, 240], temp: -20, par: 175 },
  },
  {
    targets: [
      t("rillCard", "Carve Rill's cloudy-day vows", "melt", 245, 225, 155, 90),
      t("rillBasin", "Fill beneath Rill's vow card", "fill", 255, 430, 135, 65),
      t("mossBox", "Build Moss's keepsake box", "freeze", 645, 415, 135, 65),
      warm(
        "rillRibbon",
        "Warm Rill's gentle vow ribbon",
        450,
        245,
        [25, 35],
        [15, 30],
        ["rillCard", "rillBasin"],
      ),
      warm(
        "mossRibbon",
        "Warm Moss's faithful vow ribbon",
        650,
        225,
        [35, 45],
        [20, 35],
        ["mossBox"],
      ),
    ],
    props: [
      p("placecard", 322, 307, "rillCard", { scale: 0.95 }),
      p("ribbonspool", 502, 298, "rillRibbon", { scale: 0.75 }),
      p("ribbonspool", 702, 278, "mossRibbon", { scale: 0.75 }),
      p("rill", 465, 460, "rillRibbon", { scale: 0.65 }),
      p("moss", 570, 460, "mossRibbon", { scale: 0.65 }),
      p("bookmark", 712, 409, "mossBox", { scale: 0.45, revealOnly: true }),
    ],
    stamp: "ORDINARY KINDNESS, THROUGH EVERY FORECAST.",
    extra: { start: [322, 165], par: 190 },
  },
  {
    targets: [
      warm(
        "rillVows",
        "Warm Rill's welcoming vows",
        250,
        225,
        [25, 35],
        [15, 30],
      ),
      warm(
        "mossVows",
        "Warm Moss's welcoming vows",
        650,
        225,
        [40, 50],
        [25, 40],
      ),
      t(
        "arch",
        "Build the everybody-welcome arch",
        "freeze",
        435,
        365,
        145,
        80,
        { requires: ["rillVows", "mossVows"] },
      ),
      t("toast", "Fill the toast for every family", "fill", 435, 465, 145, 50, {
        requires: ["arch"],
      }),
      t(
        "portrait",
        "Thaw the generous family portrait",
        "melt",
        735,
        350,
        110,
        95,
        { requires: ["toast"] },
      ),
    ],
    cast: [],
    props: [
      p("weddingarch", 507, 445, "arch", { scale: 0.8 }),
      p("weddingpanorama", 480, 335, "portrait", { scale: 0.9 }),
      p("placecard", 302, 278, "rillVows", {
        scale: 0.6,
        reveal: { x: 302, y: 490, scale: 0.6 },
      }),
      p("placecard", 702, 278, "mossVows", {
        scale: 0.6,
        reveal: { x: 780, y: 490, scale: 0.6 },
      }),
      p("cup", 507, 458, "toast", { scale: 0.5, revealOnly: true }),
    ],
    stamp: "THE BEST CORNER OF CAKE IS SAVED FOR YOU.",
    extra: { start: [302, 165], temp: 30, pressure: 22, par: 195 },
  },
];

const dispatches = [
  "Rill and Moss have two name cards and one very long table. Ada has drawn eight arrows to the same lovely conclusion.",
  "Cloud relatives need dew cups. Moss would like to offer a warm stone hand. Bell has brought the ceremonial polishing cloth.",
  "Two serious rings need differently sized cushions. Bell is trying very hard not to think about crowns.",
  "Ada can sign eight invitations at once. Someone has thoughtfully invited Bell's spare bow tie.",
  "Cloud guests checked an umbrella. The stone uncle checked a suitcase containing one carefully folded fern.",
  "This icy lace needs two useful little windows. Rill is secretly making a flower shaped like Ada's clipboard.",
  "Cave blossoms, garden roses, star lilies: three forecasts and three warmers. Ada thinks they will make a wonderful centerpiece.",
  "The aisle is a friendly suggestion. Please prepare a broad dais, a tall marker, and somewhere comfortable to drift beside it.",
  "One cake needs cloud icing and leaf icing. Bell has already requested the corner where the two sides meet.",
  "The crystal aunt brought an echo that says happy for you. Bell may have found a friend with a very similar speaking voice.",
  "Grandmother Moon needs a cozy shawl. She has spotted baby Rill in the family photo and would like another copy immediately.",
  "The flower cousins sign with leaf prints. Ada is leaving a little space for the fern that traveled in a suitcase.",
  "Three families, three comfort ranges. Everyone gets a seat; the traveling fern may borrow Grandmother's moonlight.",
  "Bell is practicing the quietest possible ding. Ada suspects the couple leaning closer is a very good rehearsal result.",
  "Build a splitter and two ice lenses, then open the shutter. Both names deserve a little light of their own.",
  "Two favor desks need trays, tags, and ribbons. Ada hasn't noticed that eight of the thank-you packages are for her.",
  "The rehearsal has a miniature rehearsal. Bell has remembered to draw all eight of Ada's arms in the paper audience.",
  "The first ring proof is a leaf. Warm the engraver, open the practice band, and cast it again for leaf and cloud together.",
  "Rill and Moss are promising ordinary kindness through every forecast. Bell wants a bookmark for the sentence about tea.",
  "Warm the vows, prepare the arch and toast, and reveal the portrait. The newlyweds have saved Ada and Bell the best corner of cake.",
];

const source = designs.packs.find((pack) => pack.id === "11")!;
export const weddingLevels: Level[] = recipes.map((recipe, index) => {
  const card = source.scenes[index];
  return {
    id: card.id,
    pack: "11",
    name: card.title,
    chapter: source.title,
    theme: "wedding",
    pitch: dispatches[index],
    hint: card.puzzle,
    ending: card.payoff,
    start: [475, 145],
    temp: 40,
    pressure: 40,
    par: 60 + recipe.targets.length * 25,
    targets: recipe.targets,
    props: [
      ...recipe.props,
      ...(recipe.cast ?? cast()),
      ...(recipe.front ?? []),
    ],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
