import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/12-16.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 105, 60, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.75, ...extra });
const cast = (bramble: boolean): Prop[] => [
  p("stitchtailor", 135, 310, undefined, { scale: 0.65 }),
  p("dozycourier", 835, 275, undefined, { scale: 0.7 }),
  ...(bramble ? [p("bramble", 835, 470, undefined, { scale: 0.55 })] : []),
];
const recipes: {
  targets: Target[];
  props: Prop[];
  cast?: Prop[];
  stamp: string;
  extra?: Partial<Level>;
}[] = [
  {
    targets: [
      t(
        "welcome",
        "Thaw the full width of the yawn",
        "melt",
        330,
        245,
        310,
        90,
      ),
    ],
    props: [
      p("circustable", 490, 445, undefined, { scale: 1.6 }),
      p("yawnsign", 485, 329, "welcome", { scale: 1.15 }),
      p("basket", 695, 470, undefined, { scale: 0.8 }),
    ],
    stamp: "YAWN RECEIVED. YAWN RETURNED.",
    extra: { start: [485, 185], temp: 20, par: 90 },
  },
  {
    targets: [
      t(
        "cushion",
        "Build the sensible landing cushion",
        "freeze",
        360,
        425,
        255,
        55,
      ),
      t(
        "packing",
        "Thaw the overexcited pillow parcel",
        "melt",
        430,
        225,
        125,
        90,
        { requires: ["cushion"] },
      ),
    ],
    props: [
      p("dreamquilt", 487, 417, "cushion", { scale: 0.9, revealOnly: true }),
      p("sparepillow", 492, 309, "packing", {
        scale: 0.85,
        reveal: { x: 492, y: 400, scale: 0.85 },
      }),
      p("letter", 680, 405, undefined, { scale: 0.7 }),
    ],
    stamp: "NEXT DELIVERY: SOMETHING CLOSER TO THE FLOOR.",
    extra: { start: [487, 365], temp: -20, par: 110 },
  },
  {
    targets: [
      warm(
        "goodnight",
        "Warm the shy goodnight",
        360,
        410,
        [25, 40],
        [15, 35],
        [],
        { w: 230, h: 65 },
      ),
    ],
    props: [
      p("circustable", 485, 495, undefined, { scale: 1.55 }),
      p("goodnightbrooch", 475, 460, "goodnight", { scale: 1.2 }),
      p("listeningfunnel", 690, 370, "goodnight", { scale: 1.05 }),
    ],
    stamp: "GOODNIGHT. THE REPLY IS EVEN SMALLER.",
    extra: { start: [475, 350], temp: 30, pressure: 25, par: 90 },
  },
  {
    targets: [
      t(
        "cassette",
        "Thaw tomorrow's thread cassette",
        "melt",
        280,
        220,
        140,
        100,
      ),
      t("bobbin", "Wind the sunrise bobbin", "spin", 610, 305, 120, 95, {
        requires: ["cassette"],
      }),
    ],
    props: [
      p("ribbonspool", 350, 314, "cassette", { scale: 0.95 }),
      p("dreampostcards", 475, 480, "bobbin", { scale: 1.2 }),
      p("letter", 680, 457, "bobbin", { scale: 0.65 }),
    ],
    stamp: "TOMORROW: NOW AVAILABLE BY THE SPOOL.",
    extra: { start: [350, 160], par: 115 },
  },
  {
    targets: [
      t(
        "upperPatch",
        "Stitch the high blue square",
        "freeze",
        300,
        210,
        150,
        90,
      ),
      t(
        "lowerPatch",
        "Stitch the low pink square",
        "freeze",
        575,
        375,
        150,
        90,
      ),
      warm(
        "comfort",
        "Warm the comfort badge",
        460,
        315,
        [30, 45],
        [20, 40],
        ["upperPatch", "lowerPatch"],
      ),
    ],
    props: [
      p("dreamquilt", 515, 363, "comfort", { scale: 1.15 }),
      p("goodnightbrooch", 511, 365, "comfort", { scale: 0.5 }),
    ],
    cast: [
      p("stitchtailor", 135, 310, undefined, { scale: 0.65 }),
      p("dozycourier", 835, 310, undefined, {
        scale: 0.75,
        reveal: { kind: "dozyquilt", x: 835, y: 310, scale: 0.75 },
      }),
    ],
    stamp: "LABEL OUT. COMFORT IN.",
    extra: { start: [375, 150], temp: -20, par: 145 },
  },
  {
    targets: [
      t(
        "snore",
        "Give the snore trumpet some puff",
        "spin",
        290,
        330,
        125,
        100,
      ),
      warm(
        "whisper",
        "Light the whisper brooch",
        595,
        280,
        [20, 35],
        [10, 25],
        [],
        { w: 140, h: 75 },
      ),
    ],
    props: [
      p("snoretrumpet", 350, 420, "snore", { scale: 1.15 }),
      p("goodnightbrooch", 665, 345, "whisper", { scale: 0.9 }),
      p("listeningfunnel", 487, 465, "whisper", { scale: 0.7 }),
    ],
    stamp: "DUET. INDOOR VOICES. MOSTLY.",
    extra: { start: [352, 270], temp: 20, pressure: 80, par: 130 },
  },
  {
    targets: [
      t("pane", "Clear the entire rain window", "melt", 395, 220, 235, 100),
      t(
        "rain",
        "Catch the rain below the clear pane",
        "fill",
        460,
        410,
        135,
        70,
        { requires: ["pane"] },
      ),
    ],
    props: [
      p("raincup", 527, 470, "rain", { scale: 1.05 }),
      p("raincup", 527, 470, "rain", {
        scale: 1.05,
        foreground: true,
        revealOnly: true,
      }),
      p("stamp", 748, 420, "rain", { scale: 0.65 }),
      p("letter", 295, 405, undefined, { scale: 0.5 }),
    ],
    stamp: "RAIN RECEIVED. UMBRELLA POSTAGE PAID.",
    extra: { start: [512, 160], par: 130 },
  },
  {
    targets: [
      t(
        "backdrop",
        "Build a tall, comforting forest",
        "freeze",
        430,
        190,
        120,
        240,
      ),
      warm(
        "leftLantern",
        "Light the left audition lantern",
        265,
        410,
        [25, 45],
        [15, 35],
        ["backdrop"],
      ),
      warm(
        "rightLantern",
        "Light the right audition lantern",
        625,
        410,
        [25, 45],
        [15, 35],
        ["backdrop"],
      ),
    ],
    props: [
      p("slipperlamp", 315, 465, "leftLantern", { scale: 0.7 }),
      p("slipperlamp", 680, 465, "rightLantern", { scale: 0.7 }),
      p("auditioncard", 680, 260, undefined, { scale: 0.9 }),
    ],
    cast: [
      p("stitchtailor", 135, 310, undefined, { scale: 0.65 }),
      p("dozycourier", 835, 270, undefined, { scale: 0.65 }),
      p("bramble", 680, 375, undefined, { scale: 0.65 }),
    ],
    stamp: "COMFORTING. WITH EXCELLENT POTENTIAL.",
    extra: { start: [490, 135], temp: -20, par: 160 },
  },
  {
    targets: [
      t("lid", "Thaw the pocket teapot's lid", "melt", 300, 195, 145, 75),
      t("sunset", "Fill the little horizon cup", "fill", 510, 390, 140, 70, {
        requires: ["lid"],
      }),
      warm(
        "teapot",
        "Warm one cup-sized sunset",
        315,
        395,
        [35, 50],
        [20, 40],
        ["sunset"],
      ),
    ],
    props: [
      p("pocketteapot", 375, 380, "teapot", { scale: 1.05 }),
      p("cup", 580, 450, "sunset", { scale: 0.8 }),
      p("sunsetcup", 580, 435, "sunset", {
        scale: 1,
        foreground: true,
        revealOnly: true,
      }),
      p("dreamquilt", 710, 495, "teapot", { scale: 0.65 }),
    ],
    stamp: "STEEP FOR ONE SMALL HORIZON.",
    extra: { start: [372, 140], par: 145 },
  },
  {
    targets: [
      t(
        "firstEnding",
        "Find the beginning of the ending",
        "melt",
        270,
        210,
        100,
        90,
      ),
      t("secondEnding", "Find the blanket clause", "melt", 450, 275, 100, 90),
      t("thirdEnding", "Find the cave's invitation", "melt", 630, 205, 100, 90),
      warm(
        "ending",
        "Give every ending a goodnight",
        445,
        440,
        [20, 40],
        [10, 30],
        ["firstEnding", "secondEnding", "thirdEnding"],
      ),
    ],
    props: [
      p("bookspine", 320, 292, "firstEnding", { scale: 0.65 }),
      p("bookspine", 500, 357, "secondEnding", { scale: 0.65 }),
      p("bookspine", 680, 287, "thirdEnding", { scale: 0.65 }),
      p("endingfragments", 493, 431, "ending", { scale: 1.05 }),
    ],
    stamp: "INCLUDING THE CAVE. ESPECIALLY THE CAVE.",
    extra: { start: [320, 150], par: 170 },
  },
  {
    targets: [
      t("leftWater", "Water the low tomato orbit", "fill", 280, 330, 130, 65),
      t("rightWater", "Water the high tomato orbit", "fill", 605, 230, 130, 65),
      t(
        "trellis",
        "Build a trellis for little planets",
        "freeze",
        450,
        385,
        110,
        125,
        { requires: ["leftWater", "rightWater"] },
      ),
    ],
    props: [
      p("leafbowl", 345, 390, "leftWater", { scale: 0.8 }),
      p("leafbowl", 670, 290, "rightWater", { scale: 0.8 }),
      p("tomatoplanets", 505, 377, "trellis", { scale: 1.1 }),
    ],
    stamp: "ONE TOMATO HAS RETAINED ITS MOON.",
    extra: { start: [345, 270], temp: 20, par: 145 },
  },
  {
    targets: [
      t(
        "firstCrossing",
        "Build the near sleepwalker crossing",
        "freeze",
        340,
        275,
        140,
        55,
      ),
      t(
        "secondCrossing",
        "Build the far sleepwalker crossing",
        "freeze",
        515,
        340,
        140,
        55,
      ),
      t("tea", "Fill the roadside tea basin", "fill", 245, 440, 130, 65),
      warm(
        "lamp",
        "Point the light at their slippers",
        695,
        430,
        [30, 45],
        [15, 30],
        ["firstCrossing", "secondCrossing", "tea"],
      ),
    ],
    props: [
      p("cup", 310, 500, "tea", { scale: 0.8 }),
      p("slipperlamp", 747, 422, "lamp", { scale: 0.95 }),
    ],
    cast: [
      p("stitchtailor", 135, 310, undefined, { scale: 0.65 }),
      p("dozycourier", 835, 260, undefined, {
        scale: 0.65,
        reveal: { x: 405, y: 261, scale: 0.65 },
      }),
      p("bramble", 835, 465, undefined, {
        scale: 0.55,
        reveal: { x: 585, y: 324, scale: 0.55 },
      }),
    ],
    stamp: "DESTINATION UNCERTAIN. SLIPPERS WELL LIT.",
    extra: { start: [410, 215], temp: -20, par: 175 },
  },
  {
    targets: [
      t(
        "outerPack",
        "Thaw the apology's outer wrapping",
        "melt",
        280,
        215,
        140,
        95,
      ),
      warm(
        "reassurance",
        "Warm the words inside",
        635,
        260,
        [20, 35],
        [10, 25],
        [],
        { w: 120, h: 70 },
      ),
      t("lining", "Build a softer inside lining", "freeze", 420, 430, 200, 65, {
        requires: ["outerPack", "reassurance"],
      }),
    ],
    props: [
      p("dreammask", 515, 391, "lining", { scale: 1.15 }),
      p("goodnightbrooch", 695, 318, "reassurance", { scale: 0.75 }),
      p("letter", 350, 302, "outerPack", { scale: 0.8 }),
    ],
    stamp: "APOLOGY LINED. ANTLERS NOW ACCEPT COATS.",
    extra: { start: [350, 155], par: 155 },
  },
  {
    targets: [
      t(
        "upperPrism",
        "Build the upper moonlight prism",
        "freeze",
        300,
        150,
        100,
        100,
      ),
      t(
        "lowerPrism",
        "Build the lower moonlight prism",
        "freeze",
        300,
        310,
        100,
        100,
      ),
      t("eyeFrost", "Clear the second sleepy eye", "melt", 735, 335, 50, 50, {
        requires: ["upperPrism", "lowerPrism"],
      }),
    ],
    props: [p("sleepmask", 710, 360, undefined, { scale: 1 })],
    cast: [
      p("stitchtailor", 135, 340, undefined, {
        scale: 0.6,
        reveal: { kind: "stitchstars", x: 135, y: 340, scale: 0.6 },
      }),
      p("dozycourier", 835, 245, undefined, { scale: 0.6 }),
      p("bramble", 520, 485, undefined, { scale: 0.55 }),
    ],
    stamp: "MOONS MATCHED. SAFETY STARS ON.",
    extra: {
      start: [350, 98],
      temp: -20,
      par: 170,
      optics: {
        source: { x: 160, y: 200, dx: 1, dy: 0 },
        mirrors: [
          {
            target: "upperPrism",
            x: 350,
            y: 200,
            angle: Math.PI / 4,
            length: 100,
            housing: "prism",
          },
          {
            target: "lowerPrism",
            x: 350,
            y: 360,
            angle: Math.PI / 4,
            length: 100,
            housing: "prism",
          },
        ],
        detectors: [
          {
            id: "leftEye",
            name: "Left eye",
            x: 665,
            y: 360,
            radius: 10,
            label: [635, 415],
          },
          {
            id: "rightEye",
            name: "Right eye",
            x: 755,
            y: 360,
            radius: 10,
            label: [785, 415],
          },
        ],
      },
      needsSignals: ["leftEye", "rightEye"],
      completionHint: "Both sleepy eyes need the same moonlight.",
    },
  },
  {
    targets: [
      t(
        "envelope",
        "Unwrap the very large small worry",
        "melt",
        320,
        200,
        350,
        110,
      ),
      warm(
        "firstReply",
        "Offer one small yes",
        265,
        435,
        [25, 40],
        [15, 35],
        ["envelope"],
      ),
      warm(
        "secondReply",
        "Offer another small yes",
        450,
        435,
        [25, 40],
        [15, 35],
        ["envelope"],
      ),
      warm(
        "thirdReply",
        "Offer a very comfy yes",
        635,
        435,
        [25, 40],
        [15, 35],
        ["envelope"],
      ),
    ],
    props: [
      p("worrynote", 495, 302, "envelope", { scale: 1.15 }),
      p("goodnightbrooch", 317, 485, "firstReply", { scale: 0.6 }),
      p("goodnightbrooch", 502, 485, "secondReply", { scale: 0.6 }),
      p("goodnightbrooch", 687, 485, "thirdReply", { scale: 0.6 }),
    ],
    cast: [
      p("stitchtailor", 135, 310, undefined, { scale: 0.65 }),
      p("dozycourier", 835, 275, undefined, { scale: 0.7 }),
      p("bramble", 835, 465, undefined, {
        scale: 0.6,
        reveal: { kind: "bramblemoss", x: 835, y: 465, scale: 0.6 },
      }),
    ],
    stamp: "YES. MOSS COUNTS AS A PILLOW.",
    extra: { start: [495, 140], par: 185 },
  },
  {
    targets: [
      t("waterTray", "Fill the first night's tray", "fill", 250, 200, 120, 60),
      t(
        "icedTray",
        "Unpack the second night's tray",
        "melt",
        415,
        280,
        120,
        75,
      ),
      t(
        "supportTray",
        "Support the third night's tray",
        "freeze",
        570,
        365,
        120,
        60,
      ),
      warm(
        "lastNight",
        "Warm the fourth night's badge",
        725,
        450,
        [30, 45],
        [20, 40],
        ["waterTray", "icedTray", "supportTray"],
      ),
    ],
    props: [
      p("cup", 310, 252, "waterTray", { scale: 0.65 }),
      p("sparepillow", 475, 347, "icedTray", { scale: 0.65 }),
      p("helpfulstamps", 440, 475, "lastNight", { scale: 1 }),
      p("goodnightbrooch", 777, 498, "lastNight", { scale: 0.65 }),
    ],
    cast: [
      p("stitchtailor", 135, 310, undefined, { scale: 0.65 }),
      p("dozycourier", 835, 265, undefined, { scale: 0.65 }),
      p("bramble", 665, 325, undefined, { scale: 0.55 }),
    ],
    stamp: "HELPFUL IS NOT THE SAME AS HARMLESS-LOOKING.",
    extra: { start: [310, 140], temp: 20, par: 180 },
  },
  {
    targets: [
      t(
        "leftSpine",
        "Build the left bedtime spine",
        "freeze",
        340,
        210,
        110,
        65,
      ),
      t(
        "rightSpine",
        "Build the right bedtime spine",
        "freeze",
        555,
        210,
        110,
        65,
      ),
      t("binding", "Turn the binding wheel", "spin", 435, 325, 125, 90, {
        requires: ["leftSpine", "rightSpine"],
      }),
      warm(
        "cover",
        "Warm the new cover's lantern",
        660,
        450,
        [25, 40],
        [10, 30],
        ["binding"],
      ),
    ],
    props: [
      p("dreampostcards", 325, 430, "binding", { scale: 0.75 }),
      p("dreambook", 650, 423, "cover", { scale: 1.05 }),
      p("goodnightbrooch", 712, 498, "cover", { scale: 0.6 }),
    ],
    stamp: "A NEW COVER. THE SAME LOVELY BRAMBLE.",
    extra: { start: [395, 150], temp: -20, par: 180 },
  },
  {
    targets: [
      t("seam", "Support the first panel", "freeze", 425, 280, 120, 125, {
        phase: {
          steps: [
            {
              verb: "freeze",
              name: "Support the first panel",
              signal: "panel:first",
            },
            {
              verb: "melt",
              name: "Open the second panel",
              signal: "panel:second",
            },
            {
              verb: "freeze",
              name: "Repair the new seam",
              needsSignals: ["panel:second"],
              signal: "seam:repaired",
            },
          ],
        },
      }),
    ],
    props: [
      p("dreamquilt", 305, 390, undefined, {
        scale: 0.85,
        signal: "panel:first",
      }),
      p("dreamquilt", 665, 390, undefined, {
        scale: 0.85,
        tint: "#a89bd1",
        signal: "panel:second",
      }),
      p("reconsiderquilt", 485, 500, undefined, {
        scale: 0.8,
        signal: "seam:repaired",
        revealOnly: true,
      }),
    ],
    stamp: "CHANGED MY MIND. STILL ME.",
    extra: { start: [485, 220], temp: -20, par: 155 },
  },
  {
    targets: [
      t("leftCradle", "Pack the left book cradle", "freeze", 335, 435, 130, 55),
      t(
        "rightCradle",
        "Pack the right book cradle",
        "freeze",
        515,
        435,
        130,
        55,
      ),
      t("clasp", "Open the last collection clasp", "melt", 440, 210, 115, 70, {
        requires: ["leftCradle", "rightCradle"],
      }),
      t(
        "stamper",
        "Stamp the far-left dispatch tray",
        "spin",
        235,
        305,
        110,
        80,
      ),
      warm(
        "departure",
        "Warm the departure seal",
        675,
        435,
        [30, 45],
        [15, 35],
        ["clasp", "stamper"],
      ),
    ],
    props: [
      p("dreamsatchel", 495, 414, "departure", { scale: 1.1 }),
      p("stamp", 290, 382, "stamper", { scale: 0.85 }),
      p("goodnightbrooch", 727, 485, "departure", { scale: 0.65 }),
    ],
    stamp: "POCKET FOREST INCLUDED FOR STAFF BREAKS.",
    extra: { start: [400, 375], temp: -20, par: 215 },
  },
  {
    targets: [
      t("bedtime", "Fill the shared bedtime cup", "fill", 435, 440, 135, 70),
      warm(
        "stitchNight",
        "Say goodnight to Stitch",
        265,
        445,
        [25, 40],
        [10, 30],
        ["bedtime"],
      ),
      warm(
        "dozyNight",
        "Say goodnight to Dozy",
        605,
        445,
        [25, 40],
        [10, 30],
        ["bedtime"],
      ),
      warm(
        "brambleNight",
        "Say goodnight to Bramble",
        755,
        445,
        [25, 40],
        [10, 30],
        ["bedtime"],
      ),
      t("lullaby", "Turn the little lullaby wheel", "spin", 440, 155, 115, 75, {
        requires: ["stitchNight", "dozyNight", "brambleNight"],
      }),
    ],
    props: [
      p("seamworkspanorama", 480, 410, undefined, { scale: 0.95 }),
      p("cup", 502, 503, "bedtime", { scale: 0.85 }),
    ],
    cast: [],
    stamp: "AND A GOODNIGHT FOR THE SQUAD.",
    extra: { start: [502, 380], temp: 20, par: 215 },
  },
];

const dispatches = [
  "The welcome sign has frozen mid-yawn. Dozy is prepared to receive the rest of it.",
  "This pillow booked an exciting journey. Please build it a very boring landing.",
  "One goodnight is too shy to glow. Dozy has brought an unnecessarily large listening funnel.",
  "Tomorrow is still in its packaging. Thaw the thread, then wind three little sunrises.",
  "The blanket's two sides disagree beautifully. Stitch both, then warm the comfort badge.",
  "A snore and a whisper have formed a duet. One needs puff; the other needs gentleness.",
  "The rain has requested a window seat. Clear the whole pane before filling its tiny cup.",
  "Bramble is auditioning to be comforting. Build the forest, then turn on both lanterns.",
  "This teapot carries a horizon. Open the lid, fill its cup, and warm one small sunset.",
  "Three endings got lost in a cave. Please find them all; the cave would like to be included.",
  "Someone dreamed tomatoes into orbit. Water both beds before building their planetary trellis.",
  "Two sleepwalkers, two crossings, one cup of tea. Light the slippers once everything is ready.",
  "Bramble's apology is wearing its rough side out. Open it, reassure it, then add a softer lining.",
  "The sleep mask needs matching moons. Build both reflective prisms and clear its second eye.",
  "An enormous envelope contains a tiny worry. Three warm replies should just about cover it.",
  "Four different nights need four different repairs. Finish the first three before warming the last.",
  "Bramble's new bedtime book needs two spines, a good binding, and a much kinder cover.",
  "Support the first panel, open the seam for the second, then freeze a new seam. Changing your mind is allowed.",
  "Last collection! Pack both cradles, open the clasp, and stamp the tray before warming the seal.",
  "Fill the bedtime cup and warm three goodnights. The little lullaby wheel has one more for you.",
];

const source = designs.packs.find((pack) => pack.id === "12")!;
export const seamworksLevels: Level[] = source.scenes.map((card, index) => {
  const recipe = recipes[index];
  return {
    id: card.id,
    pack: "12",
    name: card.title,
    chapter: source.title,
    theme: "seamworks",
    pitch: dispatches[index],
    hint: card.puzzle,
    ending: card.payoff,
    start: [475, 145],
    temp: 40,
    pressure: 40,
    par: 60 + recipe.targets.length * 25,
    targets: recipe.targets,
    props: [...recipe.props, ...(recipe.cast ?? cast(index >= 7))],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
