import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/12-16.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 105, 60, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.75, ...extra });
const cast = (sleet: boolean): Prop[] => [
  p("nimbusgardener", 135, 330, undefined, { scale: 0.65 }),
  p("breebarometer", 835, 275, undefined, { scale: 0.7 }),
  ...(sleet ? [p("sleetseedling", 835, 465, undefined, { scale: 0.7 })] : []),
];
const recipes: {
  targets: Target[];
  props: Prop[];
  cast?: Prop[];
  stamp: string;
  extra?: Partial<Level>;
}[] = [
  {
    targets: [
      t(
        "forecast",
        "Thaw the tall frozen forecast",
        "melt",
        410,
        200,
        170,
        240,
      ),
    ],
    props: [
      p("forecastsign", 495, 424, "forecast", {
        scale: 1.05,
        reveal: { x: 495, y: 325 },
      }),
      p("forecastpots", 485, 498, "forecast", { scale: 1.1 }),
    ],
    stamp: "OUTLOOK: CAUTIOUSLY BOTANICAL.",
    extra: { start: [495, 140], temp: 20, par: 100 },
  },
  {
    targets: [
      t("bed", "Build a bed for the snow peas", "freeze", 330, 440, 270, 50),
      t("packet", "Unpack the scarf-loving seeds", "melt", 425, 215, 140, 80, {
        requires: ["bed"],
      }),
    ],
    props: [
      p("letter", 495, 287, "packet", { scale: 0.9 }),
      p("snowpeas", 465, 425, "packet", { scale: 1.15, revealOnly: true }),
      p("storybook", 700, 405, undefined, { scale: 0.8 }),
      p("spoon", 700, 360, undefined, {
        scale: 1.15,
        reveal: { x: 702, y: 380, scale: 0.6 },
      }),
      p("scarf", 320, 400, "packet", { scale: 0.65 }),
    ],
    stamp: "THE SOUP SPOON WAS A BOOKMARK. OBVIOUSLY.",
    extra: { start: [465, 380], temp: -20, par: 120 },
  },
  {
    targets: [
      warm(
        "sunseed",
        "Warm one voluntary spring",
        350,
        420,
        [35, 50],
        [15, 35],
        [],
        { w: 230, h: 65 },
      ),
    ],
    props: [
      p("circustable", 475, 493, undefined, { scale: 1.6 }),
      p("sunseed", 465, 411, "sunseed", { scale: 1.1 }),
    ],
    stamp: "SPRING HAS AGREED TO TAKE ITS SWEATER OFF.",
    extra: { start: [465, 360], temp: 40, pressure: 25, par: 90 },
  },
  {
    targets: [
      t("cover", "Thaw the ventilation cover", "melt", 625, 205, 120, 80),
      t("wheel", "Give this breeze its first job", "spin", 615, 355, 140, 95, {
        requires: ["cover"],
      }),
    ],
    props: [
      p("breezeletters", 375, 365, "wheel", { scale: 1.1 }),
      p("nurserycloud", 470, 470, "wheel", { scale: 0.7 }),
      p("airrosette", 685, 482, "wheel", { scale: 0.8, revealOnly: true }),
    ],
    stamp: "EMPLOYEE OF THE AIR. EXCELLENT REFERENCES.",
    extra: { start: [685, 145], par: 125 },
  },
  {
    targets: [
      warm(
        "mushroom",
        "Keep the fog mushroom pleasantly mild",
        275,
        380,
        [20, 35],
        [10, 30],
        [],
        { w: 140, h: 75 },
      ),
      warm(
        "sunseed",
        "Give the sunseed a brighter afternoon",
        600,
        235,
        [55, 75],
        [35, 55],
        [],
        { w: 145, h: 85 },
      ),
    ],
    props: [
      p("fogmushroom", 345, 370, "mushroom", { scale: 1.05 }),
      p("sunseed", 672, 245, "sunseed", { scale: 0.85 }),
      p("storybook", 510, 465, undefined, { scale: 0.8 }),
    ],
    stamp: "COMFORT HAS MORE THAN ONE SETTING.",
    extra: { start: [345, 320], temp: 25, pressure: 20, par: 130 },
  },
  {
    targets: [
      t("leftPane", "Clear the centered skylight", "melt", 280, 200, 150, 95),
      t(
        "leftRain",
        "Fill the round cloud's rain basin",
        "fill",
        310,
        425,
        100,
        65,
        { requires: ["leftPane"] },
      ),
      t("rightPane", "Clear the offset skylight", "melt", 560, 260, 180, 90),
      t(
        "rightRain",
        "Fill the gloriously lopsided cloud",
        "fill",
        650,
        430,
        100,
        65,
        { requires: ["rightPane"] },
      ),
    ],
    props: [
      p("nurserycloud", 360, 385, "leftRain", { scale: 0.85 }),
      p("lopsidedcloud", 700, 390, "rightRain", { scale: 0.85 }),
    ],
    stamp: "BOTH CLOUDS ARE EQUALLY CERTIFIED.",
    extra: { start: [355, 140], par: 175 },
  },
  {
    targets: [
      t("roots", "Build Sleet's cold root bed", "freeze", 300, 425, 170, 65),
      warm(
        "care",
        "Warm Sleet's separate care badge",
        610,
        330,
        [25, 40],
        [15, 30],
        ["roots"],
        { w: 135, h: 70 },
      ),
    ],
    props: [p("mixedlabel", 490, 250, "care", { scale: 1 })],
    cast: [
      p("nimbusgardener", 135, 330, undefined, { scale: 0.65 }),
      p("breebarometer", 835, 275, undefined, { scale: 0.7 }),
      p("sleetseedling", 490, 400, undefined, { scale: 1.05 }),
    ],
    stamp: "MIXED WEATHER. NOT MIXED UP.",
    extra: { start: [385, 365], temp: -20, par: 125 },
  },
  {
    targets: [
      t("hat", "Fill the rain collector's hat", "fill", 410, 250, 160, 65),
      t(
        "rainbow",
        "Turn the separate rainbow wheel",
        "spin",
        675,
        410,
        110,
        80,
        { requires: ["hat"] },
      ),
    ],
    props: [
      p("nimbusrainhat", 490, 395, undefined, { scale: 1 }),
      p("nimbusrainhat", 490, 395, undefined, {
        scale: 1,
        foreground: true,
        revealOnly: true,
      }),
      p("airrosette", 730, 390, "rainbow", { scale: 0.6 }),
    ],
    cast: [p("sleetseedling", 835, 265, undefined, { scale: 0.65 })],
    stamp: "STAFF UNIFORM: SLIGHTLY TOO SPECTACULAR.",
    extra: { start: [490, 190], temp: 20, par: 125 },
  },
  {
    targets: [
      t(
        "leftSoup",
        "Fill the left rainy-day soup basin",
        "fill",
        275,
        375,
        135,
        70,
      ),
      t(
        "rightSoup",
        "Fill the right rainy-day soup basin",
        "fill",
        610,
        375,
        135,
        70,
      ),
      warm(
        "steam",
        "Warm the blanket-shaped steam",
        450,
        450,
        [40, 55],
        [20, 40],
        ["leftSoup", "rightSoup"],
      ),
    ],
    props: [
      p("cup", 342, 437, "leftSoup", { scale: 0.85 }),
      p("cup", 677, 437, "rightSoup", { scale: 0.85 }),
      p("steamflower", 502, 435, "steam", { scale: 1.1 }),
      p("snowpeas", 500, 260, undefined, { scale: 0.7 }),
      p("spoon", 725, 300, undefined, { scale: 0.65 }),
    ],
    stamp: "SOUP FOR A SNOW PEA. NO INGREDIENT ASSUMPTIONS.",
    extra: { start: [342, 315], temp: 20, par: 150 },
  },
  {
    targets: [
      t("highWindow", "Clear the high cave window", "melt", 310, 190, 120, 75),
      t("lowWindow", "Clear the low cave window", "melt", 480, 285, 140, 90),
      warm(
        "fog",
        "Warm the cave's privacy mushroom",
        665,
        430,
        [20, 35],
        [10, 25],
        ["highWindow", "lowWindow"],
      ),
    ],
    props: [
      p("cavegarden", 465, 415, "fog", { scale: 1.1 }),
      p("fogmushroom", 717, 420, "fog", { scale: 0.85 }),
    ],
    stamp: "HOME. PLEASE KNOCK ON THE FOG.",
    extra: { start: [370, 135], par: 150 },
  },
  {
    targets: [
      t(
        "highCollar",
        "Build the high moonflower collar",
        "freeze",
        270,
        270,
        130,
        50,
      ),
      t(
        "middleCollar",
        "Build the middle moonflower collar",
        "freeze",
        435,
        340,
        130,
        50,
      ),
      t(
        "lowCollar",
        "Build the low moonflower collar",
        "freeze",
        600,
        410,
        130,
        50,
      ),
      warm(
        "moonlight",
        "Give the observatories their noon",
        750,
        455,
        [30, 45],
        [15, 35],
        ["highCollar", "middleCollar", "lowCollar"],
      ),
    ],
    props: [
      p("moonflower", 335, 259, "moonlight", { scale: 0.7 }),
      p("moonflower", 500, 329, "moonlight", { scale: 0.7 }),
      p("moonflower", 665, 399, "moonlight", { scale: 0.7 }),
      p("moon", 590, 180, undefined, { scale: 0.45 }),
    ],
    stamp: "BINOCULARS FOR EVERY POT. EVEN THAT ONE.",
    extra: { start: [335, 210], temp: -20, par: 180 },
  },
  {
    targets: [
      t("picnic", "Thaw the picnic forecast sign", "melt", 255, 205, 130, 80),
      t("pond", "Fill the duck's requested pond", "fill", 440, 410, 130, 70),
      t(
        "skating",
        "Build the neighbor's skating patch",
        "freeze",
        655,
        250,
        130,
        65,
      ),
      t(
        "display",
        "Turn on the neighborhood forecast",
        "spin",
        450,
        175,
        120,
        85,
        { requires: ["picnic", "pond", "skating"] },
      ),
    ],
    props: [
      p("highstreetweather", 495, 383, "display", { scale: 1.05 }),
      p("forecastsign", 320, 278, "picnic", { scale: 0.65 }),
    ],
    stamp: "SOMETHING FOR EVERYONE. LOCATIONS CLEARLY MARKED.",
    extra: { start: [320, 145], par: 180 },
  },
  {
    targets: [
      t(
        "wideRain",
        "Fill the generous rainforest basin",
        "fill",
        270,
        330,
        180,
        75,
      ),
      t(
        "middleRain",
        "Fill the modest rainforest basin",
        "fill",
        505,
        405,
        120,
        65,
      ),
      t(
        "tinyRain",
        "Aim close above the tiny rainforest",
        "fill",
        700,
        320,
        70,
        55,
      ),
    ],
    props: [
      p("rainforestpot", 360, 318, "wideRain", { scale: 0.85 }),
      p("rainforestpot", 565, 393, "middleRain", { scale: 0.7 }),
      p("tinyforestpot", 735, 308, "tinyRain", { scale: 1.15 }),
    ],
    cast: [
      p("nimbusgardener", 135, 330, undefined, { scale: 0.65 }),
      p("breebarometer", 835, 200, undefined, { scale: 0.65 }),
      p("sleetseedling", 835, 470, undefined, {
        scale: 0.65,
        reveal: { kind: "sleetumbrella", x: 835, y: 470, scale: 0.65 },
      }),
    ],
    stamp: "SMALLEST BASIN. MOST CONFIDENT UMBRELLA.",
    extra: { start: [360, 270], temp: 20, par: 155 },
  },
  {
    targets: [
      t(
        "reservoir",
        "Fill the upper forecast reservoir",
        "fill",
        415,
        160,
        150,
        95,
      ),
      t("nearBlock", "Open the short cloud channel", "melt", 370, 270, 60, 60),
      t("farBlock", "Open the scenic cloud channel", "melt", 550, 270, 60, 60),
      t(
        "nearCloud",
        "Send overflow to the near cloud",
        "fill",
        235,
        410,
        150,
        80,
        { flowOnly: true, requires: ["nearBlock"] },
      ),
      t(
        "farCloud",
        "Send overflow along the scenic route",
        "fill",
        680,
        410,
        150,
        80,
        { flowOnly: true, requires: ["farBlock"] },
      ),
    ],
    props: [
      p("nurserycloud", 310, 398, "nearCloud", { scale: 0.8 }),
      p("lopsidedcloud", 755, 398, "farCloud", { scale: 0.8 }),
      p("raincurtain", 525, 410, undefined, { scale: 1.05, revealOnly: true }),
    ],
    cast: [
      p("nimbusgardener", 135, 330, undefined, { scale: 0.65 }),
      p("breebarometer", 835, 225, undefined, { scale: 0.65 }),
      p("sleetseedling", 520, 530, undefined, { scale: 0.65 }),
    ],
    stamp: "PLUMBING. OCCASIONALLY MISTAKEN FOR DESTINY.",
    extra: {
      start: [400, 210],
      temp: 40,
      par: 220,
      channels: {
        inlet: { x: 470, y: 210, w: 40, h: 25 },
        junction: [490, 280],
        branches: [
          {
            target: "nearCloud",
            gate: "nearBlock",
            overflowFrom: "reservoir",
            via: [
              [400, 300],
              [310, 300],
            ],
          },
          {
            target: "farCloud",
            gate: "farBlock",
            overflowFrom: "reservoir",
            via: [
              [580, 300],
              [780, 300],
              [850, 340],
              [850, 450],
            ],
          },
        ],
      },
    },
  },
  {
    targets: [
      t(
        "rehearsal",
        "Give the thunder rehearsal some power",
        "spin",
        275,
        285,
        145,
        105,
      ),
      warm(
        "insideVoice",
        "Ask for one tiny indoor rumble",
        635,
        415,
        [25, 40],
        [10, 20],
        ["rehearsal"],
        { w: 110, h: 65 },
      ),
    ],
    props: [
      p("thundergourd", 510, 365, "insideVoice", { scale: 1.05 }),
      p("floweraudience", 475, 495, "insideVoice", { scale: 1.05 }),
      p("airrosette", 690, 395, "insideVoice", {
        scale: 0.65,
        revealOnly: true,
      }),
    ],
    stamp: "THUNDER APPROPRIATE TO THE VENUE.",
    extra: { start: [347, 225], temp: 20, pressure: 80, par: 135 },
  },
  {
    targets: [
      t(
        "sunLabel",
        "Thaw the left tray's sun label",
        "melt",
        260,
        200,
        100,
        70,
      ),
      t(
        "steamLabel",
        "Thaw the left tray's steam label",
        "melt",
        390,
        280,
        100,
        70,
      ),
      warm(
        "warmTray",
        "Restore the warm-weather tray",
        335,
        440,
        [40, 55],
        [20, 40],
        ["sunLabel", "steamLabel"],
        { w: 120, h: 65 },
      ),
      t(
        "snowLabel",
        "Thaw the right tray's snow label",
        "melt",
        570,
        195,
        100,
        70,
      ),
      t(
        "moonLabel",
        "Thaw the right tray's moon label",
        "melt",
        700,
        275,
        100,
        70,
      ),
      t(
        "coldTray",
        "Restore the cold-weather tray",
        "freeze",
        610,
        435,
        160,
        65,
        { requires: ["snowLabel", "moonLabel"] },
      ),
    ],
    props: [
      p("sunseed", 395, 428, "warmTray", { scale: 0.85 }),
      p("snowpeas", 690, 422, "coldTray", { scale: 0.9 }),
      p("weatherlabels", 500, 210, undefined, { scale: 0.75 }),
      p("mixedlabel", 520, 495, undefined, { scale: 0.65 }),
    ],
    stamp: "DOUBLE-SIDED LABEL. THIRD EDGE RESERVED FOR DOODLES.",
    extra: { start: [310, 140], par: 235 },
  },
  {
    targets: [
      t("rainCase", "Fill the traveling rain case", "fill", 260, 250, 140, 65),
      t(
        "coldCase",
        "Build the traveling cold cradle",
        "freeze",
        455,
        345,
        150,
        60,
      ),
      t("clasp", "Thaw the packed cases' clasp", "melt", 655, 210, 120, 75, {
        requires: ["rainCase", "coldCase"],
      }),
      warm(
        "departure",
        "Warm the departure badge",
        600,
        455,
        [30, 45],
        [15, 35],
        ["clasp"],
        { w: 115, h: 60 },
      ),
    ],
    props: [
      p("seasoncases", 455, 438, "departure", {
        scale: 1.1,
        reveal: { x: 455, y: 510, scale: 0.95 },
      }),
      p("letter", 715, 278, "clasp", { scale: 0.8 }),
    ],
    stamp: "FOURTH CASE OPEN. WEATHER CHOICE PENDING.",
    extra: { start: [330, 190], temp: 20, par: 190 },
  },
  {
    targets: [
      t("planter", "Follow the hanging basket", "fill", 400, 340, 160, 70, {
        motion: { rx: 175, ry: 0, period: 14, phase: 0 },
      }),
    ],
    props: [
      p("hangingplanter", 0, 0, "planter", { follow: "planter", scale: 1 }),
      p("hangingplanter", 0, 0, "planter", {
        follow: "planter",
        scale: 1,
        foreground: true,
        revealOnly: true,
      }),
    ],
    stamp: "RETURN TICKET GROWN. SCENERY APPROVED.",
    extra: { start: [655, 288], temp: 20, par: 145 },
  },
  {
    targets: [
      t(
        "lowRoots",
        "Build Sleet's low snowy roots",
        "freeze",
        280,
        405,
        120,
        55,
      ),
      t(
        "highRoots",
        "Build Sleet's high snowy roots",
        "freeze",
        455,
        290,
        130,
        55,
      ),
      t(
        "drizzle",
        "Fill Sleet's personal rain basin",
        "fill",
        620,
        375,
        130,
        65,
      ),
      warm(
        "sun",
        "Warm Sleet's demonstration sun",
        450,
        450,
        [35, 50],
        [15, 35],
        ["lowRoots", "highRoots", "drizzle"],
        { w: 120, h: 65 },
      ),
    ],
    props: [
      p("weddingchair", 240, 385, undefined, { scale: 0.65 }),
      p("mixedlabel", 700, 480, "sun", {
        scale: 0.75,
        reveal: { x: 700, y: 520 },
      }),
    ],
    cast: [
      p("nimbusgardener", 135, 330, undefined, { scale: 0.65 }),
      p("breebarometer", 835, 275, undefined, { scale: 0.7 }),
      p("sleetseedling", 385, 375, undefined, {
        scale: 0.95,
        reveal: { kind: "sleetbloom", x: 385, y: 375, scale: 0.95 },
      }),
    ],
    stamp: "GOOD AT BEING SLEET. NO QUALIFICATIONS.",
    extra: { start: [340, 345], temp: -20, par: 185 },
  },
  {
    targets: [
      t(
        "nameplate",
        "Thaw the wide greenhouse nameplate",
        "melt",
        335,
        190,
        310,
        90,
      ),
      warm(
        "firstFarewell",
        "Warm the first traveling farewell",
        280,
        425,
        [25, 40],
        [15, 35],
        ["nameplate"],
        { w: 120, h: 65 },
      ),
      warm(
        "secondFarewell",
        "Warm the second traveling farewell",
        620,
        425,
        [25, 40],
        [15, 35],
        ["nameplate"],
        { w: 120, h: 65 },
      ),
      t(
        "dispatch",
        "Send the weather worth sharing",
        "spin",
        445,
        345,
        100,
        75,
        { requires: ["nameplate", "firstFarewell", "secondFarewell"] },
      ),
    ],
    props: [p("conservatorypanorama", 480, 415, undefined, { scale: 1 })],
    cast: [],
    stamp: "LOCALLY GROWN WEATHER. UNEXPECTED WEATHER WELCOME.",
    extra: { start: [490, 130], par: 200 },
  },
];

const dispatches = [
  "The forecast is Brisk, Possibly Very Brisk. Thaw the whole tall sign and give indoor gardening a chance.",
  "Snow peas need a cold bed before unpacking. Nimbus insists the soup spoon is a gardening bookmark.",
  "The sunseed is unconvinced about spring. Warm its care frame gently; the sweater can wait.",
  "This breeze has excellent references. Clear its cover, then give the ventilation wheel its first shift.",
  "A mushroom's cozy morning is not a sunseed's lovely afternoon. Their labels explain the difference.",
  "Clear either skylight, then fill its own rain basin. The second cloud is proudly not symmetrical.",
  "Sleet wants cold roots and a warm welcome. There is room in this nursery for both.",
  "Fill Nimbus's rain hat, then power the separate rainbow wheel. Bree has concerns about the uniform.",
  "Two soup basins and one steam-flower need attention. No one is making assumptions about the snow pea.",
  "Clear both viewing windows, then warm a little fog. Even a painted cave dragon deserves some privacy.",
  "Three moonflowers need cold collars before their light badge warms. Gardening binoculars are standing by.",
  "Picnic weather, duck weather, skating weather. Prepare all three bays before turning on the display.",
  "Three basins, three pocket rainforests. The smallest one has plans for an unreasonable leaf.",
  "Open either frozen branch and fill the upper reservoir. Keep supplying it to send overflow to both clouds.",
  "First a powerful rehearsal, then a very gentle inside voice. The flowerpot audience brought ear defenders.",
  "Each pair of frozen labels belongs to its own tray. One tray wants warmth; the other wants a cold bed.",
  "Fill the rain case and build the cold cradle before opening the clasp. Warm the badge when packing is done.",
  "Follow the hanging basket with liquid water. It keeps every useful drop and is in absolutely no hurry.",
  "Two cold root patches, one rain basin, one warm sun. Sleet would like to demonstrate being Sleet.",
  "Clear the nameplate, warm both farewells, then turn the dispatch wheel. Unexpected weather travels with us.",
];
const source = designs.packs.find((pack) => pack.id === "13")!;
export const conservatoryLevels: Level[] = source.scenes.map((card, index) => {
  const recipe = recipes[index];
  return {
    id: card.id,
    pack: "13",
    name: card.title,
    chapter: source.title,
    theme: "conservatory",
    pitch: dispatches[index],
    hint: card.puzzle,
    ending: card.payoff,
    start: [475, 145],
    temp: 40,
    pressure: 40,
    par: 60 + recipe.targets.length * 25,
    targets: recipe.targets,
    props: [...recipe.props, ...(recipe.cast ?? cast(index >= 6))],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
