import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/12-16.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 105, 60, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.75, ...extra });
const cast = (edna: boolean): Prop[] => [
  p("gillsconductor", 135, 330, undefined, { scale: 0.7 }),
  p("sprigporter", 835, 275, undefined, { scale: 0.8 }),
  ...(edna ? [p("ednalibrarian", 835, 465, undefined, { scale: 0.7 })] : []),
];
const recipes: {
  targets: Target[];
  props: Prop[];
  cast?: Prop[];
  stamp: string;
  extra?: Partial<Level>;
}[] = [
  {
    targets: [
      t("window", "Thaw the full ticket window", "melt", 310, 245, 340, 100),
    ],
    props: [
      p("giantpunchedticket", 480, 335, "window", {
        scale: 1.25,
        reveal: { x: 190, y: 350, scale: 0.6 },
      }),
      p("ticketpunch", 655, 385, "window", { scale: 1.05 }),
    ],
    cast: [
      p("gillsconductor", 135, 330, undefined, { scale: 0.7 }),
      p("sprigporter", 725, 415, undefined, { scale: 0.85 }),
    ],
    stamp: "ONE MAGNIFICENT HOLE. DESTINATION OPTIONAL.",
    extra: { start: [480, 185], temp: 20, par: 95 },
  },
  {
    targets: [
      warm(
        "boiler",
        "Warm the boiler, not the books",
        410,
        390,
        [45, 65],
        [25, 45],
        [],
        { w: 160, h: 80 },
      ),
    ],
    props: [
      p("myceliumcarriage", 485, 350, "boiler", { scale: 1.1 }),
      p("boilergauge", 690, 365, "boiler", { scale: 1 }),
      p("librarycrate", 300, 445, "boiler", { scale: 0.9 }),
    ],
    stamp: "DUST JACKETS. NEVER CRUST JACKETS.",
    extra: { start: [490, 330], temp: 55, pressure: 35, par: 95 },
  },
  {
    targets: [
      t(
        "nearTrack",
        "Build the near missing railway",
        "freeze",
        300,
        445,
        150,
        50,
      ),
      t(
        "farTrack",
        "Build the far missing railway",
        "freeze",
        490,
        445,
        150,
        50,
      ),
      t("wheelCover", "Thaw the far wheel cover", "melt", 625, 330, 125, 100, {
        requires: ["nearTrack", "farTrack"],
      }),
    ],
    props: [
      p("myceliumcarriage", 575, 390, "wheelCover", {
        scale: 1,
        reveal: { x: 450, y: 405, scale: 1 },
      }),
    ],
    stamp: "ALMOST THREE MUSHROOM CAPS. A RECORD JOURNEY.",
    extra: { start: [375, 385], temp: -20, par: 155 },
  },
  {
    targets: [
      t("board", "Thaw the high destination board", "melt", 435, 180, 350, 60),
      t("fan", "Air the departure hats", "spin", 285, 385, 125, 95, {
        requires: ["board"],
      }),
    ],
    props: [
      p("departurehats", 610, 370, "fan", { scale: 1.1 }),
      p("porterhandcart", 500, 475, "fan", { scale: 0.65 }),
    ],
    stamp: "HATS AIRED. ROUTE PREPARED.",
    extra: { start: [610, 125], par: 125 },
  },
  {
    targets: [
      t(
        "engineWater",
        "Fill the locomotive's water stop",
        "fill",
        285,
        310,
        160,
        65,
      ),
      t(
        "coachWater",
        "Fill the carriage's water stop",
        "fill",
        500,
        405,
        125,
        65,
      ),
      t(
        "cartWater",
        "Fill the tiny handcart's water stop",
        "fill",
        700,
        270,
        70,
        55,
      ),
    ],
    props: [
      p("myceliumcarriage", 365, 298, "engineWater", { scale: 0.7 }),
      p("myceliumcarriage", 562, 393, "coachWater", { scale: 0.55 }),
      p("porterhandcart", 735, 258, "cartWater", { scale: 0.45 }),
    ],
    stamp: "SMALLEST STEAM CURL. LOUDEST APPLAUSE.",
    extra: { start: [365, 250], temp: 20, par: 150 },
  },
  {
    targets: [
      t(
        "rack",
        "Build the branch-friendly luggage rack",
        "freeze",
        330,
        430,
        180,
        60,
      ),
      t(
        "coat",
        "Unpack the passenger's branching coat",
        "melt",
        350,
        215,
        150,
        90,
        { requires: ["rack"] },
      ),
      warm(
        "cushion",
        "Warm the independent seat cushion",
        635,
        400,
        [25, 40],
        [10, 30],
        [],
        { w: 125, h: 70 },
      ),
    ],
    props: [
      p("coat", 425, 297, "coat", { scale: 0.9 }),
      p("acornpassenger", 530, 409, undefined, { scale: 1 }),
      p("cushiontickets", 697, 388, "cushion", { scale: 0.9, tint: "#d6b47b" }),
    ],
    stamp: "LUGGAGE ALLOWANCE NOW INCLUDES LEAF ROOM.",
    extra: { start: [420, 370], temp: -20, par: 160 },
  },
  {
    targets: [
      t(
        "leftSkylight",
        "Clear the left reading-room skylight",
        "melt",
        275,
        205,
        150,
        90,
      ),
      t(
        "leftDrips",
        "Collect the left skylight's drips",
        "fill",
        335,
        415,
        100,
        65,
        { requires: ["leftSkylight"] },
      ),
      t(
        "rightSkylight",
        "Clear the right reading-room skylight",
        "melt",
        560,
        240,
        170,
        95,
      ),
      t(
        "rightDrips",
        "Collect the right skylight's drips",
        "fill",
        645,
        430,
        100,
        65,
        { requires: ["rightSkylight"] },
      ),
    ],
    props: [
      p("dripreadingroom", 485, 403, undefined, { scale: 1.05 }),
      p("librarycrate", 260, 470, undefined, { scale: 0.65 }),
    ],
    stamp: "A BRIEF HISTORY OF DRIPS. VOLUME ONE OF SEVEN.",
    extra: { start: [350, 145], par: 185 },
  },
  {
    targets: [
      warm(
        "nursery",
        "Set the nursery's cool comfort",
        275,
        420,
        [15, 30],
        [10, 25],
        [],
        { w: 140, h: 70 },
      ),
      warm(
        "nook",
        "Set the reading nook's cozy comfort",
        615,
        305,
        [40, 55],
        [20, 40],
        [],
        { w: 140, h: 70 },
      ),
    ],
    props: [
      p("quietnursery", 345, 408, "nursery", { scale: 0.9 }),
      p("dripreadingroom", 685, 293, "nook", { scale: 0.65 }),
      p("announcementcard", 255, 335, undefined, {
        scale: 0.75,
        revealOnly: true,
      }),
    ],
    stamp: "THIS ANNOUNCEMENT HAS BEEN QUIETLY WRITTEN.",
    extra: { start: [345, 360], temp: 20, pressure: 20, par: 135 },
  },
  {
    targets: [
      t("menu", "Thaw the platform soup menu", "melt", 365, 190, 255, 80),
      t(
        "platformOne",
        "Fill the platform one soup bowl",
        "fill",
        355,
        425,
        110,
        65,
        { requires: ["menu"] },
      ),
      t(
        "platformTwo",
        "Fill the platform two soup bowl",
        "fill",
        515,
        425,
        110,
        65,
        { requires: ["menu"] },
      ),
      warm(
        "kitchen",
        "Warm the station kitchen badge",
        445,
        315,
        [40, 55],
        [20, 40],
        ["platformOne", "platformTwo"],
      ),
    ],
    props: [
      p("letter", 492, 261, "menu", { scale: 1.1 }),
      p("platformsoup", 490, 485, undefined, {
        scale: 1,
        foreground: true,
        revealOnly: true,
      }),
      p("snowpeas", 700, 385, undefined, { scale: 0.75 }),
    ],
    stamp: "BOTH PLATFORMS HAVE ARRIVED AHEAD OF THE TRAIN.",
    extra: { start: [492, 130], par: 185 },
  },
  {
    targets: [
      t(
        "chart",
        "Clear the high observation chart",
        "melt",
        315,
        135,
        300,
        160,
      ),
      t("telescope", "Turn the local's telescope", "spin", 625, 390, 135, 95, {
        requires: ["chart"],
      }),
    ],
    props: [
      p("porterconstellation", 465, 350, "telescope", { scale: 1.05 }),
      p("moon", 710, 240, undefined, { scale: 0.5 }),
      p("porterhandcart", 375, 465, "telescope", { scale: 0.65 }),
    ],
    stamp: "PORTER'S REST. NO CELESTIAL LUGGAGE FEE.",
    extra: { start: [465, 83], par: 150 },
  },
  {
    targets: [
      t(
        "nearCrossing",
        "Build the near tiny crossing",
        "freeze",
        275,
        410,
        100,
        50,
      ),
      t(
        "middleCrossing",
        "Build the middle tiny crossing",
        "freeze",
        435,
        350,
        100,
        50,
      ),
      t(
        "farCrossing",
        "Build the far tiny crossing",
        "freeze",
        595,
        290,
        100,
        50,
      ),
      t(
        "name",
        "Reveal their respectable destination",
        "melt",
        710,
        200,
        105,
        70,
        { requires: ["nearCrossing", "middleCrossing", "farCrossing"] },
      ),
    ],
    props: [
      p("peafamily", 365, 350, "name", {
        scale: 0.9,
        reveal: { x: 645, y: 240, scale: 0.8 },
      }),
    ],
    cast: [
      p("gillsconductor", 135, 330, undefined, { scale: 0.7 }),
      p("sprigporter", 860, 330, undefined, { scale: 0.6 }),
      p("ednalibrarian", 835, 465, undefined, { scale: 0.7 }),
    ],
    stamp: "SOMEWHERE NEARBY. AN EXCELLENT DESTINATION.",
    extra: { start: [325, 350], temp: -20, par: 185 },
  },
  {
    targets: [
      t(
        "leftLabel",
        "Clear the left sleeper's label",
        "melt",
        265,
        190,
        130,
        75,
      ),
      t(
        "leftSeeds",
        "Fill the left sleeper seed basin",
        "fill",
        300,
        380,
        120,
        65,
        { requires: ["leftLabel"] },
      ),
      t(
        "rightLabel",
        "Clear the right sleeper's label",
        "melt",
        630,
        190,
        130,
        75,
      ),
      t(
        "rightSeeds",
        "Fill the right sleeper seed basin",
        "fill",
        640,
        395,
        110,
        65,
        { requires: ["rightLabel"] },
      ),
      t(
        "nightPanel",
        "Build the central night-sky panel",
        "freeze",
        460,
        245,
        110,
        230,
        { requires: ["leftSeeds", "rightSeeds"] },
      ),
    ],
    props: [
      p("sleeperseeds", 515, 465, "nightPanel", { scale: 0.95 }),
      p("sleeperseeds", 515, 465, "nightPanel", {
        scale: 0.95,
        foreground: true,
        revealOnly: true,
      }),
      p("librarycrate", 270, 490, undefined, { scale: 0.6 }),
    ],
    stamp: "BEDTIME TIMETABLE. ABSOLUTELY NO SMALL PRINT.",
    extra: { start: [330, 130], par: 225 },
  },
  {
    targets: [
      warm(
        "blueNear",
        "Welcome the near blue spore traveler",
        265,
        315,
        [15, 30],
        [10, 30],
        [],
        { w: 110, h: 70 },
      ),
      warm(
        "amberNear",
        "Welcome the near amber root visitor",
        435,
        415,
        [45, 60],
        [25, 45],
        [],
        { w: 110, h: 70 },
      ),
      warm(
        "blueFar",
        "Welcome the far blue spore traveler",
        595,
        260,
        [15, 30],
        [10, 30],
        [],
        { w: 110, h: 70 },
      ),
      warm(
        "amberFar",
        "Welcome the far amber root visitor",
        745,
        390,
        [45, 60],
        [25, 45],
        [],
        { w: 110, h: 70 },
      ),
    ],
    props: [
      p("cushiontickets", 320, 303, "blueNear", {
        scale: 0.8,
        tint: "#a9c5dc",
      }),
      p("cushiontickets", 490, 403, "amberNear", {
        scale: 0.8,
        tint: "#dfb777",
      }),
      p("cushiontickets", 650, 248, "blueFar", { scale: 0.8, tint: "#a9c5dc" }),
      p("cushiontickets", 800, 378, "amberFar", {
        scale: 0.8,
        tint: "#dfb777",
      }),
      p("ticketpunch", 595, 480, undefined, { scale: 0.65 }),
    ],
    cast: [
      p("gillsconductor", 135, 330, undefined, { scale: 0.7 }),
      p("sprigporter", 835, 225, undefined, { scale: 0.7 }),
      p("ednalibrarian", 680, 515, undefined, { scale: 0.65 }),
    ],
    stamp: "FOUR CAREFUL HOLES. FOUR ACTUAL DESTINATIONS.",
    extra: { start: [320, 255], temp: 20, pressure: 20, par: 180 },
  },
  {
    targets: [
      t("lift", "Start the freight carrier", "spin", 300, 330, 110, 100),
      t("cup", "Follow the freight cup", "fill", 600, 300, 140, 70, {
        requires: ["lift"],
        motion: {
          rx: 0,
          ry: 105,
          period: 16,
          phase: Math.PI / 2,
          after: ["lift"],
        },
      }),
    ],
    props: [
      p("freightcup", 0, 0, "cup", { follow: "cup", scale: 1 }),
      p("freightcup", 0, 0, "cup", {
        follow: "cup",
        scale: 1,
        foreground: true,
        revealOnly: true,
      }),
      p("freightcertificate", 470, 475, undefined, {
        scale: 0.75,
        revealOnly: true,
      }),
    ],
    extra: { start: [355, 278], temp: 20, pressure: 85, par: 160 },
    stamp: "CERTIFIED TO LIFT REFRESHMENTS. SLIGHTLY HIGHER.",
  },
  {
    targets: [
      t(
        "librarySign",
        "Clear the library branch sign",
        "melt",
        365,
        195,
        115,
        70,
      ),
      t(
        "libraryWheel",
        "Prepare the library branch",
        "spin",
        280,
        390,
        115,
        90,
        { requires: ["librarySign"] },
      ),
      t(
        "gardenSign",
        "Clear the garden branch sign",
        "melt",
        560,
        195,
        115,
        70,
      ),
      t("gardenWheel", "Prepare the garden branch", "spin", 650, 390, 115, 90, {
        requires: ["gardenSign"],
      }),
      warm(
        "route",
        "Warm the joined route badge",
        465,
        310,
        [30, 45],
        [15, 35],
        ["libraryWheel", "gardenWheel"],
        { w: 110, h: 70 },
      ),
    ],
    props: [p("junctionboard", 520, 298, "route", { scale: 1.05 })],
    stamp: "BOOKS TO THE GARDEN. SEEDS TO RESEARCH.",
    extra: { start: [422, 135], par: 225 },
  },
  {
    targets: [
      t("umbrella", "Clear the tall lost umbrella", "melt", 285, 185, 85, 235),
      t("scarf", "Clear the wide lost scarf", "melt", 425, 235, 210, 65),
      t(
        "lunchbox",
        "Clear the squat lost lunchbox",
        "melt",
        645,
        335,
        130,
        100,
      ),
      t(
        "returnBowl",
        "Fill a fresh lost-property water bowl",
        "fill",
        435,
        445,
        150,
        65,
        { requires: ["umbrella", "scarf", "lunchbox"] },
      ),
    ],
    props: [
      p("lostsnail", 530, 425, undefined, { scale: 1.05, revealOnly: true }),
    ],
    cast: [
      p("gillsconductor", 135, 330, undefined, { scale: 0.7 }),
      p("sprigporter", 835, 285, undefined, {
        scale: 0.8,
        reveal: { kind: "sprigscarf", x: 835, y: 285, scale: 0.8 },
      }),
      p("ednalibrarian", 835, 465, undefined, { scale: 0.7 }),
    ],
    stamp: "TWO CLAIMS. ONE KINDLY LENT SCARF.",
    extra: { start: [327, 125], par: 190 },
  },
  {
    targets: [
      t(
        "ramp",
        "Build the overlooked platform's ramp",
        "freeze",
        310,
        430,
        180,
        60,
      ),
      t(
        "water",
        "Fill the overlooked platform's basin",
        "fill",
        650,
        405,
        130,
        65,
      ),
      t(
        "nameplate",
        "Reveal the smallest platform's name",
        "melt",
        345,
        305,
        125,
        75,
        { requires: ["ramp", "water"] },
      ),
      warm(
        "welcome",
        "Warm Sprig Halt's welcome",
        510,
        210,
        [25, 40],
        [10, 30],
        ["nameplate"],
        { w: 130, h: 65 },
      ),
    ],
    props: [p("sprighalt", 500, 450, "welcome", { scale: 1.1 })],
    stamp: "SMALL PLATFORM. EXTENSIVE TRAVEL PLANS.",
    extra: { start: [400, 370], temp: -20, par: 190 },
  },
  {
    targets: [
      t(
        "counterweight",
        "Fill the freight counterweight inlet",
        "fill",
        610,
        175,
        100,
        65,
      ),
    ],
    props: [],
    extra: {
      start: [660, 123],
      temp: 20,
      pressure: 85,
      par: 160,
      balance: {
        id: "freight:level",
        x: 480,
        y: 315,
        arm: 180,
        left: { mass: 5 },
        right: { target: "counterweight", mass: 5 },
      },
      needsSignals: ["freight:level"],
      completionHint:
        "Let the freight scale settle. Modest ideas can be surprisingly heavy.",
    },
    stamp: "A SMALL BOOK OF SURPRISINGLY WEIGHTY IDEAS.",
  },
  {
    targets: [
      t("menu", "Thaw the final service menu", "melt", 330, 190, 280, 80),
      t(
        "familyBowl",
        "Fill the snail family's bowl",
        "fill",
        260,
        420,
        120,
        65,
        { requires: ["menu"] },
      ),
      t(
        "staffBowl",
        "Fill the station staff's bowl",
        "fill",
        430,
        435,
        110,
        65,
        { requires: ["menu"] },
      ),
      t("littleBowl", "Fill the little last bowl", "fill", 590, 445, 70, 55, {
        requires: ["menu"],
      }),
      t("trolley", "Turn the supper trolley wheel", "spin", 720, 330, 110, 95, {
        requires: ["familyBowl", "staffBowl", "littleBowl"],
      }),
    ],
    props: [
      p("staffsupper", 480, 420, undefined, { scale: 1 }),
      p("staffsupper", 480, 420, undefined, {
        scale: 1,
        foreground: true,
        revealOnly: true,
      }),
    ],
    cast: [],
    stamp: "FOURTH BOWL FOR THE PORTER. STAFF ARE PEOPLE TOO.",
    extra: { start: [470, 130], par: 220 },
  },
  {
    targets: [
      t(
        "nearWelcome",
        "Build the near welcome panel",
        "freeze",
        275,
        435,
        120,
        75,
      ),
      t(
        "farWelcome",
        "Build the far welcome panel",
        "freeze",
        580,
        435,
        120,
        75,
      ),
      warm(
        "boiler",
        "Warm the local service's boiler",
        430,
        330,
        [45, 65],
        [25, 45],
        ["nearWelcome", "farWelcome"],
        { w: 130, h: 65 },
      ),
      t(
        "departure",
        "Send the unhurried local on its way",
        "spin",
        745,
        430,
        110,
        85,
        { requires: ["boiler"] },
      ),
    ],
    props: [p("myceliumpanorama", 480, 380, undefined, { scale: 0.95 })],
    cast: [],
    stamp: "WE HAVE TIME. THE LITTLE PLATFORM GETS THE BIGGEST WAVE.",
    extra: { start: [335, 375], temp: -20, par: 190 },
  },
];

const dispatches = [
  "The ticket window is frozen. Sprig has brought a punch with very ambitious ideas about hole size.",
  "Warm the boiler gently. Edna's books have requested dust jackets, not a golden crust.",
  "Two short track beds are missing. Build both before thawing the carriage's far wheel cover.",
  "Clear the high destination board, then power the low fan. Airing enormous hats counts as route preparation.",
  "Three separate water stops need filling. The handcart's new smokestack is unnecessary and deeply important.",
  "Build a luggage rack before unpacking the coat. The seat cushion can have its warm welcome whenever you like.",
  "Clear either skylight and collect its drips before visiting the other branch. Edna has seven volumes ready.",
  "The nursery prefers cool comfort; the reading nook likes cozy warmth. Gills will announce both in writing.",
  "Clear the menu, fill both bowls, then warm the kitchen badge. The soup may arrive before the train.",
  "Clear the star chart, then turn the telescope. Sprig's handcart is about to acquire a constellation.",
  "Build three little crossings before revealing the stop's name. Six helpers are transporting one pea.",
  "Clear and fill either seed berth, then the other. Build their central night-sky panel when both are ready.",
  "Four tickets, two kinds of comfort. Blue travelers like mild warmth; amber visitors prefer something cozier.",
  "Start the lift once, then follow the freight cup with liquid water. Missed passes do not lose a drop of progress.",
  "Prepare either sign-and-wheel branch first. Warm the route badge once both destinations are ready.",
  "Clear the tall umbrella, wide scarf, and squat lunchbox. Then fill a fresh bowl for the lost-property reunion.",
  "Build the ramp and fill the basin before unveiling the nameplate. The smallest platform deserves a warm welcome.",
  "Fill the fixed counterweight inlet, then let the real scale settle. Edna's modest book is heavier than advertised.",
  "Clear the menu, fill all three bowls, and turn the trolley wheel. There is one more serving to remember.",
  "Build both welcome panels, warm the boiler, then turn the departure wheel. There is no countdown. We have time.",
];
const source = designs.packs.find((pack) => pack.id === "14")!;
export const myceliumLevels: Level[] = source.scenes.map((card, index) => {
  const recipe = recipes[index];
  return {
    id: card.id,
    pack: "14",
    name: card.title,
    chapter: source.title,
    theme: "mycelium",
    pitch: dispatches[index],
    hint: card.puzzle,
    ending: card.payoff,
    start: [475, 145],
    temp: 40,
    pressure: 40,
    par: 60 + recipe.targets.length * 25,
    targets: recipe.targets,
    props: [...recipe.props, ...(recipe.cast ?? cast(index >= 1))],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
