import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/12-16.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 105, 60, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.75, ...extra });
const cast = (zero: boolean): Prop[] => [
  p("drprobably", 135, 330, undefined, { scale: 0.7 }),
  p("marginassistant", 835, 275, undefined, { scale: 0.75 }),
  ...(zero ? [p("zeroexhibit", 835, 465, undefined, { scale: 0.65 })] : []),
];
const recipes: {
  targets: Target[];
  props: Prop[];
  cast?: Prop[];
  stamp: string;
  extra?: Partial<Level>;
}[] = [
  {
    targets: [
      t("plaque", "Unfreeze the whole explanation", "melt", 325, 235, 310, 100),
    ],
    props: [p("welcomeplaque", 480, 330, "plaque", { scale: 1 })],
    stamp: "WE THINK YOU'LL LIKE THIS. ENCOURAGING UNDERLINE INCLUDED.",
    extra: { start: [480, 175], temp: 20, par: 100 },
  },
  {
    targets: [
      t(
        "leftEdge",
        "Build the left edge of nothing",
        "freeze",
        325,
        235,
        70,
        210,
      ),
      t(
        "rightEdge",
        "Build the right edge of nothing",
        "freeze",
        585,
        235,
        70,
        210,
      ),
    ],
    props: [p("emptinesscaption", 490, 520, undefined, { scale: 0.85 })],
    cast: [
      p("drprobably", 135, 330, undefined, { scale: 0.7 }),
      p("marginassistant", 835, 275, undefined, { scale: 0.75 }),
      p("zeroexhibit", 490, 355, undefined, { scale: 1 }),
    ],
    stamp: "NOTHING. CAREFULLY PRESENTED.",
    extra: { start: [360, 175], temp: -20, par: 130 },
  },
  {
    targets: [
      warm(
        "kettle",
        "Give the kettle quite enough warmth",
        400,
        400,
        [45, 60],
        [20, 40],
        [],
        { w: 180, h: 75 },
      ),
    ],
    props: [
      p("almostkettle", 490, 350, "kettle", { scale: 1.05 }),
      p("biscuitclipboard", 690, 430, "kettle", { scale: 0.9 }),
    ],
    stamp: "ONE STEAM QUESTION. ONE BISCUIT ANSWER.",
    extra: { start: [490, 340], temp: 50, pressure: 30, par: 95 },
  },
  {
    targets: [
      t("cover", "Clear the wheel diagram's cover", "melt", 300, 220, 200, 100),
      t("wheel", "Turn to the other explanation", "spin", 620, 390, 125, 95, {
        requires: ["cover"],
      }),
    ],
    props: [p("turningproof", 400, 307, "wheel", { scale: 0.65 })],
    stamp: "THE REVERSE SIDE IS ALSO INTERESTING.",
    extra: { start: [400, 160], par: 130 },
  },
  {
    targets: [
      warm(
        "moss",
        "Keep the luminous moss pleasantly mild",
        275,
        380,
        [15, 30],
        [10, 25],
        [],
        { w: 140, h: 70 },
      ),
      warm(
        "sun",
        "Give the ceramic sun its warm afternoon",
        615,
        275,
        [55, 75],
        [35, 55],
        [],
        { w: 140, h: 80 },
      ),
    ],
    props: [
      p("luminousmoss", 345, 365, "moss", { scale: 0.9 }),
      p("ceramicsun", 685, 260, "sun", { scale: 0.8 }),
    ],
    stamp: "SIMILAR FRAME. DIFFERENT THING.",
    extra: { start: [345, 320], temp: 20, pressure: 20, par: 135 },
  },
  {
    targets: [
      t(
        "leftPane",
        "Carve a real opening in the left pane",
        "melt",
        310,
        210,
        140,
        95,
      ),
      t(
        "rightPane",
        "Clear the second specimen window",
        "melt",
        565,
        265,
        155,
        95,
      ),
      t(
        "basin",
        "Catch drops through the left opening",
        "fill",
        340,
        430,
        120,
        65,
      ),
    ],
    props: [p("tinymuseum", 520, 415, undefined, { scale: 1.05 })],
    stamp: "THE MUSEUM CONTAINS A MUSEUM. ZERO UNDERSTANDS.",
    extra: { start: [400, 158], par: 170 },
  },
  {
    targets: [
      t(
        "leftWater",
        "Fill the normally falling left water",
        "fill",
        275,
        405,
        150,
        70,
      ),
      t(
        "rightWater",
        "Fill the normally falling right water",
        "fill",
        600,
        435,
        150,
        70,
      ),
    ],
    props: [p("upsidedownroom", 495, 350, undefined, { scale: 1.05 })],
    stamp: "A CHANGE OF PERSPECTIVE. NOT OF PLUMBING.",
    extra: { start: [350, 345], temp: 20, par: 120 },
  },
  {
    targets: [
      t(
        "frame",
        "Build Zero's next-idea display frame",
        "freeze",
        360,
        325,
        110,
        170,
      ),
      t(
        "label",
        "Thaw the carefully prepared label",
        "melt",
        555,
        205,
        220,
        100,
        { requires: ["frame"] },
      ),
      warm(
        "welcome",
        "Warm the welcome for a next idea",
        620,
        420,
        [25, 40],
        [10, 30],
        ["label"],
        { w: 125, h: 70 },
      ),
    ],
    props: [p("roomforidea", 665, 290, "welcome", { scale: 0.65 })],
    stamp: "BLANK PAGE PROVIDED. CIRCULAR FLOURISH SIGNED.",
    extra: { start: [415, 265], temp: -20, par: 170 },
  },
  {
    targets: [
      t("wideToast", "Clear the wide toast cover", "melt", 270, 225, 150, 75),
      t("smallToast", "Clear the little toast cover", "melt", 450, 185, 90, 75),
      t(
        "grandToast",
        "Clear the ambitious toast cover",
        "melt",
        600,
        270,
        170,
        80,
      ),
      t("butter", "Fill the shared butter dish", "fill", 415, 430, 140, 65, {
        requires: ["wideToast", "smallToast", "grandToast"],
        fillColor: "#eac976bb",
      }),
      t(
        "napkin",
        "Build the independent napkin stand",
        "freeze",
        260,
        410,
        110,
        80,
      ),
    ],
    props: [
      p("squaretoast", 345, 298, "wideToast", { scale: 0.85 }),
      p("squaretoaststack", 495, 254, "smallToast", { scale: 0.6 }),
      p("squaretoastgarden", 685, 350, "grandToast", { scale: 0.95 }),
    ],
    stamp: "BREAKFAST GEOMETRY IS A MATTER OF TASTE.",
    extra: { start: [345, 165], par: 210 },
  },
  {
    targets: [
      t(
        "leftSupport",
        "Build next Tuesday's left support",
        "freeze",
        330,
        435,
        140,
        55,
      ),
      t(
        "rightSupport",
        "Build next Tuesday's right support",
        "freeze",
        525,
        435,
        140,
        55,
      ),
      t(
        "specimen",
        "Thaw the fossil of next Tuesday",
        "melt",
        335,
        175,
        330,
        195,
        { requires: ["leftSupport", "rightSupport"] },
      ),
    ],
    props: [p("tomorrowfossil", 500, 340, "specimen", { scale: 1.05 })],
    stamp: "EVIDENCE THAT SOMEONE IS LOOKING FORWARD TO SOMETHING.",
    extra: { start: [400, 375], temp: -20, par: 180 },
  },
  {
    targets: [
      t(
        "water",
        "Fill the question plant's watering basin",
        "fill",
        260,
        390,
        140,
        70,
      ),
      t(
        "lowTrellis",
        "Build the short question trellis",
        "freeze",
        420,
        435,
        110,
        50,
        { requires: ["water"] },
      ),
      t(
        "middleTrellis",
        "Build the middle question trellis",
        "freeze",
        555,
        290,
        80,
        185,
        { requires: ["water"] },
      ),
      t(
        "highTrellis",
        "Build the high question trellis",
        "freeze",
        695,
        250,
        80,
        225,
        { requires: ["water"] },
      ),
    ],
    props: [
      p("questionplant", 610, 465, undefined, { scale: 1.1 }),
      p("questionplant", 610, 465, undefined, {
        scale: 1.1,
        foreground: true,
        revealOnly: true,
      }),
    ],
    stamp: "ANSWER CARD LEFT BLANK. THERE IS NO RUSH.",
    extra: { start: [330, 330], temp: 20, par: 185 },
  },
  {
    targets: [
      t(
        "leftSign",
        "Clear the left visitor entrance",
        "melt",
        280,
        205,
        140,
        75,
      ),
      warm(
        "leftWelcome",
        "Welcome the left-hand queue",
        315,
        410,
        [25, 40],
        [15, 35],
        ["leftSign"],
        { w: 120, h: 65 },
      ),
      t(
        "rightSign",
        "Clear the right visitor entrance",
        "melt",
        605,
        245,
        150,
        75,
      ),
      warm(
        "rightWelcome",
        "Welcome the right-hand queue",
        620,
        425,
        [25, 40],
        [15, 35],
        ["rightSign"],
        { w: 120, h: 65 },
      ),
    ],
    props: [p("visitorqueue", 500, 395, undefined, { scale: 1.1 })],
    stamp: "ROOM FOR EVERYONE. THE QUEUE ACTUALLY AGREES.",
    extra: { start: [350, 145], par: 180 },
  },
  {
    targets: [
      t(
        "upperLeft",
        "Free the upper-left margin note",
        "melt",
        285,
        195,
        80,
        65,
      ),
      t(
        "upperRight",
        "Free the upper-right margin note",
        "melt",
        595,
        195,
        80,
        65,
      ),
      t(
        "lowerLeft",
        "Free the lower-left margin note",
        "melt",
        285,
        310,
        80,
        65,
      ),
      t(
        "lowerRight",
        "Free the lower-right margin note",
        "melt",
        595,
        310,
        80,
        65,
      ),
      warm(
        "original",
        "Warm the original explanation",
        355,
        440,
        [20, 35],
        [10, 25],
        ["upperLeft", "upperRight", "lowerLeft", "lowerRight"],
        { w: 115, h: 65 },
      ),
      warm(
        "correction",
        "Warm Margin's suggested correction",
        555,
        440,
        [45, 60],
        [25, 45],
        ["upperLeft", "upperRight", "lowerLeft", "lowerRight"],
        { w: 115, h: 65 },
      ),
    ],
    props: [p("marginnotes", 480, 365, undefined, { scale: 1.1 })],
    stamp: "CORRECTION CREDITED. MARGIN'S NAME IS BIGGER.",
    extra: { start: [325, 135], par: 225 },
  },
  {
    targets: [
      t(
        "leftPane",
        "Open and clear the first light pane",
        "melt",
        330,
        240,
        100,
        90,
      ),
      t(
        "rightPane",
        "Open and clear the second light pane",
        "melt",
        535,
        240,
        100,
        90,
      ),
    ],
    props: [
      p("lightquestion", 750, 235, undefined, {
        scale: 1,
        signal: "explanation:lit",
      }),
      p("letter", 700, 460, undefined, { scale: 0.8, revealOnly: true }),
    ],
    cast: [
      p("drprobably", 235, 455, undefined, { scale: 0.6 }),
      p("marginassistant", 835, 230, undefined, { scale: 0.65 }),
      p("zeroexhibit", 835, 465, undefined, { scale: 0.65 }),
    ],
    extra: {
      start: [380, 188],
      temp: 40,
      par: 150,
      optics: {
        source: { x: 165, y: 285, dx: 1, dy: 0 },
        mirrors: [],
        detectors: [
          {
            id: "explanation:lit",
            name: "Question mark",
            x: 790,
            y: 285,
            radius: 12,
            label: [790, 327],
          },
        ],
      },
      needsSignals: ["explanation:lit"],
      completionHint:
        "Clear both whole panes and let the real beam reach the question mark.",
    },
    stamp: "DOES LIGHT APPRECIATE A CLEAR EXPLANATION?",
  },
  {
    targets: [
      t("starOcean", "Fill the first little ocean", "fill", 270, 275, 170, 70),
      t(
        "horseOcean",
        "Aim into the narrow seahorse ocean",
        "fill",
        495,
        355,
        90,
        65,
      ),
      t(
        "whaleOcean",
        "Fill the whale's optimistic ocean",
        "fill",
        650,
        435,
        145,
        75,
      ),
    ],
    props: [
      p("oceanstar", 355, 335, "starOcean", { scale: 1 }),
      p("oceanhorse", 540, 415, "horseOcean", { scale: 1 }),
      p("tinyocean", 722.5, 495, "whaleOcean", { scale: 1 }),
      p("oceanstar", 355, 335, "starOcean", {
        scale: 1,
        foreground: true,
        revealOnly: true,
      }),
      p("oceanhorse", 540, 415, "horseOcean", {
        scale: 1,
        foreground: true,
        revealOnly: true,
      }),
      p("tinyocean", 722.5, 495, "whaleOcean", {
        scale: 1,
        foreground: true,
        revealOnly: true,
      }),
    ],
    stamp: "THREE OCEANS. ONE EXTREMELY POLITE FOUNTAIN.",
    extra: { start: [355, 215], temp: 20, par: 150 },
  },
  {
    targets: [
      t(
        "cradle",
        "Build the borrowed moon's display cradle",
        "freeze",
        350,
        435,
        210,
        55,
      ),
      t("case", "Open the moon's travel case", "melt", 390, 190, 180, 190, {
        requires: ["cradle"],
      }),
      t(
        "polisher",
        "Polish the independently turning moon stand",
        "spin",
        665,
        355,
        110,
        95,
      ),
    ],
    props: [
      p("moonmarble", 480, 322, undefined, {
        scale: 0.65,
        reveal: { x: 455, y: 390, scale: 0.85 },
      }),
    ],
    stamp: "LOAN DUE: WHEN EVERYONE HAS HAD A LOOK.",
    extra: { start: [455, 375], temp: -20, par: 190 },
  },
  {
    targets: [
      t(
        "waterBay",
        "Fill one visitor's exhibit bay",
        "fill",
        275,
        235,
        140,
        65,
      ),
      t(
        "coldBay",
        "Build a separate cold display frame",
        "freeze",
        700,
        350,
        90,
        115,
      ),
      t(
        "labelBay",
        "Restore the explanatory label bay",
        "melt",
        450,
        185,
        120,
        80,
      ),
      warm(
        "questions",
        "Welcome the visitors' questions",
        445,
        425,
        [30, 45],
        [15, 35],
        ["waterBay", "coldBay", "labelBay"],
        { w: 130, h: 65 },
      ),
    ],
    props: [
      p("visitorquestions", 510, 400, "questions", {
        scale: 1.05,
        reveal: { x: 510, y: 455, scale: 1.05 },
      }),
    ],
    stamp: "FIRST CURATORIAL QUESTION: ROOM TO THINK?",
    extra: { start: [345, 175], temp: 20, par: 195 },
  },
  {
    targets: [
      t(
        "tank",
        "Fill the floating footnote's fixed tank",
        "fill",
        350,
        325,
        280,
        160,
      ),
    ],
    props: [
      p("footnoteexplanation", 760, 315, undefined, {
        scale: 1,
        revealOnly: true,
      }),
    ],
    cast: [
      p("drprobably", 135, 330, undefined, { scale: 0.7 }),
      p("marginassistant", 835, 200, undefined, { scale: 0.6 }),
      p("zeroexhibit", 835, 465, undefined, { scale: 0.65 }),
    ],
    stamp: "IMPORTANT ENOUGH TO COME UP HERE. NO SMALL PRINT REQUIRED.",
    extra: {
      start: [590, 273],
      temp: 20,
      pressure: 85,
      par: 130,
      buoyancy: {
        id: "footnote:afloat",
        prebuilt: true,
        fillTarget: "tank",
        basin: { x: 350, y: 325, w: 280, h: 160 },
        pontoon: { x: 410, w: 150, h: 45, depth: 0.15 },
        pixelsPerMeter: 500,
        loadMass: 0.15,
        dockY: 322.9316666667,
        dockTolerance: 8,
      },
      needsSignals: ["footnote:afloat"],
      completionHint:
        "Let the floating footnote settle in its generous height band.",
    },
  },
  {
    targets: [
      t(
        "leftCase",
        "Build the What We Know case edge",
        "freeze",
        310,
        330,
        70,
        165,
      ),
      t("leftLabel", "Thaw What We Know", "melt", 300, 235, 160, 75, {
        requires: ["leftCase"],
      }),
      t(
        "rightCase",
        "Build the What We Wonder case edge",
        "freeze",
        600,
        330,
        70,
        165,
      ),
      t("rightLabel", "Thaw What We Wonder", "melt", 520, 235, 160, 75, {
        requires: ["rightCase"],
      }),
      warm(
        "hospitality",
        "Keep uncertainty comfortably welcome",
        440,
        440,
        [25, 40],
        [10, 30],
        ["leftLabel", "rightLabel"],
        { w: 110, h: 65 },
      ),
    ],
    props: [p("uncertaincase", 490, 360, "hospitality", { scale: 0.8 })],
    cast: [
      p("drprobably", 135, 330, undefined, { scale: 0.7 }),
      p("marginassistant", 835, 275, undefined, { scale: 0.75 }),
      p("zeroexhibit", 490, 345, undefined, { scale: 0.75 }),
    ],
    stamp: "WHAT WE KNOW. WHAT WE WONDER. PLENTY OF ROOM BETWEEN.",
    extra: { start: [345, 270], temp: -20, par: 220 },
  },
  {
    targets: [
      t(
        "banner",
        "Thaw the whole grand-opening banner",
        "melt",
        210,
        200,
        540,
        80,
      ),
      t(
        "refreshments",
        "Fill the very welcoming refreshments",
        "fill",
        270,
        445,
        140,
        65,
      ),
      t(
        "podium",
        "Build the modest opening podium",
        "freeze",
        620,
        445,
        120,
        60,
      ),
      warm(
        "welcome",
        "Welcome the museum's first visitors",
        440,
        425,
        [30, 45],
        [15, 35],
        ["banner", "refreshments", "podium"],
        { w: 120, h: 65 },
      ),
      t(
        "curtain",
        "Open the Almost Possible museum",
        "spin",
        755,
        325,
        110,
        90,
        { requires: ["welcome"] },
      ),
    ],
    props: [p("institutepanorama", 480, 397, undefined, { scale: 0.85 })],
    cast: [],
    stamp: "ALMOST POSSIBLE. DEFINITELY WORTH ASKING. ADMISSION: ONE QUESTION.",
    extra: { start: [480, 148], temp: 40, par: 240 },
  },
];

const dispatches = [
  "Dr. Probably has written a welcome. The ice would like a second opinion.",
  "Meet Zero: a black hole with excellent manners. Please give nothing a proper frame.",
  "The kettle has a question. Margin suspects the answer may be a biscuit.",
  "This diagram has another side. Dr. Probably is willing to turn the argument around.",
  "One specimen enjoys a mild afternoon. The other is a sun. Similar frames prove very little.",
  "A tiny museum is waiting behind glass. Make a real little doorway for the drops, too.",
  "The furniture is upside down. The water has declined to participate.",
  "Zero would like room for the next idea. A blank page counts as careful preparation.",
  "Breakfast has applied to become geometry. The butter dish is reviewing all three proposals.",
  "We found a fossil of next Tuesday. Please support it before asking what happens on Wednesday.",
  "This question plant needs water and something to lean on. An answer can wait.",
  "Two queues, two little welcomes. Zero has enough room to think about everybody.",
  "Margin has a correction. Dr. Probably has saved a bigger space for Margin's name.",
  "Two frosty explanations stand between the lamp and its question. Give the real beam a clear route.",
  "Three oceans, no connecting plumbing. The whale promises to keep its fountain indoors.",
  "The moon is on loan until everybody has had a look. The polisher accepts either order.",
  "Prepare three empty exhibits. Today the visitors get to write the questions.",
  "This footnote would like to come up in the world. Fill its tank; the floating plinth does the lifting.",
  "What we know goes on one side. What we wonder goes on the other. Zero likes the space between.",
  "The museum is almost possible and nearly open. Dr. Probably and Margin are sharing the step stool.",
];

const source = designs.packs.find((pack) => pack.id === "15")!;
export const instituteLevels: Level[] = source.scenes.map((card, index) => {
  const recipe = recipes[index];
  return {
    id: card.id,
    pack: "15",
    name: card.title,
    chapter: source.title,
    theme: "institute",
    pitch: dispatches[index],
    hint: card.puzzle,
    ending: card.payoff,
    start: [475, 145],
    temp: 40,
    pressure: 40,
    par: 60 + recipe.targets.length * 25,
    targets: recipe.targets,
    props: [...recipe.props, ...(recipe.cast ?? cast(index >= 1))],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
