import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/12-16.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 110, 60, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.75, ...extra });
const cast = (): Prop[] => [
  p("misocook", 135, 330, undefined, { scale: 0.75 }),
  p("mallowhost", 835, 275, undefined, { scale: 0.85 }),
  p("ziphauler", 835, 465, undefined, { scale: 0.7 }),
];
const mug = (id: string, x: number, y: number, scale = 1): Prop[] => [
  p("dinermug", x, y, id, { scale }),
];
const recipes: {
  targets: Target[];
  props: Prop[];
  cast?: Prop[];
  stamp: string;
  extra?: Partial<Level>;
}[] = [
  {
    targets: [
      t(
        "openSign",
        "Thaw the whole eventually-open sign",
        "melt",
        325,
        215,
        310,
        120,
      ),
    ],
    props: [
      p("dineropen", 480, 315, "openSign", { scale: 1 }),
      p("comettruck", 560, 445, undefined, { scale: 0.75 }),
      p("dinermug", 290, 440, undefined, { scale: 0.55 }),
    ],
    stamp: "OPEN. UNDER NEW TEMPERATURE.",
    extra: { start: [480, 155], temp: 20, par: 105 },
  },
  {
    targets: [
      t("mug", "Fill the mug's one liquid job", "fill", 270, 390, 140, 70),
      warm(
        "coaster",
        "Give the separate coaster a warm welcome",
        600,
        400,
        [35, 50],
        [15, 35],
        ["mug"],
        { w: 130, h: 70 },
      ),
    ],
    props: [
      ...mug("mug", 340, 442.5),
      p("mugservice", 340, 400, undefined, { scale: 0.8 }),
    ],
    cast: [p("mallowhost", 835, 275, undefined, { scale: 0.85 })],
    stamp: "ONE BUTTER-PAT SALUTE. BREAKFAST HOST APPOINTED.",
    extra: { start: [340, 330], temp: 20, par: 140 },
  },
  {
    targets: [
      t(
        "zipSeat",
        "Build a stool for the long journey",
        "freeze",
        330,
        445,
        160,
        60,
      ),
      t(
        "mallowSeat",
        "Build a properly tiny break stool",
        "freeze",
        530,
        465,
        85,
        60,
      ),
      t(
        "scarf",
        "Unpack the scarf after both seats are ready",
        "melt",
        430,
        195,
        180,
        100,
        { requires: ["zipSeat", "mallowSeat"] },
      ),
    ],
    props: [
      p("scarf", 520, 275, "scarf", {
        scale: 0.65,
        reveal: { x: 465, y: 420, scale: 0.4 },
      }),
      p("restingtravelers", 500, 410, undefined, { scale: 1 }),
    ],
    cast: [p("misocook", 135, 330, undefined, { scale: 0.75 })],
    stamp: "TAKE THE TIME YOU NEED. SAME PRICE.",
    extra: { start: [410, 385], temp: -20, par: 175 },
  },
  {
    targets: [
      t(
        "jukeboxCover",
        "Thaw the extremely serious record sleeve",
        "melt",
        280,
        175,
        260,
        215,
      ),
      t(
        "jukeboxWheel",
        "Give the tiny triangle a large entrance",
        "spin",
        650,
        390,
        120,
        95,
        { requires: ["jukeboxCover"] },
      ),
    ],
    props: [p("dinerjukebox", 410, 365, "jukeboxWheel", { scale: 1 })],
    cast: [
      p("misocook", 135, 330, undefined, { scale: 0.75 }),
      p("mallowtriangle", 835, 275, undefined, { scale: 0.85 }),
      p("ziphauler", 835, 465, undefined, { scale: 0.7 }),
    ],
    stamp: "ONE PERFECTLY ADEQUATE BUTTER TRIANGLE.",
    extra: { start: [410, 123], par: 160 },
  },
  {
    targets: [
      warm(
        "explorer",
        "Serve the polar explorer's usual",
        275,
        430,
        [15, 30],
        [10, 25],
        [],
        { w: 140 },
      ),
      warm(
        "courier",
        "Serve the sun courier's different usual",
        610,
        430,
        [65, 85],
        [30, 50],
        [],
        { w: 140 },
      ),
    ],
    props: [p("travelerbreakfasts", 500, 355, undefined, { scale: 0.95 })],
    stamp: "POSTCARDS EXCHANGED. BREAKFAST OPINIONS RESPECTED.",
    extra: { start: [345, 370], temp: 20, pressure: 20, par: 150 },
  },
  {
    targets: [
      t(
        "leftMenu",
        "Clear the menu above its own basin",
        "melt",
        285,
        195,
        160,
        100,
      ),
      t(
        "leftCondiment",
        "Fill through the clear left window",
        "fill",
        320,
        420,
        90,
        65,
        { requires: ["leftMenu"] },
      ),
      t(
        "rightMenu",
        "Clear the offset breakfast window",
        "melt",
        540,
        240,
        160,
        100,
      ),
      t(
        "rightCondiment",
        "Reach the right basin from its open side",
        "fill",
        665,
        420,
        90,
        65,
        { requires: ["rightMenu"] },
      ),
    ],
    props: [
      p("breakfastchart", 365, 277, "leftCondiment", {
        scale: 0.5,
        reveal: { x: 365, y: 305, scale: 0.85 },
      }),
      p("breakfastchart", 620, 322, "rightCondiment", {
        scale: 0.5,
        reveal: { x: 620, y: 350, scale: 0.85 },
      }),
    ],
    stamp: "PANCAKE MOON SPOTTED. CELESTIAL POSTURE PRACTICED.",
    extra: { start: [365, 143], par: 185 },
  },
  {
    targets: [
      t("wash", "Fill the wide dishwashing basin", "fill", 300, 215, 260, 80),
      t(
        "dryer",
        "Aim separately at the drying turbine",
        "spin",
        620,
        425,
        120,
        80,
        { requires: ["wash"] },
      ),
    ],
    props: [p("dishpat", 455, 430, undefined, { scale: 1 })],
    cast: [p("ziphauler", 835, 465, undefined, { scale: 0.7 })],
    stamp: "THREE CLEAN PLATES. ONE BUTTER HAT BACK IN ORBIT.",
    extra: { start: [430, 155], temp: 20, par: 145 },
  },
  {
    targets: [
      t(
        "display",
        "Build the moon pie's cold display",
        "freeze",
        250,
        430,
        180,
        65,
      ),
      t("saucer", "Fill the separate little saucer", "fill", 640, 405, 120, 60),
      warm(
        "hospitality",
        "Welcome a moon of a sensible size",
        470,
        400,
        [25, 40],
        [10, 30],
        ["display", "saucer"],
        { w: 120, h: 70 },
      ),
    ],
    props: [
      p("scarfmoonpie", 340, 335, undefined, {
        scale: 0.8,
        reveal: { x: 340, y: 410, scale: 0.8 },
      }),
    ],
    stamp: "MOON-SIZED HOSPITALITY. PIE-SIZED MOON.",
    extra: { start: [340, 370], temp: -20, par: 175 },
  },
  {
    targets: [
      t("tallCase", "Open the tall cave parcel", "melt", 280, 185, 100, 180),
      t("wideCase", "Sweep the wide spoon parcel", "melt", 440, 240, 215, 100),
      t(
        "smallCase",
        "Unpack the carefully wrapped little thanks",
        "melt",
        700,
        300,
        80,
        75,
      ),
      t(
        "receiving",
        "Fill the receiving basin after all three parcels",
        "fill",
        405,
        435,
        150,
        60,
        { requires: ["tallCase", "wideCase", "smallCase"] },
      ),
    ],
    props: [
      p("cavesalt", 330, 345, "tallCase", { scale: 0.65 }),
      p("cavespoons", 550, 336, "wideCase", { scale: 1 }),
      p("thankyoupebble", 740, 358, undefined, {
        scale: 0.6,
        reveal: { x: 645, y: 410, scale: 0.8 },
      }),
    ],
    stamp: "THE THANK-YOU PEBBLE GETS THE BEST SEAT.",
    extra: { start: [330, 133], par: 210 },
  },
  {
    targets: [
      t(
        "leftHerbs",
        "Water the left hopeful garnish pot",
        "fill",
        285,
        415,
        110,
        65,
      ),
      t(
        "rightHerbs",
        "Water the right windowsill pot",
        "fill",
        625,
        405,
        110,
        65,
      ),
      t(
        "trellis",
        "Build the watered vine's little trellis",
        "freeze",
        455,
        285,
        90,
        180,
        { requires: ["leftHerbs", "rightHerbs"] },
      ),
    ],
    props: [
      p("herbawning", 500, 405, undefined, { scale: 1.15 }),
      p("herbawning", 500, 405, undefined, {
        scale: 1.15,
        foreground: true,
        revealOnly: true,
      }),
    ],
    stamp: "ONE GREEN AWNING. ONE LEAF SHAPED LIKE HOME.",
    extra: { start: [340, 355], temp: 20, par: 180 },
  },
  {
    targets: [
      t(
        "longExtension",
        "Build the longer table extension",
        "freeze",
        270,
        435,
        160,
        60,
      ),
      t(
        "shortExtension",
        "Build the other perfectly useful extension",
        "freeze",
        590,
        445,
        110,
        50,
      ),
      t(
        "reservation",
        "Thaw the reservation after both extensions",
        "melt",
        310,
        250,
        340,
        60,
        { requires: ["longExtension", "shortExtension"] },
      ),
      warm(
        "leftWelcome",
        "Welcome the left-hand regulars",
        285,
        330,
        [25, 40],
        [10, 30],
        ["reservation"],
        { w: 120, h: 65 },
      ),
      warm(
        "rightWelcome",
        "Welcome the right-hand regulars",
        610,
        330,
        [25, 40],
        [10, 30],
        ["reservation"],
        { w: 120, h: 65 },
      ),
    ],
    props: [p("regularstable", 480, 410, undefined, { scale: 0.9 })],
    stamp: "RESERVED FOR ANYONE WHO CALLS THIS THEIR USUAL.",
    extra: { start: [350, 375], temp: -20, par: 220 },
  },
  {
    targets: [
      t(
        "hatch",
        "Thaw the parked truck's service hatch",
        "melt",
        375,
        260,
        120,
        70,
      ),
      t(
        "coolant",
        "Fill the unlocked coolant basin",
        "fill",
        300,
        435,
        140,
        65,
        { requires: ["hatch"] },
      ),
      t(
        "diagnostic",
        "Run the stationary truck's diagnostic",
        "spin",
        660,
        370,
        120,
        100,
        { requires: ["coolant"] },
      ),
    ],
    props: [p("truckdiagnostic", 490, 340, "diagnostic", { scale: 1 })],
    stamp: "READY, WHENEVER YOU ARE. BREAKFAST FIRST.",
    extra: { start: [435, 208], par: 185 },
  },
  {
    targets: [
      t(
        "firstMug",
        "Fill the first unhurried little mug",
        "fill",
        211,
        345,
        98,
        49,
      ),
      t("secondMug", "Reach the lower second mug", "fill", 331, 410, 98, 49),
      t("thirdMug", "Visit the high middle mug", "fill", 451, 330, 98, 49),
      t("fourthMug", "Reach the other low mug", "fill", 571, 405, 98, 49),
      t(
        "fifthMug",
        "Fill the last cup of the conversation",
        "fill",
        691,
        345,
        98,
        49,
      ),
    ],
    props: [
      p("counterconversation", 500, 305, undefined, { scale: 1 }),
      ...mug("firstMug", 260, 381.75, 0.7),
      ...mug("secondMug", 380, 446.75, 0.7),
      ...mug("thirdMug", 500, 366.75, 0.7),
      ...mug("fourthMug", 620, 441.75, 0.7),
      ...mug("fifthMug", 740, 381.75, 0.7),
    ],
    stamp: "FIVE REFILLS. ONE SPRAWLING NEBULA CONVERSATION.",
    extra: { start: [260, 285], temp: 20, par: 200 },
  },
  {
    targets: [
      t(
        "upperOutlet",
        "Open the first pancake's outlet",
        "melt",
        495,
        285,
        70,
        50,
      ),
      t(
        "lowerOutlet",
        "Open the second pancake's outlet",
        "melt",
        410,
        380,
        70,
        50,
      ),
      t(
        "reservoir",
        "Fill the scenic syrup reservoir",
        "fill",
        480,
        155,
        120,
        65,
        { requires: ["upperOutlet", "lowerOutlet"], fillColor: "#d5a469cc" },
      ),
      t(
        "pancake1",
        "Route the first pancake's helping",
        "fill",
        270,
        260,
        140,
        60,
        { flowOnly: true, requires: ["reservoir"], fillColor: "#d5a469cc" },
      ),
      t(
        "pancake2",
        "Overflow into the second pancake",
        "fill",
        600,
        345,
        140,
        60,
        { flowOnly: true, requires: ["pancake1"], fillColor: "#d5a469cc" },
      ),
      t(
        "pancake3",
        "Follow the entire journey to breakfast",
        "fill",
        320,
        440,
        140,
        60,
        { flowOnly: true, requires: ["pancake2"], fillColor: "#d5a469cc" },
      ),
    ],
    props: [
      p("pancakeroute", 340, 305, "pancake1", { scale: 1 }),
      p("pancakeroute", 670, 390, "pancake2", { scale: 1 }),
      p("pancakeroute", 390, 485, "pancake3", { scale: 1 }),
    ],
    stamp: "BREAKFAST WITH A PARTICULARLY INTERESTING JOURNEY.",
    extra: {
      start: [530, 233],
      temp: 40,
      par: 265,
      channels: {
        inlet: { x: 520, y: 170, w: 40, h: 30 },
        junction: [540, 240],
        branches: [
          { target: "pancake1", overflowFrom: "reservoir", via: [[340, 240]] },
          {
            target: "pancake2",
            gate: "upperOutlet",
            overflowFrom: "pancake1",
            via: [
              [340, 240],
              [340, 290],
              [435, 290],
              [530, 310],
              [670, 310],
            ],
          },
          {
            target: "pancake3",
            gate: "lowerOutlet",
            overflowFrom: "pancake2",
            via: [
              [340, 240],
              [340, 290],
              [435, 290],
              [530, 310],
              [670, 310],
              [670, 375],
              [670, 405],
              [445, 405],
              [390, 405],
            ],
          },
        ],
      },
    },
  },
  {
    targets: [
      warm(
        "coolDessert",
        "Offer the cool dessert its usual climate",
        275,
        435,
        [15, 30],
        [20, 35],
        [],
        { w: 140, h: 65 },
      ),
      warm(
        "noodles",
        "Keep the noodles pleasantly warm",
        615,
        435,
        [40, 55],
        [20, 35],
        [],
        { w: 140, h: 65 },
      ),
      warm(
        "sunPlate",
        "Prepare the sun courier's bright plate",
        445,
        225,
        [65, 80],
        [20, 35],
        [],
        { w: 140, h: 75 },
      ),
    ],
    props: [p("tastingtray", 515, 410, undefined, { scale: 1 })],
    stamp: "STORIES SWAPPED. HOME CLIMATES LEFT ON THEIR OWN PLATES.",
    extra: { start: [345, 375], temp: 20, pressure: 27, par: 175 },
  },
  {
    targets: [
      t(
        "order",
        "Thaw the enormous little request",
        "melt",
        290,
        185,
        380,
        120,
      ),
      t(
        "place",
        "Build one unhurried place to sit",
        "freeze",
        350,
        420,
        140,
        80,
        { requires: ["order"] },
      ),
      warm(
        "company",
        "Offer gentle company, not another special",
        615,
        435,
        [25, 40],
        [10, 25],
        ["place"],
        { w: 105 },
      ),
    ],
    props: [
      p("smallestorder", 480, 290, "order", { scale: 1 }),
      p("sittingtogether", 480, 390, undefined, {
        scale: 0.7,
        revealOnly: true,
      }),
    ],
    cast: [
      p("misocook", 135, 330, undefined, { scale: 0.75 }),
      p("ziphauler", 835, 465, undefined, { scale: 0.7 }),
    ],
    stamp: "TODAY'S SPECIAL: SOMEWHERE TO SIT. COMPANY INCLUDED.",
    extra: { start: [480, 133], par: 190 },
  },
  {
    targets: [
      t(
        "leftStrip",
        "Thaw the narrow left serving-window strip",
        "melt",
        300,
        200,
        65,
        130,
      ),
      t(
        "leftCollection",
        "Fill the left collection basin",
        "fill",
        285,
        420,
        120,
        60,
        { requires: ["leftStrip"] },
      ),
      t(
        "rightStrip",
        "Thaw the narrow right serving-window strip",
        "melt",
        600,
        230,
        65,
        130,
      ),
      t(
        "rightCollection",
        "Reach the right collection basin",
        "fill",
        630,
        425,
        110,
        55,
        { requires: ["rightStrip"] },
      ),
      t(
        "serviceSign",
        "Turn the sign after both branches are served",
        "spin",
        455,
        405,
        120,
        95,
        { requires: ["leftCollection", "rightCollection"] },
      ),
    ],
    props: [p("windowqueue", 500, 365, undefined, { scale: 1.1 })],
    cast: [
      p("misocook", 135, 330, undefined, { scale: 0.75 }),
      p("mallowhost", 835, 275, undefined, { scale: 0.85 }),
    ],
    stamp: "WALK-INS WELCOME TOO. FIRST WAVE GOES TO THE WALK-IN.",
    extra: { start: [332, 148], par: 225 },
  },
  {
    targets: [
      t("toastBeat", "Play the patient toast beat", "spin", 300, 430, 110, 80, {
        pulse: { period: 9, open: 3, phase: 0, untimedOrder: 1 },
      }),
      t(
        "mugBeat",
        "Play the mug's comfortable middle beat",
        "spin",
        475,
        430,
        110,
        80,
        { pulse: { period: 9, open: 3, phase: 6, untimedOrder: 2 } },
      ),
      t(
        "pancakeBeat",
        "Leave space for the pancake's beat",
        "spin",
        650,
        430,
        110,
        80,
        { pulse: { period: 9, open: 3, phase: 3, untimedOrder: 3 } },
      ),
    ],
    props: [p("breakfastbeat", 480, 280, undefined, { scale: 0.75 })],
    cast: [],
    stamp: "THREE BREAKFAST BEATS. PLENTY OF ROOM BETWEEN NOTES.",
    extra: { start: [355, 378], temp: 20, pressure: 80, par: 190 },
  },
  {
    targets: [
      t(
        "stand",
        "Build Mallow's fixed welcome-light stand",
        "freeze",
        350,
        430,
        170,
        60,
      ),
      t(
        "moonPicture",
        "Thaw the moon picture's rectangular case",
        "melt",
        450,
        215,
        100,
        70,
        { requires: ["stand"] },
      ),
      warm(
        "light",
        "Help a modest light feel at home",
        650,
        430,
        [25, 40],
        [10, 30],
        ["moonPicture"],
      ),
    ],
    props: [
      p("mallowlamp", 490, 355, "light", {
        scale: 1,
        reveal: { x: 410, y: 402, scale: 1 },
      }),
    ],
    cast: [
      p("misocook", 135, 330, undefined, { scale: 0.75 }),
      p("ziphauler", 835, 465, undefined, { scale: 0.7 }),
    ],
    stamp: "NOT AN ENORMOUS MOON. A VERY USEFUL LIGHT.",
    extra: { start: [435, 370], temp: -20, par: 195 },
  },
  {
    targets: [
      t(
        "leftBreakfast",
        "Fill the first shared breakfast basin",
        "fill",
        260,
        445,
        110,
        55,
      ),
      t(
        "middleBreakfast",
        "Fill the middle place at breakfast",
        "fill",
        435,
        455,
        110,
        55,
      ),
      t(
        "rightBreakfast",
        "Fill the last shared breakfast basin",
        "fill",
        620,
        445,
        110,
        55,
      ),
      t(
        "guestbook",
        "Thaw the routes that lead back here",
        "melt",
        90,
        190,
        200,
        120,
      ),
      warm(
        "misoPlace",
        "Give Miso a gentle place at the table",
        760,
        355,
        [30, 45],
        [15, 35],
        ["leftBreakfast", "middleBreakfast", "rightBreakfast", "guestbook"],
        { w: 110, h: 70 },
      ),
    ],
    props: [
      p("dinerguestbook", 168, 285, undefined, { scale: 0.65 }),
      p("dinerpanorama", 480, 410, undefined, { scale: 0.9 }),
    ],
    cast: [],
    stamp: "SEE YOU NEXT BREAKFAST. THERE IS A PLACE FOR THE COOK.",
    extra: { start: [315, 385], temp: 20, par: 235 },
  },
];

const dispatches = [
  "The sign says OPEN. The ice is considering an amendment. Zip has already brought a mug.",
  "The mug needs filling; the coaster needs warming. Mallow is in charge of dignified butter salutes.",
  "A long journey deserves a proper seat. Mallow's official break deserves a much smaller one.",
  "An asteroid has recorded a triangle solo. Please give its extremely small instrument a chance.",
  "One usual is pleasantly mild. The other belongs to a sun courier. Both customers are correct.",
  "Breakfast has constellations now. Clear each menu and mind the second basin's sideways address.",
  "Eight tentacles, three dirty plates, one ambitious butter hat. Miso would appreciate a free hand.",
  "Today's moon pie wears a scarf. Make it a cold display and a separate warm welcome.",
  "Three parcels from the cave: tall, wide, and very carefully thankful. Unpack before receiving.",
  "The garnish vine wants a window seat. Water both pots, then give its ambition a small trellis.",
  "The regulars need two table extensions. Their reservation is reassuringly unspecific.",
  "Zip's truck needs a checkup, not a countdown. Breakfast will still be here when it is ready.",
  "Five mugs, five unhurried travelers. No one has put a deadline on discussing a nice nebula.",
  "Open both outlets, then feed the reservoir. These pancakes have chosen the scenic syrup route.",
  "Three home climates, three plates. Miso recommends swapping stories rather than lunches.",
  "The order slip is enormous. The actual request becomes smaller, softer, and much easier to share.",
  "Two serving windows, one patient queue. The pedestrian would also enjoy being a customer.",
  "Toast, mug, pancake: three patient beats. The open light waits its turn in untimed mode.",
  "Mallow still likes moons. A little light over the welcome stool might be just the right size.",
  "One last gentle welcome: Miso's own place at the table. Nobody is leaving on a turbine tonight.",
];

const source = designs.packs.find((pack) => pack.id === "16")!;
export const dinerLevels: Level[] = source.scenes.map((card, index) => {
  const recipe = recipes[index];
  return {
    id: card.id,
    pack: "16",
    name: card.title,
    chapter: source.title,
    theme: "diner",
    pitch: dispatches[index],
    hint: card.puzzle,
    ending: card.payoff,
    start: [475, 145],
    temp: 40,
    pressure: 40,
    par: 65 + recipe.targets.length * 25,
    targets: recipe.targets,
    props: [...recipe.props, ...(recipe.cast ?? cast())],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
