import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/17.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 110, 60, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.75, ...extra });
const cast = (): Prop[] => [
  p("captainbutton", 135, 335, undefined, { scale: 0.75 }),
  p("glimstar", 835, 275, undefined, { scale: 0.75 }),
  p("junduck", 835, 465, undefined, { scale: 0.75 }),
];
const recipes: {
  targets: Target[];
  props: Prop[];
  cast?: Prop[];
  stamp: string;
  extra?: Partial<Level>;
}[] = [
  {
    targets: [
      t(
        "wheelCap",
        "Thaw the broad cap on one brave wheel",
        "melt",
        305,
        295,
        150,
        95,
      ),
      t(
        "axle",
        "Spin the separately exposed rescue axle",
        "spin",
        655,
        400,
        115,
        95,
        { requires: ["wheelCap"] },
      ),
    ],
    props: [
      p("toyfireengine", 440, 365, undefined, { scale: 1 }),
      p("cardboardbadge", 630, 260, "axle", { scale: 0.8 }),
    ],
    cast: [
      p("captainbutton", 135, 335, undefined, { scale: 0.75 }),
      p("glimstar", 835, 275, undefined, { scale: 0.75 }),
    ],
    stamp: "ONE WOODEN BLOCK. STATION OPERATIONAL.",
    extra: { start: [380, 243], par: 145 },
  },
  {
    targets: [
      t(
        "sleeve",
        "Thaw the captain's patched sleeve",
        "melt",
        340,
        335,
        60,
        50,
      ),
      warm(
        "badge",
        "Warm the detachable badge gently",
        555,
        425,
        [25, 45],
        [10, 35],
        ["sleeve"],
        { w: 140, h: 65 },
      ),
    ],
    props: [
      p("buttonwelcome", 480, 385, undefined, { scale: 1 }),
      p("cardboardbadge", 625, 405, "badge", { scale: 0.65 }),
    ],
    cast: [p("junduck", 835, 465, undefined, { scale: 0.75 })],
    stamp: "A PLACE ON THE CREW. NO INSPECTION REQUIRED.",
    extra: { start: [370, 283], par: 145 },
  },
  {
    targets: [
      t(
        "leftTea",
        "Fill one extremely diplomatic teacup",
        "fill",
        275,
        410,
        120,
        60,
      ),
      t(
        "rightTea",
        "Fill the equally diplomatic other cup",
        "fill",
        595,
        410,
        120,
        60,
      ),
      warm(
        "teapot",
        "Warm the shared treaty teapot",
        445,
        425,
        [30, 50],
        [10, 45],
        ["leftTea", "rightTea"],
        { w: 110, h: 65 },
      ),
    ],
    props: [
      p("toyteacup", 335, 455, "leftTea", { scale: 6 / 7 }),
      p("toyteacup", 655, 455, "rightTea", { scale: 6 / 7 }),
      p("dollteasummit", 495, 370, undefined, { scale: 0.95 }),
    ],
    cast: [
      p("captainbutton", 135, 335, undefined, { scale: 0.75 }),
      p("glimstar", 835, 275, undefined, { scale: 0.75 }),
    ],
    stamp: "BISCUIT-SHARING AGREEMENT. CARDBOARD EXEMPTION REQUESTED.",
    extra: { start: [335, 350], temp: 20, par: 180 },
  },
  {
    targets: [
      t(
        "leftLanding",
        "Build the left low landing section",
        "freeze",
        330,
        435,
        100,
        50,
      ),
      t(
        "middleLanding",
        "Build the little star's central perch",
        "freeze",
        445,
        420,
        90,
        50,
      ),
      t(
        "rightLanding",
        "Build the right low landing section",
        "freeze",
        550,
        435,
        100,
        50,
      ),
      t(
        "boots",
        "Thaw Glim's boots after all three supports",
        "melt",
        445,
        230,
        90,
        50,
        { requires: ["leftLanding", "middleLanding", "rightLanding"] },
      ),
    ],
    props: [
      p("glimstar", 480, 250, "boots", {
        scale: 0.9,
        reveal: { kind: "glimperch", x: 490, y: 420, scale: 0.85 },
      }),
    ],
    cast: [
      p("captainbutton", 135, 335, undefined, { scale: 0.75 }),
      p("junduck", 835, 465, undefined, { scale: 0.75 }),
    ],
    stamp: "RESCUERS MAY ALSO BE RESCUED. THE PERCH FITS.",
    extra: { start: [380, 375], temp: -20, par: 195 },
  },
  {
    targets: [
      t(
        "wideCap",
        "Sweep the wide pretend-soup cap",
        "melt",
        265,
        190,
        200,
        90,
      ),
      t("smallCap", "Clear the smaller serving cap", "melt", 605, 235, 100, 90),
      t(
        "leftBowl",
        "Fill one bowl after both caps are clear",
        "fill",
        295,
        415,
        130,
        65,
        { requires: ["wideCap", "smallCap"] },
      ),
      t(
        "rightBowl",
        "Fill the other bowl for the marble guests",
        "fill",
        610,
        420,
        130,
        65,
        { requires: ["wideCap", "smallCap"] },
      ),
      warm(
        "spoon",
        "Warm the chef's reassuring tasting spoon",
        455,
        420,
        [25, 40],
        [10, 35],
        ["leftBowl", "rightBowl"],
        { w: 115, h: 65 },
      ),
    ],
    props: [p("marblesoup", 500, 365, undefined, { scale: 1 })],
    stamp: "SOUP FOR MARBLES. PUNCTUATION NOW REASSURING.",
    extra: { start: [365, 138], par: 225 },
  },
  {
    targets: [
      t(
        "nearBridge",
        "Build the near bank's tail support",
        "freeze",
        265,
        435,
        115,
        55,
      ),
      t(
        "middleBridge",
        "Build the middle of the very long crossing",
        "freeze",
        430,
        455,
        120,
        45,
      ),
      t(
        "farBridge",
        "Build the far bank's final little bridge",
        "freeze",
        605,
        425,
        130,
        65,
      ),
      t(
        "departure",
        "Thaw the departure tag after every bridge",
        "melt",
        410,
        180,
        180,
        100,
        { requires: ["nearBridge", "middleBridge", "farBridge"] },
      ),
    ],
    props: [
      p("longdog", 480, 395, undefined, { scale: 0.9 }),
      p("departuretag", 500, 266, "departure", {
        scale: 0.7,
        reveal: { x: 355, y: 225, scale: 0.55 },
      }),
    ],
    cast: [
      p("captainbutton", 135, 335, undefined, { scale: 0.75 }),
      p("junduck", 835, 465, undefined, { scale: 0.75 }),
    ],
    stamp: "REAR-END NAVIGATION OFFICER. AN EXTREMELY LONG APPOINTMENT.",
    extra: { start: [322, 375], temp: -20, par: 205 },
  },
  {
    targets: [
      t(
        "firstKey",
        "Thaw the first bright lunch key",
        "melt",
        285,
        271,
        75,
        93,
      ),
      t(
        "secondKey",
        "Thaw the next fixed xylophone strip",
        "melt",
        385,
        278,
        75,
        86,
      ),
      t(
        "thirdKey",
        "Thaw the third lunch announcement",
        "melt",
        485,
        285,
        75,
        79,
      ),
      t(
        "fourthKey",
        "Thaw the final entirely untimed key",
        "melt",
        585,
        292,
        75,
        72,
      ),
      t(
        "music",
        "Spin the wordless lunch announcement",
        "spin",
        440,
        425,
        120,
        80,
        { requires: ["firstKey", "secondKey", "thirdKey", "fourthKey"] },
      ),
    ],
    props: [p("toyxylophone", 472.5, 370, "music", { scale: 1 })],
    stamp: "EVERYONE KNOWS THE WORDS. THERE ARE NO WORDS.",
    extra: { start: [322, 193], par: 220 },
  },
  {
    targets: [
      t(
        "entrance",
        "Thaw the glass-free globe's entrance",
        "melt",
        275,
        210,
        160,
        105,
      ),
      t("pond", "Fill the explorer's little pond", "fill", 620, 405, 140, 70, {
        requires: ["entrance"],
      }),
      t(
        "snowbank",
        "Build the separately unlocked snowbank",
        "freeze",
        300,
        435,
        135,
        60,
        { requires: ["entrance"] },
      ),
      warm(
        "welcome",
        "Welcome the explorer beyond the globe",
        455,
        435,
        [25, 45],
        [10, 35],
        ["pond", "snowbank"],
        { w: 125, h: 65 },
      ),
    ],
    props: [p("snowexplorer", 485, 370, undefined, { scale: 1 })],
    extra: { start: [355, 158], par: 195 },
    stamp: "NEXT EXPEDITION: FOOTBALL. NAPKIN MAP PROVIDED.",
  },
  {
    targets: [
      t(
        "leftBoot",
        "Thaw the wizard's borrowed left thruster",
        "melt",
        295,
        215,
        120,
        115,
      ),
      t(
        "rightBoot",
        "Thaw the other highly advanced boot",
        "melt",
        605,
        215,
        120,
        115,
      ),
      t(
        "leftExhaust",
        "Build the left pretend exhaust display",
        "freeze",
        320,
        435,
        110,
        55,
      ),
      t(
        "rightExhaust",
        "Build the right pretend exhaust display",
        "freeze",
        605,
        435,
        110,
        55,
      ),
      t(
        "starter",
        "Start the plainly string-powered launch",
        "spin",
        465,
        425,
        110,
        80,
        { requires: ["leftBoot", "rightBoot", "leftExhaust", "rightExhaust"] },
      ),
    ],
    props: [p("stringrocket", 510, 365, undefined, { scale: 1 })],
    stamp: "THE STRING IS A HIGHLY ADVANCED PROPULSION SPELL.",
    extra: { start: [355, 163], par: 225 },
  },
  {
    targets: [
      t(
        "blueFooting",
        "Build the blue sprout's cold pot footing",
        "freeze",
        285,
        430,
        110,
        65,
      ),
      warm(
        "yellowSprout",
        "Keep the yellow crayon garden mild",
        455,
        405,
        [25, 45],
        [10, 45],
        [],
        { w: 115, h: 65 },
      ),
      warm(
        "orangeSprout",
        "Warm the orange sprout's bright afternoon",
        640,
        325,
        [55, 75],
        [10, 45],
        [],
        { w: 120, h: 70 },
      ),
    ],
    props: [p("crayongarden", 500, 365, undefined, { scale: 1 })],
    stamp: "EVERY FLOWER IS CALLED BUTTON. BOTANY IS GOING WELL.",
    extra: { start: [340, 370], temp: -20, par: 180 },
  },
  {
    targets: [
      t(
        "overnightBag",
        "Unpack the sock guest's frozen overnight bag",
        "melt",
        290,
        205,
        200,
        125,
      ),
      t("bottle", "Fill the tiny hot-water bottle", "fill", 645, 355, 110, 70, {
        requires: ["overnightBag"],
      }),
      warm(
        "comfort",
        "Warm the separate sleepover comfort patch",
        355,
        430,
        [30, 45],
        [10, 35],
        ["bottle"],
        { w: 130, h: 65 },
      ),
    ],
    props: [
      p("toybag", 390, 315, "overnightBag", { scale: 0.8 }),
      p("mittenghost", 540, 395, undefined, { scale: 1 }),
    ],
    stamp: "SPARE MITTEN READY. YES, THE LIGHT CAN STAY ON.",
    extra: { start: [390, 153], par: 175 },
  },
  {
    targets: [
      t(
        "leftFoot",
        "Build the telescope's first stable foot",
        "freeze",
        295,
        435,
        130,
        60,
      ),
      t(
        "rightFoot",
        "Build the telescope's other little foot",
        "freeze",
        570,
        435,
        130,
        60,
      ),
      t(
        "moonShell",
        "Thaw the toy moon after both feet",
        "melt",
        500,
        205,
        90,
        90,
        { requires: ["leftFoot", "rightFoot"] },
      ),
      warm(
        "moonCenter",
        "Warm the exposed interdisciplinary moon",
        510,
        225,
        [35, 55],
        [10, 35],
        ["moonShell"],
        { w: 70, h: 60 },
      ),
    ],
    props: [p("mooncheese", 495, 405, undefined, { scale: 1 })],
    stamp: "TELESCOPE: MOON. MOUSE: CHEESE. RESEARCH: INTERDISCIPLINARY.",
    extra: { start: [360, 375], temp: -20, par: 205 },
  },
  {
    targets: [
      t(
        "helmet",
        "Thaw the first toy's little red helmet",
        "melt",
        275,
        185,
        110,
        100,
      ),
      t(
        "canteen",
        "Fill the next toy's canteen station",
        "fill",
        445,
        325,
        110,
        60,
      ),
      warm(
        "comfortPatch",
        "Warm the final toy's stiff comfort patch",
        655,
        410,
        [20, 40],
        [10, 30],
        [],
        { w: 120, h: 65 },
      ),
      t(
        "crewStamp",
        "Stamp the crew's completed repair line",
        "spin",
        270,
        415,
        120,
        85,
        { requires: ["helmet", "canteen", "comfortPatch"] },
      ),
    ],
    props: [p("repairqueue", 580, 300, undefined, { scale: 1 })],
    cast: [p("junduck", 835, 465, undefined, { scale: 0.75 })],
    stamp: "GLIM REMEMBERS EVERY NAME. THE CAPTAIN'S BADGE CAN WAIT.",
    extra: { start: [330, 133], par: 205 },
  },
  {
    targets: [
      t("leftIce", "Adjust Button's ice ballast", "freeze", 245, 380, 110, 75, {
        reversibleIce: true,
        effort: 4,
      }),
      t(
        "rightIce",
        "Adjust the feather admiral's ice ballast",
        "freeze",
        605,
        380,
        110,
        75,
        { reversibleIce: true, effort: 4 },
      ),
    ],
    props: [],
    cast: [
      p("glimstar", 835, 275, undefined, { scale: 0.75 }),
      p("junduck", 835, 465, undefined, { scale: 0.75 }),
    ],
    stamp: "BALANCE IS HARDER THAN BRAVERY. THE ADMIRAL CAN SEE.",
    extra: {
      start: [660, 328],
      temp: -20,
      pressure: 40,
      par: 260,
      balance: {
        id: "toybox:level",
        x: 480,
        y: 340,
        arm: 180,
        left: { target: "leftIce", mass: 1, fixedMass: 1 },
        right: { target: "rightIce", mass: 1, fixedMass: 0.25 },
      },
      needsSignals: ["toybox:level"],
      completionHint:
        "Cold grows ballast. Hot water trims it. Switch the spray off and let the real beam settle.",
    },
  },
  {
    targets: [
      t(
        "frostPanel",
        "Thaw the plush bus's frosty service panel",
        "melt",
        310,
        315,
        120,
        65,
      ),
      t(
        "coolingBlock",
        "Build the separately marked cooling block",
        "freeze",
        620,
        410,
        100,
        80,
        { requires: ["frostPanel"] },
      ),
      warm(
        "ticket",
        "Warm the helper's little ticket pad",
        445,
        420,
        [25, 45],
        [10, 35],
        ["coolingBlock"],
        { w: 120, h: 70 },
      ),
    ],
    props: [p("plushbus", 510, 355, undefined, { scale: 1 })],
    cast: [
      p("captainbutton", 135, 335, undefined, { scale: 0.75 }),
      p("junduck", 835, 465, undefined, { scale: 0.75 }),
    ],
    stamp: "DRIVER'S HELPER APPOINTED. GLIM GETS THE BELL.",
    extra: { start: [370, 263], par: 180 },
  },
  {
    targets: [
      t(
        "leftPlatform",
        "Build the single left rescue platform",
        "freeze",
        275,
        435,
        140,
        55,
      ),
      t(
        "leftTag",
        "Thaw the left branch's rescue tag",
        "melt",
        290,
        230,
        120,
        80,
        { requires: ["leftPlatform"] },
      ),
      t(
        "rightLower",
        "Build the first right-hand platform",
        "freeze",
        495,
        425,
        90,
        45,
      ),
      t(
        "rightUpper",
        "Build the other right-hand platform",
        "freeze",
        625,
        455,
        140,
        40,
      ),
      t(
        "rightTag",
        "Thaw the tag after both right platforms",
        "melt",
        605,
        230,
        130,
        80,
        { requires: ["rightLower", "rightUpper"] },
      ),
    ],
    props: [
      p("biscuitmountain", 450, 395, undefined, { scale: 0.85 }),
      p("departuretag", 350, 297, "leftTag", { scale: 0.5 }),
      p("departuretag", 670, 297, "rightTag", { scale: 0.5 }),
    ],
    cast: [
      p("captainbutton", 135, 335, undefined, { scale: 0.75 }),
      p("glimstar", 835, 275, undefined, { scale: 0.75 }),
    ],
    stamp: "THE BISCUIT IS ESSENTIAL EQUIPMENT. JUN HAS THE LABEL.",
    extra: { start: [345, 375], temp: -20, par: 230 },
  },
  {
    targets: [
      t(
        "leftCurtain",
        "Open the left practice curtain",
        "melt",
        270,
        190,
        130,
        150,
      ),
      t(
        "rightCurtain",
        "Open the right practice curtain",
        "melt",
        590,
        190,
        130,
        150,
      ),
      warm(
        "podium",
        "Give Glim's fixed little podium a warm glow",
        470,
        395,
        [30, 50],
        [10, 40],
        ["leftCurtain", "rightCurtain"],
        { w: 110, h: 65 },
      ),
      t(
        "applause",
        "Start the audience's hinged-hand applause",
        "spin",
        670,
        410,
        100,
        90,
        { requires: ["podium"] },
      ),
    ],
    props: [
      p("glimstage", 500, 375, "podium", { scale: 0.9 }),
      p("blockaudience", 465, 500, undefined, { scale: 0.7 }),
    ],
    cast: [
      p("captainbutton", 135, 335, undefined, { scale: 0.75 }),
      p("junduck", 835, 465, undefined, { scale: 0.75 }),
    ],
    stamp: "SEEN, NOT INSPECTED. THE BLOCKS UNDERSTAND.",
    extra: { start: [335, 138], par: 210 },
  },
  {
    targets: [
      t(
        "innerMoon",
        "Follow the inner biscuit moon",
        "melt",
        445,
        290,
        70,
        70,
        { motion: { rx: 100, ry: 65, period: 22, phase: 0 } },
      ),
      t(
        "middleMoon",
        "Follow the middle biscuit moon",
        "melt",
        445,
        290,
        70,
        70,
        { motion: { rx: 180, ry: 105, period: 22, phase: (2 * Math.PI) / 3 } },
      ),
      t(
        "outerMoon",
        "Follow the outer biscuit moon",
        "melt",
        445,
        290,
        70,
        70,
        { motion: { rx: 255, ry: 140, period: 22, phase: (4 * Math.PI) / 3 } },
      ),
    ],
    props: [
      p("biscuitmoon", 480, 342.5, "innerMoon", {
        scale: 1,
        follow: "innerMoon",
      }),
      p("biscuitmoon", 480, 342.5, "middleMoon", {
        scale: 1,
        follow: "middleMoon",
      }),
      p("biscuitmoon", 480, 342.5, "outerMoon", {
        scale: 1,
        follow: "outerMoon",
      }),
      p("ducknebula", 480, 325, undefined, { scale: 1 }),
    ],
    stamp: "DUCK NEBULA DISCOVERED. JUN MAINTAINS IT WAS ALWAYS THERE.",
    extra: {
      start: [580, 238],
      temp: 40,
      par: 205,
      mobile: {
        x: 480,
        y: 325,
        targets: ["innerMoon", "middleMoon", "outerMoon"],
      },
    },
  },
  {
    targets: [
      t(
        "axleCap",
        "Thaw the parade float's frozen axle",
        "melt",
        280,
        375,
        70,
        60,
      ),
      t(
        "axleWheel",
        "Spin the separately prepared parade axle",
        "spin",
        625,
        245,
        110,
        85,
        { requires: ["axleCap"] },
      ),
      t(
        "frontDecoration",
        "Build the float's front ice decoration",
        "freeze",
        190,
        435,
        80,
        65,
      ),
      t(
        "rearDecoration",
        "Build the float's rear ice decoration",
        "freeze",
        630,
        435,
        110,
        65,
      ),
      t(
        "reservoir",
        "Fill the reservoir after both decorations",
        "fill",
        470,
        445,
        120,
        60,
        { requires: ["frontDecoration", "rearDecoration"] },
      ),
      warm(
        "signalLamp",
        "Warm the signal after both parade preparations",
        440,
        345,
        [30, 50],
        [10, 35],
        ["axleWheel", "reservoir"],
        { w: 110, h: 60 },
      ),
    ],
    props: [p("toyparadefloat", 480, 390, undefined, { scale: 0.85 })],
    cast: [],
    stamp: "EVERY TOY HAS A JOB. EVERY PATCH BELONGS ON THE BANNER.",
    extra: { start: [315, 323], par: 260 },
  },
  {
    targets: [
      t(
        "leftBase",
        "Build the first parade route-marker base",
        "freeze",
        260,
        445,
        130,
        55,
      ),
      t(
        "rightBase",
        "Build the other route-marker base",
        "freeze",
        620,
        445,
        130,
        55,
      ),
      t(
        "leftPennant",
        "Thaw the left pennant after both bases",
        "melt",
        275,
        175,
        115,
        130,
        { requires: ["leftBase", "rightBase"] },
      ),
      t(
        "rightPennant",
        "Thaw the right pennant after both bases",
        "melt",
        605,
        175,
        115,
        130,
        { requires: ["leftBase", "rightBase"] },
      ),
      t(
        "fuelCup",
        "Fill the lamp's decorative fuel cup",
        "fill",
        445,
        435,
        110,
        65,
        { requires: ["leftPennant", "rightPennant"] },
      ),
      warm(
        "glow",
        "Warm the smallest light's separate glow",
        445,
        330,
        [35, 55],
        [10, 35],
        ["fuelCup"],
        { w: 120, h: 70 },
      ),
      t(
        "departure",
        "Let the smallest light lead the parade",
        "spin",
        755,
        380,
        100,
        100,
        { requires: ["glow"] },
      ),
    ],
    props: [
      p("paradepennant", 325, 290, "leftPennant", {
        scale: 0.75,
        reveal: { x: 230, y: 330, scale: 0.65 },
      }),
      p("paradepennant", 655, 290, "rightPennant", {
        scale: 0.75,
        reveal: { x: 755, y: 310, scale: 0.65 },
      }),
      p("toyboxpanorama", 480, 410, undefined, { scale: 0.9 }),
    ],
    cast: [],
    stamp: "THE SMALLEST LIGHT GOES FIRST. THE CAPTAIN IS HAPPY TO FOLLOW.",
    extra: { start: [325, 385], temp: -20, par: 285 },
  },
];

const dispatches = [
  "Jun's fire engine has one frozen wheel and a very serious badge. The station is one wooden block away.",
  "Button's sleeve needs thawing. His detachable badge needs gentleness. Glim could use an invitation.",
  "The dolls brought diplomatic hats larger than the table. Tea may be more useful than another meeting.",
  "Glim's boots are stuck. Build all three landing pieces first; rescuers are allowed to need a hand.",
  "The customers are marbles, not ingredients. Clear both serving caps before reviewing the menu's punctuation.",
  "The dog has nearly crossed already. Its remarkably distant tail still needs three pieces of bridge.",
  "Four frozen keys, no rhythm exam. After the thaw, everyone can sing the wordless lunch announcement.",
  "Open the little globe, then prepare its pond and snowbank. The explorer has spotted an even bigger globe.",
  "Two borrowed boots, two pretend exhaust displays. The rocket's very advanced string is quite visible.",
  "A preschool visitor has planted crayons. One needs a cold footing; two prefer different warm afternoons.",
  "A sock ghost brought an overnight bag. Jun has found a spare mitten and a very reasonable light switch.",
  "Support the telescope, thaw the moon, then warm its exposed center. The mouse has a second research interest.",
  "Three separate repairs, one crew stamp. Glim has already learned everybody's name.",
  "Cold grows ice ballast; hot water trims it back. Switch the hose off to let the real seesaw find its level.",
  "The plush bus is having an uncomfortable afternoon. Glim would like to help without hopping between seats.",
  "One rescue branch needs one platform; the other needs two. Jun is safeguarding an essential biscuit.",
  "Open the practice curtains and warm Glim's podium. The painted blocks have rehearsed their applause.",
  "Three biscuit moons share a patient clock. Follow their real orbits, or park them with stationary assist.",
  "Prepare the axle on one branch and the decorated reservoir on the other. Every repaired toy gets a job.",
  "Build the markers, clear the pennants, and prepare Glim's light. Tonight the captain is ready to follow.",
];

const source = designs.packs.find((pack) => pack.id === "17")!;
export const toyboxLevels: Level[] = source.scenes.map((card, index) => {
  const recipe = recipes[index];
  return {
    id: card.id,
    pack: "17",
    name: card.title,
    chapter: source.title,
    theme: "toybox",
    pitch: dispatches[index],
    hint: card.puzzle,
    ending: card.payoff,
    start: [475, 145],
    temp: 40,
    pressure: 40,
    par: 65 + recipe.targets.length * 25,
    targets: recipe.targets,
    props: [...recipe.props, ...(recipe.cast ?? cast())],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
