import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/18.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 120, 65, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.75, ...extra });
const ann = () => p("annmoth", 135, 335, undefined, { scale: 0.75 });
const giant = () => p("pocketgiant", 835, 465, undefined, { scale: 0.8 });
const cup = (x: number, y: number, target: string) =>
  p("omenmilk", x + 70, y + 52.5, target, { scale: 1 });
const bowl = (x: number, y: number, target: string) =>
  p("omenbowl", x + 70, y + 48.75, target, { scale: 1 });
const recipes: {
  targets: Target[];
  props: Prop[];
  cast?: Prop[];
  stamp: string;
  extra?: Partial<Level>;
}[] = [
  {
    targets: [
      t(
        "notice",
        "Thaw the enormous warning notice",
        "melt",
        305,
        160,
        350,
        95,
      ),
      t(
        "signature",
        "Thaw the much less enormous signature",
        "melt",
        385,
        285,
        190,
        50,
      ),
      t(
        "bell",
        "Ring the town's request for clarification",
        "spin",
        645,
        405,
        120,
        90,
        { requires: ["notice", "signature"] },
      ),
    ],
    props: [p("schedulingnotice", 480, 315, undefined, { scale: 1 })],
    stamp: "REGARDS, SCHEDULING. COSMIC AUTHORITY PENDING.",
    extra: { start: [480, 108], par: 200 },
  },
  {
    targets: [
      t("cereal", "Thaw the pony's overdue cereal", "melt", 300, 250, 140, 85),
      t("milk", "Fill the adjacent breakfast cup", "fill", 555, 410, 140, 70),
      warm(
        "spoon",
        "Warm the reasonably prompt serving spoon",
        335,
        430,
        [25, 40],
        [10, 35],
        ["cereal", "milk"],
        { w: 125 },
      ),
    ],
    props: [
      p("breakfastservice", 400, 365, undefined, { scale: 1 }),
      cup(555, 410, "milk"),
    ],
    stamp: "THE PONY OF REASONABLY SOON. NAPKIN PROVIDED.",
    extra: { start: [370, 198], par: 170 },
  },
  {
    targets: [
      t(
        "leftCradle",
        "Build the meteor's left picnic cradle",
        "freeze",
        310,
        445,
        100,
        50,
      ),
      t(
        "rightCradle",
        "Build its equally reassuring right foot",
        "freeze",
        600,
        445,
        100,
        50,
      ),
      t(
        "shell",
        "Thaw the safely displayed meteor shell",
        "melt",
        430,
        195,
        130,
        100,
        { requires: ["leftCradle", "rightCradle"] },
      ),
      warm(
        "marshmallow",
        "Warm the exposed marshmallow center",
        445,
        215,
        [30, 50],
        [10, 35],
        ["shell"],
        { w: 100 },
      ),
    ],
    props: [p("marshmallowmeteor", 495, 360, undefined, { scale: 1 })],
    cast: [ann()],
    stamp: "PLANET DELICIOUSLY SAFE. GIANT-SIZED SMALL BITE.",
    extra: { start: [360, 393], temp: -20, par: 210 },
  },
  {
    targets: [
      t(
        "spout",
        "Thaw the very dramatic little spout",
        "melt",
        355,
        310,
        95,
        65,
      ),
      t(
        "kettle",
        "Fill the kraken's one real kettle",
        "fill",
        455,
        380,
        140,
        70,
        { requires: ["spout"] },
      ),
      warm(
        "teaCharm",
        "Warm the separately hung tea charm",
        650,
        420,
        [35, 55],
        [10, 45],
        ["kettle"],
        { w: 110 },
      ),
    ],
    props: [p("krakenkettle", 525, 432.5, undefined, { scale: 1 })],
    stamp: "DESTINY IS TEA. THE MARKETING DEPARTMENT HAS EIGHT ARMS.",
    extra: { start: [402, 258], par: 175 },
  },
  {
    targets: [
      t(
        "firstSeal",
        "Open the first entirely postal seal",
        "melt",
        245,
        355,
        65,
        70,
      ),
      t(
        "secondSeal",
        "Thaw the next small invitation seal",
        "melt",
        280,
        245,
        65,
        70,
      ),
      t("thirdSeal", "Clear the upper-left envelope", "melt", 380, 185, 65, 70),
      t(
        "fourthSeal",
        "Clear the top of the invitation arc",
        "melt",
        480,
        165,
        65,
        70,
      ),
      t(
        "fifthSeal",
        "Thaw the upper-right invitation",
        "melt",
        580,
        195,
        65,
        70,
      ),
      t(
        "sixthSeal",
        "Open the next-to-last ominous seal",
        "melt",
        690,
        245,
        65,
        70,
      ),
      t(
        "seventhSeal",
        "Thaw the seventh and final envelope",
        "melt",
        730,
        355,
        65,
        70,
      ),
      warm(
        "applause",
        "Give the relieved walrus gentle applause",
        470,
        435,
        [25, 45],
        [10, 35],
        [
          "firstSeal",
          "secondSeal",
          "thirdSeal",
          "fourthSeal",
          "fifthSeal",
          "sixthSeal",
          "seventhSeal",
        ],
        { w: 125 },
      ),
    ],
    props: [
      p("walrusinvites", 490, 375, undefined, { scale: 0.85 }),
      p("omeninvitation", 277.5, 415, "firstSeal", { scale: 0.7 }),
      p("omeninvitation", 312.5, 305, "secondSeal", { scale: 0.7 }),
      p("omeninvitation", 412.5, 245, "thirdSeal", { scale: 0.7 }),
      p("omeninvitation", 512.5, 225, "fourthSeal", { scale: 0.7 }),
      p("omeninvitation", 612.5, 255, "fifthSeal", { scale: 0.7 }),
      p("omeninvitation", 722.5, 305, "sixthSeal", { scale: 0.7 }),
      p("omeninvitation", 762.5, 415, "seventhSeal", { scale: 0.7 }),
    ],
    stamp: "SEVEN INVITATIONS. EVIDENCE AGAINST DOOM: A NEW FOLDER.",
    extra: { start: [277, 303], par: 260 },
  },
  {
    targets: [
      t(
        "nearBowl",
        "Fill the near bank's separate lunch basin",
        "fill",
        275,
        390,
        140,
        65,
        { fillColor: "#ce7454cc" },
      ),
      t(
        "middleBowl",
        "Fill the lower independent serving basin",
        "fill",
        440,
        430,
        140,
        65,
        { fillColor: "#ce7454cc" },
      ),
      t(
        "farBowl",
        "Fill the far bank without a hidden channel",
        "fill",
        665,
        360,
        140,
        65,
        { fillColor: "#ce7454cc" },
      ),
      warm(
        "lantern",
        "Warm the soup kitchen's welcome lantern",
        445,
        315,
        [30, 50],
        [10, 35],
        ["nearBowl", "middleBowl", "farBowl"],
      ),
    ],
    props: [
      p("soupcounter", 500, 340, undefined, { scale: 1 }),
      bowl(275, 390, "nearBowl"),
      bowl(440, 430, "middleBowl"),
      bowl(665, 360, "farBowl"),
    ],
    stamp: "THE LONGEST LUNCH COUNTER. ONE SMALLER SPOON, PLEASE.",
    extra: { start: [345, 338], temp: 20, par: 200 },
  },
  {
    targets: [
      t(
        "firstPatch",
        "Build the blanket's first narrow repair",
        "freeze",
        280,
        340,
        55,
        100,
      ),
      t(
        "secondPatch",
        "Build the lower-left picnic repair",
        "freeze",
        410,
        385,
        55,
        110,
      ),
      t(
        "thirdPatch",
        "Build the upper-right blanket repair",
        "freeze",
        550,
        335,
        55,
        110,
      ),
      t(
        "fourthPatch",
        "Build the final narrow picnic footprint",
        "freeze",
        675,
        390,
        55,
        100,
      ),
      t(
        "leftClasp",
        "Thaw the left basket after all four repairs",
        "melt",
        225,
        200,
        70,
        60,
        {
          requires: ["firstPatch", "secondPatch", "thirdPatch", "fourthPatch"],
        },
      ),
      t(
        "rightClasp",
        "Thaw the other end of the repaired picnic",
        "melt",
        705,
        195,
        70,
        60,
        {
          requires: ["firstPatch", "secondPatch", "thirdPatch", "fourthPatch"],
        },
      ),
    ],
    props: [p("giantpicnic", 480, 390, undefined, { scale: 0.9 })],
    cast: [ann()],
    stamp: "ONE NORMAL SANDWICH. ONE SHORTER GIANT.",
    extra: { start: [307, 288], temp: -20, par: 245 },
  },
  {
    targets: [
      warm(
        "coolVoice",
        "Keep the first voice softly cool",
        275,
        325,
        [20, 35],
        [10, 40],
      ),
      warm(
        "mildVoice",
        "Warm the middle singer's mild station",
        450,
        405,
        [35, 50],
        [10, 40],
      ),
      warm(
        "brightVoice",
        "Warm the bright voice's higher range",
        650,
        300,
        [50, 65],
        [10, 40],
      ),
      t(
        "musicStand",
        "Thaw the music stand after all three voices",
        "melt",
        250,
        430,
        120,
        70,
        { requires: ["coolVoice", "mildVoice", "brightVoice"] },
      ),
    ],
    props: [p("shoppingchoir", 505, 330, undefined, { scale: 1 })],
    stamp: "UPLIFTING SHOPPING LIST. MINOR KEY NO LONGER REQUIRED.",
    extra: { start: [335, 273], temp: 27, pressure: 25, par: 200 },
  },
  {
    targets: [
      t("leftPage", "Thaw the first calendar page", "melt", 310, 180, 130, 100),
      t(
        "rightPage",
        "Clear the second date-checking panel",
        "melt",
        500,
        210,
        130,
        100,
      ),
      t(
        "ink",
        "Fill the clerk's separate ink basin",
        "fill",
        445,
        420,
        140,
        70,
        { fillColor: "#78659dcc" },
      ),
      t(
        "dateStamp",
        "Stamp only after both pages and the ink",
        "spin",
        670,
        390,
        115,
        100,
        { requires: ["leftPage", "rightPage", "ink"] },
      ),
    ],
    props: [p("dragoncalendar", 470, 340, undefined, { scale: 1 })],
    stamp: "END OF DAY. SECOND OPINION: SMALLER HANDWRITING.",
    extra: { start: [375, 128], par: 210 },
  },
  {
    targets: [
      t(
        "anchor",
        "Build the grounded dream-maintenance anchor",
        "freeze",
        290,
        435,
        130,
        60,
      ),
      t(
        "pillow",
        "Thaw the pillow on its separate service stand",
        "melt",
        560,
        205,
        140,
        80,
        { requires: ["anchor"] },
      ),
      warm(
        "bedtime",
        "Warm the stationary bedtime charm",
        480,
        425,
        [25, 45],
        [10, 35],
        ["pillow"],
      ),
    ],
    props: [p("ponybed", 500, 340, undefined, { scale: 1 })],
    stamp: "THE NIGHTMARE WAS LAUNDRY. STILL A MANAGEABLE PROBLEM.",
    extra: { start: [355, 383], temp: -20, par: 175 },
  },
  {
    targets: [
      t(
        "reservoir",
        "Fill the upper soup reservoir",
        "fill",
        420,
        150,
        120,
        65,
        { fillColor: "#ce7454cc" },
      ),
      t(
        "leftBowl",
        "Deliver soup through the left tributary",
        "fill",
        210,
        425,
        140,
        65,
        { flowOnly: true, fillColor: "#ce7454cc" },
      ),
      t(
        "middleBowl",
        "Divert soup over the raised middle weir",
        "fill",
        410,
        425,
        140,
        65,
        { flowOnly: true, fillColor: "#ce7454cc" },
      ),
      t(
        "rightBowl",
        "Deliver soup through the right tributary",
        "fill",
        610,
        425,
        140,
        65,
        { flowOnly: true, fillColor: "#ce7454cc" },
      ),
      t("leftPlug", "Close the left tributary", "freeze", 335, 255, 70, 50, {
        phase: {
          steps: [
            {
              verb: "freeze",
              name: "Close the left tributary",
              signal: "leftPlug:formed",
            },
            {
              verb: "melt",
              name: "Reopen the left tributary",
              requires: ["middleBowl"],
            },
          ],
        },
      }),
      t("rightPlug", "Close the right tributary", "freeze", 555, 255, 70, 50, {
        phase: {
          steps: [
            {
              verb: "freeze",
              name: "Close the right tributary",
              signal: "rightPlug:formed",
            },
            {
              verb: "melt",
              name: "Reopen the right tributary",
              requires: ["middleBowl"],
            },
          ],
        },
      }),
    ],
    props: [
      bowl(210, 425, "leftBowl"),
      bowl(410, 425, "middleBowl"),
      bowl(610, 425, "rightBowl"),
      p("soupmap", 815, 315, undefined, { scale: 0.75 }),
    ],
    stamp: "TRIBUTARIES OF DINNER. AMBASSADOR FOR SECOND HELPINGS.",
    extra: {
      start: [370, 203],
      temp: -20,
      par: 285,
      channels: {
        inlet: { x: 460, y: 170, w: 40, h: 30 },
        junction: [480, 235],
        branches: [
          {
            target: "leftBowl",
            overflowFrom: "reservoir",
            iceGates: [{ target: "leftPlug", state: "open" }],
            via: [
              [370, 235],
              [370, 280],
              [280, 280],
            ],
          },
          {
            target: "middleBowl",
            overflowFrom: "reservoir",
            iceGates: [
              { target: "leftPlug", state: "formed" },
              { target: "rightPlug", state: "formed" },
            ],
            via: [[480, 255]],
          },
          {
            target: "rightBowl",
            overflowFrom: "reservoir",
            iceGates: [{ target: "rightPlug", state: "open" }],
            via: [
              [590, 235],
              [590, 280],
              [680, 280],
            ],
          },
        ],
      },
    },
  },
  {
    targets: [
      t(
        "leftPlatform",
        "Build the supper train's first station platform",
        "freeze",
        280,
        435,
        140,
        55,
      ),
      t(
        "rightPlatform",
        "Build the other last-service platform",
        "freeze",
        600,
        435,
        140,
        55,
      ),
      t(
        "engineBadge",
        "Thaw the engine badge after both platforms",
        "melt",
        465,
        275,
        100,
        75,
        { requires: ["leftPlatform", "rightPlatform"] },
      ),
      t(
        "departure",
        "Spin the entirely stationary departure wheel",
        "spin",
        685,
        300,
        110,
        95,
        { requires: ["engineBadge"] },
      ),
    ],
    props: [p("lasttrain", 480, 375, undefined, { scale: 0.9 })],
    stamp: "LAST SERVICE BEFORE SUPPER. EXCELLENT PICNIC CLOTH.",
    extra: { start: [350, 383], temp: -20, par: 210 },
  },
  {
    targets: [
      t(
        "upperLeftNote",
        "Thaw the first large-print footnote card",
        "melt",
        300,
        180,
        110,
        85,
      ),
      t(
        "upperRightNote",
        "Clear the upper-right clarification",
        "melt",
        575,
        185,
        110,
        85,
      ),
      t(
        "lowerLeftNote",
        "Open the lower-left small-print card",
        "melt",
        270,
        390,
        110,
        85,
      ),
      t(
        "lowerRightNote",
        "Thaw the final very readable footnote",
        "melt",
        655,
        390,
        110,
        85,
      ),
      warm(
        "readingLamp",
        "Warm Ann's moth-sized reading lamp",
        445,
        325,
        [25, 40],
        [10, 30],
        ["upperLeftNote", "upperRightNote", "lowerLeftNote", "lowerRightNote"],
        { w: 130, h: 70 },
      ),
    ],
    props: [
      p("footnotecard", 355, 252, "upperLeftNote", { scale: 0.9 }),
      p("footnotecard", 630, 257, "upperRightNote", { scale: 0.9 }),
      p("footnotecard", 325, 462, "lowerLeftNote", { scale: 0.9 }),
      p("footnotecard", 710, 462, "lowerRightNote", { scale: 0.9 }),
      p("smallprint", 480, 300, undefined, { scale: 1 }),
    ],
    cast: [giant()],
    stamp: "CELEBRATION. BRING SNACKS. A VERY SMALL CHAIR, TOO.",
    extra: { start: [355, 128], par: 225 },
  },
  {
    targets: [
      t(
        "firstBell",
        "Ring the first patient tea bell",
        "spin",
        265,
        345,
        130,
        100,
        { pulse: { period: 8, open: 4, phase: 0, untimedOrder: 1 } },
      ),
      t(
        "secondBell",
        "Ring the second bell after the first",
        "spin",
        445,
        345,
        130,
        100,
        {
          requires: ["firstBell"],
          pulse: { period: 8, open: 4, phase: 0, untimedOrder: 2 },
        },
      ),
      t(
        "thirdBell",
        "Finish the chime with the third bell",
        "spin",
        625,
        345,
        130,
        100,
        {
          requires: ["secondBell"],
          pulse: { period: 8, open: 4, phase: 0, untimedOrder: 3 },
        },
      ),
    ],
    props: [p("doomclocktea", 135, 365, undefined, { scale: 0.7 })],
    cast: [p("annmoth", 835, 275, undefined, { scale: 0.75 })],
    stamp: "COUNTDOWN COMPLETE. A POLITE KETTLE WHISTLE.",
    extra: { start: [330, 293], temp: 20, pressure: 85, par: 210 },
  },
  {
    targets: [
      t(
        "bewareCap",
        "Thaw the first warning pennant",
        "melt",
        280,
        180,
        105,
        140,
      ),
      t(
        "hopeCap",
        "Thaw the unnecessarily gloomy soup banner",
        "melt",
        445,
        195,
        105,
        140,
      ),
      t(
        "skullCap",
        "Thaw the little skull's smiling pennant",
        "melt",
        615,
        175,
        105,
        140,
      ),
      t(
        "leftDecoration",
        "Build the first newly unlocked decoration",
        "freeze",
        280,
        435,
        105,
        55,
        { requires: ["bewareCap", "hopeCap", "skullCap"] },
      ),
      t(
        "middleDecoration",
        "Build the middle party mould",
        "freeze",
        455,
        450,
        95,
        50,
        { requires: ["bewareCap", "hopeCap", "skullCap"] },
      ),
      t(
        "rightDecoration",
        "Build the last cheerful ice decoration",
        "freeze",
        630,
        430,
        110,
        65,
        { requires: ["bewareCap", "hopeCap", "skullCap"] },
      ),
      warm(
        "welcome",
        "Warm the seal after all party decorations",
        430,
        350,
        [30, 50],
        [10, 35],
        ["leftDecoration", "middleDecoration", "rightDecoration"],
        { w: 130, h: 60 },
      ),
    ],
    props: [
      p("warningpennant", 332.5, 310, "bewareCap", {
        scale: 0.7,
        reveal: { x: 315, y: 325, scale: 0.95 },
      }),
      p("souppennant", 497.5, 325, "hopeCap", {
        scale: 0.7,
        reveal: { x: 500, y: 325, scale: 0.95 },
      }),
      p("skullpennant", 667.5, 305, "skullCap", {
        scale: 0.7,
        reveal: { x: 685, y: 325, scale: 0.95 },
      }),
    ],
    stamp: "BE HERE. ABUNDANT SOUP. KEEP THE LITTLE SMILING SKULL.",
    extra: { start: [332, 128], par: 265 },
  },
  {
    targets: [
      t(
        "stool",
        "Thaw the pocket giant's own serving stool",
        "melt",
        310,
        300,
        100,
        85,
      ),
      t(
        "drink",
        "Fill the giant host's one real cup",
        "fill",
        585,
        405,
        140,
        70,
        { requires: ["stool"] },
      ),
      warm(
        "handRest",
        "Warm the host's comfortable hand-rest badge",
        430,
        425,
        [25, 45],
        [10, 35],
        ["drink"],
      ),
      t(
        "leftFooting",
        "Independently build the table's left foot",
        "freeze",
        225,
        435,
        75,
        55,
      ),
      t(
        "rightFooting",
        "Build the table's independent right foot",
        "freeze",
        750,
        440,
        80,
        55,
      ),
      t(
        "serviceBell",
        "Ring for service after all five preparations",
        "spin",
        470,
        220,
        115,
        90,
        {
          requires: [
            "stool",
            "drink",
            "handRest",
            "leftFooting",
            "rightFooting",
          ],
        },
      ),
    ],
    props: [
      p("giantservice", 480, 370, undefined, { scale: 1 }),
      cup(585, 405, "drink"),
    ],
    cast: [ann()],
    stamp: "HOST, NOT HEAVY EQUIPMENT. ASK FOR THE RECOMMENDATION.",
    extra: { start: [360, 248], par: 255 },
  },
  {
    targets: [
      t(
        "buns",
        "Thaw the breakfast pony's bun tray",
        "melt",
        235,
        360,
        110,
        80,
      ),
      t(
        "drinks",
        "Fill the drinks pony's independent bowl",
        "fill",
        640,
        430,
        140,
        65,
      ),
      t(
        "pedestal",
        "Build the third errand's little ice pedestal",
        "freeze",
        370,
        425,
        100,
        70,
      ),
      warm(
        "comfort",
        "Warm the company pony's comfort lantern",
        500,
        405,
        [30, 50],
        [10, 40],
        [],
        { w: 110 },
      ),
      t(
        "parade",
        "Start the parade after all four useful errands",
        "spin",
        780,
        185,
        110,
        100,
        { requires: ["buns", "drinks", "pedestal", "comfort"] },
      ),
    ],
    props: [
      p("ponyerrands", 490, 340, undefined, { scale: 0.9 }),
      bowl(640, 430, "drinks"),
    ],
    stamp: "BREAKFAST. NAPS. SNACKS. COMPANY. MUCH BETTER BRANDING.",
    extra: { start: [290, 308], par: 225 },
  },
];

const finalRecipes: typeof recipes = [
  {
    targets: [
      t(
        "leftInvitation",
        "Thaw the first neighbor's invitation board",
        "melt",
        325,
        180,
        130,
        95,
      ),
      t(
        "rightInvitation",
        "Clear the other nervous guest's invitation",
        "melt",
        540,
        210,
        130,
        95,
      ),
      t(
        "leftRefreshment",
        "Fill the first independent refreshment cup",
        "fill",
        345,
        425,
        140,
        70,
      ),
      t(
        "rightRefreshment",
        "Fill the other guest's separate cup",
        "fill",
        575,
        430,
        140,
        70,
      ),
      warm(
        "leftWelcome",
        "Warm a welcome without hurrying anyone",
        225,
        330,
        [25, 45],
        [10, 35],
        [],
        { w: 110, h: 60 },
      ),
      warm(
        "rightWelcome",
        "Warm the quiet guest's own welcome badge",
        705,
        325,
        [25, 45],
        [10, 35],
        [],
        { w: 110, h: 60 },
      ),
      t(
        "doorbell",
        "Ring only after all six welcoming preparations",
        "spin",
        470,
        325,
        110,
        85,
        {
          requires: [
            "leftInvitation",
            "rightInvitation",
            "leftRefreshment",
            "rightRefreshment",
            "leftWelcome",
            "rightWelcome",
          ],
        },
      ),
    ],
    props: [
      p("omeninvitation", 390, 262, "leftInvitation", { scale: 1.5 }),
      p("omeninvitation", 605, 292, "rightInvitation", { scale: 1.5 }),
      cup(345, 425, "leftRefreshment"),
      cup(575, 430, "rightRefreshment"),
      p("quietguests", 480, 325, undefined, { scale: 0.95 }),
    ],
    stamp: "BRING CHAIRS, NOT EMERGENCY BAGS. A QUIET SEAT IS SAVED.",
    extra: { start: [390, 128], par: 270 },
  },
  {
    targets: [
      t(
        "leftDecoration",
        "Build the party's first ice decoration",
        "freeze",
        270,
        445,
        120,
        55,
      ),
      t(
        "rightDecoration",
        "Build the other tomorrow-ready decoration",
        "freeze",
        650,
        435,
        120,
        60,
      ),
      t(
        "dateSign",
        "Thaw the date on the old doom platform",
        "melt",
        395,
        175,
        190,
        95,
      ),
      t(
        "drinks",
        "Fill the bowl after the sign and both decorations",
        "fill",
        445,
        440,
        140,
        65,
        { requires: ["leftDecoration", "rightDecoration", "dateSign"] },
      ),
      warm(
        "sunset",
        "Warm the separate sunset lantern",
        440,
        335,
        [35, 55],
        [10, 35],
        ["drinks"],
      ),
      t(
        "celebration",
        "Ring the perfectly ordinary celebration bell",
        "spin",
        780,
        325,
        100,
        100,
        { requires: ["sunset"] },
      ),
    ],
    props: [
      p("datesign", 490, 255, "dateSign", { scale: 1 }),
      bowl(445, 440, "drinks"),
      p("tomorrowparty", 480, 405, undefined, { scale: 0.9 }),
    ],
    cast: [],
    stamp: "SEE YOU TOMORROW. EMERGENCY CLIPBOARD LIGHT: OFF.",
    extra: { start: [330, 393], temp: -20, par: 255 },
  },
];

recipes.push(
  {
    targets: [
      t(
        "leftPrism",
        "Shape the left prism at its 65% notch",
        "freeze",
        240,
        170,
        80,
        200,
        { reversibleIce: true, effort: 4 },
      ),
      t(
        "centerPrism",
        "Grow the center prism to its full-height mark",
        "freeze",
        450,
        215,
        90,
        185,
        { reversibleIce: true, effort: 4 },
      ),
      t(
        "rightPrism",
        "Shape the right prism at its 65% notch",
        "freeze",
        670,
        210,
        140,
        200,
        { reversibleIce: true, effort: 4 },
      ),
    ],
    props: [
      p("reassuringsky", 480, 405, undefined, { scale: 1, revealOnly: true }),
    ],
    cast: [p("annmoth", 135, 385, undefined, { scale: 0.6 })],
    stamp: "MILD REASSURANCE. ONE VERY REAL BISCUIT CRUMB ON THE CHIN.",
    extra: {
      start: [280, 118],
      temp: -20,
      pressure: 85,
      par: 300,
      optics: {
        source: { x: 110, y: 260, dx: 1, dy: 0 },
        mirrors: [],
        prisms: [
          {
            target: "leftPrism",
            vertices: [
              [240, 170],
              [320, 370],
              [240, 370],
            ],
            refractiveIndex: 1.31,
            height: { mark: 0.65 },
          },
          {
            target: "centerPrism",
            vertices: [
              [450, 400],
              [540, 215],
              [450, 215],
            ],
            refractiveIndex: 1.31,
            height: { mark: 1 },
          },
          {
            target: "rightPrism",
            vertices: [
              [670, 410],
              [810, 210],
              [670, 210],
            ],
            refractiveIndex: 1.31,
            height: { mark: 0.65 },
          },
        ],
        detectors: [
          {
            id: "reassurance:left",
            name: "Left star",
            x: 380,
            y: 286.56356065760247,
            radius: 4,
            label: [380, 145],
          },
          {
            id: "reassurance:middle",
            name: "Middle star",
            x: 600,
            y: 314.4602877081673,
            radius: 4,
            label: [600, 145],
          },
          {
            id: "reassurance:right",
            name: "Right star",
            x: 865,
            y: 286.9632041719589,
            radius: 4,
            label: [865, 390],
          },
        ],
      },
      needsSignals: [
        "reassurance:left",
        "reassurance:middle",
        "reassurance:right",
      ],
      completionHint:
        "Fill the middle prism. Trim both sides toward their 65% notches until the real beam lights all three stars.",
    },
  },
  ...finalRecipes,
);

const dispatches = [
  "Ann brought an enormous warning and a tiny signature. Thaw both before asking the town bell for clarification.",
  "The first ominous pony is only late for breakfast. Its cereal and cup can be prepared separately.",
  "This meteor is already safely parked. Build its cradle, open the shell, and investigate the soft center.",
  "A tiny kraken has advertised tea as destiny. Clear the spout, fill the kettle, and warm the separate charm.",
  "Seven frozen seals. One embarrassed walrus. The applause badge can wait until every envelope is open.",
  "The red river is painted; these three lunch bowls are not connected. Fill each, then light the welcome lantern.",
  "Four narrow blanket repairs, two basket clasps. The pocket giant is almost ready for a very normal sandwich.",
  "Three voices want three different warm-ups. Their music stand will thaw after everyone is comfortable.",
  "Flint has brought a calendar and very confident handwriting. Both pages and the ink must be ready for the stamp.",
  "The bed only floats in the picture. Its grounded anchor, separate pillow, and bedtime charm need ordinary care.",
  "Close both side tributaries to serve the middle bowl. Then thaw the plugs and send real reservoir water outward.",
  "The final train means the last train before supper. Build both platforms before preparing the engine badge.",
  "Four frozen footnotes surround Ann's lamp. Their clarification has thoughtfully abandoned small print.",
  "Three patient tea bells, one at a time. Missed windows return; untimed assist keeps the current bell open.",
  "Thaw all three warnings before building their party decorations. Ann would like to keep the little smiling skull.",
  "Prepare the giant's stool, cup, and hand rest; build either table foot independently. Then ring for the host.",
  "Four ponies have four useful errands. Any order is welcome; the shared parade wheel waits for all four.",
  "Fill the center prism; trim both sides to their 65% notches. Cold grows ice, hot water trims, and real rays find the stars.",
  "Six separate preparations, no hurried guests. Ring the doorbell when the invitations, cups, and welcomes are ready.",
  "Decorate the stage and thaw its date. Prepare drinks and sunset light; the celebration bell can take it from there.",
];

const source = designs.packs.find((pack) => pack.id === "18")!;
export const apocalypseLevels: Level[] = source.scenes.map((card, index) => {
  const recipe = recipes[index];
  return {
    id: card.id,
    pack: "18",
    name: card.title,
    chapter: source.title,
    theme: "apocalypse",
    pitch: dispatches[index],
    hint: card.puzzle,
    ending: card.payoff,
    start: [475, 145],
    temp: 40,
    pressure: 40,
    par: 90 + recipe.targets.length * 25,
    targets: recipe.targets,
    props: [...recipe.props, ...(recipe.cast ?? [ann(), giant()])],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
