import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/19.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number] = [10, 35],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 120, 65, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 0.8, ...extra });
const between = () =>
  p("betweenreceptionist", 130, 335, undefined, { scale: 0.85 });
const yesterday = () =>
  p("yesterdayporter", 835, 465, undefined, { scale: 0.8 });
const cup = (x: number, y: number, target: string, extra: Partial<Prop> = {}) =>
  p("hotelcup", x + 70, y + 52.5, target, { scale: 1, ...extra });
const vessel = (
  kind: "hotelvase" | "hotelbowl" | "umbrellabasin",
  x: number,
  y: number,
  target: string,
) => p(kind, x + 70, y + 52.5, target, { scale: 1 });
type Recipe = {
  targets: Target[];
  props: Prop[];
  cast?: Prop[];
  stamp: string;
  extra?: Partial<Level>;
};
const recipes: Recipe[] = [
  {
    targets: [
      t(
        "bellCap",
        "Thaw the oversized reception-bell cube",
        "melt",
        340,
        190,
        150,
        120,
      ),
      t("ringer", "Ring the exposed brass bell", "spin", 365, 215, 100, 90, {
        requires: ["bellCap"],
      }),
      warm(
        "welcome",
        "Warm the separate welcome seal",
        645,
        425,
        [25, 45],
        [10, 35],
        ["ringer"],
      ),
    ],
    props: [
      p("hotelbell", 415, 302, "ringer", { scale: 1 }),
      p("hotelentrance", 480, 425, undefined, { scale: 1 }),
    ],
    cast: [],
    stamp: "WELCOME DELIVERED. MAT ONLY SLIGHTLY LATER.",
    extra: { start: [415, 138], par: 180 },
  },
  {
    targets: [
      t(
        "curtainCatch",
        "Thaw Monday's curtain catch",
        "melt",
        285,
        240,
        90,
        80,
      ),
      t("vase", "Fill the bedside flower vase", "fill", 580, 400, 140, 70, {
        requires: ["curtainCatch"],
      }),
      warm(
        "lamp",
        "Warm the lamp for Monday's best minute",
        395,
        425,
        [30, 50],
        [10, 40],
        ["vase"],
      ),
    ],
    props: [
      p("mondaywindow", 480, 330, undefined, { scale: 1 }),
      vessel("hotelvase", 580, 400, "vase"),
    ],
    stamp: "ONE PLEASANT MINUTE. PORTER'S NOTES AVAILABLE.",
    extra: { start: [330, 188], par: 175 },
  },
  {
    targets: [
      t(
        "snowbank",
        "Build the pillow's bedside snowbank",
        "freeze",
        280,
        430,
        150,
        60,
      ),
      t(
        "blanketBadge",
        "Thaw the grumpy pillow's blanket badge",
        "melt",
        585,
        235,
        115,
        80,
      ),
      warm(
        "bedtime",
        "Warm the quiet bedtime charm",
        500,
        435,
        [20, 35],
        [10, 35],
        ["snowbank", "blanketBadge"],
      ),
    ],
    props: [
      p("cloudpillow", 475, 350, undefined, { scale: 1.05 }),
      p("silentbell", 775, 395, "bedtime", { scale: 0.65, revealOnly: true }),
    ],
    stamp: "SILENT BELL AWARDED. PLEASE DO NOT RING IT.",
    extra: { start: [355, 378], temp: -20, par: 190 },
  },
  {
    targets: [
      t(
        "leftUmbrella",
        "Fill the first umbrella basin",
        "fill",
        260,
        410,
        140,
        70,
      ),
      t(
        "rightUmbrella",
        "Fill the second umbrella basin",
        "fill",
        550,
        410,
        140,
        70,
      ),
      t(
        "luggageTag",
        "Thaw the cloud's luggage tag",
        "melt",
        685,
        225,
        100,
        85,
        { requires: ["leftUmbrella", "rightUmbrella"] },
      ),
      warm(
        "guestBadge",
        "Warm the raincloud's guest badge",
        420,
        425,
        [25, 45],
        [10, 35],
        ["luggageTag"],
      ),
    ],
    props: [
      p("rainluggage", 475, 330, undefined, { scale: 1 }),
      vessel("umbrellabasin", 260, 410, "leftUmbrella"),
      vessel("umbrellabasin", 550, 410, "rightUmbrella"),
    ],
    cast: [between()],
    stamp: "LUGGAGE DRY. PORTER GLADLY SLIGHTLY DAMP.",
    extra: { start: [330, 358], temp: 20, par: 200 },
  },
  {
    targets: [
      t(
        "servingHatch",
        "Thaw the shared midnight serving hatch",
        "melt",
        400,
        165,
        160,
        85,
      ),
      t("sunCup", "Fill the sleepy sun's drink", "fill", 240, 365, 140, 70, {
        requires: ["servingHatch"],
      }),
      t(
        "moonCup",
        "Fill the energetic moon's drink",
        "fill",
        600,
        365,
        140,
        70,
        { requires: ["servingHatch"] },
      ),
      warm(
        "sunTray",
        "Warm the sun's hotter breakfast station",
        260,
        465,
        [50, 70],
        [10, 35],
        ["sunCup", "moonCup"],
      ),
      warm(
        "moonTray",
        "Warm the moon's gentler breakfast station",
        605,
        465,
        [20, 40],
        [10, 35],
        ["sunCup", "moonCup"],
      ),
    ],
    props: [
      p("midnightbreakfast", 480, 335, undefined, { scale: 1 }),
      cup(240, 365, "sunCup"),
      cup(600, 365, "moonCup"),
    ],
    stamp: "BREAKFAST PREFERENCES: PLEASE CONSULT THE OTHER GUEST.",
    extra: { start: [480, 113], par: 260 },
  },
  {
    targets: [
      t(
        "lowStep",
        "Build the lowest temporary step",
        "freeze",
        275,
        440,
        105,
        55,
      ),
      t(
        "middleStep",
        "Build the middle temporary step",
        "freeze",
        405,
        375,
        105,
        55,
      ),
      t(
        "highStep",
        "Build the upper temporary step",
        "freeze",
        535,
        310,
        105,
        55,
      ),
      t(
        "release",
        "Thaw the luggage trolley's release badge",
        "melt",
        660,
        185,
        100,
        85,
        { requires: ["lowStep", "middleStep", "highStep"] },
      ),
      t(
        "axle",
        "Turn the trolley's stationary service axle",
        "spin",
        670,
        395,
        110,
        100,
        { requires: ["release"] },
      ),
    ],
    props: [
      p("holidaystairs", 410, 285, undefined, { scale: 0.95 }),
      p("reliablepostcard", 695, 315, "axle", {
        scale: 0.65,
        revealOnly: true,
      }),
    ],
    stamp: "TO: THE RELIABLE ONE. POSTAGE: ONE SMALL SOUVENIR.",
    extra: { start: [327, 388], temp: -20, par: 255 },
  },
  {
    targets: [
      t(
        "latch",
        "Thaw the conservatory suitcase latch",
        "melt",
        230,
        295,
        80,
        90,
      ),
      t(
        "tank",
        "Fill the tiny greenhouse water tank",
        "fill",
        370,
        405,
        140,
        70,
        { requires: ["latch"] },
      ),
      t(
        "plantBed",
        "Build the separate plant-bed footprint",
        "freeze",
        575,
        400,
        135,
        75,
        { requires: ["latch"] },
      ),
      warm(
        "orchid",
        "Warm the orchid's sunlight marker",
        490,
        240,
        [25, 45],
        [10, 35],
        ["tank", "plantBed"],
      ),
    ],
    props: [
      p("conservatorycase", 485, 485, undefined, { scale: 1 }),
      vessel("hotelbowl", 370, 405, "tank"),
    ],
    stamp: "HANDLE WITH CARE. THE LUGGAGE HAS GROWN ATTACHED.",
    extra: { start: [270, 243], par: 225 },
  },
  {
    targets: [
      t(
        "clockCap",
        "Thaw the planet's clock-turbine cap",
        "melt",
        275,
        235,
        130,
        100,
      ),
      t(
        "teaCap",
        "Thaw the tea stand's separate ice cap",
        "melt",
        570,
        385,
        150,
        90,
      ),
      t(
        "clock",
        "Turn the exposed geological alarm",
        "spin",
        290,
        250,
        100,
        85,
        { requires: ["clockCap"] },
      ),
      t("tea", "Fill the newly opened tea cup", "fill", 575, 395, 140, 70, {
        requires: ["teaCap"],
      }),
      warm(
        "sunrise",
        "Warm the planet's gentle sunrise badge",
        420,
        445,
        [35, 55],
        [10, 35],
        ["clock", "tea"],
      ),
    ],
    props: [
      p("sleepyplanet", 480, 320, undefined, { scale: 1 }),
      cup(575, 395, "tea"),
    ],
    stamp: "FIVE MORE GEOLOGICAL MINUTES. LATE CHECKOUT APPROVED.",
    extra: { start: [340, 183], par: 245 },
  },
  {
    targets: [
      t(
        "caveDecoration",
        "Build the cave-side honeymoon decoration",
        "freeze",
        245,
        405,
        135,
        75,
      ),
      warm(
        "gardenLamp",
        "Warm the garden-side welcome lamp",
        610,
        395,
        [30, 50],
      ),
      t(
        "blueCup",
        "Fill the remembered blue breakfast cup",
        "fill",
        390,
        270,
        140,
        70,
        { requires: ["caveDecoration", "gardenLamp"], fillColor: "#609dbbcc" },
      ),
      t(
        "creamCup",
        "Fill the neighboring breakfast cup",
        "fill",
        390,
        420,
        140,
        70,
        { requires: ["caveDecoration", "gardenLamp"] },
      ),
    ],
    props: [
      p("honeymoonnook", 480, 350, undefined, { scale: 1 }),
      cup(390, 270, "blueCup", { tint: "#8dbdd4" }),
      cup(390, 420, "creamCup"),
    ],
    stamp: "TWO PRIVATE VIEWS. ONE VERY GOOD SHARED WINDOW.",
    extra: { start: [312, 353], temp: -20, par: 220 },
  },
  {
    targets: [
      t(
        "seminarCap",
        "Thaw the seminar bell's forgotten ice cap",
        "melt",
        415,
        175,
        135,
        90,
      ),
      t(
        "leftRack",
        "Build the first low naptime mat rack",
        "freeze",
        265,
        440,
        110,
        55,
      ),
      t(
        "rightRack",
        "Build the second low naptime mat rack",
        "freeze",
        620,
        440,
        110,
        55,
      ),
      warm(
        "milkBadge",
        "Warm the nursery's separate milk badge",
        405,
        420,
        [25, 40],
        [10, 30],
      ),
      t(
        "quietSign",
        "Turn the quiet-time sign, not the bell",
        "spin",
        710,
        245,
        110,
        100,
        { requires: ["seminarCap", "leftRack", "rightRack", "milkBadge"] },
      ),
    ],
    props: [p("preschoolseminar", 480, 360, undefined, { scale: 1 })],
    cast: [between()],
    stamp: "TEMPORARY HEAD TEACHER. ALL PERMANENT TEACHERS ASLEEP.",
    extra: { start: [482, 123], par: 250 },
  },
  {
    targets: [
      t(
        "lowLinen",
        "Thaw the lowest moonlit linen parcel",
        "melt",
        260,
        330,
        100,
        85,
      ),
      t(
        "middleLinen",
        "Thaw the middle service-stand parcel",
        "melt",
        430,
        250,
        100,
        85,
      ),
      t(
        "highLinen",
        "Thaw the high parcel from above",
        "melt",
        600,
        170,
        100,
        85,
      ),
      t(
        "bath",
        "Fill the guest's small bath basin",
        "fill",
        610,
        430,
        140,
        70,
        { requires: ["lowLinen", "middleLinen", "highLinen"] },
      ),
      warm(
        "towel",
        "Warm the linen's quiet towel badge",
        360,
        435,
        [30, 50],
        [10, 35],
        ["lowLinen", "middleLinen", "highLinen", "bath"],
      ),
    ],
    props: [
      p("linenfort", 490, 370, undefined, { scale: 1 }),
      vessel("hotelbowl", 610, 430, "bath"),
    ],
    cast: [between()],
    stamp: "BLANKET FORT: KNOCK SOFTLY. WAIT TO BE INVITED.",
    extra: { start: [310, 278], par: 250 },
  },
  {
    targets: [
      t(
        "leftPlatform",
        "Build the balcony's first platform section",
        "freeze",
        285,
        445,
        110,
        50,
      ),
      t(
        "rightPlatform",
        "Build the balcony's second platform section",
        "freeze",
        575,
        445,
        110,
        50,
      ),
      t(
        "timetable",
        "Thaw the conductor's timetable cap",
        "melt",
        420,
        175,
        140,
        90,
        { requires: ["leftPlatform", "rightPlatform"] },
      ),
      t(
        "departure",
        "Turn the stationary departure seal",
        "spin",
        430,
        325,
        120,
        100,
        { requires: ["leftPlatform", "rightPlatform", "timetable"] },
      ),
    ],
    props: [p("balconytrain", 485, 340, undefined, { scale: 1 })],
    cast: [between()],
    stamp: "TOUR DELAYED FOR CURTAIN PREFERENCES. TRAIN DELIGHTED.",
    extra: { start: [340, 393], temp: -20, par: 225 },
  },
  {
    targets: [
      t(
        "leftWindow",
        "Thaw the lift's left fish window",
        "melt",
        290,
        240,
        100,
        90,
        { motion: { rx: 0, ry: 85, period: 18, phase: Math.PI / 2 } },
      ),
      t(
        "middleWindow",
        "Thaw the lift's middle fish window",
        "melt",
        440,
        240,
        100,
        90,
        { motion: { rx: 0, ry: 85, period: 18, phase: Math.PI / 2 } },
      ),
      t(
        "rightWindow",
        "Thaw the lift's right fish window",
        "melt",
        590,
        240,
        100,
        90,
        { motion: { rx: 0, ry: 85, period: 18, phase: Math.PI / 2 } },
      ),
      warm(
        "cabinBadge",
        "Warm the moving cabin badge",
        435,
        365,
        [25, 45],
        [10, 35],
        ["leftWindow", "middleWindow", "rightWindow"],
        {
          w: 110,
          h: 60,
          motion: { rx: 0, ry: 85, period: 18, phase: Math.PI / 2 },
        },
      ),
    ],
    props: [
      p("aquariumcabin", 490, 307.5, undefined, {
        scale: 1,
        follow: "middleWindow",
      }),
    ],
    stamp: "NEXT FLOOR: WHICHEVER ONE YOU FIND INTERESTING.",
    extra: { start: [340, 273], par: 270 },
  },
  {
    targets: [
      t(
        "giantLeft",
        "Build the giant's first cool slipper form",
        "freeze",
        230,
        445,
        100,
        60,
      ),
      t(
        "giantRight",
        "Build the giant's second cool slipper form",
        "freeze",
        355,
        445,
        100,
        60,
      ),
      warm(
        "sunLeft",
        "Warm the little sun's first slipper badge",
        565,
        400,
        [55, 75],
        [10, 45],
      ),
      warm(
        "sunRight",
        "Warm the little sun's second slipper badge",
        710,
        400,
        [55, 75],
        [10, 45],
      ),
      t(
        "sharedTea",
        "Fill the storytellers' shared tea bowl",
        "fill",
        440,
        230,
        140,
        70,
        { requires: ["giantLeft", "giantRight", "sunLeft", "sunRight"] },
      ),
    ],
    props: [
      p("slipperlounge", 510, 370, undefined, { scale: 1 }),
      vessel("hotelbowl", 440, 230, "sharedTea"),
    ],
    cast: [between()],
    stamp: "FOUR SLIPPERS. TWO STORIES. ONE UNSPECIFIED CUSHION.",
    extra: { start: [280, 393], temp: -20, par: 265 },
  },
  {
    targets: [
      t(
        "departureCard",
        "Thaw the card that arrived before its guest",
        "melt",
        425,
        180,
        150,
        95,
      ),
      warm(
        "cardSeal",
        "Warm the out-of-order departure seal",
        450,
        315,
        [30, 45],
        [10, 35],
        ["departureCard"],
      ),
      t(
        "welcomeCup",
        "Fill the newly unlocked welcome cup",
        "fill",
        320,
        435,
        140,
        70,
        { requires: ["cardSeal"] },
      ),
      t(
        "dateStamp",
        "Turn the date stamp after refreshments",
        "spin",
        650,
        410,
        120,
        100,
        { requires: ["welcomeCup"] },
      ),
    ],
    props: [
      p("tuesdayguest", 520, 350, undefined, { scale: 1 }),
      cup(320, 435, "welcomeCup"),
    ],
    stamp: "WELCOME ANYWAY. CALENDAR COMPLAINTS MAY HAVE BISCUITS.",
    extra: { start: [500, 128], par: 215 },
  },
  {
    targets: [
      t(
        "leftGate",
        "Thaw the left room-service channel gate",
        "melt",
        300,
        280,
        70,
        55,
      ),
      t(
        "middleGate",
        "Thaw the lower middle channel gate",
        "melt",
        445,
        315,
        70,
        55,
      ),
      t(
        "rightGate",
        "Thaw the right room-service channel gate",
        "melt",
        590,
        280,
        70,
        55,
      ),
      t(
        "reservoir",
        "Fill the upper room-service reservoir",
        "fill",
        420,
        150,
        120,
        70,
        { requires: ["leftGate", "middleGate", "rightGate"] },
      ),
      t(
        "leftCup",
        "Deliver real tributary water to the left cup",
        "fill",
        210,
        425,
        140,
        70,
        { requires: ["leftGate"], flowOnly: true },
      ),
      t(
        "middleCup",
        "Deliver real tributary water to the middle cup",
        "fill",
        410,
        425,
        140,
        70,
        { requires: ["middleGate"], flowOnly: true },
      ),
      t(
        "rightCup",
        "Deliver real tributary water to the right cup",
        "fill",
        610,
        425,
        140,
        70,
        { requires: ["rightGate"], flowOnly: true },
      ),
    ],
    props: [
      p("tributaryguests", 480, 385, undefined, { scale: 1 }),
      cup(210, 425, "leftCup"),
      cup(410, 425, "middleCup"),
      cup(610, 425, "rightCup"),
    ],
    stamp: "THREE TOASTS. ONE PORTER FOLLOWING WITH A SAFETY TRAY.",
    extra: {
      start: [335, 228],
      par: 300,
      channels: {
        inlet: { x: 460, y: 170, w: 40, h: 30 },
        junction: [480, 245],
        branches: [
          {
            target: "leftCup",
            gate: "leftGate",
            overflowFrom: "reservoir",
            via: [
              [335, 245],
              [335, 307.5],
              [280, 307.5],
            ],
          },
          {
            target: "middleCup",
            gate: "middleGate",
            overflowFrom: "reservoir",
            via: [[480, 342.5]],
          },
          {
            target: "rightCup",
            gate: "rightGate",
            overflowFrom: "reservoir",
            via: [
              [625, 245],
              [625, 307.5],
              [680, 307.5],
            ],
          },
        ],
      },
    },
  },
  {
    targets: [
      t(
        "nameTag",
        "Carve a hole in the guest's frozen name tag",
        "melt",
        385,
        240,
        190,
        90,
      ),
      t(
        "welcomeBowl",
        "Fill the active welcome bowl through the opening",
        "fill",
        400,
        425,
        140,
        70,
      ),
      warm(
        "welcomeSeal",
        "Warm the label's separate welcome seal",
        650,
        400,
        [25, 45],
        [10, 35],
        ["nameTag", "welcomeBowl"],
      ),
    ],
    props: [
      p("guesthearttag", 480, 325, "welcomeSeal", { scale: 1 }),
      p("guestcoat", 735, 340, undefined, { scale: 1 }),
      vessel("hotelbowl", 400, 425, "welcomeBowl"),
    ],
    cast: [between(), yesterday()],
    stamp: "NAME: GUEST. SPECIAL REQUIREMENTS: A LITTLE HEART.",
    extra: { start: [480, 188], par: 210 },
  },
  {
    targets: [
      t(
        "chairBadge",
        "Thaw the receptionist's tiny chair badge",
        "melt",
        275,
        210,
        110,
        90,
      ),
      t(
        "tea",
        "Fill Ms Between's own break-time tea",
        "fill",
        420,
        335,
        140,
        70,
      ),
      warm(
        "readingLamp",
        "Warm her diagonal reading-lamp station",
        640,
        425,
        [30, 45],
      ),
      t(
        "privacySign",
        "Turn the off-duty privacy sign",
        "spin",
        650,
        205,
        110,
        100,
        { requires: ["chairBadge", "tea", "readingLamp"] },
      ),
    ],
    props: [
      p("nightdesk", 465, 430, undefined, { scale: 1 }),
      cup(420, 335, "tea"),
    ],
    cast: [],
    stamp: "SIX ARMS. ZERO TASKS. COVERED BY YESTERDAY.",
    extra: { start: [330, 158], par: 220 },
  },
  {
    targets: [
      t(
        "cloudPerch",
        "Build the returning cloud's remembered perch",
        "freeze",
        260,
        200,
        120,
        65,
      ),
      warm(
        "planetLamp",
        "Warm the returning planet's familiar lamp",
        430,
        190,
        [40, 60],
      ),
      t(
        "ghostClasp",
        "Thaw the returning ghost's blanket clasp",
        "melt",
        650,
        200,
        100,
        80,
      ),
      t(
        "firstRefreshment",
        "Fill the first shared welcome refreshment",
        "fill",
        330,
        430,
        140,
        70,
        { requires: ["cloudPerch", "planetLamp", "ghostClasp"] },
      ),
      t(
        "secondRefreshment",
        "Fill the second shared welcome refreshment",
        "fill",
        545,
        430,
        140,
        70,
        { requires: ["cloudPerch", "planetLamp", "ghostClasp"] },
      ),
    ],
    props: [
      p("returningkeys", 485, 380, undefined, { scale: 1 }),
      cup(330, 430, "firstRefreshment"),
      cup(545, 430, "secondRefreshment"),
    ],
    cast: [between()],
    stamp: "RIGHT ROOMS. NO LIST. EVERYONE REMEMBERS YESTERDAY.",
    extra: { start: [320, 148], temp: -20, par: 245 },
  },
  {
    targets: [
      t(
        "routeBoard",
        "Thaw the shared departure route board",
        "melt",
        330,
        155,
        270,
        90,
      ),
      t(
        "leftBase",
        "Build the first lounge lantern base",
        "freeze",
        220,
        460,
        100,
        55,
      ),
      t(
        "rightBase",
        "Build the second lounge lantern base",
        "freeze",
        735,
        460,
        100,
        55,
      ),
      t(
        "leftTea",
        "Fill the first farewell tea cup",
        "fill",
        355,
        425,
        140,
        70,
        { requires: ["routeBoard", "leftBase", "rightBase"] },
      ),
      t(
        "rightTea",
        "Fill the second farewell tea cup",
        "fill",
        520,
        425,
        140,
        70,
        { requires: ["routeBoard", "leftBase", "rightBase"] },
      ),
      warm(
        "loungeBeacon",
        "Warm the lounge beacon before departures",
        680,
        330,
        [30, 50],
        [10, 35],
        ["leftTea", "rightTea"],
      ),
      t(
        "departureBell",
        "Ring the final shared departure bell",
        "spin",
        435,
        300,
        110,
        100,
        { requires: ["loungeBeacon"] },
      ),
    ],
    props: [
      p("hotelrouteboard", 465, 240, "routeBoard", { scale: 1 }),
      p("hotelpanorama", 480, 410, undefined, { scale: 0.9 }),
      cup(355, 425, "leftTea"),
      cup(520, 425, "rightTea"),
      p("alwayscard", 800, 260, "departureBell", {
        scale: 0.7,
        revealOnly: true,
      }),
    ],
    cast: [],
    stamp: "ALWAYS WELCOME. YES, EVEN ON WEDNESDAYS.",
    extra: { start: [465, 103], par: 320 },
  },
];

const dispatches = [
  "The welcome is ready. Its bell is not. Thaw, ring, and warm the separate seal; Yesterday is bringing the mat.",
  "Monday has one pleasant minute. Open the curtain, fill the vase, and give that minute a bedside lamp.",
  "This pillow woke up before its guest and resents the promotion. Prepare its snowbank and blanket before bedtime.",
  "Fill both umbrella basins before handling the luggage tag. The cloud has packed weather for every occasion.",
  "One sleepy sun, one wide-awake moon. Open the hatch, prepare both drinks, then mind their different breakfast stations.",
  "The staircase has earned a holiday. Build three temporary steps before releasing and servicing the luggage trolley.",
  "A conservatory has checked in as luggage. Open its latch; the separate water tank and plant bed can come in either order.",
  "Both bedside stands are frozen. Prepare the alarm and tea independently before trying the planet's gentle sunrise badge.",
  "Rill and Moss have two climates and one breakfast nook. Prepare both welcomes before filling their shared-view cups.",
  "Prepare the bell, mat racks, and milk badge in any order. The last wheel turns a quiet sign. Very important distinction.",
  "Three parcels have taken the scenic route upstairs. Open every wrapper before drawing the bath and warming the towel badge.",
  "Build both balcony platforms, clear the timetable, and service the departure seal. The train is happy to wait for curtain questions.",
  "One cabin, three moving windows. Thaw them all before warming its traveling badge; stationary assist keeps the same fish and goals.",
  "Two cool slipper forms and two sunny badges need separate care. Their owners would like one shared bowl and a long conversation.",
  "Yesterday's guest is from next Tuesday. Follow the card, seal, cup, and date stamp; refreshments are safely in chronological order.",
  "Clear all three channel gates, then fill the upper reservoir. Keep feeding it: only actual tributary water delivers room service.",
  "A blank tag is not a booking problem. Carve a pour-through opening above the active bowl, then finish the tag and welcome seal.",
  "Prepare Ms Between's chair, cup, and lamp in any order, then turn the privacy sign. Yesterday already knows where the desk is.",
  "The cloud, planet, and ghost have familiar preferences. Prepare their three stations before pouring the shared refreshments.",
  "Thaw the route board and build both lantern bases. Tea, a warm beacon, and the departure bell leave nobody unwaved-to.",
];

const source = designs.packs.find((pack) => pack.id === "19")!;
export const hotelLevels: Level[] = source.scenes.map((card, index) => {
  const recipe = recipes[index];
  return {
    id: card.id,
    pack: "19",
    name: card.title,
    chapter: source.title,
    theme: "hotel",
    pitch: dispatches[index],
    hint: card.puzzle,
    ending: card.payoff,
    start: [480, 150],
    temp: 40,
    pressure: 40,
    par: 90 + recipe.targets.length * 25,
    targets: recipe.targets,
    props: [...recipe.props, ...(recipe.cast ?? [between(), yesterday()])],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
