import type { Level, Target, Prop, PropKind, Verb } from "../types";
import designs from "../../docs/campaign/20.json" with { type: "json" };

const t = (
  id: string,
  name: string,
  verb: Verb,
  x: number,
  y: number,
  w = 100,
  h = 60,
  extra: Partial<Target> = {},
): Target => ({ id, name, verb, x, y, w, h, ...extra });
const warm = (
  id: string,
  name: string,
  x: number,
  y: number,
  temp: [number, number],
  pressure: [number, number] = [10, 35],
  requires: string[] = [],
  extra: Partial<Target> = {},
) => t(id, name, "warm", x, y, 120, 65, { temp, pressure, requires, ...extra });
const p = (
  kind: PropKind,
  x: number,
  y: number,
  target?: string,
  extra: Partial<Prop> = {},
): Prop => ({ kind, x, y, target, scale: 1, ...extra });
const pigeon = () => p("festivalpigeon", 135, 335, undefined, { scale: 0.85 });
const vessel = (
  kind: "festivalcup" | "festivalbasin" | "festivalvase",
  x: number,
  y: number,
  target: string,
  scale = 1,
) => p(kind, x + 70 * scale, y + 52.5 * scale, target, { scale });
type Recipe = {
  targets: Target[];
  props: Prop[];
  cast?: Prop[];
  stamp: string;
  extra?: Partial<Level>;
};
const recipes: Recipe[] = [
  {
    targets: [
      t(
        "welcomeSign",
        "Thaw the wizard's left-hand welcome sign",
        "melt",
        235,
        230,
        150,
        100,
      ),
      t(
        "squadCup",
        "Fill the original smiling teacup",
        "fill",
        430,
        365,
        140,
        70,
        { requires: ["welcomeSign"] },
      ),
      warm(
        "heartLamp",
        "Warm Cupid's right-hand welcome lamp",
        660,
        350,
        [25, 45],
        [10, 40],
        ["squadCup"],
      ),
    ],
    props: [
      p("firstwelcome", 480, 390),
      vessel("festivalcup", 430, 365, "squadCup"),
    ],
    cast: [],
    stamp: "FIRST CUP: THE VOLUNTEER. BOOTS: RIGHT WAY UP.",
    extra: { start: [310, 178], par: 185 },
  },
  {
    targets: [
      t(
        "leftClip",
        "Thaw the arch's high left sock clip",
        "melt",
        275,
        200,
        70,
        60,
      ),
      t(
        "topClip",
        "Thaw the arch's highest mismatched clip",
        "melt",
        445,
        145,
        70,
        60,
      ),
      t("rightClip", "Thaw the high right sock clip", "melt", 615, 205, 70, 60),
      t(
        "leftAttachment",
        "Build the low left bunting attachment",
        "freeze",
        235,
        445,
        100,
        55,
        { requires: ["leftClip", "topClip", "rightClip"] },
      ),
      t(
        "rightAttachment",
        "Build the low right bunting attachment",
        "freeze",
        650,
        445,
        100,
        55,
        { requires: ["leftClip", "topClip", "rightClip"] },
      ),
      t(
        "hangingCrank",
        "Turn the stationary sock-hanging crank",
        "spin",
        430,
        350,
        120,
        100,
        { requires: ["leftAttachment", "rightAttachment"] },
      ),
    ],
    props: [p("sockarch", 480, 425)],
    stamp: "ODD SOCKS, EXCELLENT PARTNERS. MATCHING NOT REQUIRED.",
    extra: { start: [310, 148], par: 270 },
  },
  {
    targets: [
      t(
        "topStamp",
        "Fill the top of the postage triangle",
        "fill",
        420,
        200,
        140,
        70,
      ),
      t(
        "leftStamp",
        "Fill the lower-left stamp basin",
        "fill",
        270,
        385,
        140,
        70,
      ),
      t(
        "rightStamp",
        "Fill the lower-right stamp basin",
        "fill",
        580,
        385,
        140,
        70,
      ),
      t(
        "addressBoard",
        "Thaw the postal cart's address board",
        "melt",
        610,
        200,
        150,
        90,
        { requires: ["topStamp", "leftStamp", "rightStamp"] },
      ),
      warm(
        "postageSeal",
        "Warm the shared waterproof postage seal",
        435,
        430,
        [30, 50],
        [10, 35],
        ["addressBoard"],
      ),
    ],
    props: [
      p("postaltriangle", 485, 350),
      vessel("festivalbasin", 420, 200, "topStamp"),
      vessel("festivalbasin", 270, 385, "leftStamp"),
      vessel("festivalbasin", 580, 385, "rightStamp"),
    ],
    stamp: "DEAR PUDDLE: YOUR PRESENCE IS REQUESTED. UMBRELLA ENCLOSED.",
    extra: { start: [490, 148], temp: 20, par: 245 },
  },
  {
    targets: [
      t(
        "leftWheelCap",
        "Thaw the queue's left wheel cap",
        "melt",
        260,
        205,
        130,
        105,
      ),
      t(
        "rightWheelCap",
        "Thaw the queue's right wheel cap",
        "melt",
        570,
        205,
        130,
        105,
      ),
      t(
        "leftPedestal",
        "Build the separated left waiting pedestal",
        "freeze",
        260,
        445,
        100,
        55,
        { requires: ["leftWheelCap", "rightWheelCap"] },
      ),
      t(
        "middlePedestal",
        "Build the slightly raised middle pedestal",
        "freeze",
        430,
        405,
        100,
        55,
        { requires: ["leftWheelCap", "rightWheelCap"] },
      ),
      t(
        "rightPedestal",
        "Build the separated right waiting pedestal",
        "freeze",
        600,
        445,
        100,
        55,
        { requires: ["leftWheelCap", "rightWheelCap"] },
      ),
      t(
        "leftHub",
        "Turn the exposed left queue turbine",
        "spin",
        275,
        220,
        100,
        85,
        {
          requires: [
            "leftWheelCap",
            "rightWheelCap",
            "leftPedestal",
            "middlePedestal",
            "rightPedestal",
          ],
        },
      ),
      t(
        "rightHub",
        "Turn the exposed right queue turbine",
        "spin",
        585,
        220,
        100,
        85,
        {
          requires: [
            "leftWheelCap",
            "rightWheelCap",
            "leftPedestal",
            "middlePedestal",
            "rightPedestal",
          ],
        },
      ),
    ],
    props: [p("circusqueue", 480, 360)],
    stamp: "MOST CONSIDERATE INTERVAL. THE QUEUE APPLAUDS THE QUEUE.",
    extra: { start: [325, 153], par: 310 },
  },
  {
    targets: [
      t(
        "leftForm",
        "Thaw the narrow left permission form",
        "melt",
        250,
        245,
        50,
        100,
      ),
      t(
        "upperLeftForm",
        "Thaw the upper-left delight application",
        "melt",
        355,
        155,
        50,
        100,
      ),
      t(
        "upperRightForm",
        "Thaw the upper-right enjoyment supplement",
        "melt",
        565,
        155,
        50,
        100,
      ),
      t(
        "rightForm",
        "Thaw the narrow right volunteer footnote",
        "melt",
        720,
        245,
        50,
        100,
      ),
      warm(
        "welcomeInk",
        "Warm the separate welcoming ink station",
        300,
        430,
        [25, 45],
        [10, 35],
        ["leftForm", "upperLeftForm", "upperRightForm", "rightForm"],
      ),
      t(
        "stampRinse",
        "Fill the independent stamp-rinse basin",
        "fill",
        570,
        425,
        140,
        70,
        {
          requires: [
            "leftForm",
            "upperLeftForm",
            "upperRightForm",
            "rightForm",
          ],
        },
      ),
      t(
        "approval",
        "Turn the large final approval stamp",
        "spin",
        425,
        295,
        120,
        100,
        { requires: ["welcomeInk", "stampRinse"] },
      ),
    ],
    props: [
      p("delightpermit", 480, 355),
      vessel("festivalbasin", 570, 425, "stampRinse"),
    ],
    stamp: "EVERYONE MAY HAVE A NICE TIME. YES, VOLUNTEERS TOO.",
    extra: { start: [275, 193], par: 290 },
  },
  {
    targets: [
      t(
        "biscuitTray",
        "Thaw the buffet's broad biscuit tray",
        "melt",
        240,
        205,
        240,
        85,
      ),
      t(
        "dessertMould",
        "Build the narrow icy dessert mould",
        "freeze",
        600,
        180,
        70,
        75,
      ),
      warm(
        "custardBadge",
        "Warm the independent custard station",
        675,
        340,
        [30, 45],
      ),
      t(
        "firstBowl",
        "Fill the first shared serving bowl",
        "fill",
        355,
        430,
        140,
        70,
        { requires: ["biscuitTray", "dessertMould", "custardBadge"] },
      ),
      t(
        "secondBowl",
        "Fill the second shared serving bowl",
        "fill",
        535,
        430,
        140,
        70,
        { requires: ["biscuitTray", "dessertMould", "custardBadge"] },
      ),
    ],
    props: [
      p("dessertcitizens", 480, 365),
      vessel("festivalbasin", 355, 430, "firstBowl"),
      vessel("festivalbasin", 535, 430, "secondBowl"),
    ],
    stamp: "SOUP: STILL SOUP. CITIZENSHIP: HONORARILY DESSERT.",
    extra: { start: [360, 153], par: 240 },
  },
  {
    targets: [
      t(
        "leftPlayPad",
        "Build the far-left tail-room play pad",
        "freeze",
        235,
        455,
        110,
        55,
      ),
      t(
        "rightPlayPad",
        "Build the far-right tail-room play pad",
        "freeze",
        685,
        455,
        110,
        55,
      ),
      t(
        "leftToyChest",
        "Thaw the left toy-chest cap",
        "melt",
        300,
        270,
        100,
        95,
        { requires: ["leftPlayPad", "rightPlayPad"] },
      ),
      t(
        "upperToyChest",
        "Thaw the higher middle toy-chest cap",
        "melt",
        445,
        205,
        100,
        95,
        { requires: ["leftPlayPad", "rightPlayPad"] },
      ),
      t(
        "rightToyChest",
        "Thaw the right toy-chest cap",
        "melt",
        590,
        270,
        100,
        95,
        { requires: ["leftPlayPad", "rightPlayPad"] },
      ),
      warm(
        "welcomeSun",
        "Warm the playground's welcome sun badge",
        440,
        430,
        [25, 45],
        [10, 35],
        ["leftToyChest", "upperToyChest", "rightToyChest"],
      ),
    ],
    props: [p("tailroom", 480, 400)],
    stamp: "TAIL ROOM IS NOW A NEIGHBORHOOD. NO APOLOGY NECESSARY.",
    extra: { start: [290, 403], temp: -20, par: 270 },
  },
  {
    targets: [
      t(
        "lowCounterCap",
        "Thaw the low wyvern service cap",
        "melt",
        265,
        345,
        110,
        85,
      ),
      t(
        "middleCounterCap",
        "Thaw the medium dragon service cap",
        "melt",
        435,
        255,
        110,
        85,
      ),
      t(
        "highCounterCap",
        "Thaw the high giant-dragon sign",
        "melt",
        645,
        165,
        110,
        85,
      ),
      t("lowBase", "Build the low counter base", "freeze", 285, 455, 120, 55, {
        requires: ["lowCounterCap", "middleCounterCap", "highCounterCap"],
      }),
      t(
        "highBase",
        "Build the contrasting high counter base",
        "freeze",
        630,
        350,
        120,
        55,
        { requires: ["lowCounterCap", "middleCounterCap", "highCounterCap"] },
      ),
      warm(
        "flintWelcome",
        "Warm Flint's shared welcome badge",
        450,
        430,
        [30, 50],
        [10, 35],
        ["lowBase", "highBase"],
      ),
    ],
    props: [p("flintcounter", 480, 420)],
    stamp: "NOBODY CROUCHES. NOBODY HAS TO ASK FOR A STOOL.",
    extra: { start: [320, 293], par: 270 },
  },
  {
    targets: [
      t(
        "leftBookCap",
        "Thaw the left reading stand's book cap",
        "melt",
        260,
        205,
        120,
        100,
      ),
      t(
        "rightBookCap",
        "Thaw the right reading stand's book cap",
        "melt",
        600,
        205,
        120,
        100,
      ),
      t(
        "middleFooting",
        "Build the independent middle nest footing",
        "freeze",
        430,
        450,
        110,
        45,
      ),
      t(
        "leftNest",
        "Build only the left book's outer nest section",
        "freeze",
        245,
        420,
        120,
        70,
        { requires: ["leftBookCap"] },
      ),
      t(
        "rightNest",
        "Build only the right book's outer nest section",
        "freeze",
        615,
        420,
        120,
        70,
        { requires: ["rightBookCap"] },
      ),
      warm(
        "readingLamp",
        "Warm the shared quiet reading lamp",
        440,
        265,
        [25, 40],
        [10, 30],
        ["middleFooting", "leftNest", "rightNest"],
      ),
    ],
    props: [p("endingnest", 480, 385)],
    stamp: "STAY AS LONG AS YOU LIKE. ENDY HAS THE LAST WORD.",
    extra: { start: [320, 153], par: 265 },
  },
  {
    targets: [
      t(
        "participationBanner",
        "Thaw the shared participation banner",
        "melt",
        320,
        160,
        320,
        90,
      ),
      warm(
        "firstMedal",
        "Warm the first equally high medal station",
        245,
        335,
        [20, 35],
        [10, 35],
        ["participationBanner"],
      ),
      warm(
        "middleMedal",
        "Warm the middle equally high medal station",
        425,
        335,
        [35, 50],
        [10, 35],
        ["participationBanner"],
      ),
      warm(
        "lastMedal",
        "Warm the last equally high medal station",
        605,
        335,
        [50, 65],
        [10, 35],
        ["participationBanner"],
      ),
      t(
        "applause",
        "Turn the shared participation applause wheel",
        "spin",
        735,
        430,
        110,
        100,
        { requires: ["firstMedal", "middleMedal", "lastMedal"] },
      ),
    ],
    props: [p("tryingpodium", 480, 415)],
    cast: [],
    stamp: "ONE MEDAL FOR JOINING IN. ONE FOR MAKING ROOM.",
    extra: { start: [480, 108], par: 255 },
  },
  {
    targets: [
      t(
        "leftFloor",
        "Build the first independent dance-floor section",
        "freeze",
        245,
        435,
        140,
        60,
      ),
      t(
        "rightFloor",
        "Build the second independent dance-floor section",
        "freeze",
        575,
        435,
        140,
        60,
      ),
      t(
        "musicCap",
        "Thaw the band's shared music stand",
        "melt",
        425,
        170,
        130,
        100,
      ),
      t(
        "bandWheel",
        "Turn the band wheel after the floor is ready",
        "spin",
        435,
        285,
        110,
        100,
        { requires: ["leftFloor", "rightFloor", "musicCap"] },
      ),
      t(
        "smallCup",
        "Fill the small dancer's independent refreshment",
        "fill",
        275,
        295,
        98,
        49,
      ),
      t(
        "largeCup",
        "Fill the larger independent refreshment cup",
        "fill",
        610,
        295,
        140,
        70,
      ),
      warm(
        "welcomeHeart",
        "Warm the shared dance-floor welcome heart",
        445,
        425,
        [25, 45],
        [10, 35],
        ["bandWheel", "smallCup", "largeCup"],
      ),
    ],
    props: [
      p("everypairdance", 480, 395),
      vessel("festivalcup", 275, 295, "smallCup", 0.7),
      vessel("festivalcup", 610, 295, "largeCup"),
    ],
    cast: [],
    stamp: "PAIRS WELCOME. SOLOS WELCOME. SITTING THIS ONE OUT WELCOME.",
    extra: { start: [315, 383], temp: -20, par: 315 },
  },
  {
    targets: [
      t(
        "tentSign",
        "Thaw the quiet tent's welcome sign",
        "melt",
        370,
        160,
        240,
        80,
      ),
      t(
        "leftLanternFoot",
        "Build the quiet tent's left lantern footing",
        "freeze",
        250,
        440,
        100,
        55,
      ),
      t(
        "rightLanternFoot",
        "Build the quiet tent's right lantern footing",
        "freeze",
        675,
        440,
        100,
        55,
      ),
      warm(
        "firstRepair",
        "Warm the first soft dream-repair badge",
        280,
        350,
        [20, 35],
        [10, 30],
        ["tentSign", "leftLanternFoot", "rightLanternFoot"],
      ),
      warm(
        "middleRepair",
        "Warm the middle soft dream-repair badge",
        440,
        350,
        [20, 35],
        [10, 30],
        ["tentSign", "leftLanternFoot", "rightLanternFoot"],
      ),
      warm(
        "lastRepair",
        "Warm the last soft dream-repair badge",
        600,
        350,
        [20, 35],
        [10, 30],
        ["tentSign", "leftLanternFoot", "rightLanternFoot"],
      ),
    ],
    props: [p("quietdreamtent", 480, 415)],
    cast: [],
    stamp: "A BREAK IS PART OF THE JOB. THE FOREST WILL KEEP WATCH.",
    extra: { start: [490, 108], par: 275 },
  },
  {
    targets: [
      t(
        "lowSnow",
        "Build the snow garden's lower footprint",
        "freeze",
        220,
        430,
        100,
        55,
      ),
      t(
        "middleSnow",
        "Build its separate middle snow footprint",
        "freeze",
        325,
        365,
        90,
        55,
      ),
      t(
        "highSnow",
        "Build the high snow-garden footprint",
        "freeze",
        230,
        280,
        90,
        55,
      ),
      warm(
        "sunBadge",
        "Warm the independent sunny picnic awning",
        640,
        270,
        [50, 70],
      ),
      t(
        "welcomeBasin",
        "Fill the welcome basin between both climates",
        "fill",
        440,
        415,
        140,
        70,
        { requires: ["lowSnow", "middleSnow", "highSnow", "sunBadge"] },
      ),
    ],
    props: [
      p("twoweatherpicnic", 510, 390),
      vessel("festivalbasin", 440, 415, "welcomeBasin"),
    ],
    stamp: "CHOOSE YOUR WEATHER. WAVE TO THE OTHER PICNIC.",
    extra: { start: [270, 378], temp: -20, par: 245 },
  },
  {
    targets: [
      t(
        "firstPlatform",
        "Build the railway's first extra-stop platform",
        "freeze",
        230,
        445,
        100,
        55,
      ),
      t(
        "middlePlatform",
        "Build the railway's separate middle platform",
        "freeze",
        430,
        445,
        100,
        55,
      ),
      t(
        "lastPlatform",
        "Build the railway's last extra-stop platform",
        "freeze",
        630,
        445,
        100,
        55,
      ),
      t(
        "timetable",
        "Thaw the expanded goodbye timetable",
        "melt",
        650,
        180,
        140,
        95,
        { requires: ["firstPlatform", "middlePlatform", "lastPlatform"] },
      ),
      t(
        "departure",
        "Turn the stationary departure turbine",
        "spin",
        270,
        245,
        120,
        100,
        { requires: ["timetable"] },
      ),
      warm(
        "conductorLantern",
        "Gently warm the final conductor's lantern",
        450,
        300,
        [30, 45],
        [10, 35],
        ["departure"],
      ),
    ],
    props: [p("extrastoptrain", 480, 395)],
    stamp: "ONE MORE GOODBYE IS AN OFFICIAL STOP. WINDOW SEAT SAVED.",
    extra: { start: [280, 393], temp: -20, par: 275 },
  },
  {
    targets: [
      t(
        "questionTop",
        "Thaw the question mark's broad upper section",
        "melt",
        350,
        155,
        220,
        90,
      ),
      t(
        "questionStem",
        "Thaw its offset middle ice section",
        "melt",
        490,
        265,
        80,
        85,
      ),
      t(
        "questionDot",
        "Thaw the question mark's separate final dot",
        "melt",
        460,
        390,
        60,
        60,
      ),
      t(
        "firstDemonstration",
        "Fill the first demonstration basin",
        "fill",
        250,
        420,
        140,
        70,
        { requires: ["questionTop", "questionStem", "questionDot"] },
      ),
      t(
        "secondDemonstration",
        "Fill the second demonstration basin",
        "fill",
        620,
        420,
        140,
        70,
        { requires: ["questionTop", "questionStem", "questionDot"] },
      ),
      warm(
        "curiosityLamp",
        "Warm the little lamp that kept asking",
        465,
        475,
        [25, 45],
        [10, 35],
        ["firstDemonstration", "secondDemonstration"],
        { w: 80, h: 50 },
      ),
    ],
    props: [
      p("firstsketchexhibit", 480, 350),
      vessel("festivalbasin", 250, 420, "firstDemonstration"),
      vessel("festivalbasin", 620, 420, "secondDemonstration"),
    ],
    stamp: "FIRST MESSY SKETCH. EXHIBIT OF UNFINISHED CERTAINTY.",
    extra: { start: [460, 103], par: 270 },
  },
  {
    targets: [
      t(
        "leftDispenser",
        "Thaw the tall left coffee-dispenser cap",
        "melt",
        260,
        175,
        120,
        170,
      ),
      t(
        "rightDispenser",
        "Thaw the tall right coffee-dispenser cap",
        "melt",
        580,
        175,
        120,
        170,
      ),
      t(
        "firstCrewCup",
        "Fill the first cook's coffee cup",
        "fill",
        270,
        385,
        140,
        70,
        { requires: ["leftDispenser", "rightDispenser"] },
      ),
      t(
        "secondCrewCup",
        "Fill the second cook's coffee cup",
        "fill",
        585,
        385,
        140,
        70,
        { requires: ["leftDispenser", "rightDispenser"] },
      ),
      warm(
        "crewToast",
        "Gently warm the crew's low toast station",
        445,
        445,
        [30, 45],
        [10, 35],
        ["firstCrewCup", "secondCrewCup"],
      ),
      t(
        "servingBell",
        "Move right to ring the separate serving bell",
        "spin",
        765,
        325,
        110,
        100,
        { requires: ["crewToast"] },
      ),
    ],
    props: [
      p("crewbreakfast", 480, 370),
      vessel("festivalcup", 270, 385, "firstCrewCup"),
      vessel("festivalcup", 585, 385, "secondCrewCup"),
    ],
    cast: [],
    stamp: "THE CREW IS EATING. THE CLIPBOARD IS NOT AT THE TABLE.",
    extra: { start: [320, 123], par: 280 },
  },
  {
    targets: [
      t(
        "leftPennant",
        "Thaw the toy float's left pennant block",
        "melt",
        280,
        190,
        110,
        110,
      ),
      t(
        "rightPennant",
        "Thaw the toy float's right pennant block",
        "melt",
        600,
        190,
        110,
        110,
      ),
      t(
        "leftDecoration",
        "Build the left wheel-decoration form",
        "freeze",
        260,
        440,
        110,
        60,
      ),
      t(
        "rightDecoration",
        "Build the right wheel-decoration form",
        "freeze",
        655,
        440,
        110,
        60,
      ),
      warm(
        "glimLamp",
        "Warm Glim's little leading lamp",
        440,
        260,
        [35, 55],
        [10, 35],
        ["leftPennant", "rightPennant", "leftDecoration", "rightDecoration"],
      ),
      t(
        "departureAxle",
        "Turn the float's stationary departure axle",
        "spin",
        435,
        405,
        120,
        100,
        { requires: ["glimLamp"] },
      ),
    ],
    props: [p("toyparade", 480, 390)],
    stamp: "THE PARADE IS TINY. THE WELCOME KNEELS DOWN.",
    extra: { start: [335, 138], par: 275 },
  },
  {
    targets: [
      t(
        "tomorrowSign",
        "Thaw Ann's Tomorrow flower-delivery sign",
        "melt",
        350,
        155,
        270,
        95,
      ),
      t(
        "leftFlowers",
        "Fill the first flower basin",
        "fill",
        320,
        380,
        140,
        70,
        { requires: ["tomorrowSign"] },
      ),
      t(
        "rightFlowers",
        "Fill the second flower basin",
        "fill",
        520,
        380,
        140,
        70,
        { requires: ["tomorrowSign"] },
      ),
      warm(
        "eveningLantern",
        "Warm the end-of-day flower lantern",
        700,
        330,
        [30, 50],
        [10, 35],
        ["leftFlowers", "rightFlowers"],
      ),
      t(
        "leftDisplayFoot",
        "Build the independent left display foot",
        "freeze",
        250,
        470,
        100,
        55,
      ),
      t(
        "rightDisplayFoot",
        "Build the independent right display foot",
        "freeze",
        660,
        470,
        100,
        55,
      ),
      t(
        "flowerChime",
        "Turn the chime after lantern and feet are ready",
        "spin",
        445,
        280,
        120,
        85,
        { requires: ["eveningLantern", "leftDisplayFoot", "rightDisplayFoot"] },
      ),
    ],
    props: [
      p("tomorrowflowers", 480, 345),
      vessel("festivalvase", 320, 380, "leftFlowers"),
      vessel("festivalvase", 520, 380, "rightFlowers"),
    ],
    stamp: "EMERGENCY FOLDER RETIRED. PHOTO ALBUM NOW IN SERVICE.",
    extra: { start: [485, 103], par: 295 },
  },
  {
    targets: [
      t(
        "leftLanternBase",
        "Build the volunteer room's left lantern base",
        "freeze",
        260,
        450,
        100,
        55,
      ),
      t(
        "rightLanternBase",
        "Build the volunteer room's right lantern base",
        "freeze",
        640,
        450,
        100,
        55,
      ),
      t(
        "pillowBadge",
        "Thaw the independently prepared pillow badge",
        "melt",
        400,
        195,
        160,
        110,
      ),
      t(
        "roomTea",
        "Fill the coordinator's own guest-room tea",
        "fill",
        440,
        395,
        140,
        70,
        { requires: ["leftLanternBase", "rightLanternBase", "pillowBadge"] },
      ),
      warm(
        "bedsideGlow",
        "Warm the quiet room's separate bedside glow",
        625,
        280,
        [25, 40],
        [10, 30],
        ["roomTea"],
      ),
    ],
    props: [
      p("volunteerroom", 480, 385),
      vessel("festivalcup", 440, 395, "roomTea"),
    ],
    cast: [],
    stamp: "ROOM RESERVED FOR THE PERSON WHO REMEMBERED EVERYONE.",
    extra: { start: [310, 398], temp: -20, par: 245 },
  },
  {
    targets: [
      t(
        "leftPennant",
        "Thaw the first shared welcome pennant",
        "melt",
        305,
        175,
        100,
        100,
      ),
      t(
        "rightPennant",
        "Thaw the second shared welcome pennant",
        "melt",
        560,
        175,
        100,
        100,
      ),
      t(
        "leftBase",
        "Build the first festival ice-lantern base",
        "freeze",
        250,
        450,
        100,
        55,
      ),
      t(
        "rightBase",
        "Build the second festival ice-lantern base",
        "freeze",
        675,
        450,
        100,
        55,
      ),
      t(
        "sharedBasin",
        "Fill the basin after all four preparations",
        "fill",
        410,
        410,
        140,
        70,
        { requires: ["leftPennant", "rightPennant", "leftBase", "rightBase"] },
      ),
      warm(
        "heart",
        "Warm the heart of the shared welcome",
        435,
        300,
        [30, 50],
        [10, 35],
        ["sharedBasin"],
      ),
      t(
        "celebration",
        "Turn the final celebration turbine",
        "spin",
        750,
        280,
        110,
        100,
        { requires: ["heart"] },
      ),
    ],
    props: [
      p("festivalpanorama", 480, 400),
      vessel("festivalbasin", 410, 410, "sharedBasin"),
    ],
    cast: [],
    stamp: "GLAD YOU CAME. YOUR PLACE WAS PART OF THE PLAN.",
    extra: { start: [355, 123], par: 330 },
  },
];

const dispatches = [
  "Three old friends, one new square. Open the welcome sign, fill the original cup, and warm the heart to the right.",
  "Three high clips need thawing before the two low attachments. The hanging crank knows absolutely nothing about matching socks.",
  "Brine & Parcel arranged its stamp basins in a triangle. Fill them all before clearing the address board and warming the seal.",
  "Clear both wheel caps and build all three waiting pedestals. The exposed hubs will then begin the queue's performance review.",
  "Four small forms surround one very welcoming stamp. Their warm ink and rinse basin are separate preparations for approval.",
  "Biscuits, an icy mould, and custard can prepare independently. The two shared serving bowls are awaiting new citizens.",
  "Build both distant play pads before opening the three toy chests. The welcome sun should leave plenty of room for a happy tail.",
  "Three frozen service heights, two very different bases. Flint's welcome badge is waiting until nobody needs to ask for a stool.",
  "Each thawed book opens only its own outer nest section. The middle footing can start now; all three support the reading lamp.",
  "One banner, three different warm-ups, no taller podium. The applause wheel waits until every medal is comfortable.",
  "Prepare the floor and music for the band wheel. The two cups can fill independently; band and refreshments together unlock the heart.",
  "Prepare the sign and both lantern feet before warming the three repair badges. The crowd has kindly agreed not to be a mechanic.",
  "The snowy footprints and sunny badge are separate neighbors. Prepare both climates before filling the basin between their picnics.",
  "Build three platforms, clear the timetable, and service the departure turbine. Finish gently with the conductor's lantern.",
  "Three pieces of frozen question mark, two demonstration basins, one small curiosity lamp. Dr. Probably has kept the first sketch.",
  "Open both tall dispensers and fill both crew cups. Warm the toast, then move over to ring the serving bell; the cooks are sitting down.",
  "Prepare both pennants and wheel decorations in any order. Glim's lamp comes next, then the axle of a very small, very visible parade.",
  "Thaw Tomorrow, fill the flower basins, and warm the evening lantern. The two display feet can be built independently before the chime.",
  "Both lantern bases and the pillow can be prepared in parallel. Then pour the volunteer's tea and warm a room that asks nothing in return.",
  "Thaw both pennants and build both lantern bases in any order. Fill the basin, warm the heart, and turn the final celebration wheel.",
];

const source = designs.packs.find((pack) => pack.id === "20")!;
export const festivalLevels: Level[] = source.scenes.map((card, index) => {
  const recipe = recipes[index];
  return {
    id: card.id,
    pack: "20",
    name: card.title,
    chapter: source.title,
    theme: "festival",
    pitch: dispatches[index],
    hint: card.puzzle,
    ending: card.payoff,
    start: [480, 150],
    temp: 40,
    pressure: 40,
    par: 90 + recipe.targets.length * 25,
    targets: recipe.targets,
    props: [...recipe.props, ...(recipe.cast ?? [pigeon()])],
    stamp: recipe.stamp,
    ...recipe.extra,
  };
});
