import type { BalancePlan } from "./mechanics/balance";
import type { OpticsPlan } from "./mechanics/optics";
import type { FlowBranch } from "./mechanics/flow";
import type { BuoyancyPlan } from "./mechanics/buoyancy";

export type Verb = "melt" | "freeze" | "warm" | "fill" | "spin";
export type Theme =
  | "kitchen"
  | "cave"
  | "garden"
  | "cosmos"
  | "town"
  | "laundry"
  | "reef"
  | "circus"
  | "borough"
  | "pudding"
  | "preschool"
  | "emberborough"
  | "library"
  | "sports"
  | "wedding"
  | "seamworks"
  | "conservatory"
  | "mycelium"
  | "institute"
  | "diner"
  | "toybox"
  | "apocalypse"
  | "hotel";
export type PropKind =
  | "cup"
  | "wizard"
  | "heart"
  | "penguin"
  | "flower"
  | "ufo"
  | "jukebox"
  | "duck"
  | "cake"
  | "moon"
  | "robot"
  | "cat"
  | "dragon"
  | "snowcone"
  | "letter"
  | "sun"
  | "ghost"
  | "sock"
  | "moth"
  | "washer"
  | "basket"
  | "coat"
  | "scarf"
  | "apron"
  | "worm"
  | "cape"
  | "trousers"
  | "receipt"
  | "crab"
  | "eel"
  | "octopus"
  | "snail"
  | "mailbox"
  | "shell"
  | "divingbell"
  | "parcel"
  | "anemone"
  | "bubble"
  | "ringmaster"
  | "giraffe"
  | "beetle"
  | "drum"
  | "circuswheel"
  | "circustable"
  | "clockhat"
  | "microphone"
  | "ticket"
  | "biscuit"
  | "spotlight"
  | "mousemayor"
  | "hedgehog"
  | "inspector"
  | "leafbug"
  | "stamp"
  | "pencil"
  | "paperclip"
  | "ruler"
  | "eraser"
  | "archive"
  | "townsign"
  | "puddle"
  | "pudding"
  | "biscuitcaptain"
  | "jellybean"
  | "whisk"
  | "layercake"
  | "eclair"
  | "dumpling"
  | "strawberry"
  | "pancake"
  | "recipe"
  | "wafer"
  | "spoon"
  | "principal"
  | "principalsocks"
  | "ankylosaur"
  | "diplodocus"
  | "diplodocusframe"
  | "pterosaur"
  | "nest"
  | "leafbowl"
  | "fossilblock"
  | "badge"
  | "crayon"
  | "cubby"
  | "mobile"
  | "storybook"
  | "classfern"
  | "toothflower"
  | "bat"
  | "papercrown"
  | "cindermayor"
  | "flintclerk"
  | "duckdragon"
  | "frostarchivist"
  | "beedragon"
  | "cometdragon"
  | "catdragon"
  | "helpbell"
  | "servicewindow"
  | "queueroll"
  | "brasshorn"
  | "moustachefountain"
  | "dragonchair"
  | "featherduster"
  | "dragonrug"
  | "wingdoor"
  | "councilclap"
  | "ribbonpanorama"
  | "pagelibrarian"
  | "endy"
  | "comma"
  | "questionmark"
  | "exclamation"
  | "paperwolf"
  | "paperknight"
  | "papermoon"
  | "paperdragon"
  | "openbook"
  | "bookcart"
  | "booklamp"
  | "bookmark"
  | "librarychair"
  | "bookspine"
  | "paperboat"
  | "communalbook"
  | "bookplate"
  | "guestbook"
  | "coachnika"
  | "gus"
  | "irisharpy"
  | "centaurathlete"
  | "cyclopsathlete"
  | "paddedcolumn"
  | "sportsbench"
  | "whistle"
  | "relaybaton"
  | "sportsribbon"
  | "pastalaurel"
  | "vegetablemedal"
  | "scoreplacard"
  | "hurdle"
  | "sportsplate"
  | "sportsdiscus"
  | "sportstowel"
  | "modelathletes"
  | "sportshug"
  | "sportscup"
  | "adaplanner"
  | "weddingbell"
  | "bellringcrown"
  | "crystalchime"
  | "rill"
  | "moss"
  | "crystalaunt"
  | "moongrandmother"
  | "flowercousins"
  | "stoneuncle"
  | "cloudfamily"
  | "weddingarch"
  | "placecard"
  | "lacepanel"
  | "ringcushion"
  | "emptyringcushion"
  | "weddingrings"
  | "twosidedcake"
  | "ribbonspool"
  | "weddingfavors"
  | "ceremonymodel"
  | "memorybook"
  | "weddingpanorama"
  | "clipboardflower"
  | "weddingchair"
  | "weddingguestbook"
  | "bowtieinvite"
  | "stitchtailor"
  | "dozycourier"
  | "bramble"
  | "yawnsign"
  | "sparepillow"
  | "goodnightbrooch"
  | "listeningfunnel"
  | "dreampostcards"
  | "dreamquilt"
  | "snoretrumpet"
  | "raincup"
  | "auditioncard"
  | "pocketteapot"
  | "endingfragments"
  | "tomatoplanets"
  | "slipperlamp"
  | "dreammask"
  | "sleepmask"
  | "worrynote"
  | "helpfulstamps"
  | "dreambook"
  | "reconsiderquilt"
  | "dreamsatchel"
  | "seamworkspanorama"
  | "stitchstars"
  | "dozyquilt"
  | "bramblemoss"
  | "sunsetcup"
  | "nimbusgardener"
  | "breebarometer"
  | "sleetseedling"
  | "forecastsign"
  | "forecastpots"
  | "snowpeas"
  | "sunseed"
  | "fogmushroom"
  | "breezeletters"
  | "airrosette"
  | "nurserycloud"
  | "lopsidedcloud"
  | "mixedlabel"
  | "nimbusrainhat"
  | "steamflower"
  | "cavegarden"
  | "moonflower"
  | "highstreetweather"
  | "rainforestpot"
  | "tinyforestpot"
  | "sleetumbrella"
  | "raincurtain"
  | "thundergourd"
  | "floweraudience"
  | "weatherlabels"
  | "seasoncases"
  | "hangingplanter"
  | "sleetbloom"
  | "conservatorypanorama"
  | "gillsconductor"
  | "sprigporter"
  | "sprigscarf"
  | "ednalibrarian"
  | "myceliumcarriage"
  | "boilergauge"
  | "ticketpunch"
  | "giantpunchedticket"
  | "librarycrate"
  | "departurehats"
  | "porterhandcart"
  | "acornpassenger"
  | "dripreadingroom"
  | "quietnursery"
  | "announcementcard"
  | "platformsoup"
  | "porterconstellation"
  | "peafamily"
  | "sleeperseeds"
  | "cushiontickets"
  | "freightcup"
  | "freightcertificate"
  | "junctionboard"
  | "lostsnail"
  | "sprighalt"
  | "modestcrate"
  | "staffsupper"
  | "myceliumpanorama"
  | "drprobably"
  | "marginassistant"
  | "zeroexhibit"
  | "welcomeplaque"
  | "emptinesscaption"
  | "almostkettle"
  | "biscuitclipboard"
  | "turningproof"
  | "luminousmoss"
  | "ceramicsun"
  | "tinymuseum"
  | "upsidedownroom"
  | "roomforidea"
  | "squaretoast"
  | "squaretoaststack"
  | "squaretoastgarden"
  | "tomorrowfossil"
  | "questionplant"
  | "visitorqueue"
  | "marginnotes"
  | "lightquestion"
  | "tinyocean"
  | "oceanstar"
  | "oceanhorse"
  | "moonmarble"
  | "visitorquestions"
  | "footnotesymbol"
  | "footnoteexplanation"
  | "uncertaincase"
  | "institutepanorama"
  | "misocook"
  | "mallowhost"
  | "ziphauler"
  | "dineropen"
  | "comettruck"
  | "mugservice"
  | "restingtravelers"
  | "dinerjukebox"
  | "mallowtriangle"
  | "travelerbreakfasts"
  | "breakfastchart"
  | "dishpat"
  | "scarfmoonpie"
  | "cavesalt"
  | "cavespoons"
  | "thankyoupebble"
  | "herbawning"
  | "regularstable"
  | "truckdiagnostic"
  | "counterconversation"
  | "pancakeroute"
  | "tastingtray"
  | "smallestorder"
  | "sittingtogether"
  | "windowqueue"
  | "breakfastbeat"
  | "mallowlamp"
  | "dinerguestbook"
  | "dinerpanorama"
  | "dinermug"
  | "captainbutton"
  | "glimstar"
  | "junduck"
  | "toyfireengine"
  | "cardboardbadge"
  | "buttonwelcome"
  | "dollteasummit"
  | "glimperch"
  | "marblesoup"
  | "longdog"
  | "toyxylophone"
  | "snowexplorer"
  | "stringrocket"
  | "crayongarden"
  | "mittenghost"
  | "mooncheese"
  | "repairqueue"
  | "featheradmiral"
  | "plushbus"
  | "biscuitmountain"
  | "blockaudience"
  | "glimstage"
  | "biscuitmoon"
  | "ducknebula"
  | "toyparadefloat"
  | "toyboxpanorama"
  | "toyteacup"
  | "toybag"
  | "departuretag"
  | "paradepennant"
  | "buttonseated"
  | "annmoth"
  | "breakfastpony"
  | "spoonpony"
  | "laundrypony"
  | "trainpony"
  | "pocketgiant"
  | "schedulingnotice"
  | "breakfastservice"
  | "marshmallowmeteor"
  | "krakenkettle"
  | "walrusinvites"
  | "soupcounter"
  | "giantpicnic"
  | "shoppingchoir"
  | "dragoncalendar"
  | "ponybed"
  | "soupmap"
  | "lasttrain"
  | "smallprint"
  | "doomclocktea"
  | "warningpennant"
  | "giantservice"
  | "ponyerrands"
  | "reassuringsky"
  | "quietguests"
  | "tomorrowparty"
  | "omenmilk"
  | "omenbowl"
  | "footnotecard"
  | "omeninvitation"
  | "datesign"
  | "souppennant"
  | "skullpennant"
  | "betweenreceptionist"
  | "yesterdayporter"
  | "hotelbell"
  | "hotelentrance"
  | "mondaywindow"
  | "cloudpillow"
  | "silentbell"
  | "rainluggage"
  | "umbrellabasin"
  | "midnightbreakfast"
  | "holidaystairs"
  | "reliablepostcard"
  | "conservatorycase"
  | "sleepyplanet"
  | "honeymoonnook"
  | "preschoolseminar"
  | "linenparcel"
  | "linenfort"
  | "balconytrain"
  | "aquariumcabin"
  | "slipperlounge"
  | "tuesdayguest"
  | "hotelcup"
  | "hotelvase"
  | "hotelbowl"
  | "tributaryguests"
  | "guestcoat"
  | "guesthearttag"
  | "nightdesk"
  | "returningkeys"
  | "hotelrouteboard"
  | "hotelpanorama"
  | "alwayscard";
export interface PhaseStep {
  verb: "freeze" | "melt";
  name: string;
  signal?: string;
  requires?: string[];
  needsSignals?: string[];
}
export interface Target {
  /** Actual ice volume: cold grows it, hot trims it, even when full. A named
   * physical balance or adjustable-prism detectors determine completion. */
  reversibleIce?: boolean;
  id: string;
  name: string;
  verb: Verb;
  x: number;
  y: number;
  w: number;
  h: number;
  requires?: string[];
  needsSignals?: string[];
  /** Only explicitly authored targets may reverse a completed construction. */
  phase?: { steps: PhaseStep[] };
  temp?: [number, number];
  pressure?: [number, number];
  effort?: number;
  flowOnly?: boolean;
  /** Optional finished FILL color; a story reveal, not a different fluid. */
  fillColor?: string;
  motion?: {
    rx: number;
    ry: number;
    period: number;
    phase?: number;
    after?: string[];
  };
  /** Seconds per beat, seconds accepting water, and a seconds offset. */
  pulse?: {
    period: number;
    open: number;
    phase?: number;
    /** In untimed mode, lower numbered lanes finish before this lamp opens. */
    untimedOrder?: number;
  };
}
export interface Prop {
  kind: PropKind;
  x: number;
  y: number;
  scale?: number;
  target?: string;
  /** If present, an earned/live signal controls this prop's happy/revealOnly state. */
  signal?: string;
  tint?: string;
  follow?: string;
  reveal?: { x: number; y: number; kind?: PropKind; scale?: number };
  revealOnly?: boolean;
  /** Earned art drawn over completed work surfaces, never before its ready state. */
  foreground?: boolean;
}
export interface Level {
  id: string;
  name: string;
  chapter: string;
  theme: Theme;
  pitch: string;
  hint: string;
  ending: string;
  par: number;
  start: [number, number];
  temp: number;
  pressure: number;
  targets: Target[];
  props: Prop[];
  pack?: string;
  stamp?: string;
  balance?: BalancePlan;
  buoyancy?: BuoyancyPlan;
  optics?: OpticsPlan;
  /** Physical readings required in addition to completed targets. */
  needsSignals?: string[];
  completionHint?: string;
  mobile?: { x: number; y: number; targets: string[] };
  channels?: {
    inlet: { x: number; y: number; w: number; h: number };
    junction: [number, number];
    branches: (FlowBranch & {
      via?: [number, number][];
    })[];
  };
}
export interface Controls {
  x: number;
  y: number;
  heat: number;
  pressure: number;
  tilt: number;
}
export const clamp = (n: number, lo: number, hi: number) =>
  Math.max(lo, Math.min(hi, n));
export const W = 960,
  H = 580;
